#%RAML 1.0 DataType
type: object
(originalType): object
displayName: Address


properties:
  country:
    required: true
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    type: CountryCode
  lastName:
    required: false
    type: string
  pOBox:
    required: false
    type: string
  city:
    required: false
    type: string
  streetNumber:
    required: false
    type: string
  postalCode:
    required: false
    type: string
  mobile:
    required: false
    type: string
  externalId:
    required: false
    type: string
  additionalAddressInfo:
    required: false
    type: string
  title:
    required: false
    type: string
  building:
    required: false
    type: string
  firstName:
    required: false
    type: string
  streetName:
    required: false
    type: string
  phone:
    required: false
    type: string
  additionalStreetInfo:
    required: false
    type: string
  company:
    required: false
    type: string
  state:
    required: false
    type: string
  salutation:
    required: false
    type: string
  id:
    required: false
    type: string
  fax:
    required: false
    type: string
  department:
    required: false
    type: string
  region:
    required: false
    type: string
  email:
    required: false
    type: string
  apartment:
    required: false
    type: string
  key:
    required: false
    type: string