#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: AssetDraft
properties:
  sources:
    type: array
    items:
      type: AssetSource
    (builtinType): array
    required: true
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  key:
    type: string
    (builtinType): string
    required: false
  tags:
    type: array
    items:
      type: string
    (builtinType): array
    required: false