#%RAML 1.0 DataType
displayName: AssetDraft
type: object
(builtinType): object
(package): "Common"
properties:
  sources:
    type: array
    items:
      type: AssetSource
    (builtinType): array
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  tags:
    type: array
    items:
      type: string
    (builtinType): array
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false
  key:
    type: string
    (builtinType): string
    required: false