#%RAML 1.0 DataType
displayName: CentPrecisionMoney
type: TypedMoney
(builtinType): object
discriminatorValue: centPrecision
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-types.html#money"
properties:
  type:
    type: MoneyType
    (builtinType): string
    enum:
    - centPrecision
    required: true