#%RAML 1.0 DataType
type: object
(originalType): TypedMoney
displayName: CentPrecisionMoney
# discriminator: type
# discriminatorValue: centPrecision
properties:
  centAmount:
    required: true
    format: int64
    type: number
  fractionDigits:
    required: true
    format: int32
    maximum: 12
    type: number
  type:
    default: centPrecision
    required: true
    type: MoneyType
  currencyCode:
    required: true
    description: |-
      The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    type: CurrencyCode