#%RAML 1.0 DataType
displayName: ClientLogging
type: object
(builtinType): object
(oneOf):
- CreatedBy
- LastModifiedBy
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-types#client-logging"
properties:
  clientId:
    type: string
    (builtinType): string
    required: false
  externalUserId:
    type: string
    (builtinType): string
    required: false
  customer:
    type: CustomerReference
    (builtinType): object
    required: false
  anonymousId:
    type: string
    (builtinType): string
    required: false