#%RAML 1.0 DataType
type: object
(originalType): object
displayName: DiscountedPrice
# 
# 
properties:
  discount:
    required: true
    type: ProductDiscountReference
  value:
    required: true
    type: Money