#%RAML 1.0 DataType
displayName: DiscountedPrice
type: object
(builtinType): object
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#discountedprice"
properties:
  value:
    type: Money
    (builtinType): object
    required: true
  discount:
    type: ProductDiscountReference
    (builtinType): object
    required: true