#%RAML 1.0 DataType
displayName: GeoJsonPoint
type: GeoJson
(builtinType): object
discriminatorValue: Point
(package): "Common"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Point
    required: true
  coordinates:
    type: array
    items:
      type: number
    (builtinType): array
    required: true