#%RAML 1.0 DataType
(builtinType): object
type: GeoJson
displayName: GeoJsonPoint
discriminator: type
discriminatorValue: Point
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Point
    required: true
  coordinates:
    type: array
    items:
      type: number
    (builtinType): array
    required: true