#%RAML 1.0 DataType
displayName: GeoJson
type: object
(builtinType): object
discriminator: type
(oneOf):
- GeoJsonPoint
(package): "Common"
properties:
  type:
    type: string
    (builtinType): string
    required: true