#%RAML 1.0 DataType
displayName: HighPrecisionMoneyDraft
type: TypedMoneyDraft
(builtinType): object
discriminatorValue: highPrecision
properties:
  type:
    type: MoneyType
    (builtinType): string
    enum:
    - highPrecision
    required: true
  preciseAmount:
    format: int64
    type: number
    (builtinType): number
    required: true