#%RAML 1.0 DataType
displayName: HighPrecisionMoney
type: TypedMoney
(builtinType): object
discriminatorValue: highPrecision
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-types.html#money"
properties:
  type:
    type: MoneyType
    (builtinType): string
    enum:
    - highPrecision
    required: true
  preciseAmount:
    format: int64
    type: integer
    (builtinType): integer
    required: true