#%RAML 1.0 DataType
displayName: ImageDimensions
type: object
(builtinType): object
properties:
  w:
    type: integer
    (builtinType): integer
    required: true
  h:
    type: integer
    (builtinType): integer
    required: true