#%RAML 1.0 DataType
displayName: KeyReference
type: object
(builtinType): object
discriminator: typeId
(oneOf):
- StoreKeyReference
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-types.html#keyreference"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - cart
    - cart-discount
    - category
    - channel
    - customer
    - customer-group
    - discount-code
    - key-value-document
    - payment
    - product
    - product-type
    - product-discount
    - order
    - review
    - shopping-list
    - shipping-method
    - state
    - store
    - tax-category
    - type
    - zone
    - inventory-entry
    - order-edit
    required: true
  key:
    type: string
    (builtinType): string
    required: true