#%RAML 1.0 DataType
displayName: KeyReference
type: object
(builtinType): object
discriminator: typeId
(oneOf):
- StoreKeyReference
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    required: true
  key:
    type: string
    (builtinType): string
    required: true