#%RAML 1.0 DataType
(builtinType): object
type: ClientLogging
displayName: LastModifiedBy
properties:
  anonymousId:
    type: string
    (builtinType): string
    required: false
  clientId:
    type: string
    (builtinType): string
    required: false
  externalUserId:
    type: string
    (builtinType): string
    required: false
  customer:
    type: CustomerReference
    (builtinType): object
    required: false