#%RAML 1.0 DataType
displayName: LastModifiedBy
type: ClientLogging
(builtinType): object
(package): "Common"
properties:
  clientId:
    type: string
    (builtinType): string
    required: false
  externalUserId:
    type: string
    (builtinType): string
    required: false
  customer:
    type: CustomerReference
    (builtinType): object
    required: false
  anonymousId:
    type: string
    (builtinType): string
    required: false