#%RAML 1.0 DataType
displayName: LocalizedString
type: object
(builtinType): object
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-types.html#localizedstring"
(asMap):
  key: "string"
  value: "string"
properties:
  /^[a-z]{2}(-[A-Z]{2})?$/:
    type: string
    (builtinType): string
    required: true