#%RAML 1.0 DataType
displayName: PagedQueryResponse
type: object
(builtinType): object
properties:
  total:
    format: int64
    type: number
    (builtinType): number
    required: false
  offset:
    format: int64
    type: number
    (builtinType): number
    required: true
  meta:
    type: object
    (builtinType): object
    required: false
  count:
    format: int64
    type: number
    (builtinType): number
    required: true
  limit:
    format: int64
    type: number
    (builtinType): number
    required: true
  results:
    type: array
    items:
      type: BaseResource
    (builtinType): array
    required: true
  facets:
    type: FacetResults
    (builtinType): object
    required: false