#%RAML 1.0 DataType
type: object
(originalType): object
displayName: PagedQueryResponse


properties:
  total:
    format: int64
    type: number
  offset:
    format: int64
    type: number
  meta:
    type: object
  count:
    format: int64
    type: number
  limit:
    format: int64
    type: number
  results:
    type: array
    items:
      type: BaseResource
  facets:
    type: FacetResults