#%RAML 1.0 DataType
displayName: PriceTierDraft
type: object
(builtinType): object
properties:
  value:
    type: Money
    (builtinType): object
    required: true
  minimumQuantity:
    format: int64
    type: number
    (builtinType): number
    required: true