#%RAML 1.0 DataType
displayName: PriceTier
type: object
(builtinType): object
properties:
  minimumQuantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  value:
    type: TypedMoney
    (builtinType): object
    required: true