#%RAML 1.0 DataType
displayName: PriceTierDraft
type: object
(builtinType): object
(package): "Common"
properties:
  minimumQuantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  value:
    type: Money
    (builtinType): object
    required: true