#%RAML 1.0 DataType
displayName: QueryPrice
type: object
(builtinType): object
properties:
  discounted:
    type: DiscountedPrice
    (builtinType): object
    required: false
  country:
    type: CountryCode
    (builtinType): string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    required: false
  tiers:
    type: array
    items:
      type: PriceTierDraft
    (builtinType): array
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  channel:
    type: ChannelReference
    (builtinType): object
    required: false
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false
  id:
    type: string
    (builtinType): string
    required: true
  value:
    type: Money
    (builtinType): object
    required: true