#%RAML 1.0 DataType
type: object
(originalType): object
displayName: QueryPrice


properties:
  discounted:
    required: false
    type: DiscountedPrice
  country:
    required: false
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    type: CountryCode
  tiers:
    required: false
    type: array
    items:
      type: PriceTierDraft
  customerGroup:
    required: false
    type: CustomerGroupReference
  custom:
    required: false
    type: CustomFields
  channel:
    required: false
    type: ChannelReference
  validUntil:
    required: false
    type: datetime
  validFrom:
    required: false
    type: datetime
  id:
    required: true
    type: string
  value:
    required: true
    type: Money