#%RAML 1.0 DataType
displayName: Reference
type: object
(builtinType): object
discriminator: typeId
(oneOf):
- CustomObjectReference
- CustomerGroupReference
- CustomerReference
- DiscountCodeReference
- InventoryEntryReference
- OrderEditReference
- OrderReference
- PaymentReference
- ProductDiscountReference
- ProductTypeReference
- ProductReference
- ReviewReference
- ShippingMethodReference
- ShoppingListReference
- StateReference
- StoreReference
- TaxCategoryReference
- TypeReference
- ZoneReference
- CartDiscountReference
- CartReference
- CategoryReference
- ChannelReference
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    required: true
  id:
    type: string
    (builtinType): string
    required: true