#%RAML 1.0 DataType
displayName: Reference
type: object
(builtinType): object
discriminator: typeId
(oneOf):
- CartDiscountReference
- CartReference
- CategoryReference
- ChannelReference
- CustomObjectReference
- CustomerGroupReference
- CustomerReference
- DiscountCodeReference
- InventoryEntryReference
- OrderEditReference
- OrderReference
- PaymentReference
- ProductDiscountReference
- ProductReference
- ProductTypeReference
- ReviewReference
- ShippingMethodReference
- ShoppingListReference
- StateReference
- StoreReference
- TaxCategoryReference
- TypeReference
- ZoneReference
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-types.html#reference"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    required: true
  id:
    type: string
    (builtinType): string
    required: true