#%RAML 1.0 DataType
displayName: ResourceIdentifier
type: object
(builtinType): object
discriminator: typeId
(oneOf):
- CartDiscountResourceIdentifier
- CartResourceIdentifier
- CategoryResourceIdentifier
- ChannelResourceIdentifier
- CustomerGroupResourceIdentifier
- CustomerResourceIdentifier
- DiscountCodeResourceIdentifier
- InventoryEntryResourceIdentifier
- OrderEditResourceIdentifier
- OrderResourceIdentifier
- PaymentResourceIdentifier
- ProductDiscountResourceIdentifier
- ProductResourceIdentifier
- ProductTypeResourceIdentifier
- ReviewResourceIdentifier
- ShippingMethodResourceIdentifier
- ShoppingListResourceIdentifier
- StateResourceIdentifier
- StoreResourceIdentifier
- TaxCategoryResourceIdentifier
- TypeResourceIdentifier
- ZoneResourceIdentifier
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false