#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ResourceIdentifier
discriminator: typeId
(subTypes):
- CustomerGroupResourceIdentifier
- CustomerResourceIdentifier
- DiscountCodeResourceIdentifier
- InventoryEntryResourceIdentifier
- OrderEditResourceIdentifier
- OrderResourceIdentifier
- PaymentResourceIdentifier
- ProductDiscountResourceIdentifier
- ProductTypeResourceIdentifier
- ProductResourceIdentifier
- ReviewResourceIdentifier
- ShippingMethodResourceIdentifier
- ShoppingListResourceIdentifier
- StateResourceIdentifier
- StoreResourceIdentifier
- TaxCategoryResourceIdentifier
- TypeResourceIdentifier
- ZoneResourceIdentifier
- CartDiscountResourceIdentifier
- CartResourceIdentifier
- CategoryResourceIdentifier
- ChannelResourceIdentifier
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false