#%RAML 1.0 DataType
displayName: ScopedPrice
type: object
(builtinType): object
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#scopedprice"
properties:
  id:
    type: string
    (builtinType): string
    required: true
  value:
    type: TypedMoney
    (builtinType): object
    required: true
  currentValue:
    type: TypedMoney
    (builtinType): object
    required: true
  country:
    type: CountryCode
    (builtinType): string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  channel:
    type: ChannelReference
    (builtinType): object
    required: false
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false
  discounted:
    type: DiscountedPrice
    (builtinType): object
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false