#%RAML 1.0 DataType
displayName: TypedMoney
type: object
(builtinType): object
discriminator: type
(oneOf):
- CentPrecisionMoney
- HighPrecisionMoney
properties:
  type:
    type: MoneyType
    (builtinType): string
    required: true
  fractionDigits:
    format: int32
    maximum: 12
    type: number
    (builtinType): number
    required: true
  centAmount:
    format: int64
    type: number
    (builtinType): number
    required: true
  currencyCode:
    type: CurrencyCode
    (builtinType): string
    description: |-
      The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    required: true