#%RAML 1.0 DataType
displayName: TypedMoney
type: object
(builtinType): object
discriminator: type
(oneOf):
- CentPrecisionMoney
- HighPrecisionMoney
(package): "Common"
(docs-uri): "https://docs.commercetools.com/http-api-types.html#money"
properties:
  type:
    type: MoneyType
    (builtinType): string
    enum:
    - centPrecision
    - highPrecision
    required: true
  fractionDigits:
    format: int32
    maximum: 12
    type: integer
    (builtinType): integer
    required: true
  centAmount:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  currencyCode:
    type: CurrencyCode
    (builtinType): string
    description: |-
      The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    required: true