(resourceName): ByProjectKeyImportSinks
(resourcePathUri): /{projectKey}/import-sinks

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
post:
  description: |-
    Creates a new import sink.
  body:
    application/json:
      type: ImportSinkDraft
      (builtinType): object
  responses:
    201:
      body:
        application/json:
          type: ImportSink
          (builtinType): object