# ByProjectKeyImportSinksByImportSinkKeyItems
(resourceName): ByProjectKeyImportSinksByImportSinkKeyItems
(resourcePathUri): /{projectKey}/import-sinks/{importSinkKey}/items

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
  importSinkKey:
    type: string
    (builtinType): string
get:
  description: |-
    Retieves all import items of an import sink key
  queryParameters:
    limit:
      required: false
      type: number
      (builtinType): number
    offset:
      required: false
      type: number
      (builtinType): number
  responses:
    200:
      body:
        application/json:
          type: ImportItemPagedResponse
          (builtinType): object