# Resource
(resourceName): ByProjectKeyProductVariantsImportSinkKeyByImportSinkKeyResourceKeyByResourceKey
(resourcePathUri): /{projectKey}/product-variants/importSinkKey={importSinkKey}/resourceKey={resourceKey}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
  importSinkKey:
    type: string
    (builtinType): string
    description: |-
      The import sink used to create the new resource
    required: true
  resourceKey:
    type: string
    (builtinType): string
    required: true
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  displayName: Delete product-variant
  description: |-
    Deletes the product variant given by the resource key.
  responses:
    200:
      body:
        application/json:
          type: ImportOperationStatus
          (builtinType): object

  (codeExamples):
    curl: |-
      curl -XDELETE /{projectKey}/product-variants/importSinkKey={importSinkKey}/resourceKey={resourceKey} -i \
      --header 'Authorization: Bearer YOUR_TOKEN'
