# Resource
(resourceName): ByProjectKeyImportSinksByImportSinkKey
(resourcePathUri): /{projectKey}/import-sinks/{importSinkKey}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
  importSinkKey:
    type: string
    (builtinType): string
    description: |-
      The key of the import sink.
    required: true
put:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_import_sinks:{projectKey}"
  displayName: Update import-sink
  description: |-
    Updates the import sink given by the key.
  body:
    application/json:
      type: ImportSinkDraft
      (builtinType): object

  responses:
    200:
      description: |-
        The import sink was successfully updated.
      body:
        application/json:
          type: ImportSink
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyImportSinksByImportSinkKeyPut-200-default.json

get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_import_sinks:{projectKey}"
      - "view_import_sinks:{projectKey}"
  displayName: Get import-sink
  description: |-
    Retrieves the import sink given by the key.
  responses:
    200:
      description: |-
        The requested import sink was found.
      body:
        application/json:
          type: ImportSink
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyImportSinksByImportSinkKeyGet-200-default.json

  (codeExamples):
    curl: |-
      curl -XGET /{projectKey}/import-sinks/{importSinkKey} -i \
      --header 'Authorization: Bearer YOUR_TOKEN'
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_import_sinks:{projectKey}"
  displayName: Delete import-sink
  description: |-
    Deletes the import sink given by the key.
  responses:
    200:
      description: |-
        The deleted import sink.
      body:
        application/json:
          type: ImportSink
          (builtinType): object

  (codeExamples):
    curl: |-
      curl -XDELETE /{projectKey}/import-sinks/{importSinkKey} -i \
      --header 'Authorization: Bearer YOUR_TOKEN'
