# Resource
(resourceName): ByProjectKeyImportSinks
(resourcePathUri): /{projectKey}/import-sinks

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The commercetools project key.
    required: true
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_import_sinks:{projectKey}"
  displayName: Creates a new import sink.
  description: |-
    Creates a new import sink.
  body:
    application/json:
      type: ImportSinkDraft
      (builtinType): object

  responses:
    201:
      body:
        application/json:
          type: ImportSink
          (builtinType): object
          examples:
            default:
              strict: true
              value: !include ../examples/ByProjectKeyImportSinksPost-201-default.json

get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_import_sinks:{projectKey}"
      - "view_import_sinks:{projectKey}"
  displayName: Query import-sinks
  description: |-
    Retrieves all import sinks of a project key.
  queryParameters:
    limit:
      required: true
      type: number
      (builtinType): number
    offset:
      required: true
      type: number
      (builtinType): number
  responses:
    200:
      body:
        application/json:
          type: ImportSinkPagedResponse
          (builtinType): object

  (codeExamples):
    curl: |-
      curl -XGET /{projectKey}/import-sinks -i \
      --header 'Authorization: Bearer YOUR_TOKEN'
