#ByProjectKeyImportSinksByImportSinkKeyItems
(resourcePathUri): /{projectKey}/import-sinks/{importSinkKey}/items

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      The CTP project key.
  importSinkKey:
    type: string
    (builtinType): string
get:
  description: |-
    Retieves all import items of an import sink key
  queryParameters:
    limit:
      required: false
      type: integer
      (builtinType): integer
    offset:
      required: false
      type: integer
      (builtinType): integer
  responses:
    200:
      body:
        application/json:
          type: ImportItemPagedResponse
          (builtinType): object
          description: |-
            This type represents a paged import item result.