#%RAML 1.0 DataType
displayName: CustomerSetCompanyNameAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setCompanyName
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-company-name"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerSetCompanyNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCompanyName
    required: true
  companyName:
    type: string
    (builtinType): string
    required: false