#%RAML 1.0 DataType
displayName: CustomerUpdate
type: object
(builtinType): object
(package): "Customer"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: CustomerUpdateAction
    (builtinType): array
    required: true