#%RAML 1.0 DataType
displayName: CustomerResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: customer
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#customer"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - customer
    required: false