#%RAML 1.0 DataType
(builtinType): object
type: CustomerUpdateAction
displayName: CustomerSetSalutationAction
discriminator: action
discriminatorValue: setSalutation
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSalutation
    required: true
  salutation:
    type: string
    (builtinType): string
    required: false