#%RAML 1.0 DataType
displayName: CustomerSetLastNameAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setLastName
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-last-name"
examples:
  postman: !include ../../examples/Customer/CustomerSetLastNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLastName
    required: true
  lastName:
    type: string
    (builtinType): string
    required: false