#%RAML 1.0 DataType
displayName: CustomerSetTitleAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setTitle
examples:
  postman: !include ../../examples/Customer/CustomerSetTitleAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTitle
    required: true
  title:
    type: string
    (builtinType): string
    required: false