#%RAML 1.0 DataType
displayName: CustomerAddBillingAddressIdAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: addBillingAddressId
examples:
  postman: !include ../../examples/Customer/CustomerAddBillingAddressIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addBillingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true