#%RAML 1.0 DataType
displayName: CustomerSetDefaultBillingAddressAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setDefaultBillingAddress
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-default-billing-address"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerSetDefaultBillingAddressAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDefaultBillingAddress
    required: true
  addressId:
    type: string
    (builtinType): string
    required: false