#%RAML 1.0 DataType
type: object
displayName: CustomerResetPassword


properties:
   tokenValue:
      type: string
   newPassword:
      type: string
   version:
      format: int64
      type: number