#%RAML 1.0 DataType
displayName: CustomerSetFirstNameAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setFirstName
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-first-name"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerSetFirstNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setFirstName
    required: true
  firstName:
    type: string
    (builtinType): string
    required: false