#%RAML 1.0 DataType
type: object
(originalType): object
displayName: CustomerUpdate


properties:
  actions:
    type: array
    items:
      type: CustomerUpdateAction
  version:
    format: int64
    type: number