#%RAML 1.0 DataType
(builtinType): object
type: CustomerUpdateAction
displayName: CustomerSetDateOfBirthAction
discriminator: action
discriminatorValue: setDateOfBirth
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDateOfBirth
    required: true
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: false