#%RAML 1.0 DataType
displayName: CustomerChangeEmailAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: changeEmail
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeEmail
    required: true
  email:
    type: string
    (builtinType): string
    required: true