#%RAML 1.0 DataType
displayName: CustomerSetSalutationAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setSalutation
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-salutation"
examples:
  postman: !include ../../examples/Customer/CustomerSetSalutationAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSalutation
    required: true
  salutation:
    type: string
    (builtinType): string
    required: false