#%RAML 1.0 DataType
displayName: CustomerRemoveShippingAddressIdAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: removeShippingAddressId
examples:
  postman: !include ../../examples/Customer/CustomerRemoveShippingAddressIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeShippingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true