#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: CustomerReference
discriminator: typeId
discriminatorValue: customer
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - customer
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Customer
    (builtinType): object
    required: false