#%RAML 1.0 DataType
displayName: CustomerAddBillingAddressIdAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: addBillingAddressId
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#add-billing-address-id"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerAddBillingAddressIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addBillingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true