#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: CustomerSignInResult
properties:
  cart:
    type: object
    (builtinType): object
    description: |-
      A cart that is associated to the customer.
               Empty if the customer does not have a cart yet.
    required: false
  customer:
    type: Customer
    (builtinType): object
    required: true