#%RAML 1.0 DataType
displayName: CustomerSetKeyAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setKey
examples:
  postman: !include ../../examples/Customer/CustomerSetKeyAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false