#%RAML 1.0 DataType
displayName: CustomerSetCustomerNumberAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setCustomerNumber
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerNumber
    required: true
  customerNumber:
    type: string
    (builtinType): string
    required: false