#%RAML 1.0 DataType
displayName: CustomerCreatePasswordResetToken
type: object
(builtinType): object
(package): "Customer"
properties:
  email:
    type: string
    (builtinType): string
    required: true
  ttlMinutes:
    format: int64
    type: integer
    (builtinType): integer
    required: false