#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: CustomerUpdateAction
discriminator: action
(subTypes):
- CustomerAddAddressAction
- CustomerAddBillingAddressIdAction
- CustomerAddShippingAddressIdAction
- CustomerChangeAddressAction
- CustomerChangeEmailAction
- CustomerRemoveAddressAction
- CustomerRemoveBillingAddressIdAction
- CustomerRemoveShippingAddressIdAction
- CustomerSetCompanyNameAction
- CustomerSetCustomFieldAction
- CustomerSetCustomTypeAction
- CustomerSetCustomerGroupAction
- CustomerSetCustomerNumberAction
- CustomerSetDateOfBirthAction
- CustomerSetDefaultBillingAddressAction
- CustomerSetDefaultShippingAddressAction
- CustomerSetExternalIdAction
- CustomerSetFirstNameAction
- CustomerSetKeyAction
- CustomerSetLastNameAction
- CustomerSetLocaleAction
- CustomerSetMiddleNameAction
- CustomerSetSalutationAction
- CustomerSetTitleAction
- CustomerSetVatIdAction
properties:
  action:
    type: string
    (builtinType): string
    required: true