#%RAML 1.0 DataType
type: object
(originalType): CustomerUpdateAction
displayName: CustomerChangeAddressAction

discriminatorValue: changeAddress
properties:
  action:
    required: true
    type: string
  address:
    required: true
    type: Address
  addressId:
    required: true
    type: string