#%RAML 1.0 DataType
type: object
(originalType): object
displayName: CustomerSignin


properties:
  updateProductData:
    required: false
    type: boolean
  anonymousId:
    required: false
    type: string
  password:
    required: true
    type: string
  anonymousCartSignInMode:
    required: false
    type: AnonymousCartSignInMode
  anonymousCartId:
    required: false
    type: string
  email:
    required: true
    type: string