#%RAML 1.0 DataType
displayName: CustomerSetVatIdAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setVatId
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-vat-id"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerSetVatIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setVatId
    required: true
  vatId:
    type: string
    (builtinType): string
    description: |-
      If not defined, the vat Id is unset.
    required: false