#%RAML 1.0 DataType
displayName: CustomerSetCustomerNumberAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setCustomerNumber
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-customer-number"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerSetCustomerNumberAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerNumber
    required: true
  customerNumber:
    type: string
    (builtinType): string
    required: false