#%RAML 1.0 DataType
displayName: CustomerSignin
type: object
(builtinType): object
(package): "Customer"
properties:
  email:
    type: string
    (builtinType): string
    required: true
  password:
    type: string
    (builtinType): string
    required: true
  anonymousCartId:
    type: string
    (builtinType): string
    required: false
  anonymousCartSignInMode:
    type: AnonymousCartSignInMode
    (builtinType): string
    enum:
    - MergeWithExistingCustomerCart
    - UseAsNewActiveCustomerCart
    required: false
  anonymousId:
    type: string
    (builtinType): string
    required: false
  updateProductData:
    type: boolean
    (builtinType): boolean
    required: false