#%RAML 1.0 DataType
(builtinType): object
type: CustomerUpdateAction
displayName: CustomerSetCompanyNameAction
discriminator: action
discriminatorValue: setCompanyName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCompanyName
    required: true
  companyName:
    type: string
    (builtinType): string
    required: false