#%RAML 1.0 DataType
displayName: CustomerSetExternalIdAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setExternalId
examples:
  postman: !include ../../examples/Customer/CustomerSetExternalIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExternalId
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false