#%RAML 1.0 DataType
type: object
(originalType): object
displayName: CustomerChangePassword


properties:
  newPassword:
    type: string
  id:
    type: string
  version:
    format: int64
    type: number
  currentPassword:
    type: string