#%RAML 1.0 DataType
(builtinType): object
type: CustomerUpdateAction
displayName: CustomerSetFirstNameAction
discriminator: action
discriminatorValue: setFirstName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setFirstName
    required: true
  firstName:
    type: string
    (builtinType): string
    required: false