#%RAML 1.0 DataType
(builtinType): object
type: CustomerUpdateAction
displayName: CustomerSetVatIdAction
discriminator: action
discriminatorValue: setVatId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setVatId
    required: true
  vatId:
    type: string
    (builtinType): string
    required: false