#%RAML 1.0 DataType
(builtinType): object
type: CustomerUpdateAction
displayName: CustomerSetExternalIdAction
discriminator: action
discriminatorValue: setExternalId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExternalId
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false