#%RAML 1.0 DataType
type: object
displayName: CustomerCreateEmailToken


properties:
   id:
      type: string
   version:
      format: int64
      type: number
   ttlMinutes:
      format: int64
      type: number