#%RAML 1.0 DataType
displayName: CustomerSetKeyAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setKey
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-key"
examples:
  postman: !include ../../examples/Customer/CustomerSetKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false