#%RAML 1.0 DataType
displayName: CustomerRemoveBillingAddressIdAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: removeBillingAddressId
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#remove-billing-address-id"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerRemoveBillingAddressIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeBillingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true