#%RAML 1.0 DataType
displayName: CustomerEmailVerify
type: object
(builtinType): object
(package): "Customer"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  tokenValue:
    type: string
    (builtinType): string
    required: true