#%RAML 1.0 DataType
displayName: CustomerChangePassword
type: object
(builtinType): object
properties:
  newPassword:
    type: string
    (builtinType): string
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  currentPassword:
    type: string
    (builtinType): string
    required: true