#%RAML 1.0 DataType
displayName: CustomerSetDateOfBirthAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setDateOfBirth
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-date-of-birth"
examples:
  postman:
    strict: true
    value: !include ../../examples/Customer/CustomerSetDateOfBirthAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDateOfBirth
    required: true
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    description: |-
      If not defined, the date of birth is unset.
    required: false