#%RAML 1.0 DataType
type: object
(originalType): LoggedResource
displayName: Customer


properties:
  createdAt:
    format: rfc3339
    type: datetime
  lastModifiedAt:
    format: rfc3339
    type: datetime
  id:
    description: |-
      The unique ID of the customer.
    type: string
  version:
    description: |-
      The current version of the customer.
    format: int64
    type: number
  createdBy:
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    type: CreatedBy
  lastModifiedBy:
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    type: LastModifiedBy
  lastName:
    type: string
  addresses:
    description: |-
      The addresses have unique IDs in the addresses list
    type: array
    items:
      type: Address
  companyName:
    type: string
  vatId:
    type: string
  locale:
    type: string
  title:
    type: string
  isEmailVerified:
    type: boolean
  shippingAddressIds:
    description: |-
      The IDs from the addresses list which are used as shipping addresses
    type: array
    items:
      type: string
  password:
    type: string
  key:
    description: |-
      User-specific unique identifier for a customer.
      Must be unique across a project.
      The field can be reset using the Set Key UpdateAction
    type: string
  email:
    description: |-
      The customer's email address and the main identifier of uniqueness for a customer account.
      Email addresses are either unique to the store they're specified for, _or_ for the entire project.
      For more information, see Email uniquenes.
    type: string
  stores:
    description: |-
      References to the stores the customer account is associated with.
      If no stores are specified, the customer is a global customer, and can log in using the Password Flow for global Customers.
      If one or more stores are specified, the customer can only log in using the Password Flow for Customers in a Store for those specific stores.
    type: array
    items:
      type: StoreKeyReference
  customerGroup:
    discriminatorValue: customer-group
    type: CustomerGroupReference
  custom:
    type: CustomFields
  externalId:
    type: string
  dateOfBirth:
    type: date-only
  billingAddressIds:
    description: |-
      The IDs from the addresses list which are used as billing addresses
    type: array
    items:
      type: string
  defaultShippingAddressId:
    description: |-
      The address ID in the addresses list
    type: string
  customerNumber:
    description: |-
      The customer number can be used to create a more human-readable (in contrast to ID) identifier for the customer.
      It should be unique across a project.
      Once the field was set it cannot be changed anymore.
    type: string
  defaultBillingAddressId:
    description: |-
      The address ID in the addresses list
    type: string
  firstName:
    type: string
  middleName:
    type: string
  salutation:
    type: string