#%RAML 1.0 DataType
displayName: CustomerDraft
type: object
(builtinType): object
properties:
  anonymousId:
    type: string
    (builtinType): string
    description: |-
      Identifies carts and orders belonging to an anonymous session that will be assigned to the new customer account.
    required: false
  lastName:
    type: string
    (builtinType): string
    required: false
  addresses:
    type: array
    items:
      type: Address
    (builtinType): array
    description: |-
      Sets the ID of each address to be unique in the addresses list.
    required: false
  defaultShippingAddress:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The index of the address in the addresses array.
               The `defaultShippingAddressId` of the customer will be set to the ID of that address.
    required: false
  stores:
    type: array
    items:
      type: StoreResourceIdentifier
    (builtinType): array
    description: |-
      References to the stores the customer account is associated with.
               If no stores are specified, the customer is a global customer, and can log in using the Password Flow for global Customers.
               If one or more stores are specified, the customer can only log in using the Password Flow for Customers in a Store for those specific stores.
    required: false
  customerGroup:
    discriminatorValue: customer-group
    type: CustomerGroupResourceIdentifier
    (builtinType): object
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  companyName:
    type: string
    (builtinType): string
    required: false
  vatId:
    type: string
    (builtinType): string
    required: false
  externalId:
    type: string
    (builtinType): string
    required: false
  billingAddresses:
    type: array
    items:
      type: integer
    (builtinType): array
    description: |-
      The indices of the billing addresses in the addresses array.
               The `billingAddressIds` of the customer will be set to the IDs of that addresses.
    required: false
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: false
  locale:
    type: string
    (builtinType): string
    description: |-
      Must be one of the languages supported for this project
    required: false
  title:
    type: string
    (builtinType): string
    required: false
  customerNumber:
    type: string
    (builtinType): string
    description: |-
      String that uniquely identifies a customer.
               It can be used to create more human-readable (in contrast to ID) identifier for the customer.
               It should be **unique** across a project.
               Once it's set it cannot be changed.
    required: false
  isEmailVerified:
    type: boolean
    (builtinType): boolean
    required: false
  firstName:
    type: string
    (builtinType): string
    required: false
  password:
    type: string
    (builtinType): string
    required: true
  middleName:
    type: string
    (builtinType): string
    required: false
  salutation:
    type: string
    (builtinType): string
    required: false
  anonymousCartId:
    type: string
    (builtinType): string
    description: |-
      Identifies a single cart that will be assigned to the new customer account.
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for a customer.
               Must be unique across a project.
               The field can be reset using the Set Key UpdateAction
    required: false
  defaultBillingAddress:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The index of the address in the addresses array.
               The `defaultBillingAddressId` of the customer will be set to the ID of that address.
    required: false
  email:
    type: string
    (builtinType): string
    description: |-
      The customer's email address and the main identifier of uniqueness for a customer account.
               Email addresses are either unique to the store they're specified for, _or_ for the entire project, and are case insensitive.
               For more information, see Email uniquenes.
    required: true
  shippingAddresses:
    type: array
    items:
      type: integer
    (builtinType): array
    description: |-
      The indices of the shipping addresses in the addresses array.
               The `shippingAddressIds` of the Customer will be set to the IDs of that addresses.
    required: false