#%RAML 1.0 DataType
(builtinType): object
type: CustomerUpdateAction
displayName: CustomerChangeEmailAction
discriminator: action
discriminatorValue: changeEmail
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeEmail
    required: true
  email:
    type: string
    (builtinType): string
    required: true