#%RAML 1.0 DataType
displayName: CustomerRemoveAddressAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: removeAddress
examples:
  postman: !include ../../examples/Customer/CustomerRemoveAddressAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAddress
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true