#%RAML 1.0 DataType
displayName: CustomerChangeEmailAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: changeEmail
(package): "Customer"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#change-email"
examples:
  postman: !include ../../examples/Customer/CustomerChangeEmailAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeEmail
    required: true
  email:
    type: string
    (builtinType): string
    required: true