#%RAML 1.0 DataType
displayName: CustomerSetLastNameAction
type: CustomerUpdateAction
(builtinType): object
discriminatorValue: setLastName
examples:
  postman: !include ../../examples/Customer/CustomerSetLastNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLastName
    required: true
  lastName:
    type: string
    (builtinType): string
    required: false