#%RAML 1.0 DataType
(builtinType): object
type: DiscountCodeUpdateAction
displayName: DiscountCodeChangeCartDiscountsAction
discriminator: action
discriminatorValue: changeCartDiscounts
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCartDiscounts
    required: true
  cartDiscounts:
    type: array
    items:
      type: CartDiscountResourceIdentifier
    (builtinType): array
    required: true