#%RAML 1.0 DataType
displayName: DiscountCodeChangeCartDiscountsAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: changeCartDiscounts
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeChangeCartDiscountsAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCartDiscounts
    required: true
  cartDiscounts:
    type: array
    items:
      type: CartDiscountResourceIdentifier
    (builtinType): array
    required: true