#%RAML 1.0 DataType
type: object
(originalType): DiscountCodeUpdateAction
displayName: DiscountCodeSetMaxApplicationsPerCustomerAction
# discriminator: action
# discriminatorValue: setMaxApplicationsPerCustomer
properties:
  action:
    default: setMaxApplicationsPerCustomer
    required: true
    type: string
  maxApplicationsPerCustomer:
    required: false
    format: int64
    type: number