#%RAML 1.0 DataType
displayName: DiscountCodeSetValidFromAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setValidFrom
(package): "DiscountCode"
(docs-uri): "https://docs.commercetools.com/http-api-projects-discountCodes.html#set-validfrom"
examples:
  postman:
    strict: true
    value: !include ../../examples/DiscountCode/DiscountCodeSetValidFromAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidFrom
    required: true
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false