#%RAML 1.0 DataType
displayName: DiscountCodeSetValidFromAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setValidFrom
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetValidFromAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidFrom
    required: true
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false