#%RAML 1.0 DataType
displayName: DiscountCodeSetValidUntilAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setValidUntil
(package): "DiscountCode"
(docs-uri): "https://docs.commercetools.com/http-api-projects-discountCodes.html#set-validuntil"
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetValidUntilAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidUntil
    required: true
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false