#%RAML 1.0 DataType
displayName: DiscountCodeSetMaxApplicationsPerCustomerAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setMaxApplicationsPerCustomer
(package): "DiscountCode"
(docs-uri): "https://docs.commercetools.com/http-api-projects-discountCodes.html#set-max-applications-per-customer"
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetMaxApplicationsPerCustomerAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMaxApplicationsPerCustomer
    required: true
  maxApplicationsPerCustomer:
    format: int64
    type: number
    (builtinType): number
    required: false