#%RAML 1.0 DataType
displayName: DiscountCodeSetValidFromAndUntilAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setValidFromAndUntil
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetValidFromAndUntilAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidFromAndUntil
    required: true
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false