#%RAML 1.0 DataType
displayName: DiscountCodeSetValidUntilAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setValidUntil
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetValidUntilAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidUntil
    required: true
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false