#%RAML 1.0 DataType
(builtinType): object
type: DiscountCodeUpdateAction
displayName: DiscountCodeChangeGroupsAction
discriminator: action
discriminatorValue: changeGroups
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeGroups
    required: true
  groups:
    type: array
    items:
      type: string
    (builtinType): array
    required: true