#%RAML 1.0 DataType
displayName: DiscountCodeUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- DiscountCodeChangeCartDiscountsAction
- DiscountCodeChangeGroupsAction
- DiscountCodeChangeIsActiveAction
- DiscountCodeSetCartPredicateAction
- DiscountCodeSetCustomFieldAction
- DiscountCodeSetCustomTypeAction
- DiscountCodeSetDescriptionAction
- DiscountCodeSetMaxApplicationsAction
- DiscountCodeSetMaxApplicationsPerCustomerAction
- DiscountCodeSetNameAction
- DiscountCodeSetValidFromAction
- DiscountCodeSetValidFromAndUntilAction
- DiscountCodeSetValidUntilAction
(package): "DiscountCode"
properties:
  action:
    type: string
    (builtinType): string
    required: true