#%RAML 1.0 DataType
displayName: DiscountCodeSetCustomFieldAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setCustomField
(package): "DiscountCode"
(docs-uri): "https://docs.commercetools.com/http-api-projects-discountCodes.html#set-customfield"
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetCustomFieldAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false