#%RAML 1.0 DataType
(builtinType): object
type: DiscountCodeUpdateAction
displayName: DiscountCodeSetValidUntilAction
discriminator: action
discriminatorValue: setValidUntil
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidUntil
    required: true
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false