#%RAML 1.0 DataType
displayName: DiscountCodeResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: discount-code
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - discount-code
    required: false