#%RAML 1.0 DataType
displayName: DiscountCodePagedQueryResponse
type: object
(builtinType): object
(package): "DiscountCode"
properties:
  limit:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  count:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  total:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  offset:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  results:
    type: array
    items:
      type: DiscountCode
    (builtinType): array
    required: true