#%RAML 1.0 DataType
displayName: DiscountCodeSetDescriptionAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setDescription
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetDescriptionAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false