#%RAML 1.0 DataType
displayName: DiscountCodeSetMaxApplicationsAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setMaxApplications
examples:
  postman: !include ../../examples/DiscountCode/DiscountCodeSetMaxApplicationsAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMaxApplications
    required: true
  maxApplications:
    format: int64
    type: number
    (builtinType): number
    required: false