#%RAML 1.0 DataType
displayName: DiscountCodeSetCartPredicateAction
type: DiscountCodeUpdateAction
(builtinType): object
discriminatorValue: setCartPredicate
(package): "DiscountCode"
(docs-uri): "https://docs.commercetools.com/http-api-projects-discountCodes.html#set-cart-predicate"
examples:
  postman:
    strict: true
    value: !include ../../examples/DiscountCode/DiscountCodeSetCartPredicateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCartPredicate
    required: true
  cartPredicate:
    type: string
    (builtinType): string
    required: false