#%RAML 1.0 DataType
displayName: DiscountCodeReference
type: Reference
(builtinType): object
discriminatorValue: discount-code
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - discount-code
    required: true
  obj:
    type: DiscountCode
    (builtinType): object
    required: false