#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: CategoryCreatedMessagePayload

discriminatorValue: CategoryCreated
properties:
  type:
    type: string
  category:
    type: Category