#%RAML 1.0 DataType
displayName: CategoryCreatedMessage
type: Message
(builtinType): object
discriminatorValue: CategoryCreated
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#categorycreated-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CategoryCreated
    required: true
  category:
    type: Category
    (builtinType): object
    required: true