#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: CategoryCreatedMessagePayload
discriminator: type
discriminatorValue: CategoryCreated
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CategoryCreated
    required: true
  category:
    type: Category
    (builtinType): object
    required: true