#%RAML 1.0 DataType
displayName: CategorySlugChangedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: CategorySlugChanged
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#categoryslugchanged-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CategorySlugChanged
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: true