#%RAML 1.0 DataType
displayName: CustomLineItemStateTransitionMessage
type: Message
(builtinType): object
discriminatorValue: CustomLineItemStateTransition
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomLineItemStateTransition
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  transitionDate:
    type: datetime
    (builtinType): datetime
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  fromState:
    type: StateReference
    (builtinType): object
    required: true
  toState:
    type: StateReference
    (builtinType): object
    required: true