#%RAML 1.0 DataType
displayName: CustomerEmailVerifiedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: CustomerEmailVerified
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#customeremailverified-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerEmailVerified
    required: true