#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: CustomerAddressAddedMessagePayload
# discriminator: type
# discriminatorValue: CustomerAddressAdded
properties:
  type:
    default: CustomerAddressAdded
    required: true
    type: string
  address:
    required: true
    type: Address