#%RAML 1.0 DataType
displayName: CustomerEmailChangedMessage
type: Message
(builtinType): object
discriminatorValue: CustomerEmailChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerEmailChanged
    required: true
  email:
    type: string
    (builtinType): string
    required: true