#%RAML 1.0 DataType
displayName: CustomerEmailVerifiedMessage
type: Message
(builtinType): object
discriminatorValue: CustomerEmailVerified
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerEmailVerified
    required: true