#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: CustomerGroupSetMessagePayload

discriminatorValue: CustomerGroupSet
properties:
  type:
    required: true
    type: string
  customerGroup:
    required: true
    type: CustomerGroupReference