#%RAML 1.0 DataType
displayName: CustomerCompanyNameSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: CustomerCompanyNameSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#customercompanynameset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerCompanyNameSet
    required: true
  companyName:
    type: string
    (builtinType): string
    required: true