#%RAML 1.0 DataType
displayName: CustomerGroupSetMessage
type: Message
(builtinType): object
discriminatorValue: CustomerGroupSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#customergroupset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerGroupSet
    required: true
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: true