#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: CustomerCompanyNameSetMessagePayload
discriminator: type
discriminatorValue: CustomerCompanyNameSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerCompanyNameSet
    required: true
  companyName:
    type: string
    (builtinType): string
    required: true