#%RAML 1.0 DataType
displayName: CustomerCreatedMessage
type: Message
(builtinType): object
discriminatorValue: CustomerCreated
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerCreated
    required: true
  customer:
    type: Customer
    (builtinType): object
    required: true