#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: CustomerAddressChangedMessagePayload
discriminator: type
discriminatorValue: CustomerAddressChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerAddressChanged
    required: true
  address:
    type: Address
    (builtinType): object
    required: true