#%RAML 1.0 DataType
displayName: CustomerCompanyNameSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: CustomerCompanyNameSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerCompanyNameSet
    required: true
  companyName:
    type: string
    (builtinType): string
    required: true