#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: CustomerEmailVerifiedMessagePayload
discriminator: type
discriminatorValue: CustomerEmailVerified
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerEmailVerified
    required: true