#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: CustomerDateOfBirthSetMessagePayload
discriminator: type
discriminatorValue: CustomerDateOfBirthSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerDateOfBirthSet
    required: true
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: true