#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: CustomerAddressAddedMessagePayload
discriminator: type
discriminatorValue: CustomerAddressAdded
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerAddressAdded
    required: true
  address:
    type: Address
    (builtinType): object
    required: true