#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: CustomerEmailVerifiedMessagePayload
# discriminator: type
# discriminatorValue: CustomerEmailVerified
properties:
  type:
    default: CustomerEmailVerified
    required: true
    type: string