#%RAML 1.0 DataType
displayName: CustomerDateOfBirthSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: CustomerDateOfBirthSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#customerdateofbirthset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerDateOfBirthSet
    required: true
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: true