#%RAML 1.0 DataType
displayName: CustomerAddressRemovedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: CustomerAddressRemoved
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CustomerAddressRemoved
    required: true
  address:
    type: Address
    (builtinType): object
    required: true