#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: CustomerAddressAddedMessagePayload

discriminatorValue: CustomerAddressAdded
properties:
  type:
    type: string
  address:
    type: Address