#%RAML 1.0 DataType
displayName: DeliveryItemsUpdatedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: DeliveryItemsUpdated
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - DeliveryItemsUpdated
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true
  oldItems:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true