#%RAML 1.0 DataType
displayName: DeliveryRemovedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: DeliveryRemoved
(package): "Message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - DeliveryRemoved
    required: true
  delivery:
    type: Delivery
    (builtinType): object
    required: true