#%RAML 1.0 DataType
displayName: DeliveryAddedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: DeliveryAdded
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - DeliveryAdded
    required: true
  delivery:
    type: Delivery
    (builtinType): object
    required: true