#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: InventoryEntryDeletedMessagePayload
# discriminator: type
# discriminatorValue: InventoryEntryDeleted
properties:
  type:
    default: InventoryEntryDeleted
    required: true
    type: string
  supplyChannel:
    required: true
    type: ChannelReference
  sku:
    required: true
    type: string