#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: InventoryEntryDeletedMessagePayload
discriminator: type
discriminatorValue: InventoryEntryDeleted
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - InventoryEntryDeleted
    required: true
  supplyChannel:
    type: ChannelReference
    (builtinType): object
    required: true
  sku:
    type: string
    (builtinType): string
    required: true