#%RAML 1.0 DataType
displayName: InventoryEntryDeletedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: InventoryEntryDeleted
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#inventoryentrydeleted-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - InventoryEntryDeleted
    required: true
  sku:
    type: string
    (builtinType): string
    required: true
  supplyChannel:
    type: ChannelReference
    (builtinType): object
    required: true