#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: LineItemStateTransitionMessagePayload
discriminator: type
discriminatorValue: LineItemStateTransition
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - LineItemStateTransition
    required: true
  toState:
    type: StateReference
    (builtinType): object
    required: true
  fromState:
    type: StateReference
    (builtinType): object
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  transitionDate:
    type: datetime
    (builtinType): datetime
    required: true