#%RAML 1.0 DataType
displayName: LineItemStateTransitionMessage
type: Message
(builtinType): object
discriminatorValue: LineItemStateTransition
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#lineitemstatetransition-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - LineItemStateTransition
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  transitionDate:
    type: datetime
    (builtinType): datetime
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  fromState:
    type: StateReference
    (builtinType): object
    required: true
  toState:
    type: StateReference
    (builtinType): object
    required: true