#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: LineItemStateTransitionMessagePayload

discriminatorValue: LineItemStateTransition
properties:
  type:
    required: true
    type: string
  toState:
    required: true
    type: StateReference
  fromState:
    required: true
    type: StateReference
  quantity:
    required: true
    format: int64
    type: number
  lineItemId:
    required: true
    type: string
  transitionDate:
    required: true
    type: datetime