#%RAML 1.0 DataType
displayName: Message
type: LoggedResource
(builtinType): object
discriminator: type
(oneOf):
- OrderBillingAddressSetMessage
- OrderCreatedMessage
- OrderCustomLineItemDiscountSetMessage
- OrderCustomerEmailSetMessage
- OrderCustomerSetMessage
- OrderDeletedMessage
- OrderDiscountCodeAddedMessage
- OrderDiscountCodeRemovedMessage
- OrderDiscountCodeStateSetMessage
- OrderEditAppliedMessage
- OrderImportedMessage
- OrderLineItemAddedMessage
- OrderLineItemDiscountSetMessage
- OrderPaymentStateChangedMessage
- OrderReturnInfoAddedMessage
- OrderReturnShipmentStateChangedMessage
- OrderShipmentStateChangedMessage
- OrderShippingAddressSetMessage
- OrderShippingInfoSetMessage
- OrderShippingRateInputSetMessage
- OrderStateChangedMessage
- OrderStateTransitionMessage
- ParcelAddedToDeliveryMessage
- ParcelItemsUpdatedMessage
- ParcelMeasurementsUpdatedMessage
- ParcelRemovedFromDeliveryMessage
- ParcelTrackingDataUpdatedMessage
- PaymentCreatedMessage
- PaymentInteractionAddedMessage
- PaymentStatusInterfaceCodeSetMessage
- PaymentStatusStateTransitionMessage
- PaymentTransactionAddedMessage
- PaymentTransactionStateChangedMessage
- ProductAddedToCategoryMessage
- ProductCreatedMessage
- ProductDeletedMessage
- ProductImageAddedMessage
- ProductPriceDiscountsSetMessage
- ProductPriceExternalDiscountSetMessage
- ProductPublishedMessage
- ProductRemovedFromCategoryMessage
- ProductRevertedStagedChangesMessage
- ProductSlugChangedMessage
- ProductStateTransitionMessage
- ProductUnpublishedMessage
- ProductVariantDeletedMessage
- ReviewCreatedMessage
- ReviewRatingSetMessage
- ReviewStateTransitionMessage
- CategoryCreatedMessage
- CategorySlugChangedMessage
- CustomLineItemStateTransitionMessage
- CustomerAddressAddedMessage
- CustomerAddressChangedMessage
- CustomerAddressRemovedMessage
- CustomerCompanyNameSetMessage
- CustomerCreatedMessage
- CustomerDateOfBirthSetMessage
- CustomerEmailChangedMessage
- CustomerEmailVerifiedMessage
- CustomerGroupSetMessage
- DeliveryAddedMessage
- DeliveryAddressSetMessage
- DeliveryItemsUpdatedMessage
- DeliveryRemovedMessage
- InventoryEntryDeletedMessage
- LineItemStateTransitionMessage
properties:
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  sequenceNumber:
    format: int64
    type: number
    (builtinType): number
    required: true
  resource:
    type: Reference
    (builtinType): object
    required: true
  resourceUserProvidedIdentifiers:
    type: UserProvidedIdentifiers
    (builtinType): object
    required: false
  resourceVersion:
    format: int64
    type: number
    (builtinType): number
    required: true
  type:
    type: string
    (builtinType): string
    required: true