#%RAML 1.0 DataType
displayName: MessagePayload
type: object
(builtinType): object
discriminator: type
(oneOf):
- CategoryCreatedMessagePayload
- CategorySlugChangedMessagePayload
- CustomLineItemStateTransitionMessagePayload
- CustomerAddressAddedMessagePayload
- CustomerAddressChangedMessagePayload
- CustomerAddressRemovedMessagePayload
- CustomerCompanyNameSetMessagePayload
- CustomerCreatedMessagePayload
- CustomerDateOfBirthSetMessagePayload
- CustomerEmailChangedMessagePayload
- CustomerEmailVerifiedMessagePayload
- CustomerGroupSetMessagePayload
- DeliveryAddedMessagePayload
- DeliveryAddressSetMessagePayload
- DeliveryItemsUpdatedMessagePayload
- DeliveryRemovedMessagePayload
- InventoryEntryDeletedMessagePayload
- LineItemStateTransitionMessagePayload
- OrderBillingAddressSetMessagePayload
- OrderCreatedMessagePayload
- OrderCustomLineItemDiscountSetMessagePayload
- OrderCustomerEmailSetMessagePayload
- OrderCustomerGroupSetMessagePayload
- OrderCustomerSetMessagePayload
- OrderDeletedMessagePayload
- OrderDiscountCodeAddedMessagePayload
- OrderDiscountCodeRemovedMessagePayload
- OrderDiscountCodeStateSetMessagePayload
- OrderEditAppliedMessagePayload
- OrderImportedMessagePayload
- OrderLineItemAddedMessagePayload
- OrderLineItemDiscountSetMessagePayload
- OrderPaymentStateChangedMessagePayload
- OrderReturnInfoAddedMessagePayload
- OrderReturnShipmentStateChangedMessagePayload
- OrderShipmentStateChangedMessagePayload
- OrderShippingAddressSetMessagePayload
- OrderShippingInfoSetMessagePayload
- OrderShippingRateInputSetMessagePayload
- OrderStateChangedMessagePayload
- OrderStateTransitionMessagePayload
- ParcelAddedToDeliveryMessagePayload
- ParcelItemsUpdatedMessagePayload
- ParcelMeasurementsUpdatedMessagePayload
- ParcelRemovedFromDeliveryMessagePayload
- ParcelTrackingDataUpdatedMessagePayload
- PaymentCreatedMessagePayload
- PaymentInteractionAddedMessagePayload
- PaymentStatusInterfaceCodeSetMessagePayload
- PaymentStatusStateTransitionMessagePayload
- PaymentTransactionAddedMessagePayload
- PaymentTransactionStateChangedMessagePayload
- ProductAddedToCategoryMessagePayload
- ProductCreatedMessagePayload
- ProductDeletedMessagePayload
- ProductImageAddedMessagePayload
- ProductPriceDiscountsSetMessagePayload
- ProductPriceExternalDiscountSetMessagePayload
- ProductPublishedMessagePayload
- ProductRemovedFromCategoryMessagePayload
- ProductRevertedStagedChangesMessagePayload
- ProductSlugChangedMessagePayload
- ProductStateTransitionMessagePayload
- ProductUnpublishedMessagePayload
- ProductVariantDeletedMessagePayload
- ReviewCreatedMessagePayload
- ReviewRatingSetMessagePayload
- ReviewStateTransitionMessagePayload
(package): "Message"
properties:
  type:
    type: string
    (builtinType): string
    required: true