#%RAML 1.0 DataType
displayName: MessageConfiguration
type: object
(builtinType): object
properties:
  enabled:
    type: boolean
    (builtinType): boolean
    required: true
  deleteDaysAfterCreation:
    format: int32
    type: number
    (builtinType): number
    required: false