#%RAML 1.0 DataType
type: object
(originalType): object
displayName: MessageConfiguration
# 
# 
properties:
  deleteDaysAfterCreation:
    required: false
    format: int32
    type: number
  enabled:
    required: true
    type: boolean