#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderImportedMessagePayload
discriminator: type
discriminatorValue: OrderImported
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderImported
    required: true
  order:
    type: Order
    (builtinType): object
    required: true