#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderStateChangedMessagePayload

discriminatorValue: OrderStateChanged
properties:
  type:
    type: string
  oldOrderState:
    type: OrderState
  orderState:
    type: OrderState