#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderDiscountCodeRemovedMessagePayload
discriminator: type
discriminatorValue: OrderDiscountCodeRemoved
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderDiscountCodeRemoved
    required: true
  discountCode:
    type: DiscountCodeReference
    (builtinType): object
    required: true