#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderReturnInfoAddedMessagePayload

discriminatorValue: ReturnInfoAdded
properties:
  type:
    type: string
  returnInfo:
    type: ReturnInfo