#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderCustomLineItemDiscountSetMessagePayload
# discriminator: type
# discriminatorValue: OrderCustomLineItemDiscountSet
properties:
  type:
    default: OrderCustomLineItemDiscountSet
    required: true
    type: string
  customLineItemId:
    required: true
    type: string
  taxedPrice:
    required: false
    type: TaxedItemPrice
  discountedPricePerQuantity:
    required: true
    type: array
    items:
      type: DiscountedLineItemPriceForQuantity