#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderLineItemDiscountSetMessagePayload

discriminatorValue: OrderLineItemDiscountSet
properties:
  type:
    type: string
  totalPrice:
    type: Money
  lineItemId:
    type: string
  taxedPrice:
    type: TaxedItemPrice
  discountedPricePerQuantity:
    type: array
    items:
      type: DiscountedLineItemPriceForQuantity