#%RAML 1.0 DataType
displayName: OrderDiscountCodeAddedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderDiscountCodeAdded
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-message-types.html#orderdiscountcodeadded"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderDiscountCodeAdded
    required: true
  discountCode:
    type: DiscountCodeReference
    (builtinType): object
    required: true