#%RAML 1.0 DataType
displayName: OrderShippingRateInputSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderShippingRateInputSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-message-types.html#ordershippingrateinputset"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShippingRateInputSet
    required: true
  shippingRateInput:
    type: ShippingRateInput
    (builtinType): object
    required: false
  oldShippingRateInput:
    type: ShippingRateInput
    (builtinType): object
    required: false