#%RAML 1.0 DataType
displayName: OrderCreatedMessage
type: Message
(builtinType): object
discriminatorValue: OrderCreated
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#ordercreated-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderCreated
    required: true
  order:
    type: Order
    (builtinType): object
    required: true