#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderShippingRateInputSetMessagePayload
discriminator: type
discriminatorValue: OrderShippingRateInputSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShippingRateInputSet
    required: true
  shippingRateInput:
    type: ShippingRateInput
    (builtinType): object
    required: false
  oldShippingRateInput:
    type: ShippingRateInput
    (builtinType): object
    required: false