#%RAML 1.0 DataType
displayName: OrderDeletedMessage
type: Message
(builtinType): object
discriminatorValue: OrderDeleted
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderDeleted
    required: true
  order:
    type: Order
    (builtinType): object
    required: true