#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderDiscountCodeRemovedMessagePayload
# discriminator: type
# discriminatorValue: OrderDiscountCodeRemoved
properties:
  type:
    default: OrderDiscountCodeRemoved
    required: true
    type: string
  discountCode:
    required: true
    type: DiscountCodeReference