#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderPaymentStateChangedMessagePayload
discriminator: type
discriminatorValue: OrderPaymentStateChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderPaymentStateChanged
    required: true
  oldPaymentState:
    type: PaymentState
    (builtinType): string
    required: false
  paymentState:
    type: PaymentState
    (builtinType): string
    required: true