#%RAML 1.0 DataType
displayName: OrderCustomLineItemDiscountSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderCustomLineItemDiscountSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderCustomLineItemDiscountSet
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  discountedPricePerQuantity:
    type: array
    items:
      type: DiscountedLineItemPriceForQuantity
    (builtinType): array
    required: true
  taxedPrice:
    type: TaxedItemPrice
    (builtinType): object
    required: false