#%RAML 1.0 DataType
displayName: OrderCustomerEmailSetMessage
type: Message
(builtinType): object
discriminatorValue: OrderCustomerEmailSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderCustomerEmailSet
    required: true
  email:
    type: string
    (builtinType): string
    required: false
  oldEmail:
    type: string
    (builtinType): string
    required: false