#%RAML 1.0 DataType
displayName: OrderLineItemDiscountSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderLineItemDiscountSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderLineItemDiscountSet
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  discountedPricePerQuantity:
    type: array
    items:
      type: DiscountedLineItemPriceForQuantity
    (builtinType): array
    required: true
  totalPrice:
    type: Money
    (builtinType): object
    required: true
  taxedPrice:
    type: TaxedItemPrice
    (builtinType): object
    required: false