#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderShippingInfoSetMessagePayload
discriminator: type
discriminatorValue: OrderShippingInfoSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShippingInfoSet
    required: true
  shippingInfo:
    type: ShippingInfo
    (builtinType): object
    required: false
  oldShippingInfo:
    type: ShippingInfo
    (builtinType): object
    required: false