#%RAML 1.0 DataType
displayName: OrderReturnInfoAddedMessage
type: Message
(builtinType): object
discriminatorValue: ReturnInfoAdded
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ReturnInfoAdded
    required: true
  returnInfo:
    type: ReturnInfo
    (builtinType): object
    required: true