#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderDeletedMessagePayload
# discriminator: type
# discriminatorValue: OrderDeleted
properties:
  type:
    default: OrderDeleted
    required: true
    type: string
  order:
    required: true
    type: Order