#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderStateTransitionMessagePayload
# discriminator: type
# discriminatorValue: OrderStateTransition
properties:
  type:
    default: OrderStateTransition
    required: true
    type: string
  force:
    required: true
    type: boolean
  state:
    required: true
    type: StateReference