#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderCustomerSetMessagePayload
discriminator: type
discriminatorValue: OrderCustomerSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderCustomerSet
    required: true
  oldCustomerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  oldCustomer:
    type: CustomerReference
    (builtinType): object
    required: false
  customer:
    type: CustomerReference
    (builtinType): object
    required: false