#%RAML 1.0 DataType
displayName: OrderShippingAddressSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderShippingAddressSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#ordershippingaddressset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShippingAddressSet
    required: true
  address:
    type: Address
    (builtinType): object
    required: false
  oldAddress:
    type: Address
    (builtinType): object
    required: false