#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderReturnShipmentStateChangedMessagePayload
discriminator: type
discriminatorValue: OrderReturnShipmentStateChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderReturnShipmentStateChanged
    required: true
  returnItemId:
    type: string
    (builtinType): string
    required: true
  returnShipmentState:
    type: ReturnShipmentState
    (builtinType): string
    required: true