#%RAML 1.0 DataType
displayName: OrderLineItemAddedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderLineItemAdded
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderLineItemAdded
    required: true
  lineItem:
    type: LineItem
    (builtinType): object
    required: true
  addedQuantity:
    format: int64
    type: number
    (builtinType): number
    required: true