#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderBillingAddressSetMessagePayload
# discriminator: type
# discriminatorValue: OrderBillingAddressSet
properties:
  type:
    default: OrderBillingAddressSet
    required: true
    type: string
  oldAddress:
    required: false
    type: Address
  address:
    required: false
    type: Address