#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderCustomerEmailSetMessagePayload
discriminator: type
discriminatorValue: OrderCustomerEmailSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderCustomerEmailSet
    required: true
  oldEmail:
    type: string
    (builtinType): string
    required: false
  email:
    type: string
    (builtinType): string
    required: false