#%RAML 1.0 DataType
displayName: OrderReturnShipmentStateChangedMessage
type: Message
(builtinType): object
discriminatorValue: OrderReturnShipmentStateChanged
(package): "Message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderReturnShipmentStateChanged
    required: true
  returnItemId:
    type: string
    (builtinType): string
    required: true
  returnShipmentState:
    type: ReturnShipmentState
    (builtinType): string
    enum:
    - Advised
    - Returned
    - BackInStock
    - Unusable
    required: true