#%RAML 1.0 DataType
displayName: OrderShippingInfoSetMessage
type: Message
(builtinType): object
discriminatorValue: OrderShippingInfoSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShippingInfoSet
    required: true
  shippingInfo:
    type: ShippingInfo
    (builtinType): object
    required: false
  oldShippingInfo:
    type: ShippingInfo
    (builtinType): object
    required: false