#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderShippingInfoSetMessagePayload

discriminatorValue: OrderShippingInfoSet
properties:
  type:
    type: string
  shippingInfo:
    type: ShippingInfo
  oldShippingInfo:
    type: ShippingInfo