#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderShipmentStateChangedMessagePayload
discriminator: type
discriminatorValue: OrderShipmentStateChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShipmentStateChanged
    required: true
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: true
  oldShipmentState:
    type: ShipmentState
    (builtinType): string
    required: false