#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderBillingAddressSetMessagePayload
discriminator: type
discriminatorValue: OrderBillingAddressSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderBillingAddressSet
    required: true
  oldAddress:
    type: Address
    (builtinType): object
    required: false
  address:
    type: Address
    (builtinType): object
    required: false