#%RAML 1.0 DataType
displayName: OrderCustomerSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderCustomerSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-message-types.html#ordercustomeremailset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderCustomerSet
    required: true
  customer:
    type: CustomerReference
    (builtinType): object
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  oldCustomer:
    type: CustomerReference
    (builtinType): object
    required: false
  oldCustomerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false