#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderStateTransitionMessagePayload
discriminator: type
discriminatorValue: OrderStateTransition
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderStateTransition
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: true
  state:
    type: StateReference
    (builtinType): object
    required: true