#%RAML 1.0 DataType
displayName: OrderDiscountCodeAddedMessage
type: Message
(builtinType): object
discriminatorValue: OrderDiscountCodeAdded
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderDiscountCodeAdded
    required: true
  discountCode:
    type: DiscountCodeReference
    (builtinType): object
    required: true