#%RAML 1.0 DataType
displayName: OrderImportedMessage
type: Message
(builtinType): object
discriminatorValue: OrderImported
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#orderimported-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderImported
    required: true
  order:
    type: Order
    (builtinType): object
    required: true