#%RAML 1.0 DataType
displayName: OrderDiscountCodeStateSetMessage
type: Message
(builtinType): object
discriminatorValue: OrderDiscountCodeStateSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderDiscountCodeStateSet
    required: true
  discountCode:
    type: DiscountCodeReference
    (builtinType): object
    required: true
  state:
    type: DiscountCodeState
    (builtinType): string
    required: true
  oldState:
    type: DiscountCodeState
    (builtinType): string
    required: false