#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderShipmentStateChangedMessagePayload

discriminatorValue: OrderShipmentStateChanged
properties:
  type:
    required: true
    type: string
  shipmentState:
    required: true
    type: ShipmentState
  oldShipmentState:
    required: false
    type: ShipmentState