#%RAML 1.0 DataType
displayName: OrderShipmentStateChangedMessage
type: Message
(builtinType): object
discriminatorValue: OrderShipmentStateChanged
(package): "Message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShipmentStateChanged
    required: true
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: true
  oldShipmentState:
    type: ShipmentState
    (builtinType): string
    required: false