#%RAML 1.0 DataType
displayName: OrderStateChangedMessage
type: Message
(builtinType): object
discriminatorValue: OrderStateChanged
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#orderstatechanged-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderStateChanged
    required: true
  orderState:
    type: OrderState
    (builtinType): string
    required: true
  oldOrderState:
    type: OrderState
    (builtinType): string
    required: true