#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: OrderShippingAddressSetMessagePayload
discriminator: type
discriminatorValue: OrderShippingAddressSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShippingAddressSet
    required: true
  oldAddress:
    type: Address
    (builtinType): object
    required: false
  address:
    type: Address
    (builtinType): object
    required: false