#%RAML 1.0 DataType
displayName: OrderShipmentStateChangedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderShipmentStateChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderShipmentStateChanged
    required: true
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: true
  oldShipmentState:
    type: ShipmentState
    (builtinType): string
    required: false