#%RAML 1.0 DataType
displayName: OrderStateTransitionMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderStateTransition
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#orderstatetransition-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderStateTransition
    required: true
  state:
    type: StateReference
    (builtinType): object
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: true