#%RAML 1.0 DataType
displayName: OrderEditAppliedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderEditApplied
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#ordercreated-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderEditApplied
    required: true
  edit:
    type: OrderEditReference
    (builtinType): object
    required: true
  result:
    type: OrderEditApplied
    (builtinType): object
    required: true