#%RAML 1.0 DataType
displayName: OrderStateChangedMessage
type: Message
(builtinType): object
discriminatorValue: OrderStateChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderStateChanged
    required: true
  orderState:
    type: OrderState
    (builtinType): string
    required: true
  oldOrderState:
    type: OrderState
    (builtinType): string
    required: true