#%RAML 1.0 DataType
displayName: OrderPaymentStateChangedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: OrderPaymentStateChanged
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#orderpaymentstatechanged-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - OrderPaymentStateChanged
    required: true
  paymentState:
    type: PaymentState
    (builtinType): string
    required: true
  oldPaymentState:
    type: PaymentState
    (builtinType): string
    required: false