#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: OrderLineItemAddedMessagePayload
# discriminator: type
# discriminatorValue: OrderLineItemAdded
properties:
  type:
    default: OrderLineItemAdded
    required: true
    type: string
  lineItem:
    required: true
    type: LineItem
  addedQuantity:
    required: true
    format: int64
    type: number