#%RAML 1.0 DataType
displayName: OrderReturnInfoAddedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ReturnInfoAdded
(package): "Message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ReturnInfoAdded
    required: true
  returnInfo:
    type: ReturnInfo
    (builtinType): object
    required: true