#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ParcelRemovedFromDeliveryMessagePayload
# discriminator: type
# discriminatorValue: ParcelRemovedFromDelivery
properties:
  type:
    default: ParcelRemovedFromDelivery
    required: true
    type: string
  parcel:
    required: true
    type: Parcel
  deliveryId:
    required: true
    type: string