#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ParcelTrackingDataUpdatedMessagePayload
discriminator: type
discriminatorValue: ParcelTrackingDataUpdated
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ParcelTrackingDataUpdated
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  trackingData:
    type: TrackingData
    (builtinType): object
    required: false
  parcelId:
    type: string
    (builtinType): string
    required: true