#%RAML 1.0 DataType
displayName: ParcelAddedToDeliveryMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ParcelAddedToDelivery
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ParcelAddedToDelivery
    required: true
  delivery:
    type: Delivery
    (builtinType): object
    required: true
  parcel:
    type: Parcel
    (builtinType): object
    required: true