#%RAML 1.0 DataType
type: object
(originalType): Message
displayName: ParcelItemsUpdatedMessage

discriminatorValue: ParcelItemsUpdated
properties:
  createdAt:
    type: datetime
  lastModifiedAt:
    type: datetime
  id:
    type: string
  version:
    format: int64
    type: number
  createdBy:
    type: CreatedBy
  lastModifiedBy:
    type: LastModifiedBy
  sequenceNumber:
    format: int64
    type: number
  resource:
    type: Reference
  resourceUserProvidedIdentifiers:
    type: UserProvidedIdentifiers
  resourceVersion:
    format: int64
    type: number
  type:
    type: string
  deliveryId:
    type: string
  oldItems:
    type: array
    items:
      type: DeliveryItem
  items:
    type: array
    items:
      type: DeliveryItem
  parcelId:
    type: string