#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ParcelTrackingDataUpdatedMessagePayload
# discriminator: type
# discriminatorValue: ParcelTrackingDataUpdated
properties:
  type:
    default: ParcelTrackingDataUpdated
    required: true
    type: string
  deliveryId:
    required: true
    type: string
  trackingData:
    required: false
    type: TrackingData
  parcelId:
    required: true
    type: string