#%RAML 1.0 DataType
displayName: ParcelItemsUpdatedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ParcelItemsUpdated
(package): "Message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ParcelItemsUpdated
    required: true
  parcelId:
    type: string
    (builtinType): string
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: false
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true
  oldItems:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true