#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ParcelRemovedFromDeliveryMessagePayload
discriminator: type
discriminatorValue: ParcelRemovedFromDelivery
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ParcelRemovedFromDelivery
    required: true
  parcel:
    type: Parcel
    (builtinType): object
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true