#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ParcelMeasurementsUpdatedMessagePayload
discriminator: type
discriminatorValue: ParcelMeasurementsUpdated
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ParcelMeasurementsUpdated
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  measurements:
    type: ParcelMeasurements
    (builtinType): object
    required: false
  parcelId:
    type: string
    (builtinType): string
    required: true