#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ParcelMeasurementsUpdatedMessagePayload
# discriminator: type
# discriminatorValue: ParcelMeasurementsUpdated
properties:
  type:
    default: ParcelMeasurementsUpdated
    required: true
    type: string
  deliveryId:
    required: true
    type: string
  measurements:
    required: false
    type: ParcelMeasurements
  parcelId:
    required: true
    type: string