#%RAML 1.0 DataType
displayName: ParcelRemovedFromDeliveryMessage
type: Message
(builtinType): object
discriminatorValue: ParcelRemovedFromDelivery
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ParcelRemovedFromDelivery
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  parcel:
    type: Parcel
    (builtinType): object
    required: true