#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ParcelAddedToDeliveryMessagePayload
# discriminator: type
# discriminatorValue: ParcelAddedToDelivery
properties:
  type:
    default: ParcelAddedToDelivery
    required: true
    type: string
  delivery:
    required: true
    type: Delivery
  parcel:
    required: true
    type: Parcel