#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: PaymentStatusInterfaceCodeSetMessagePayload
discriminator: type
discriminatorValue: PaymentStatusInterfaceCodeSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentStatusInterfaceCodeSet
    required: true
  paymentId:
    type: string
    (builtinType): string
    required: true
  interfaceCode:
    type: string
    (builtinType): string
    required: true