#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: PaymentStatusStateTransitionMessagePayload
# discriminator: type
# discriminatorValue: PaymentStatusStateTransition
properties:
  type:
    default: PaymentStatusStateTransition
    required: true
    type: string
  force:
    required: true
    type: boolean
  state:
    required: true
    type: StateReference