#%RAML 1.0 DataType
displayName: PaymentTransactionStateChangedMessage
type: Message
(builtinType): object
discriminatorValue: PaymentTransactionStateChanged
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#paymenttransactionstatechanged-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentTransactionStateChanged
    required: true
  transactionId:
    type: string
    (builtinType): string
    required: true
  state:
    type: TransactionState
    (builtinType): string
    enum:
    - Initial
    - Pending
    - Success
    - Failure
    required: true