#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: PaymentStatusInterfaceCodeSetMessagePayload
# discriminator: type
# discriminatorValue: PaymentStatusInterfaceCodeSet
properties:
  type:
    default: PaymentStatusInterfaceCodeSet
    required: true
    type: string
  paymentId:
    required: true
    type: string
  interfaceCode:
    required: true
    type: string