#%RAML 1.0 DataType
displayName: PaymentTransactionAddedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: PaymentTransactionAdded
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#paymenttransactionadded-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentTransactionAdded
    required: true
  transaction:
    type: Transaction
    (builtinType): object
    required: true