#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: PaymentStatusStateTransitionMessagePayload
discriminator: type
discriminatorValue: PaymentStatusStateTransition
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentStatusStateTransition
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: true
  state:
    type: StateReference
    (builtinType): object
    required: true