#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: PaymentTransactionAddedMessagePayload
discriminator: type
discriminatorValue: PaymentTransactionAdded
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentTransactionAdded
    required: true
  transaction:
    type: Transaction
    (builtinType): object
    required: true