#%RAML 1.0 DataType
displayName: PaymentCreatedMessage
type: Message
(builtinType): object
discriminatorValue: PaymentCreated
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentCreated
    required: true
  payment:
    type: Payment
    (builtinType): object
    required: true