#%RAML 1.0 DataType
displayName: PaymentStatusInterfaceCodeSetMessage
type: Message
(builtinType): object
discriminatorValue: PaymentStatusInterfaceCodeSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentStatusInterfaceCodeSet
    required: true
  paymentId:
    type: string
    (builtinType): string
    required: true
  interfaceCode:
    type: string
    (builtinType): string
    required: true