#%RAML 1.0 DataType
displayName: PaymentCreatedMessage
type: Message
(builtinType): object
discriminatorValue: PaymentCreated
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#paymentcreated-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PaymentCreated
    required: true
  payment:
    type: Payment
    (builtinType): object
    required: true