#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ProductPriceExternalDiscountSetMessagePayload

discriminatorValue: ProductPriceExternalDiscountSet
properties:
  type:
    type: string
  discounted:
    type: DiscountedPrice
  staged:
    type: boolean
  variantId:
    type: integer
  priceId:
    type: string
  sku:
    type: string
  variantKey:
    type: string