#%RAML 1.0 DataType
displayName: ProductRevertedStagedChangesMessage
type: Message
(builtinType): object
discriminatorValue: ProductRevertedStagedChanges
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#productrevertedstagedchanges-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductRevertedStagedChanges
    required: true
  removedImageUrls:
    type: array
    items:
      type: string
    (builtinType): array
    required: true