#%RAML 1.0 DataType
type: MessagePayload
displayName: ProductAddedToCategoryMessagePayload

discriminatorValue: ProductAddedToCategory
properties:
   category:
      type: CategoryReference
   staged:
      type: boolean