#%RAML 1.0 DataType
displayName: ProductStateTransitionMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ProductStateTransition
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductStateTransition
    required: true
  state:
    type: StateReference
    (builtinType): object
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: true