#%RAML 1.0 DataType
displayName: ProductSlugChangedMessage
type: Message
(builtinType): object
discriminatorValue: ProductSlugChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductSlugChanged
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: true