#%RAML 1.0 DataType
displayName: ProductCreatedMessage
type: Message
(builtinType): object
discriminatorValue: ProductCreated
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#productcreated-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductCreated
    required: true
  productProjection:
    type: ProductProjection
    (builtinType): object
    required: true