#%RAML 1.0 DataType
displayName: ProductPriceDiscountsSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ProductPriceDiscountsSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-message-types.html#productpricediscountsset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductPriceDiscountsSet
    required: true
  updatedPrices:
    type: array
    items:
      type: ProductPriceDiscountsSetUpdatedPrice
    (builtinType): array
    required: true