#%RAML 1.0 DataType
displayName: ProductUnpublishedMessage
type: Message
(builtinType): object
discriminatorValue: ProductUnpublished
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductUnpublished
    required: true