#%RAML 1.0 DataType
type: MessagePayload
displayName: ProductPublishedMessagePayload

discriminatorValue: ProductPublished
properties:
   removedImageUrls:
      type: array
      items:
        type: string
   productProjection:
      type: ProductProjection
   scope:
      type: ProductPublishScope