#%RAML 1.0 DataType
displayName: ProductDeletedMessage
type: Message
(builtinType): object
discriminatorValue: ProductDeleted
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#productdeleted-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductDeleted
    required: true
  removedImageUrls:
    type: array
    items:
      type: string
    (builtinType): array
    required: true
  currentProjection:
    type: ProductProjection
    (builtinType): object
    required: true