#%RAML 1.0 DataType
displayName: ProductCreatedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ProductCreated
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductCreated
    required: true
  productProjection:
    type: ProductProjection
    (builtinType): object
    required: true