#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ProductRevertedStagedChangesMessagePayload

discriminatorValue: ProductRevertedStagedChanges
properties:
  type:
    type: string
  removedImageUrls:
    type: array
    items:
      type: string