#%RAML 1.0 DataType
displayName: ProductPriceExternalDiscountSetMessage
type: Message
(builtinType): object
discriminatorValue: ProductPriceExternalDiscountSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-message-types.html#productpriceexternaldiscountset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductPriceExternalDiscountSet
    required: true
  variantId:
    type: integer
    (builtinType): integer
    required: true
  variantKey:
    type: string
    (builtinType): string
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  priceId:
    type: string
    (builtinType): string
    required: true
  discounted:
    type: DiscountedPrice
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: true