#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ProductVariantDeletedMessagePayload
discriminator: type
discriminatorValue: ProductVariantDeleted
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductVariantDeleted
    required: true
  removedImageUrls:
    type: array
    items:
      type: string
    (builtinType): array
    required: true
  variant:
    type: ProductVariant
    (builtinType): object
    required: true