#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ProductUnpublishedMessagePayload
discriminator: type
discriminatorValue: ProductUnpublished
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductUnpublished
    required: true