#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ProductPublishedMessagePayload
discriminator: type
discriminatorValue: ProductPublished
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductPublished
    required: true
  removedImageUrls:
    type: array
    items:
      type: string
    (builtinType): array
    required: true
  productProjection:
    type: ProductProjection
    (builtinType): object
    required: true
  scope:
    type: ProductPublishScope
    (builtinType): string
    required: true