#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ProductPriceDiscountsSetMessagePayload
discriminator: type
discriminatorValue: ProductPriceDiscountsSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductPriceDiscountsSet
    required: true
  updatedPrices:
    type: array
    items:
      type: ProductPriceDiscountsSetUpdatedPrice
    (builtinType): array
    required: true