#%RAML 1.0 DataType
(builtinType): object
type: MessagePayload
displayName: ProductSlugChangedMessagePayload
discriminator: type
discriminatorValue: ProductSlugChanged
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductSlugChanged
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: true