#%RAML 1.0 DataType
displayName: ProductRemovedFromCategoryMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ProductRemovedFromCategory
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductRemovedFromCategory
    required: true
  category:
    type: CategoryReference
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: true