#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductPriceDiscountsSetUpdatedPrice
# 
# 
properties:
  discounted:
    required: false
    type: DiscountedPrice
  staged:
    required: true
    type: boolean
  variantId:
    required: true
    type: integer
  priceId:
    required: true
    type: string
  sku:
    required: false
    type: string
  variantKey:
    required: false
    type: string