#%RAML 1.0 DataType
type: object
(originalType): Message
displayName: ProductPriceExternalDiscountSetMessage
# discriminator: type
# discriminatorValue: ProductPriceExternalDiscountSet
properties:
  createdAt:
    required: true
    type: datetime
  lastModifiedAt:
    required: true
    type: datetime
  id:
    required: true
    type: string
  version:
    required: true
    format: int64
    type: number
  createdBy:
    required: false
    type: CreatedBy
  lastModifiedBy:
    required: false
    type: LastModifiedBy
  sequenceNumber:
    required: true
    format: int64
    type: number
  resource:
    required: true
    type: Reference
  resourceUserProvidedIdentifiers:
    required: false
    type: UserProvidedIdentifiers
  resourceVersion:
    required: true
    format: int64
    type: number
  type:
    default: ProductPriceExternalDiscountSet
    required: true
    type: string
  discounted:
    required: false
    type: DiscountedPrice
  staged:
    required: true
    type: boolean
  variantId:
    required: true
    type: integer
  priceId:
    required: true
    type: string
  sku:
    required: false
    type: string
  variantKey:
    required: false
    type: string