#%RAML 1.0 DataType
displayName: ProductImageAddedMessage
type: Message
(builtinType): object
discriminatorValue: ProductImageAdded
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#productimageadded-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductImageAdded
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  image:
    type: Image
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: true