#%RAML 1.0 DataType
displayName: ProductSlugChangedMessage
type: Message
(builtinType): object
discriminatorValue: ProductSlugChanged
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#productslugchanged-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductSlugChanged
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: true