#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ProductDeletedMessagePayload
# discriminator: type
# discriminatorValue: ProductDeleted
properties:
  type:
    default: ProductDeleted
    required: true
    type: string
  removedImageUrls:
    required: true
    type: array
    items:
      type: string
  currentProjection:
    required: true
    type: ProductProjection