#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ProductPriceDiscountsSetUpdatedPrice
properties:
  discounted:
    type: DiscountedPrice
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: true
  variantId:
    type: integer
    (builtinType): integer
    required: true
  priceId:
    type: string
    (builtinType): string
    required: true
  sku:
    type: string
    (builtinType): string
    required: false
  variantKey:
    type: string
    (builtinType): string
    required: false