#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductPriceDiscountsSetUpdatedPrice


properties:
  discounted:
    type: DiscountedPrice
  staged:
    type: boolean
  variantId:
    type: integer
  priceId:
    type: string
  sku:
    type: string
  variantKey:
    type: string