#%RAML 1.0 DataType
displayName: ProductUnpublishedMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ProductUnpublished
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#productunpublished-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ProductUnpublished
    required: true