#%RAML 1.0 DataType
displayName: ReviewCreatedMessage
type: Message
(builtinType): object
discriminatorValue: ReviewCreated
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#reviewcreated-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ReviewCreated
    required: true
  review:
    type: Review
    (builtinType): object
    required: true