#%RAML 1.0 DataType
displayName: ReviewRatingSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ReviewRatingSet
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ReviewRatingSet
    required: true
  oldRating:
    type: integer
    (builtinType): integer
    required: false
  newRating:
    type: integer
    (builtinType): integer
    required: false
  includedInStatistics:
    type: boolean
    (builtinType): boolean
    required: true
  target:
    type: Reference
    (builtinType): object
    required: false