#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ReviewCreatedMessagePayload
# discriminator: type
# discriminatorValue: ReviewCreated
properties:
  type:
    default: ReviewCreated
    required: true
    type: string
  review:
    required: true
    type: Review