#%RAML 1.0 DataType
displayName: ReviewRatingSetMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ReviewRatingSet
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#reviewratingset-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ReviewRatingSet
    required: true
  oldRating:
    type: number
    (builtinType): number
    required: false
  newRating:
    type: number
    (builtinType): number
    required: false
  includedInStatistics:
    type: boolean
    (builtinType): boolean
    required: true
  target:
    type: Reference
    (builtinType): object
    required: false