#%RAML 1.0 DataType
displayName: ReviewStateTransitionMessagePayload
type: MessagePayload
(builtinType): object
discriminatorValue: ReviewStateTransition
(package): "Message"
(docs-uri): "https://docs.commercetools.com/http-api-projects-messages.html#reviewstatetransition-message"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - ReviewStateTransition
    required: true
  oldState:
    type: StateReference
    (builtinType): object
    required: true
  newState:
    type: StateReference
    (builtinType): object
    required: true
  oldIncludedInStatistics:
    type: boolean
    (builtinType): boolean
    required: true
  newIncludedInStatistics:
    type: boolean
    (builtinType): boolean
    required: true
  target:
    type: Reference
    (builtinType): object
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: true