#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ReviewStateTransitionMessagePayload

discriminatorValue: ReviewStateTransition
properties:
  type:
    type: string
  newIncludedInStatistics:
    type: boolean
  oldState:
    type: StateReference
  force:
    type: boolean
  oldIncludedInStatistics:
    type: boolean
  newState:
    type: StateReference
  target:
    type: Reference