#%RAML 1.0 DataType
type: object
(originalType): MessagePayload
displayName: ReviewRatingSetMessagePayload

discriminatorValue: ReviewRatingSet
properties:
  type:
    type: string
  oldRating:
    type: number
  includedInStatistics:
    type: boolean
  newRating:
    type: number
  target:
    type: Reference