#%RAML 1.0 DataType
type: object
(originalType): object
displayName: UserProvidedIdentifiers
# 
# 
properties:
  orderNumber:
    required: false
    type: string
  externalId:
    required: false
    type: string
  sku:
    required: false
    type: string
  customerNumber:
    required: false
    type: string
  slug:
    required: false
    type: LocalizedString
  key:
    required: false
    type: string