#%RAML 1.0 DataType
displayName: MyCartSetLocaleAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: setLocale
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-carts#set-locale"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLocale
    required: true
  locale:
    type: string
    (builtinType): string
    required: false