#%RAML 1.0 DataType
type: object
(originalType): MyCartUpdateAction
displayName: MyCartSetLocaleAction

discriminatorValue: setLocale
properties:
  action:
    required: true
    type: string
  locale:
    required: false
    type: string