#%RAML 1.0 DataType
type: object
(originalType): object
displayName: MyCartDraft


properties:
  lineItems:
    type: array
    items:
      type: MyLineItemDraft
  country:
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    type: string
  itemShippingAddresses:
    description: |-
      Contains addresses for orders with multiple shipping addresses.
      Each address must contain a key which is unique in this cart.
    type: array
    items:
      type: Address
  taxMode:
    description: |-
      The `TaxMode` `Disabled` can not be set on the My Carts endpoint.
    type: TaxMode
  deleteDaysAfterLastModification:
    description: |-
      The cart will be deleted automatically if it hasn't been modified for the specified amount of days and it is in the `Active` CartState.
      If a ChangeSubscription for carts exists, a `ResourceDeleted` notification will be sent.
    format: int64
    type: number
  custom:
    description: |-
      The custom fields.
    type: CustomFieldsDraft
  shippingMethod:
    type: ShippingMethodResourceIdentifier
  customerEmail:
    type: string
  shippingAddress:
    type: Address
  currency:
    description: |-
      A three-digit currency code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    pattern: ^[A-Z]{3}$
    type: CurrencyCode
  billingAddress:
    type: Address
  locale:
    type: string
  inventoryMode:
    description: |-
      Default inventory mode is `None`.
    type: InventoryMode