#%RAML 1.0 DataType
type: object
(originalType): MyCartUpdateAction
displayName: MyCartRecalculateAction

discriminatorValue: recalculate
properties:
  action:
    type: string
  updateProductData:
    type: boolean