#%RAML 1.0 DataType
(builtinType): object
type: MyCartUpdateAction
displayName: MyCartChangeTaxModeAction
discriminator: action
discriminatorValue: changeTaxMode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxMode
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    required: true