#%RAML 1.0 DataType
type: object
(originalType): MyCartUpdateAction
displayName: MyCartAddItemShippingAddressAction

discriminatorValue: addItemShippingAddress
properties:
  action:
    required: true
    type: string
  address:
    required: true
    type: Address