#%RAML 1.0 DataType
(builtinType): object
type: MyCartUpdateAction
displayName: MyCartSetDeleteDaysAfterLastModificationAction
discriminator: action
discriminatorValue: setDeleteDaysAfterLastModification
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDeleteDaysAfterLastModification
    required: true
  deleteDaysAfterLastModification:
    type: integer
    (builtinType): integer
    required: false