#%RAML 1.0 DataType
displayName: MyCartSetLineItemCustomTypeAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: setLineItemCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemCustomType
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false