#%RAML 1.0 DataType
displayName: MyCartApplyDeltaToLineItemShippingDetailsTargetsAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: applyDeltaToLineItemShippingDetailsTargets
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - applyDeltaToLineItemShippingDetailsTargets
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  targetsDelta:
    type: array
    items:
      type: ItemShippingTarget
    (builtinType): array
    required: true