#%RAML 1.0 DataType
(builtinType): object
type: MyCartUpdateAction
displayName: MyCartRemovePaymentAction
discriminator: action
discriminatorValue: removePayment
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removePayment
    required: true
  payment:
    type: PaymentResourceIdentifier
    (builtinType): object
    required: true