#%RAML 1.0 DataType
displayName: MyCartRemoveItemShippingAddressAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: removeItemShippingAddress
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeItemShippingAddress
    required: true
  addressKey:
    type: string
    (builtinType): string
    required: true