#%RAML 1.0 DataType
(builtinType): object
type: MyCartUpdateAction
displayName: MyCartSetLineItemShippingDetailsAction
discriminator: action
discriminatorValue: setLineItemShippingDetails
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemShippingDetails
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false
  lineItemId:
    type: string
    (builtinType): string
    required: true