#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: MyCartUpdateAction
discriminator: action
(subTypes):
- MyCartAddDiscountCodeAction
- MyCartAddItemShippingAddressAction
- MyCartAddLineItemAction
- MyCartAddPaymentAction
- MyCartApplyDeltaToLineItemShippingDetailsTargetsAction
- MyCartChangeLineItemQuantityAction
- MyCartChangeTaxModeAction
- MyCartRecalculateAction
- MyCartRemoveDiscountCodeAction
- MyCartRemoveItemShippingAddressAction
- MyCartRemoveLineItemAction
- MyCartRemovePaymentAction
- MyCartSetBillingAddressAction
- MyCartSetCountryAction
- MyCartSetCustomFieldAction
- MyCartSetCustomShippingMethodAction
- MyCartSetCustomTypeAction
- MyCartSetDeleteDaysAfterLastModificationAction
- MyCartSetLineItemCustomFieldAction
- MyCartSetLineItemCustomTypeAction
- MyCartSetLineItemShippingDetailsAction
- MyCartSetLocaleAction
- MyCartSetShippingAddressAction
- MyCartSetShippingMethodAction
- MyCartUpdateItemShippingAddressAction
properties:
  action:
    type: string
    (builtinType): string
    required: true