#%RAML 1.0 DataType
type: object
(originalType): MyCartUpdateAction
displayName: MyCartSetCustomShippingMethodAction

discriminatorValue: setCustomShippingMethod
properties:
  action:
    required: true
    type: string
  shippingRate:
    required: true
    type: ShippingRateDraft
  externalTaxRate:
    required: false
    type: ExternalTaxRateDraft
  shippingMethodName:
    required: true
    type: string
  taxCategory:
    required: false
    type: TaxCategoryResourceIdentifier