#%RAML 1.0 DataType
(builtinType): object
type: LoggedResource
displayName: MyCart
properties:
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  country:
    type: CountryCode
    (builtinType): string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    required: false
  totalPrice:
    type: TypedMoney
    (builtinType): object
    required: true
  shippingRateInput:
    type: ShippingRateInput
    (builtinType): object
    required: false
  taxedPrice:
    type: TaxedPrice
    (builtinType): object
    required: false
  origin:
    type: CartOrigin
    (builtinType): string
    required: true
  deleteDaysAfterLastModification:
    type: integer
    (builtinType): integer
    required: false
  shippingInfo:
    type: ShippingInfo
    (builtinType): object
    required: false
  refusedGifts:
    type: array
    items:
      type: CartDiscountReference
    (builtinType): array
    required: true
  locale:
    type: string
    (builtinType): string
    required: false
  inventoryMode:
    type: InventoryMode
    (builtinType): string
    required: false
  lineItems:
    type: array
    items:
      type: LineItem
    (builtinType): array
    required: true
  customLineItems:
    type: array
    items:
      type: CustomLineItem
    (builtinType): array
    required: true
  itemShippingAddresses:
    type: array
    items:
      type: Address
    (builtinType): array
    required: false
  customerEmail:
    type: string
    (builtinType): string
    required: false
  cartState:
    type: CartState
    (builtinType): string
    required: true
  customerId:
    type: string
    (builtinType): string
    required: false
  anonymousId:
    type: string
    (builtinType): string
    required: false
  discountCodes:
    type: array
    items:
      type: DiscountCodeInfo
    (builtinType): array
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  taxCalculationMode:
    type: TaxCalculationMode
    (builtinType): string
    required: true
  store:
    type: StoreKeyReference
    (builtinType): object
    required: false
  taxRoundingMode:
    type: RoundingMode
    (builtinType): string
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    required: true
  shippingAddress:
    type: Address
    (builtinType): object
    required: false
  billingAddress:
    type: Address
    (builtinType): object
    required: false
  paymentInfo:
    type: PaymentInfo
    (builtinType): object
    required: false