#%RAML 1.0 DataType
displayName: MyCartSetDeleteDaysAfterLastModificationAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: setDeleteDaysAfterLastModification
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-carts#set-deletedaysafterlastmodification-beta"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDeleteDaysAfterLastModification
    required: true
  deleteDaysAfterLastModification:
    type: integer
    (builtinType): integer
    required: false