#%RAML 1.0 DataType
displayName: MyCartRecalculateAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: recalculate
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-carts#recalculate"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - recalculate
    required: true
  updateProductData:
    type: boolean
    (builtinType): boolean
    required: false