#%RAML 1.0 DataType
(builtinType): object
type: MyCartUpdateAction
displayName: MyCartSetLocaleAction
discriminator: action
discriminatorValue: setLocale
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLocale
    required: true
  locale:
    type: string
    (builtinType): string
    required: false