#%RAML 1.0 DataType
displayName: MyCartAddPaymentAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: addPayment
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addPayment
    required: true
  payment:
    type: PaymentResourceIdentifier
    (builtinType): object
    required: true