#%RAML 1.0 DataType
displayName: MyCartSetShippingMethodAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: setShippingMethod
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-carts#set-shipping-method"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethod
    required: true
  shippingMethod:
    type: ShippingMethodResourceIdentifier
    (builtinType): object
    required: false
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false