#%RAML 1.0 DataType
displayName: MyCartChangeTaxModeAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: changeTaxMode
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-carts#change-taxmode"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxMode
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    enum:
    - Platform
    - External
    - ExternalAmount
    - Disabled
    required: true