#%RAML 1.0 DataType
displayName: MyCartDraft
type: object
(builtinType): object
properties:
  lineItems:
    type: array
    items:
      type: MyLineItemDraft
    (builtinType): array
    required: false
  country:
    type: string
    (builtinType): string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    required: false
  itemShippingAddresses:
    type: array
    items:
      type: Address
    (builtinType): array
    description: |-
      Contains addresses for orders with multiple shipping addresses.
               Each address must contain a key which is unique in this cart.
    required: false
  taxMode:
    type: TaxMode
    (builtinType): string
    description: |-
      The `TaxMode` `Disabled` can not be set on the My Carts endpoint.
    required: false
  deleteDaysAfterLastModification:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The cart will be deleted automatically if it hasn't been modified for the specified amount of days and it is in the `Active` CartState.
               If a ChangeSubscription for carts exists, a `ResourceDeleted` notification will be sent.
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  shippingMethod:
    type: ShippingMethodResourceIdentifier
    (builtinType): object
    required: false
  customerEmail:
    type: string
    (builtinType): string
    required: false
  shippingAddress:
    type: Address
    (builtinType): object
    required: false
  currency:
    pattern: ^[A-Z]{3}$
    type: CurrencyCode
    (builtinType): string
    description: |-
      A three-digit currency code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    required: true
  billingAddress:
    type: Address
    (builtinType): object
    required: false
  locale:
    type: string
    (builtinType): string
    required: false
  inventoryMode:
    type: InventoryMode
    (builtinType): string
    description: |-
      Default inventory mode is `None`.
    required: false