#%RAML 1.0 DataType
displayName: MyCartChangeTaxModeAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: changeTaxMode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxMode
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    required: true