#%RAML 1.0 DataType
displayName: MyCartRemoveLineItemAction
type: MyCartUpdateAction
(builtinType): object
discriminatorValue: removeLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLineItem
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    type: number
    (builtinType): number
    required: false
  externalPrice:
    type: Money
    (builtinType): object
    required: false
  externalTotalPrice:
    type: ExternalLineItemTotalPrice
    (builtinType): object
    required: false
  shippingDetailsToRemove:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false