#%RAML 1.0 DataType
displayName: MyCustomerSetDefaultShippingAddressAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: setDefaultShippingAddress
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-default-shipping-address"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDefaultShippingAddress
    required: true
  addressId:
    type: string
    (builtinType): string
    required: false