#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerSetSalutationAction
# discriminator: action
# discriminatorValue: setSalutation
properties:
  action:
    default: setSalutation
    required: true
    type: string
  salutation:
    required: false
    type: string