#%RAML 1.0 DataType
(builtinType): object
type: MyCustomerUpdateAction
displayName: MyCustomerSetDefaultShippingAddressAction
discriminator: action
discriminatorValue: setDefaultShippingAddress
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDefaultShippingAddress
    required: true
  addressId:
    type: string
    (builtinType): string
    required: false