#%RAML 1.0 DataType
displayName: MyCustomerAddShippingAddressIdAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: addShippingAddressId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShippingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true