#%RAML 1.0 DataType
displayName: MyCustomerSetDateOfBirthAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: setDateOfBirth
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDateOfBirth
    required: true
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: false