#%RAML 1.0 DataType
displayName: MyCustomerSetFirstNameAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: setFirstName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setFirstName
    required: true
  firstName:
    type: string
    (builtinType): string
    required: false