#%RAML 1.0 DataType
(builtinType): object
type: MyCustomerUpdateAction
displayName: MyCustomerRemoveShippingAddressIdAction
discriminator: action
discriminatorValue: removeShippingAddressId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeShippingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true