#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerSetDefaultBillingAddressAction
# discriminator: action
# discriminatorValue: setDefaultBillingAddress
properties:
  action:
    default: setDefaultBillingAddress
    required: true
    type: string
  addressId:
    required: false
    type: string