#%RAML 1.0 DataType
(builtinType): object
type: MyCustomerUpdateAction
displayName: MyCustomerSetDefaultBillingAddressAction
discriminator: action
discriminatorValue: setDefaultBillingAddress
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDefaultBillingAddress
    required: true
  addressId:
    type: string
    (builtinType): string
    required: false