#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerChangeEmailAction
# discriminator: action
# discriminatorValue: changeEmail
properties:
  action:
    default: changeEmail
    required: true
    type: string
  email:
    required: true
    type: string