#%RAML 1.0 DataType
displayName: MyCustomerRemoveBillingAddressIdAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: removeBillingAddressId
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#remove-billing-address-id"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeBillingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true