#%RAML 1.0 DataType
displayName: MyCustomer
type: LoggedResource
(builtinType): object
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#customer"
(updateType): "MyCustomerUpdate"
(actionType): "MyCustomerUpdateAction"
properties:
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  customerNumber:
    type: string
    (builtinType): string
    required: false
  email:
    type: string
    (builtinType): string
    required: true
  password:
    type: string
    (builtinType): string
    required: true
  firstName:
    type: string
    (builtinType): string
    required: false
  lastName:
    type: string
    (builtinType): string
    required: false
  middleName:
    type: string
    (builtinType): string
    required: false
  title:
    type: string
    (builtinType): string
    required: false
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: false
  companyName:
    type: string
    (builtinType): string
    required: false
  vatId:
    type: string
    (builtinType): string
    required: false
  addresses:
    type: array
    items:
      type: Address
    (builtinType): array
    required: true
  defaultShippingAddressId:
    type: string
    (builtinType): string
    required: false
  shippingAddressIds:
    type: array
    items:
      type: string
    (builtinType): array
    required: false
  defaultBillingAddressId:
    type: string
    (builtinType): string
    required: false
  billingAddressIds:
    type: array
    items:
      type: string
    (builtinType): array
    required: false
  isEmailVerified:
    type: boolean
    (builtinType): boolean
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  locale:
    type: string
    (builtinType): string
    required: false
  salutation:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false
  stores:
    type: array
    items:
      type: StoreKeyReference
    (builtinType): array
    required: false