#%RAML 1.0 DataType
displayName: MyCustomerSetLastNameAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: setLastName
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-last-name"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLastName
    required: true
  lastName:
    type: string
    (builtinType): string
    required: false