#%RAML 1.0 DataType
type: object
(originalType): object
displayName: MyCustomerDraft


properties:
  lastName:
    type: string
  addresses:
    description: |-
      Sets the ID of each address to be unique in the addresses list.
    type: array
    items:
      type: Address
  defaultShippingAddress:
    description: |-
      The index of the address in the addresses array.
      The `defaultShippingAddressId` of the customer will be set to the ID of that address.
    format: int64
    type: number
  stores:
    type: array
    items:
      type: StoreResourceIdentifier
  custom:
    description: |-
      The custom fields.
    type: CustomFields
  companyName:
    type: string
  vatId:
    type: string
  dateOfBirth:
    type: date-only
  locale:
    type: string
  title:
    type: string
  firstName:
    type: string
  password:
    type: string
  middleName:
    type: string
  defaultBillingAddress:
    description: |-
      The index of the address in the addresses array.
      The `defaultBillingAddressId` of the customer will be set to the ID of that address.
    format: int64
    type: number
  email:
    type: string