#%RAML 1.0 DataType
displayName: MyCustomerSetCompanyNameAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: setCompanyName
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#set-company-name"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCompanyName
    required: true
  companyName:
    type: string
    (builtinType): string
    required: false