#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerSetMiddleNameAction
# discriminator: action
# discriminatorValue: setMiddleName
properties:
  action:
    default: setMiddleName
    required: true
    type: string
  middleName:
    required: false
    type: string