#%RAML 1.0 DataType
(builtinType): object
type: MyCustomerUpdateAction
displayName: MyCustomerSetMiddleNameAction
discriminator: action
discriminatorValue: setMiddleName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMiddleName
    required: true
  middleName:
    type: string
    (builtinType): string
    required: false