#%RAML 1.0 DataType
(builtinType): object
type: MyCustomerUpdateAction
displayName: MyCustomerSetLastNameAction
discriminator: action
discriminatorValue: setLastName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLastName
    required: true
  lastName:
    type: string
    (builtinType): string
    required: false