#%RAML 1.0 DataType
(builtinType): object
type: MyCustomerUpdateAction
displayName: MyCustomerRemoveAddressAction
discriminator: action
discriminatorValue: removeAddress
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAddress
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true