#%RAML 1.0 DataType
displayName: MyCustomer
type: LoggedResource
(builtinType): object
properties:
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  lastName:
    type: string
    (builtinType): string
    required: false
  addresses:
    type: array
    items:
      type: Address
    (builtinType): array
    required: true
  companyName:
    type: string
    (builtinType): string
    required: false
  vatId:
    type: string
    (builtinType): string
    required: false
  locale:
    type: string
    (builtinType): string
    required: false
  title:
    type: string
    (builtinType): string
    required: false
  isEmailVerified:
    type: boolean
    (builtinType): boolean
    required: true
  shippingAddressIds:
    type: array
    items:
      type: string
    (builtinType): array
    required: false
  password:
    type: string
    (builtinType): string
    required: true
  key:
    type: string
    (builtinType): string
    required: false
  email:
    type: string
    (builtinType): string
    required: true
  stores:
    type: array
    items:
      type: StoreKeyReference
    (builtinType): array
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  externalId:
    type: string
    (builtinType): string
    required: false
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: false
  billingAddressIds:
    type: array
    items:
      type: string
    (builtinType): array
    required: false
  defaultShippingAddressId:
    type: string
    (builtinType): string
    required: false
  customerNumber:
    type: string
    (builtinType): string
    required: false
  defaultBillingAddressId:
    type: string
    (builtinType): string
    required: false
  firstName:
    type: string
    (builtinType): string
    required: false
  middleName:
    type: string
    (builtinType): string
    required: false
  salutation:
    type: string
    (builtinType): string
    required: false