#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: MyCustomerDraft
properties:
  lastName:
    type: string
    (builtinType): string
    required: false
  addresses:
    type: array
    items:
      type: Address
    (builtinType): array
    description: |-
      Sets the ID of each address to be unique in the addresses list.
    required: false
  defaultShippingAddress:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The index of the address in the addresses array.
               The `defaultShippingAddressId` of the customer will be set to the ID of that address.
    required: false
  stores:
    type: array
    items:
      type: StoreResourceIdentifier
    (builtinType): array
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  companyName:
    type: string
    (builtinType): string
    required: false
  vatId:
    type: string
    (builtinType): string
    required: false
  dateOfBirth:
    type: date-only
    (builtinType): date-only
    required: false
  locale:
    type: string
    (builtinType): string
    required: false
  title:
    type: string
    (builtinType): string
    required: false
  firstName:
    type: string
    (builtinType): string
    required: false
  password:
    type: string
    (builtinType): string
    required: true
  middleName:
    type: string
    (builtinType): string
    required: false
  defaultBillingAddress:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The index of the address in the addresses array.
               The `defaultBillingAddressId` of the customer will be set to the ID of that address.
    required: false
  email:
    type: string
    (builtinType): string
    required: true