#%RAML 1.0 DataType
displayName: MyCustomerRemoveBillingAddressIdAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: removeBillingAddressId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeBillingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true