#%RAML 1.0 DataType
displayName: MyCustomerAddShippingAddressIdAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: addShippingAddressId
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customers.html#add-shipping-address-id"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShippingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true