#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerAddShippingAddressIdAction
# discriminator: action
# discriminatorValue: addShippingAddressId
properties:
  action:
    default: addShippingAddressId
    required: true
    type: string
  addressId:
    required: true
    type: string