#%RAML 1.0 DataType
displayName: MyCustomerUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- MyCustomerAddAddressAction
- MyCustomerAddBillingAddressIdAction
- MyCustomerAddShippingAddressIdAction
- MyCustomerChangeAddressAction
- MyCustomerChangeEmailAction
- MyCustomerRemoveAddressAction
- MyCustomerRemoveBillingAddressIdAction
- MyCustomerRemoveShippingAddressIdAction
- MyCustomerSetCompanyNameAction
- MyCustomerSetCustomFieldAction
- MyCustomerSetCustomTypeAction
- MyCustomerSetDateOfBirthAction
- MyCustomerSetDefaultBillingAddressAction
- MyCustomerSetDefaultShippingAddressAction
- MyCustomerSetFirstNameAction
- MyCustomerSetLastNameAction
- MyCustomerSetLocaleAction
- MyCustomerSetMiddleNameAction
- MyCustomerSetSalutationAction
- MyCustomerSetTitleAction
- MyCustomerSetVatIdAction
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-profile#update-actions"
properties:
  action:
    type: string
    (builtinType): string
    required: true