#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerSetFirstNameAction
# discriminator: action
# discriminatorValue: setFirstName
properties:
  action:
    default: setFirstName
    required: true
    type: string
  firstName:
    required: false
    type: string