#%RAML 1.0 DataType
displayName: MyCustomerSetLastNameAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: setLastName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLastName
    required: true
  lastName:
    type: string
    (builtinType): string
    required: false