#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerSetLocaleAction

discriminatorValue: setLocale
properties:
  action:
    type: string
  locale:
    type: string