#%RAML 1.0 DataType
displayName: MyCustomerSetDefaultBillingAddressAction
type: MyCustomerUpdateAction
(builtinType): object
discriminatorValue: setDefaultBillingAddress
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDefaultBillingAddress
    required: true
  addressId:
    type: string
    (builtinType): string
    required: false