#%RAML 1.0 DataType
type: object
(originalType): LoggedResource
displayName: MyCustomer


properties:
  createdAt:
    type: datetime
  lastModifiedAt:
    type: datetime
  id:
    type: string
  version:
    format: int64
    type: number
  createdBy:
    type: CreatedBy
  lastModifiedBy:
    type: LastModifiedBy
  lastName:
    type: string
  addresses:
    type: array
    items:
      type: Address
  companyName:
    type: string
  vatId:
    type: string
  locale:
    type: string
  title:
    type: string
  isEmailVerified:
    type: boolean
  shippingAddressIds:
    type: array
    items:
      type: string
  password:
    type: string
  key:
    type: string
  email:
    type: string
  stores:
    type: array
    items:
      type: StoreKeyReference
  customerGroup:
    type: CustomerGroupReference
  custom:
    type: CustomFields
  externalId:
    type: string
  dateOfBirth:
    type: date-only
  billingAddressIds:
    type: array
    items:
      type: string
  defaultShippingAddressId:
    type: string
  customerNumber:
    type: string
  defaultBillingAddressId:
    type: string
  firstName:
    type: string
  middleName:
    type: string
  salutation:
    type: string