#%RAML 1.0 DataType
type: object
(originalType): MyCustomerUpdateAction
displayName: MyCustomerSetTitleAction
# discriminator: action
# discriminatorValue: setTitle
properties:
  action:
    default: setTitle
    required: true
    type: string
  title:
    required: false
    type: string