#%RAML 1.0 DataType
(builtinType): object
type: MyCustomerUpdateAction
displayName: MyCustomerAddBillingAddressIdAction
discriminator: action
discriminatorValue: addBillingAddressId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addBillingAddressId
    required: true
  addressId:
    type: string
    (builtinType): string
    required: true