#%RAML 1.0 DataType
type: object
(originalType): LoggedResource
displayName: MyOrder


properties:
  createdAt:
    type: datetime
  lastModifiedAt:
    type: datetime
  id:
    type: string
  version:
    format: int64
    type: number
  createdBy:
    type: CreatedBy
  lastModifiedBy:
    type: LastModifiedBy
  shipmentState:
    type: ShipmentState
  country:
    type: string
  orderNumber:
    type: string
  totalPrice:
    type: TypedMoney
  shippingRateInput:
    type: ShippingRateInput
  taxedPrice:
    type: TaxedPrice
  origin:
    type: CartOrigin
  shippingInfo:
    type: ShippingInfo
  refusedGifts:
    type: array
    items:
      type: CartDiscountReference
  locale:
    type: string
  cart:
    type: CartReference
  inventoryMode:
    type: InventoryMode
  orderState:
    type: OrderState
  returnInfo:
    type: array
    items:
      type: ReturnInfo
  lineItems:
    type: array
    items:
      type: LineItem
  customLineItems:
    type: array
    items:
      type: CustomLineItem
  itemShippingAddresses:
    type: array
    items:
      type: Address
  customerEmail:
    type: string
  customerId:
    type: string
  state:
    type: StateReference
  paymentState:
    type: PaymentState
  anonymousId:
    type: string
  discountCodes:
    type: array
    items:
      type: DiscountCodeInfo
  completedAt:
    type: datetime
  customerGroup:
    type: CustomerGroupReference
  custom:
    type: CustomFields
  taxCalculationMode:
    type: TaxCalculationMode
  store:
    type: StoreKeyReference
  lastMessageSequenceNumber:
    format: int64
    type: number
  syncInfo:
    type: array
    items:
      type: SyncInfo
  taxRoundingMode:
    type: RoundingMode
  taxMode:
    type: TaxMode
  shippingAddress:
    type: Address
  billingAddress:
    type: Address
  paymentInfo:
    type: PaymentInfo