#%RAML 1.0 DataType
displayName: MyOrder
type: LoggedResource
(builtinType): object
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#order"
properties:
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  completedAt:
    type: datetime
    (builtinType): datetime
    required: false
  orderNumber:
    type: string
    (builtinType): string
    required: false
  customerId:
    type: string
    (builtinType): string
    required: false
  customerEmail:
    type: string
    (builtinType): string
    required: false
  anonymousId:
    type: string
    (builtinType): string
    required: false
  store:
    type: StoreKeyReference
    (builtinType): object
    required: false
  lineItems:
    type: array
    items:
      type: LineItem
    (builtinType): array
    required: true
  customLineItems:
    type: array
    items:
      type: CustomLineItem
    (builtinType): array
    required: true
  totalPrice:
    type: TypedMoney
    (builtinType): object
    required: true
  taxedPrice:
    type: TaxedPrice
    (builtinType): object
    required: false
  shippingAddress:
    type: Address
    (builtinType): object
    required: false
  billingAddress:
    type: Address
    (builtinType): object
    required: false
  taxMode:
    type: TaxMode
    (builtinType): string
    enum:
    - Platform
    - External
    - ExternalAmount
    - Disabled
    required: false
  taxRoundingMode:
    type: RoundingMode
    (builtinType): string
    enum:
    - HalfEven
    - HalfUp
    - HalfDown
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  country:
    type: string
    (builtinType): string
    required: false
  orderState:
    type: OrderState
    (builtinType): string
    enum:
    - Open
    - Confirmed
    - Complete
    - Cancelled
    required: true
  state:
    type: StateReference
    (builtinType): object
    required: false
  shipmentState:
    type: ShipmentState
    (builtinType): string
    enum:
    - Shipped
    - Ready
    - Pending
    - Delayed
    - Partial
    - Backorder
    required: false
  paymentState:
    type: PaymentState
    (builtinType): string
    enum:
    - BalanceDue
    - Failed
    - Pending
    - CreditOwed
    - Paid
    required: false
  shippingInfo:
    type: ShippingInfo
    (builtinType): object
    required: false
  syncInfo:
    type: array
    items:
      type: SyncInfo
    (builtinType): array
    required: true
  returnInfo:
    type: array
    items:
      type: ReturnInfo
    (builtinType): array
    required: false
  discountCodes:
    type: array
    items:
      type: DiscountCodeInfo
    (builtinType): array
    required: false
  lastMessageSequenceNumber:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  cart:
    type: CartReference
    (builtinType): object
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  paymentInfo:
    type: PaymentInfo
    (builtinType): object
    required: false
  locale:
    type: string
    (builtinType): string
    required: false
  inventoryMode:
    type: InventoryMode
    (builtinType): string
    enum:
    - TrackOnly
    - ReserveOnOrder
    - None
    required: false
  origin:
    type: CartOrigin
    (builtinType): string
    enum:
    - Customer
    - Merchant
    required: true
  taxCalculationMode:
    type: TaxCalculationMode
    (builtinType): string
    enum:
    - LineItemLevel
    - UnitPriceLevel
    required: false
  shippingRateInput:
    type: ShippingRateInput
    (builtinType): object
    required: false
  itemShippingAddresses:
    type: array
    items:
      type: Address
    (builtinType): array
    required: false
  refusedGifts:
    type: array
    items:
      type: CartDiscountReference
    (builtinType): array
    required: true