#%RAML 1.0 DataType
displayName: MyPaymentDraft
type: object
(builtinType): object
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-payments#mypaymentdraft"
properties:
  amountPlanned:
    type: Money
    (builtinType): object
    description: |-
      How much money this payment intends to receive from the customer.
      The value usually matches the cart or order gross total.
    required: true
  paymentMethodInfo:
    type: PaymentMethodInfo
    (builtinType): object
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false
  transaction:
    type: MyTransactionDraft
    (builtinType): object
    description: |-
      A list of financial transactions of the `Authorization` or `Charge`
      TransactionTypes.
    required: false