#%RAML 1.0 DataType
displayName: MyPaymentUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- MyPaymentAddTransactionAction
- MyPaymentChangeAmountPlannedAction
- MyPaymentSetCustomFieldAction
- MyPaymentSetMethodInfoInterfaceAction
- MyPaymentSetMethodInfoMethodAction
- MyPaymentSetMethodInfoNameAction
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-payments#update-actions"
properties:
  action:
    type: string
    (builtinType): string
    required: true