#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: MyPaymentDraft
properties:
  paymentMethodInfo:
    type: PaymentMethodInfo
    (builtinType): object
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false
  amountPlanned:
    type: Money
    (builtinType): object
    description: |-
      How much money this payment intends to receive from the customer.
               The value usually matches the cart or order gross total.
    required: true
  transaction:
    type: MyTransactionDraft
    (builtinType): object
    description: |-
      A list of financial transactions of the `Authorization` or `Charge`
               TransactionTypes.
    required: false