#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: MyPaymentUpdateAction
discriminator: action
(subTypes):
- MyPaymentAddTransactionAction
- MyPaymentChangeAmountPlannedAction
- MyPaymentSetCustomFieldAction
- MyPaymentSetMethodInfoInterfaceAction
- MyPaymentSetMethodInfoMethodAction
- MyPaymentSetMethodInfoNameAction
properties:
  action:
    type: string
    (builtinType): string
    required: true