#%RAML 1.0 DataType
displayName: MyPaymentAddTransactionAction
type: MyPaymentUpdateAction
(builtinType): object
discriminatorValue: addTransaction
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-payments#add-transaction"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTransaction
    required: true
  transaction:
    type: TransactionDraft
    (builtinType): object
    required: true