#%RAML 1.0 DataType
displayName: MyPaymentSetMethodInfoInterfaceAction
type: MyPaymentUpdateAction
(builtinType): object
discriminatorValue: setMethodInfoInterface
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-payments#set-methodinfointerface"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoInterface
    required: true
  interface:
    type: string
    (builtinType): string
    required: true