#%RAML 1.0 DataType
type: object
(originalType): MyPaymentUpdateAction
displayName: MyPaymentSetMethodInfoMethodAction

discriminatorValue: setMethodInfoMethod
properties:
  action:
    type: string
  method:
    type: string