#%RAML 1.0 DataType
displayName: MyPaymentSetMethodInfoMethodAction
type: MyPaymentUpdateAction
(builtinType): object
discriminatorValue: setMethodInfoMethod
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoMethod
    required: true
  method:
    type: string
    (builtinType): string
    required: false