#%RAML 1.0 DataType
displayName: MyPaymentSetMethodInfoNameAction
type: MyPaymentUpdateAction
(builtinType): object
discriminatorValue: setMethodInfoName
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-payments#set-methodinfoname"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: false