#%RAML 1.0 DataType
(builtinType): object
type: MyPaymentUpdateAction
displayName: MyPaymentSetMethodInfoMethodAction
discriminator: action
discriminatorValue: setMethodInfoMethod
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoMethod
    required: true
  method:
    type: string
    (builtinType): string
    required: false