#%RAML 1.0 DataType
(builtinType): object
type: MyPaymentUpdateAction
displayName: MyPaymentAddTransactionAction
discriminator: action
discriminatorValue: addTransaction
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTransaction
    required: true
  transaction:
    type: TransactionDraft
    (builtinType): object
    required: true