#%RAML 1.0 DataType
displayName: MyShoppingListRemoveLineItemAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: removeLineItem
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#remove-lineitem"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLineItem
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: false