#%RAML 1.0 DataType
displayName: MyShoppingListSetCustomTypeAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setCustomType
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-custom-type"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false