#%RAML 1.0 DataType
type: object
(originalType): MyShoppingListUpdateAction
displayName: MyShoppingListRemoveTextLineItemAction

discriminatorValue: removeTextLineItem
properties:
  action:
    required: true
    type: string
  quantity:
    required: false
    format: int64
    type: number
  textLineItemId:
    required: true
    type: string