#%RAML 1.0 DataType
displayName: MyShoppingListRemoveLineItemAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: removeLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLineItem
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: false