#%RAML 1.0 DataType
displayName: MyShoppingListSetDeleteDaysAfterLastModificationAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setDeleteDaysAfterLastModification
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDeleteDaysAfterLastModification
    required: true
  deleteDaysAfterLastModification:
    format: int64
    type: number
    (builtinType): number
    required: false