#%RAML 1.0 DataType
displayName: MyShoppingListChangeLineItemsOrderAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeLineItemsOrder
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#change-lineitems-order"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLineItemsOrder
    required: true
  lineItemOrder:
    type: array
    items:
      type: string
    (builtinType): array
    required: true