#%RAML 1.0 DataType
displayName: MyShoppingListSetDescriptionAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setDescription
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-description"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false