#%RAML 1.0 DataType
displayName: MyShoppingListSetTextLineItemCustomTypeAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setTextLineItemCustomType
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-textlineitem-custom-type"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTextLineItemCustomType
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false