#%RAML 1.0 DataType
displayName: MyShoppingListChangeNameAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeName
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#change-name"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true