#%RAML 1.0 DataType
displayName: MyShoppingListChangeTextLineItemsOrderAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeTextLineItemsOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTextLineItemsOrder
    required: true
  textLineItemOrder:
    type: array
    items:
      type: string
    (builtinType): array
    required: true