#%RAML 1.0 DataType
displayName: MyShoppingListRemoveTextLineItemAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: removeTextLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeTextLineItem
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: false