#%RAML 1.0 DataType
(builtinType): object
type: MyShoppingListUpdateAction
displayName: MyShoppingListChangeTextLineItemQuantityAction
discriminator: action
discriminatorValue: changeTextLineItemQuantity
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTextLineItemQuantity
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true