#%RAML 1.0 DataType
displayName: MyShoppingListSetTextLineItemDescriptionAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setTextLineItemDescription
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-textlineitem-description"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTextLineItemDescription
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false