#%RAML 1.0 DataType
(builtinType): object
type: MyShoppingListUpdateAction
displayName: MyShoppingListSetTextLineItemCustomTypeAction
discriminator: action
discriminatorValue: setTextLineItemCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTextLineItemCustomType
    required: true
  fields:
    type: FieldContainer
    (builtinType): object
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  textLineItemId:
    type: string
    (builtinType): string
    required: true