#%RAML 1.0 DataType
displayName: MyShoppingListSetCustomFieldAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setCustomField
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-customfield"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false