#%RAML 1.0 DataType
displayName: MyShoppingListSetDeleteDaysAfterLastModificationAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setDeleteDaysAfterLastModification
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-deletedaysafterlastmodification"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDeleteDaysAfterLastModification
    required: true
  deleteDaysAfterLastModification:
    format: int64
    type: integer
    (builtinType): integer
    required: false