#%RAML 1.0 DataType
displayName: MyShoppingListSetCustomTypeAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false