#%RAML 1.0 DataType
displayName: MyShoppingListSetLineItemCustomFieldAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: setLineItemCustomField
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#set-lineitem-customfield"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemCustomField
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false