#%RAML 1.0 DataType
(builtinType): object
type: MyShoppingListUpdateAction
displayName: MyShoppingListSetLineItemCustomTypeAction
discriminator: action
discriminatorValue: setLineItemCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemCustomType
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  fields:
    type: FieldContainer
    (builtinType): object
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false