#%RAML 1.0 DataType
displayName: MyShoppingListDraft
type: object
(builtinType): object
properties:
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  lineItems:
    type: array
    items:
      type: ShoppingListLineItemDraft
    (builtinType): array
    required: false
  textLineItems:
    type: array
    items:
      type: TextLineItemDraft
    (builtinType): array
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  deleteDaysAfterLastModification:
    format: int64
    type: integer
    (builtinType): integer
    description: |-
      The shopping list will be deleted automatically if it hasn't been modified for the specified amount of days.
    required: false