#%RAML 1.0 DataType
displayName: MyShoppingListAddLineItemAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: addLineItem
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#add-lineitem"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addLineItem
    required: true
  sku:
    type: string
    (builtinType): string
    required: false
  productId:
    type: string
    (builtinType): string
    required: false
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  addedAt:
    type: datetime
    (builtinType): datetime
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false