#%RAML 1.0 DataType
type: object
(originalType): MyShoppingListUpdateAction
displayName: MyShoppingListChangeTextLineItemQuantityAction
# discriminator: action
# discriminatorValue: changeTextLineItemQuantity
properties:
  action:
    default: changeTextLineItemQuantity
    required: true
    type: string
  quantity:
    required: true
    format: int64
    type: number
  textLineItemId:
    required: true
    type: string