#%RAML 1.0 DataType
displayName: MyShoppingListChangeTextLineItemNameAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeTextLineItemName
(package): "Me"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#change-textlineitem-name"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTextLineItemName
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true