#%RAML 1.0 DataType
displayName: MyShoppingListChangeTextLineItemQuantityAction
type: MyShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeTextLineItemQuantity
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTextLineItemQuantity
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true