#%RAML 1.0 DataType
displayName: MyTransactionDraft
type: object
(builtinType): object
properties:
  timestamp:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      The time at which the transaction took place.
    required: false
  type:
    type: TransactionType
    (builtinType): string
    description: |-
      The type of this transaction.
               Only the `Authorization` or `Charge`
               TransactionTypes are allowed here.
    required: true
  amount:
    type: Money
    (builtinType): object
    required: true
  interactionId:
    type: string
    (builtinType): string
    description: |-
      The identifier that is used by the interface that managed the transaction (usually the PSP).
               If a matching interaction was logged in the interfaceInteractions array,
               the corresponding interaction should be findable with this ID.
               The `state` is set to the `Initial` TransactionState.
    required: false