#%RAML 1.0 DataType
type: object
(originalType): PaymentUpdateAction
displayName: PaymentSetMethodInfoInterfaceAction

discriminatorValue: setMethodInfoInterface
properties:
  action:
    required: true
    type: string
  interface:
    required: true
    type: string