#%RAML 1.0 DataType
(builtinType): object
type: ResourceIdentifier
displayName: PaymentResourceIdentifier
discriminator: typeId
discriminatorValue: payment
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - payment
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false