#%RAML 1.0 DataType
displayName: PaymentSetMethodInfoInterfaceAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setMethodInfoInterface
examples:
  postman: !include ../../examples/Payment/PaymentSetMethodInfoInterfaceAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoInterface
    required: true
  interface:
    type: string
    (builtinType): string
    required: true