#%RAML 1.0 DataType
type: object
(originalType): PaymentUpdateAction
displayName: PaymentChangeTransactionStateAction
# discriminator: action
# discriminatorValue: changeTransactionState
properties:
  action:
    default: changeTransactionState
    required: true
    type: string
  state:
    required: true
    type: TransactionState
  transactionId:
    required: true
    type: string