#%RAML 1.0 DataType
displayName: PaymentSetCustomTypeAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setCustomType
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-custom-type"
examples:
  postman:
    strict: true
    value: !include ../../examples/Payment/PaymentSetCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    description: |-
      If set, the custom type is set to this new value.
      If absent, the custom type and any existing custom fields are removed.
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    description: |-
      Sets the custom fields to this value.
    required: false