#%RAML 1.0 DataType
displayName: PaymentChangeTransactionInteractionIdAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: changeTransactionInteractionId
examples:
  postman: !include ../../examples/Payment/PaymentChangeTransactionInteractionIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTransactionInteractionId
    required: true
  transactionId:
    type: string
    (builtinType): string
    required: true
  interactionId:
    type: string
    (builtinType): string
    required: true