#%RAML 1.0 DataType
displayName: PaymentSetCustomerAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setCustomer
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-customer"
examples:
  postman:
    strict: true
    value: !include ../../examples/Payment/PaymentSetCustomerAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomer
    required: true
  customer:
    type: CustomerResourceIdentifier
    (builtinType): object
    required: false