#%RAML 1.0 DataType
displayName: PaymentResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: payment
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#payment"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - payment
    required: false