#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentSetAmountRefundedAction
discriminator: action
discriminatorValue: setAmountRefunded
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAmountRefunded
    required: true
  amount:
    type: Money
    (builtinType): object
    required: false