#%RAML 1.0 DataType
displayName: PaymentSetAnonymousIdAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setAnonymousId
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-anonymousid"
examples:
  postman: !include ../../examples/Payment/PaymentSetAnonymousIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAnonymousId
    required: true
  anonymousId:
    type: string
    (builtinType): string
    required: false