#%RAML 1.0 DataType
displayName: PaymentReference
type: Reference
(builtinType): object
discriminatorValue: payment
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - payment
    required: true
  obj:
    type: Payment
    (builtinType): object
    required: false