#%RAML 1.0 DataType
displayName: PaymentSetMethodInfoNameAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setMethodInfoName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: false