#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: PaymentUpdateAction
discriminator: action
(subTypes):
- PaymentAddInterfaceInteractionAction
- PaymentAddTransactionAction
- PaymentChangeAmountPlannedAction
- PaymentChangeTransactionInteractionIdAction
- PaymentChangeTransactionStateAction
- PaymentChangeTransactionTimestampAction
- PaymentSetAmountPaidAction
- PaymentSetAmountRefundedAction
- PaymentSetAnonymousIdAction
- PaymentSetAuthorizationAction
- PaymentSetCustomFieldAction
- PaymentSetCustomTypeAction
- PaymentSetCustomerAction
- PaymentSetExternalIdAction
- PaymentSetInterfaceIdAction
- PaymentSetKeyAction
- PaymentSetMethodInfoInterfaceAction
- PaymentSetMethodInfoMethodAction
- PaymentSetMethodInfoNameAction
- PaymentSetStatusInterfaceCodeAction
- PaymentSetStatusInterfaceTextAction
- PaymentTransitionStateAction
properties:
  action:
    type: string
    (builtinType): string
    required: true