#%RAML 1.0 DataType
displayName: PaymentSetExternalIdAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setExternalId
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-externalid"
(deprecated): true
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExternalId
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false