#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentChangeTransactionTimestampAction
discriminator: action
discriminatorValue: changeTransactionTimestamp
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTransactionTimestamp
    required: true
  transactionId:
    type: string
    (builtinType): string
    required: true
  timestamp:
    type: datetime
    (builtinType): datetime
    required: true