#%RAML 1.0 DataType
displayName: PaymentSetInterfaceIdAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setInterfaceId
examples:
  postman: !include ../../examples/Payment/PaymentSetInterfaceIdAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setInterfaceId
    required: true
  interfaceId:
    type: string
    (builtinType): string
    required: true