#%RAML 1.0 DataType
type: object
(originalType): PaymentUpdateAction
displayName: PaymentSetAnonymousIdAction

discriminatorValue: setAnonymousId
properties:
  action:
    required: true
    type: string
  anonymousId:
    required: false
    type: string