#%RAML 1.0 DataType
displayName: PaymentSetAmountPaidAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setAmountPaid
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAmountPaid
    required: true
  amount:
    type: Money
    (builtinType): object
    required: false