#%RAML 1.0 DataType
displayName: PaymentSetKeyAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setKey
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-key"
examples:
  postman:
    strict: true
    value: !include ../../examples/Payment/PaymentSetKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false