#%RAML 1.0 DataType
type: object
(originalType): PaymentUpdateAction
displayName: PaymentChangeAmountPlannedAction
# discriminator: action
# discriminatorValue: changeAmountPlanned
properties:
  action:
    default: changeAmountPlanned
    required: true
    type: string
  amount:
    required: true
    type: Money