#%RAML 1.0 DataType
displayName: PaymentAddTransactionAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: addTransaction
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#add-transaction"
examples:
  postman: !include ../../examples/Payment/PaymentAddTransactionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTransaction
    required: true
  transaction:
    type: TransactionDraft
    (builtinType): object
    required: true