#%RAML 1.0 DataType
displayName: PaymentAddInterfaceInteractionAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: addInterfaceInteraction
examples:
  postman: !include ../../examples/Payment/PaymentAddInterfaceInteractionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addInterfaceInteraction
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: true
  fields:
    type: FieldContainer
    (builtinType): object
    required: false