#%RAML 1.0 DataType
displayName: PaymentSetStatusInterfaceCodeAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setStatusInterfaceCode
examples:
  postman: !include ../../examples/Payment/PaymentSetStatusInterfaceCodeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setStatusInterfaceCode
    required: true
  interfaceCode:
    type: string
    (builtinType): string
    required: false