#%RAML 1.0 DataType
displayName: PaymentResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: payment
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - payment
    required: false