#%RAML 1.0 DataType
displayName: PaymentStatusDraft
type: object
(builtinType): object
properties:
  interfaceText:
    type: string
    (builtinType): string
    required: false
  state:
    type: StateResourceIdentifier
    (builtinType): object
    required: false
  interfaceCode:
    type: string
    (builtinType): string
    required: false