#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentChangeTransactionInteractionIdAction
discriminator: action
discriminatorValue: changeTransactionInteractionId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTransactionInteractionId
    required: true
  interactionId:
    type: string
    (builtinType): string
    required: true
  transactionId:
    type: string
    (builtinType): string
    required: true