#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentSetAuthorizationAction
discriminator: action
discriminatorValue: setAuthorization
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAuthorization
    required: true
  amount:
    type: Money
    (builtinType): object
    required: false
  until:
    type: datetime
    (builtinType): datetime
    required: false