#%RAML 1.0 DataType
displayName: PaymentChangeAmountPlannedAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: changeAmountPlanned
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#change-amountplanned"
examples:
  postman:
    strict: true
    value: !include ../../examples/Payment/PaymentChangeAmountPlannedAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAmountPlanned
    required: true
  amount:
    type: Money
    (builtinType): object
    required: true