#%RAML 1.0 DataType
displayName: PaymentUpdate
type: object
(builtinType): object
(package): "Payment"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: PaymentUpdateAction
    (builtinType): array
    required: true