#%RAML 1.0 DataType
displayName: PaymentSetCustomerAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setCustomer
examples:
  postman: !include ../../examples/Payment/PaymentSetCustomerAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomer
    required: true
  customer:
    type: CustomerResourceIdentifier
    (builtinType): object
    required: false