#%RAML 1.0 DataType
displayName: PaymentSetStatusInterfaceTextAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setStatusInterfaceText
examples:
  postman: !include ../../examples/Payment/PaymentSetStatusInterfaceTextAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setStatusInterfaceText
    required: true
  interfaceText:
    type: string
    (builtinType): string
    required: true