#%RAML 1.0 DataType
type: object
(originalType): PaymentUpdateAction
displayName: PaymentSetMethodInfoMethodAction

discriminatorValue: setMethodInfoMethod
properties:
  action:
    type: string
  method:
    type: string