#%RAML 1.0 DataType
type: object
(originalType): PaymentUpdateAction
displayName: PaymentChangeTransactionInteractionIdAction

discriminatorValue: changeTransactionInteractionId
properties:
  action:
    required: true
    type: string
  interactionId:
    required: true
    type: string
  transactionId:
    required: true
    type: string