#%RAML 1.0 DataType
displayName: PaymentSetMethodInfoMethodAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setMethodInfoMethod
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-methodinfomethod"
examples:
  postman:
    strict: true
    value: !include ../../examples/Payment/PaymentSetMethodInfoMethodAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoMethod
    required: true
  method:
    type: string
    (builtinType): string
    description: |-
      If not provided, the method is unset.
    required: false