#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentAddInterfaceInteractionAction
discriminator: action
discriminatorValue: addInterfaceInteraction
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addInterfaceInteraction
    required: true
  fields:
    type: FieldContainer
    (builtinType): object
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: true