#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentSetMethodInfoInterfaceAction
discriminator: action
discriminatorValue: setMethodInfoInterface
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMethodInfoInterface
    required: true
  interface:
    type: string
    (builtinType): string
    required: true