#%RAML 1.0 DataType
displayName: PaymentSetAmountRefundedAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setAmountRefunded
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-amountrefunded"
(deprecated): true
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAmountRefunded
    required: true
  amount:
    type: Money
    (builtinType): object
    required: false