#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentSetAmountPaidAction
discriminator: action
discriminatorValue: setAmountPaid
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAmountPaid
    required: true
  amount:
    type: Money
    (builtinType): object
    required: false