#%RAML 1.0 DataType
type: object
(originalType): object
displayName: PaymentMethodInfo


properties:
  method:
    description: |-
      The payment method that is used, e.g.
      e.g.
      a conventional string representing Credit Card, Cash Advance etc.
    type: string
  name:
    description: |-
      A human-readable, localized name for the payment method, e.g.
      'Credit Card'.
    type: LocalizedString
  paymentInterface:
    description: |-
      The interface that handles the payment (usually a PSP).
      Cannot be changed once it has been set.
      The combination of Payment`interfaceId` and this field must be unique.
    type: string