#%RAML 1.0 DataType
displayName: PaymentSetStatusInterfaceTextAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setStatusInterfaceText
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-statusinterfacetext"
examples:
  postman: !include ../../examples/Payment/PaymentSetStatusInterfaceTextAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setStatusInterfaceText
    required: true
  interfaceText:
    type: string
    (builtinType): string
    required: true