#%RAML 1.0 DataType
type: object
(originalType): PaymentUpdateAction
displayName: PaymentSetAmountRefundedAction

discriminatorValue: setAmountRefunded
properties:
  action:
    type: string
  amount:
    type: Money