#%RAML 1.0 DataType
type: object
(originalType): object
displayName: PaymentStatusDraft


properties:
  interfaceText:
    required: false
    type: string
  state:
    required: false
    type: StateResourceIdentifier
  interfaceCode:
    required: false
    type: string