#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentSetStatusInterfaceCodeAction
discriminator: action
discriminatorValue: setStatusInterfaceCode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setStatusInterfaceCode
    required: true
  interfaceCode:
    type: string
    (builtinType): string
    required: false