#%RAML 1.0 DataType
(builtinType): object
type: PaymentUpdateAction
displayName: PaymentSetInterfaceIdAction
discriminator: action
discriminatorValue: setInterfaceId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setInterfaceId
    required: true
  interfaceId:
    type: string
    (builtinType): string
    required: true