#%RAML 1.0 DataType
displayName: PaymentSetCustomFieldAction
type: PaymentUpdateAction
(builtinType): object
discriminatorValue: setCustomField
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#set-customfield"
examples:
  postman: !include ../../examples/Payment/PaymentSetCustomFieldAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false