#%RAML 1.0 DataType
displayName: TransactionState

type: string
enum:
- Initial
- Pending
- Success
- Failure
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#transactionstate"