#%RAML 1.0 DataType
displayName: Transaction
type: object
(builtinType): object
properties:
  interactionId:
    type: string
    (builtinType): string
    description: |-
      The identifier that is used by the interface that managed the transaction (usually the PSP).
               If a matching interaction was logged in the `interfaceInteractions` array, the corresponding interaction should be findable with this ID.
    required: false
  amount:
    discriminator: type
    type: TypedMoney
    (builtinType): object
    required: true
  state:
    type: TransactionState
    (builtinType): string
    description: |-
      The state of this transaction.
    required: false
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of this object.
    required: true
  type:
    type: TransactionType
    (builtinType): string
    description: |-
      The type of this transaction.
    required: true
  timestamp:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      The time at which the transaction took place.
    required: false