#%RAML 1.0 DataType
displayName: TransactionType

type: string
enum:
- Authorization
- CancelAuthorization
- Charge
- Refund
- Chargeback
(package): "Payment"
(docs-uri): "https://docs.commercetools.com/http-api-projects-payments.html#transactiontype"