#%RAML 1.0 DataType
displayName: CartDiscountResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: cart-discount
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#cartdiscount"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - cart-discount
    required: false