#%RAML 1.0 DataType
displayName: CartDiscount
type: LoggedResource
(builtinType): object
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#cartdiscount"
(updateType): "CartDiscountUpdate"
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the cart discount.
    (identifier): true
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    description: |-
      The current version of the cart discount.
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for a cart discount.
      Must be unique across a project.
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  value:
    type: CartDiscountValue
    (builtinType): object
    required: true
  cartPredicate:
    type: string
    (builtinType): string
    description: |-
      A valid Cart predicate.
    required: true
  target:
    type: CartDiscountTarget
    (builtinType): object
    description: |-
      Empty when the `value` has type `giftLineItem`, otherwise a CartDiscountTarget is set.
    required: false
  sortOrder:
    type: string
    (builtinType): string
    description: |-
      The string must contain a number between 0 and 1.
      All matching cart discounts are applied to a cart in the order defined by this field.
      A discount with greater sort order is prioritized higher than a discount with lower sort order.
      The sort order is unambiguous among all cart discounts.
    required: true
  isActive:
    type: boolean
    (builtinType): boolean
    description: |-
      Only active discount can be applied to the cart.
    required: true
  validFrom:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false
  validUntil:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false
  requiresDiscountCode:
    type: boolean
    (builtinType): boolean
    description: |-
      States whether the discount can only be used in a connection with a DiscountCode.
    required: true
  references:
    type: array
    items:
      type: Reference
    (builtinType): array
    description: |-
      The platform will generate this array from the predicate.
      It contains the references of all the resources that are addressed in the predicate.
    required: true
  stackingMode:
    type: StackingMode
    (builtinType): string
    description: |-
      Specifies whether the application of this discount causes the following discounts to be ignored.
      Defaults to Stacking.
    required: true
  custom:
    type: CustomFields
    (builtinType): object
    required: false