#%RAML 1.0 DataType
displayName: CartDiscountUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- CartDiscountChangeCartPredicateAction
- CartDiscountChangeIsActiveAction
- CartDiscountChangeNameAction
- CartDiscountChangeRequiresDiscountCodeAction
- CartDiscountChangeSortOrderAction
- CartDiscountChangeStackingModeAction
- CartDiscountChangeTargetAction
- CartDiscountChangeValueAction
- CartDiscountSetCustomFieldAction
- CartDiscountSetCustomTypeAction
- CartDiscountSetDescriptionAction
- CartDiscountSetKeyAction
- CartDiscountSetValidFromAction
- CartDiscountSetValidFromAndUntilAction
- CartDiscountSetValidUntilAction
(package): "CartDiscount"
properties:
  action:
    type: string
    (builtinType): string
    required: true