#%RAML 1.0 DataType
displayName: CartDiscountChangeCartPredicateAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeCartPredicate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCartPredicate
    required: true
  cartPredicate:
    type: string
    (builtinType): string
    required: true