#%RAML 1.0 DataType
type: object
(originalType): CartDiscountUpdateAction
displayName: CartDiscountChangeNameAction

discriminatorValue: changeName
properties:
  action:
    type: string
  name:
    type: LocalizedString