#%RAML 1.0 DataType
displayName: CartDiscountChangeCartPredicateAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeCartPredicate
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#change-cart-predicate"
examples:
  postman:
    strict: true
    value: !include ../../examples/CartDiscount/CartDiscountChangeCartPredicateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCartPredicate
    required: true
  cartPredicate:
    type: string
    (builtinType): string
    required: true