#%RAML 1.0 DataType
displayName: CartDiscountTarget
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartDiscountCustomLineItemsTarget
- CartDiscountLineItemsTarget
- CartDiscountShippingCostTarget
- MultiBuyCustomLineItemsTarget
- MultiBuyLineItemsTarget
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#cartdiscounttarget"
properties:
  type:
    type: string
    (builtinType): string
    required: true