#%RAML 1.0 DataType
displayName: CartDiscountSetDescriptionAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: setDescription
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountSetDescriptionAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false