#%RAML 1.0 DataType
displayName: CartDiscountDraft
type: object
(builtinType): object
properties:
  requiresDiscountCode:
    type: boolean
    (builtinType): boolean
    description: |-
      States whether the discount can only be used in a connection with a DiscountCode.
               Defaults to `false`.
    required: true
  cartPredicate:
    type: string
    (builtinType): string
    description: |-
      A valid Cart predicate.
    required: true
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  stackingMode:
    type: StackingMode
    (builtinType): string
    description: |-
      Specifies whether the application of this discount causes the following discounts to be ignored.
               Defaults to Stacking.
    required: false
  sortOrder:
    type: string
    (builtinType): string
    description: |-
      The string must contain a number between 0 and 1.
               A discount with greater sort order is prioritized higher than a discount with lower sort order.
               The sort order must be unambiguous among all cart discounts.
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  validUntil:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  validFrom:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false
  isActive:
    type: boolean
    (builtinType): boolean
    description: |-
      Only active discount can be applied to the cart.
               Defaults to `true`.
    required: false
  value:
    type: CartDiscountValueDraft
    (builtinType): object
    required: true
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for a cart discount.
               Must be unique across a project.
               The field can be reset using the Set Key UpdateAction.
    required: false
  target:
    type: CartDiscountTarget
    (builtinType): object
    description: |-
      Must not be set when the `value` has type `giftLineItem`, otherwise a CartDiscountTarget must be set.
    required: false