#%RAML 1.0 DataType
displayName: CartDiscountSetValidFromAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: setValidFrom
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#set-valid-from"
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountSetValidFromAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidFrom
    required: true
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false