#%RAML 1.0 DataType
displayName: CartDiscountValueGiftLineItem
type: CartDiscountValue
(builtinType): object
discriminatorValue: giftLineItem
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - giftLineItem
    required: true
  product:
    type: ProductReference
    (builtinType): object
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  supplyChannel:
    type: ChannelReference
    (builtinType): object
    required: false
  distributionChannel:
    type: ChannelReference
    (builtinType): object
    required: false