#%RAML 1.0 DataType
displayName: CartDiscountTarget
type: object
(builtinType): object
discriminator: type
(oneOf):
- MultiBuyCustomLineItemsTarget
- MultiBuyLineItemsTarget
- CartDiscountCustomLineItemsTarget
- CartDiscountLineItemsTarget
- CartDiscountShippingCostTarget
properties:
  type:
    type: string
    (builtinType): string
    required: true