#%RAML 1.0 DataType
displayName: CartDiscountSetValidUntilAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: setValidUntil
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#set-valid-until"
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountSetValidUntilAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidUntil
    required: true
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false