#%RAML 1.0 DataType
displayName: CartDiscountSetDescriptionAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: setDescription
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#set-description"
examples:
  postman:
    strict: true
    value: !include ../../examples/CartDiscount/CartDiscountSetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    description: |-
      If the `description` parameter is not included, the field will be emptied.
    required: false