#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountUpdateAction
displayName: CartDiscountChangeCartPredicateAction
discriminator: action
discriminatorValue: changeCartPredicate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCartPredicate
    required: true
  cartPredicate:
    type: string
    (builtinType): string
    required: true