#%RAML 1.0 DataType
type: object
(originalType): CartDiscountUpdateAction
displayName: CartDiscountSetCustomTypeAction
# discriminator: action
# discriminatorValue: setCustomType
properties:
  action:
    default: setCustomType
    required: true
    type: string
  fields:
    required: false
    type: object
  type:
    required: false
    type: TypeResourceIdentifier