#%RAML 1.0 DataType
displayName: CartDiscountValueAbsoluteDraft
type: CartDiscountValueDraft
(builtinType): object
discriminatorValue: absolute
(package): "CartDiscount"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - absolute
    required: true
  money:
    type: array
    items:
      type: Money
    (builtinType): array
    required: true