#%RAML 1.0 DataType
displayName: CartDiscountChangeSortOrderAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeSortOrder
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountChangeSortOrderAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeSortOrder
    required: true
  sortOrder:
    type: string
    (builtinType): string
    required: true