#%RAML 1.0 DataType
displayName: CartDiscountReference
type: Reference
(builtinType): object
discriminatorValue: cart-discount
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - cart-discount
    required: true
  obj:
    type: CartDiscount
    (builtinType): object
    required: false