#%RAML 1.0 DataType
displayName: CartDiscountChangeRequiresDiscountCodeAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeRequiresDiscountCode
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#change-requires-discountcode"
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountChangeRequiresDiscountCodeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeRequiresDiscountCode
    required: true
  requiresDiscountCode:
    type: boolean
    (builtinType): boolean
    required: true