#%RAML 1.0 DataType
displayName: CartDiscountChangeStackingModeAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeStackingMode
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#change-stacking-mode"
examples:
  postman:
    strict: true
    value: !include ../../examples/CartDiscount/CartDiscountChangeStackingModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeStackingMode
    required: true
  stackingMode:
    type: StackingMode
    (builtinType): string
    enum:
    - Stacking
    - StopAfterThisDiscount
    required: true