#%RAML 1.0 DataType
type: object
(originalType): CartDiscountUpdateAction
displayName: CartDiscountSetKeyAction

discriminatorValue: setKey
properties:
  action:
    type: string
  key:
    type: string