#%RAML 1.0 DataType
displayName: CartDiscountSetKeyAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: setKey
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#set-key"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    description: |-
      If `key` is absent or `null`, this field will be removed if it exists.
    required: false