#%RAML 1.0 DataType
displayName: CartDiscountUpdate
type: object
(builtinType): object
(package): "CartDiscount"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: CartDiscountUpdateAction
    (builtinType): array
    required: true