#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountUpdateAction
displayName: CartDiscountSetValidFromAction
discriminator: action
discriminatorValue: setValidFrom
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidFrom
    required: true
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false