#%RAML 1.0 DataType
displayName: CartDiscountChangeStackingModeAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeStackingMode
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountChangeStackingModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeStackingMode
    required: true
  stackingMode:
    type: StackingMode
    (builtinType): string
    required: true