#%RAML 1.0 DataType
displayName: CartDiscountChangeIsActiveAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeIsActive
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#change-isactive"
examples:
  postman:
    strict: true
    value: !include ../../examples/CartDiscount/CartDiscountChangeIsActiveAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeIsActive
    required: true
  isActive:
    type: boolean
    (builtinType): boolean
    required: true