#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountUpdateAction
displayName: CartDiscountChangeStackingModeAction
discriminator: action
discriminatorValue: changeStackingMode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeStackingMode
    required: true
  stackingMode:
    type: StackingMode
    (builtinType): string
    required: true