#%RAML 1.0 DataType
displayName: CartDiscountChangeTargetAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeTarget
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountChangeTargetAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTarget
    required: true
  target:
    type: CartDiscountTarget
    (builtinType): object
    required: true