#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountUpdateAction
displayName: CartDiscountChangeIsActiveAction
discriminator: action
discriminatorValue: changeIsActive
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeIsActive
    required: true
  isActive:
    type: boolean
    (builtinType): boolean
    required: true