#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountUpdateAction
displayName: CartDiscountSetCustomTypeAction
discriminator: action
discriminatorValue: setCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  fields:
    type: object
    (builtinType): object
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false