#%RAML 1.0 DataType
displayName: CartDiscountValueDraft
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartDiscountValueAbsoluteDraft
- CartDiscountValueGiftLineItemDraft
- CartDiscountValueRelativeDraft
properties:
  type:
    type: string
    (builtinType): string
    required: true