#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountTarget
displayName: CartDiscountLineItemsTarget
discriminator: type
discriminatorValue: lineItems
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - lineItems
    required: true
  predicate:
    type: string
    (builtinType): string
    required: true