#%RAML 1.0 DataType
displayName: CartDiscountValueDraft
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartDiscountValueAbsoluteDraft
- CartDiscountValueGiftLineItemDraft
- CartDiscountValueRelativeDraft
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#cartdiscountvalue"
properties:
  type:
    type: string
    (builtinType): string
    required: true