#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountUpdateAction
displayName: CartDiscountSetCustomFieldAction
discriminator: action
discriminatorValue: setCustomField
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false