#%RAML 1.0 DataType
type: object
(originalType): CartDiscountTarget
displayName: CartDiscountCustomLineItemsTarget
# discriminator: type
# discriminatorValue: customLineItems
properties:
  type:
    default: customLineItems
    required: true
    type: string
  predicate:
    required: true
    type: string