#%RAML 1.0 DataType
displayName: CartDiscountSetCustomFieldAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: setCustomField
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#set-customfield"
examples:
  postman: !include ../../examples/CartDiscount/CartDiscountSetCustomFieldAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false