#%RAML 1.0 DataType
type: object
(originalType): CartDiscountValueDraft
displayName: CartDiscountValueRelativeDraft

discriminatorValue: relative
properties:
  type:
    required: true
    type: string
  permyriad:
    required: true
    format: int64
    type: number