#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountUpdateAction
displayName: CartDiscountChangeSortOrderAction
discriminator: action
discriminatorValue: changeSortOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeSortOrder
    required: true
  sortOrder:
    type: string
    (builtinType): string
    required: true