#%RAML 1.0 DataType
type: CartDiscountValueDraft
displayName: CartDiscountValueGiftLineItemDraft

discriminatorValue: giftLineItem
properties:
   product:
      type: ProductReference
   variantId:
      format: int64
      type: number
   supplyChannel:
      type: ChannelReference
   distributionChannel:
      type: ChannelReference