#%RAML 1.0 DataType
displayName: CartDiscountValue
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartDiscountValueAbsolute
- CartDiscountValueGiftLineItem
- CartDiscountValueRelative
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#cartdiscountvalue"
properties:
  type:
    type: string
    (builtinType): string
    required: true