#%RAML 1.0 DataType
displayName: CartDiscountChangeValueAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeValue
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeValue
    required: true
  value:
    type: CartDiscountValueDraft
    (builtinType): object
    required: true