#%RAML 1.0 DataType
displayName: CartDiscountValue
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartDiscountValueAbsolute
- CartDiscountValueGiftLineItem
- CartDiscountValueRelative
properties:
  type:
    type: string
    (builtinType): string
    required: true