#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: CartDiscountReference
discriminator: typeId
discriminatorValue: cart-discount
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - cart-discount
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: CartDiscount
    (builtinType): object
    required: false