#%RAML 1.0 DataType
(builtinType): object
type: CartDiscountValue
displayName: CartDiscountValueAbsolute
discriminator: type
discriminatorValue: absolute
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - absolute
    required: true
  money:
    type: array
    items:
      type: TypedMoney
    (builtinType): array
    required: true