#%RAML 1.0 DataType
displayName: CartDiscountChangeSortOrderAction
type: CartDiscountUpdateAction
(builtinType): object
discriminatorValue: changeSortOrder
(package): "CartDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-cartDiscounts.html#change-sort-order"
examples:
  postman:
    strict: true
    value: !include ../../examples/CartDiscount/CartDiscountChangeSortOrderAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeSortOrder
    required: true
  sortOrder:
    type: string
    (builtinType): string
    required: true