#%RAML 1.0 DataType
type: object
(originalType): FieldType
displayName: CustomFieldTimeType
# discriminator: name
# discriminatorValue: Time
properties:
  name:
    default: Time
    required: true
    type: string