#%RAML 1.0 DataType
type: object
(originalType): FieldType
displayName: CustomFieldLocalizedStringType
# discriminator: name
# discriminatorValue: LocalizedString
properties:
  name:
    default: LocalizedString
    required: true
    type: string