#%RAML 1.0 DataType
displayName: CustomFieldTimeType
type: FieldType
(builtinType): object
discriminatorValue: Time
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#timetype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Time
    required: true