#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: CustomFields
properties:
  fields:
    type: FieldContainer
    (builtinType): object
    description: |-
      A valid JSON object, based on FieldDefinition.
    required: true
  type:
    type: TypeReference
    (builtinType): object
    required: true