#%RAML 1.0 DataType
displayName: CustomFields
type: object
(builtinType): object
properties:
  type:
    type: TypeReference
    (builtinType): object
    required: true
  fields:
    type: FieldContainer
    (builtinType): object
    description: |-
      A valid JSON object, based on FieldDefinition.
    required: true