#%RAML 1.0 DataType
displayName: CustomFieldEnumValue
type: object
(builtinType): object
properties:
  label:
    type: string
    (builtinType): string
    required: true
  key:
    type: string
    (builtinType): string
    required: true