#%RAML 1.0 DataType
displayName: CustomFieldLocalizedEnumType
type: FieldType
(builtinType): object
discriminatorValue: LocalizedEnum
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - LocalizedEnum
    required: true
  values:
    type: array
    items:
      type: CustomFieldLocalizedEnumValue
    (builtinType): array
    required: true