#%RAML 1.0 DataType
displayName: CustomFieldLocalizedStringType
type: FieldType
(builtinType): object
discriminatorValue: LocalizedString
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#localizedstringtype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - LocalizedString
    required: true