#%RAML 1.0 DataType
displayName: CustomFieldBooleanType
type: FieldType
(builtinType): object
discriminatorValue: Boolean
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#booleantype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Boolean
    required: true