#%RAML 1.0 DataType
type: object
(originalType): FieldType
displayName: CustomFieldSetType

discriminatorValue: Set
properties:
  name:
    required: true
    type: string
  elementType:
    required: true
    type: FieldType