#%RAML 1.0 DataType
displayName: CustomFieldEnumType
type: FieldType
(builtinType): object
discriminatorValue: Enum
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Enum
    required: true
  values:
    type: array
    items:
      type: CustomFieldEnumValue
    (builtinType): array
    required: true