#%RAML 1.0 DataType
(builtinType): object
type: FieldType
displayName: CustomFieldDateType
discriminator: name
discriminatorValue: Date
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Date
    required: true