#%RAML 1.0 DataType
displayName: CustomFieldNumberType
type: FieldType
(builtinType): object
discriminatorValue: Number
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#numbertype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Number
    required: true