#%RAML 1.0 DataType
type: object
(originalType): FieldType
displayName: CustomFieldSetType
# discriminator: name
# discriminatorValue: Set
properties:
  name:
    default: Set
    required: true
    type: string
  elementType:
    required: true
    type: FieldType