#%RAML 1.0 DataType
displayName: CustomFieldNumberType
type: FieldType
(builtinType): object
discriminatorValue: Number
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Number
    required: true