#%RAML 1.0 DataType
displayName: CustomFieldEnumValue
type: object
(builtinType): object
(package): "Type"
properties:
  key:
    type: string
    (builtinType): string
    required: true
  label:
    type: string
    (builtinType): string
    required: true