#%RAML 1.0 DataType
(builtinType): object
type: FieldType
displayName: CustomFieldNumberType
discriminator: name
discriminatorValue: Number
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Number
    required: true