#%RAML 1.0 DataType
displayName: CustomFieldEnumType
type: FieldType
(builtinType): object
discriminatorValue: Enum
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#enumtype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Enum
    required: true
  values:
    type: array
    items:
      type: CustomFieldEnumValue
    (builtinType): array
    required: true