#%RAML 1.0 DataType
(builtinType): object
type: FieldType
displayName: CustomFieldLocalizedStringType
discriminator: name
discriminatorValue: LocalizedString
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - LocalizedString
    required: true