#%RAML 1.0 DataType
displayName: CustomFieldsDraft
type: object
(builtinType): object
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-custom-fields.html#customfieldsdraft"
properties:
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    description: |-
      The `id` or the `key` of the type to use.
    required: true
  fields:
    type: FieldContainer
    (builtinType): object
    description: |-
      A valid JSON object, based on the FieldDefinitions of the Type.
    required: false