#%RAML 1.0 DataType
type: object
(originalType): FieldType
displayName: CustomFieldReferenceType
# discriminator: name
# discriminatorValue: Reference
properties:
  name:
    default: Reference
    required: true
    type: string
  referenceTypeId:
    required: true
    type: ReferenceTypeId