#%RAML 1.0 DataType
displayName: CustomFieldSetType
type: FieldType
(builtinType): object
discriminatorValue: Set
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Set
    required: true
  elementType:
    type: FieldType
    (builtinType): object
    required: true