#%RAML 1.0 DataType
(builtinType): object
type: FieldType
displayName: CustomFieldMoneyType
discriminator: name
discriminatorValue: Money
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Money
    required: true