#%RAML 1.0 DataType
displayName: CustomFieldDateTimeType
type: FieldType
(builtinType): object
discriminatorValue: DateTime
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - DateTime
    required: true