#%RAML 1.0 DataType
displayName: CustomFieldDateType
type: FieldType
(builtinType): object
discriminatorValue: Date
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#datetype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Date
    required: true