#%RAML 1.0 DataType
displayName: CustomFieldMoneyType
type: FieldType
(builtinType): object
discriminatorValue: Money
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Money
    required: true