#%RAML 1.0 DataType
(builtinType): object
type: FieldType
displayName: CustomFieldTimeType
discriminator: name
discriminatorValue: Time
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Time
    required: true