#%RAML 1.0 DataType
displayName: CustomFieldStringType
type: FieldType
(builtinType): object
discriminatorValue: String
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - String
    required: true