#%RAML 1.0 DataType
(builtinType): object
type: FieldType
displayName: CustomFieldEnumType
discriminator: name
discriminatorValue: Enum
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - Enum
    required: true
  values:
    type: array
    items:
      type: CustomFieldEnumValue
    (builtinType): array
    required: true