#%RAML 1.0 DataType
displayName: CustomFieldDateTimeType
type: FieldType
(builtinType): object
discriminatorValue: DateTime
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#datetimetype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - DateTime
    required: true