#%RAML 1.0 DataType
displayName: FieldType
type: object
(builtinType): object
discriminator: name
(oneOf):
- CustomFieldBooleanType
- CustomFieldDateTimeType
- CustomFieldDateType
- CustomFieldEnumType
- CustomFieldLocalizedEnumType
- CustomFieldLocalizedStringType
- CustomFieldMoneyType
- CustomFieldNumberType
- CustomFieldReferenceType
- CustomFieldSetType
- CustomFieldStringType
- CustomFieldTimeType
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#fieldtype"
properties:
  name:
    type: string
    (builtinType): string
    required: true