#%RAML 1.0 DataType
displayName: TypeAddFieldDefinitionAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: addFieldDefinition
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#add-fielddefinition"
examples:
  postman:
    strict: true
    value: !include ../../examples/Type/TypeAddFieldDefinitionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addFieldDefinition
    required: true
  fieldDefinition:
    type: FieldDefinition
    (builtinType): object
    required: true