#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: TypeReference
discriminator: typeId
discriminatorValue: type
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - type
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Type
    (builtinType): object
    required: false