#%RAML 1.0 DataType
(builtinType): object
type: TypeUpdateAction
displayName: TypeAddFieldDefinitionAction
discriminator: action
discriminatorValue: addFieldDefinition
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addFieldDefinition
    required: true
  fieldDefinition:
    type: FieldDefinition
    (builtinType): object
    required: true