#%RAML 1.0 DataType
displayName: TypeAddEnumValueAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: addEnumValue
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#add-enumvalue-to-fielddefinition"
examples:
  postman: !include ../../examples/Type/TypeAddEnumValueAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addEnumValue
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  value:
    type: CustomFieldEnumValue
    (builtinType): object
    required: true