#%RAML 1.0 DataType
displayName: TypeAddLocalizedEnumValueAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: addLocalizedEnumValue
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#add-localizedenumvalue-to-fielddefinition"
examples:
  postman: !include ../../examples/Type/TypeAddLocalizedEnumValueAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addLocalizedEnumValue
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  value:
    type: CustomFieldLocalizedEnumValue
    (builtinType): object
    required: true