#%RAML 1.0 DataType
displayName: TypeChangeEnumValueLabelAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeEnumValueLabel
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#change-enumvalue-label"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeEnumValueLabel
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  value:
    type: CustomFieldEnumValue
    (builtinType): object
    required: true