#%RAML 1.0 DataType
displayName: TypeChangeLocalizedEnumValueOrderAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeLocalizedEnumValueOrder
examples:
  postman: !include ../../examples/Type/TypeChangeLocalizedEnumValueOrderAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLocalizedEnumValueOrder
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  keys:
    type: array
    items:
      type: string
    (builtinType): array
    required: true