#%RAML 1.0 DataType
displayName: TypeChangeFieldDefinitionLabelAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeFieldDefinitionLabel
(package): "Type"
(deprecated): true
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeFieldDefinitionLabel
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  label:
    type: LocalizedString
    (builtinType): object
    required: true