#%RAML 1.0 DataType
type: object
(originalType): TypeUpdateAction
displayName: TypeChangeLocalizedEnumValueOrderAction

discriminatorValue: changeLocalizedEnumValueOrder
properties:
  action:
    type: string
  fieldName:
    type: string
  keys:
    type: array
    items:
      type: string