#%RAML 1.0 DataType
(builtinType): object
type: TypeUpdateAction
displayName: TypeChangeFieldDefinitionOrderAction
discriminator: action
discriminatorValue: changeFieldDefinitionOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeFieldDefinitionOrder
    required: true
  fieldNames:
    type: array
    items:
      type: string
    (builtinType): array
    required: true