#%RAML 1.0 DataType
displayName: TypeSetDescriptionAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: setDescription
examples:
  postman: !include ../../examples/Type/TypeSetDescriptionAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false