#%RAML 1.0 DataType
displayName: TypeSetDescriptionAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: setDescription
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#set-description"
examples:
  postman: !include ../../examples/Type/TypeSetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false