#%RAML 1.0 DataType
type: object
(originalType): Reference
displayName: TypeReference
# discriminator: typeId
# discriminatorValue: type
properties:
  typeId:
    default: type
    required: true
    type: ReferenceTypeId
  id:
    required: true
    type: string
  obj:
    required: false
    type: Type