#%RAML 1.0 DataType
type: object
(originalType): TypeUpdateAction
displayName: TypeChangeEnumValueLabelAction
# discriminator: action
# discriminatorValue: changeEnumValueLabel
properties:
  action:
    default: changeEnumValueLabel
    required: true
    type: string
  fieldName:
    required: true
    type: string
  value:
    required: true
    type: CustomFieldEnumValue