#%RAML 1.0 DataType
displayName: TypeAddEnumValueAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: addEnumValue
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addEnumValue
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  value:
    type: CustomFieldEnumValue
    (builtinType): object
    required: true