#%RAML 1.0 DataType
displayName: TypeChangeLabelAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeLabel
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#change-label"
examples:
  postman:
    strict: true
    value: !include ../../examples/Type/TypeChangeLabelAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLabel
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  label:
    type: LocalizedString
    (builtinType): object
    required: true