#%RAML 1.0 DataType
displayName: TypeChangeFieldDefinitionOrderAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeFieldDefinitionOrder
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#change-the-order-of-fielddefinitions"
examples:
  postman:
    strict: true
    value: !include ../../examples/Type/TypeChangeFieldDefinitionOrderAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeFieldDefinitionOrder
    required: true
  fieldNames:
    type: array
    items:
      type: string
    (builtinType): array
    required: true