#%RAML 1.0 DataType
(builtinType): object
type: TypeUpdateAction
displayName: TypeRemoveFieldDefinitionAction
discriminator: action
discriminatorValue: removeFieldDefinition
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeFieldDefinition
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true