#%RAML 1.0 DataType
type: object
(originalType): TypeUpdateAction
displayName: TypeChangeLabelAction
# discriminator: action
# discriminatorValue: changeLabel
properties:
  action:
    default: changeLabel
    required: true
    type: string
  fieldName:
    required: true
    type: string
  label:
    required: true
    type: LocalizedString