#%RAML 1.0 DataType
displayName: TypeAddFieldDefinitionAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: addFieldDefinition
examples:
  postman: !include ../../examples/Type/TypeAddFieldDefinitionAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addFieldDefinition
    required: true
  fieldDefinition:
    type: FieldDefinition
    (builtinType): object
    required: true