#%RAML 1.0 DataType
(builtinType): object
type: TypeUpdateAction
displayName: TypeChangeInputHintAction
discriminator: action
discriminatorValue: changeInputHint
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeInputHint
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  inputHint:
    type: TypeTextInputHint
    (builtinType): string
    required: true