#%RAML 1.0 DataType
displayName: TypeResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: type
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - type
    required: false