#%RAML 1.0 DataType
displayName: TypeDraft
type: object
(builtinType): object
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#typedraft"
properties:
  key:
    type: string
    (builtinType): string
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  resourceTypeIds:
    type: array
    items:
      type: ResourceTypeId
    (builtinType): array
    description: |-
      The IDs of the resources that can be customized with this type.
    required: true
  fieldDefinitions:
    type: array
    items:
      type: FieldDefinition
    (builtinType): array
    required: false