#%RAML 1.0 DataType
displayName: TypeRemoveFieldDefinitionAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: removeFieldDefinition
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeFieldDefinition
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true