#%RAML 1.0 DataType
displayName: TypeUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- TypeAddEnumValueAction
- TypeAddFieldDefinitionAction
- TypeAddLocalizedEnumValueAction
- TypeChangeEnumValueLabelAction
- TypeChangeEnumValueOrderAction
- TypeChangeFieldDefinitionLabelAction
- TypeChangeFieldDefinitionOrderAction
- TypeChangeInputHintAction
- TypeChangeKeyAction
- TypeChangeLabelAction
- TypeChangeLocalizedEnumValueLabelAction
- TypeChangeLocalizedEnumValueOrderAction
- TypeChangeNameAction
- TypeRemoveFieldDefinitionAction
- TypeSetDescriptionAction
properties:
  action:
    type: string
    (builtinType): string
    required: true