#%RAML 1.0 DataType
displayName: TypeChangeKeyAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeKey
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#change-key"
examples:
  postman: !include ../../examples/Type/TypeChangeKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeKey
    required: true
  key:
    type: string
    (builtinType): string
    required: true