#%RAML 1.0 DataType
displayName: TypeChangeLocalizedEnumValueOrderAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeLocalizedEnumValueOrder
(package): "Type"
(docs-uri): "https://docs.commercetools.com/http-api-projects-types.html#change-the-order-of-localizedenumvalues"
examples:
  postman:
    strict: true
    value: !include ../../examples/Type/TypeChangeLocalizedEnumValueOrderAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLocalizedEnumValueOrder
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  keys:
    type: array
    items:
      type: string
    (builtinType): array
    required: true