#%RAML 1.0 DataType
displayName: TypeReference
type: Reference
(builtinType): object
discriminatorValue: type
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - type
    required: true
  obj:
    type: Type
    (builtinType): object
    required: false