#%RAML 1.0 DataType
displayName: TypeChangeInputHintAction
type: TypeUpdateAction
(builtinType): object
discriminatorValue: changeInputHint
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeInputHint
    required: true
  fieldName:
    type: string
    (builtinType): string
    required: true
  inputHint:
    type: TypeTextInputHint
    (builtinType): string
    required: true