#%RAML 1.0 DataType
displayName: CartClassificationType
type: ShippingRateInputType
(builtinType): object
discriminatorValue: CartClassification
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#cartclassification"
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartClassification
    required: true
  values:
    type: array
    items:
      type: CustomFieldLocalizedEnumValue
    (builtinType): array
    required: true