#%RAML 1.0 DataType
displayName: CartScoreType
type: ShippingRateInputType
(builtinType): object
discriminatorValue: CartScore
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartScore
    required: true