#%RAML 1.0 DataType
(builtinType): object
type: ShippingRateInputType
displayName: CartClassificationType
discriminator: type
discriminatorValue: CartClassification
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartClassification
    required: true
  values:
    type: array
    items:
      type: CustomFieldLocalizedEnumValue
    (builtinType): array
    required: true