#%RAML 1.0 DataType
(builtinType): object
type: ShippingRateInputType
displayName: CartScoreType
discriminator: type
discriminatorValue: CartScore
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartScore
    required: true