#%RAML 1.0 DataType
displayName: ExternalOAuth
type: object
(builtinType): object
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#externaloauth"
properties:
  url:
    type: string
    (builtinType): string
    required: true
  authorizationHeader:
    type: string
    (builtinType): string
    required: true