#%RAML 1.0 DataType
displayName: ExternalOAuth
type: object
(builtinType): object
properties:
  url:
    type: string
    (builtinType): string
    required: true
  authorizationHeader:
    type: string
    (builtinType): string
    required: true