#%RAML 1.0 DataType
(builtinType): object
type: ProjectUpdateAction
displayName: ProjectChangeMessagesConfigurationAction
discriminator: action
discriminatorValue: changeMessagesConfiguration
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeMessagesConfiguration
    required: true
  messagesConfiguration:
    type: MessageConfigurationDraft
    (builtinType): object
    required: true