#%RAML 1.0 DataType
(builtinType): object
type: ProjectUpdateAction
displayName: ProjectSetShippingRateInputTypeAction
discriminator: action
discriminatorValue: setShippingRateInputType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingRateInputType
    required: true
  shippingRateInputType:
    type: ShippingRateInputType
    (builtinType): object
    required: false