#%RAML 1.0 DataType
displayName: ProjectUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- ProjectChangeCountriesAction
- ProjectChangeCurrenciesAction
- ProjectChangeLanguagesAction
- ProjectChangeMessagesConfigurationAction
- ProjectChangeMessagesEnabledAction
- ProjectChangeNameAction
- ProjectSetExternalOAuthAction
- ProjectSetShippingRateInputTypeAction
properties:
  action:
    type: string
    (builtinType): string
    required: true