#%RAML 1.0 DataType
displayName: ProjectChangeCountriesAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeCountries
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#change-countries"
examples:
  postman:
    strict: true
    value: !include ../../examples/Project/ProjectChangeCountriesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCountries
    required: true
  countries:
    type: array
    items:
      type: CountryCode
    (builtinType): array
    required: true