#%RAML 1.0 DataType
displayName: ProjectSetExternalOAuthAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: setExternalOAuth
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#set-externaloauth"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExternalOAuth
    required: true
  externalOAuth:
    type: ExternalOAuth
    (builtinType): object
    description: |-
      If you do not provide the `externalOAuth` field or provide a value
      of `null`, the update action unsets the External OAuth provider.
    required: false