#%RAML 1.0 DataType
displayName: ProjectChangeCountriesAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeCountries
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCountries
    required: true
  countries:
    type: array
    items:
      type: CountryCode
    (builtinType): array
    required: true