#%RAML 1.0 DataType
displayName: ProjectChangeMessagesEnabledAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeMessagesEnabled
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeMessagesEnabled
    required: true
  messagesEnabled:
    type: boolean
    (builtinType): boolean
    required: true