#%RAML 1.0 DataType
displayName: ProjectChangeMessagesEnabledAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeMessagesEnabled
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#change-messages-enabled"
(deprecated): true
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeMessagesEnabled
    required: true
  messagesEnabled:
    type: boolean
    (builtinType): boolean
    required: true