#%RAML 1.0 DataType
displayName: ProjectChangeMessagesConfigurationAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeMessagesConfiguration
examples:
  postman: !include ../../examples/Project/ProjectChangeMessagesConfigurationAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeMessagesConfiguration
    required: true
  messagesConfiguration:
    type: MessageConfigurationDraft
    (builtinType): object
    required: true