#%RAML 1.0 DataType
(builtinType): object
type: ProjectUpdateAction
displayName: ProjectChangeMessagesEnabledAction
discriminator: action
discriminatorValue: changeMessagesEnabled
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeMessagesEnabled
    required: true
  messagesEnabled:
    type: boolean
    (builtinType): boolean
    required: true