#%RAML 1.0 DataType
type: object
(originalType): ProjectUpdateAction
displayName: ProjectSetShippingRateInputTypeAction

discriminatorValue: setShippingRateInputType
properties:
  action:
    required: true
    type: string
  shippingRateInputType:
    required: false
    type: ShippingRateInputType