#%RAML 1.0 DataType
displayName: ProjectChangeCurrenciesAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeCurrencies
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#change-currencies"
examples:
  postman: !include ../../examples/Project/ProjectChangeCurrenciesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCurrencies
    required: true
  currencies:
    type: array
    items:
      type: CurrencyCode
    (builtinType): array
    required: true