#%RAML 1.0 DataType
displayName: ProjectSetShippingRateInputTypeAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: setShippingRateInputType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingRateInputType
    required: true
  shippingRateInputType:
    type: ShippingRateInputType
    (builtinType): object
    required: false