#%RAML 1.0 DataType
displayName: ProjectChangeLanguagesAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeLanguages
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#change-languages"
examples:
  postman:
    strict: true
    value: !include ../../examples/Project/ProjectChangeLanguagesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLanguages
    required: true
  languages:
    type: array
    items:
      type: Locale
    (builtinType): array
    description: |-
      .
    required: true