#%RAML 1.0 DataType
(builtinType): object
type: ProjectUpdateAction
displayName: ProjectSetExternalOAuthAction
discriminator: action
discriminatorValue: setExternalOAuth
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExternalOAuth
    required: true
  externalOAuth:
    type: ExternalOAuth
    (builtinType): object
    required: false