#%RAML 1.0 DataType
displayName: ProjectChangeCountriesAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeCountries
examples:
  postman: !include ../../examples/Project/ProjectChangeCountriesAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCountries
    required: true
  countries:
    type: array
    items:
      type: CountryCode
    (builtinType): array
    required: true