#%RAML 1.0 DataType
(builtinType): object
type: ProjectUpdateAction
displayName: ProjectChangeLanguagesAction
discriminator: action
discriminatorValue: changeLanguages
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLanguages
    required: true
  languages:
    type: array
    items:
      type: Locale
    (builtinType): array
    required: true