#%RAML 1.0 DataType
type: object
(originalType): ProjectUpdateAction
displayName: ProjectSetExternalOAuthAction
# discriminator: action
# discriminatorValue: setExternalOAuth
properties:
  action:
    default: setExternalOAuth
    required: true
    type: string
  externalOAuth:
    required: false
    type: ExternalOAuth