#%RAML 1.0 DataType
displayName: Project
type: object
(builtinType): object
properties:
  externalOAuth:
    type: ExternalOAuth
    (builtinType): object
    required: false
  shippingRateInputType:
    type: ShippingRateInputType
    (builtinType): object
    required: false
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  languages:
    type: array
    items:
      type: Locale
    (builtinType): array
    required: true
  name:
    type: string
    (builtinType): string
    description: |-
      The name of the project.
    required: true
  messages:
    type: MessageConfiguration
    (builtinType): object
    required: true
  countries:
    type: array
    items:
      type: CountryCode
    (builtinType): array
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    required: true
  trialUntil:
    type: string
    (builtinType): string
    description: |-
      The time is in the format Year-Month `YYYY-MM`.
    required: false
  version:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The current version of the project.
    required: true
  key:
    type: string
    (builtinType): string
    description: |-
      The unique key of the project.
    required: true
  currencies:
    type: array
    items:
      type: CurrencyCode
    (builtinType): array
    description: |-
      A three-digit currency code as per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    required: true