#%RAML 1.0 DataType
displayName: ProjectChangeMessagesConfigurationAction
type: ProjectUpdateAction
(builtinType): object
discriminatorValue: changeMessagesConfiguration
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#change-messages-configuration"
examples:
  postman:
    strict: true
    value: !include ../../examples/Project/ProjectChangeMessagesConfigurationAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeMessagesConfiguration
    required: true
  messagesConfiguration:
    type: MessageConfigurationDraft
    (builtinType): object
    required: true