#%RAML 1.0 DataType
(builtinType): object
type: ProjectUpdateAction
displayName: ProjectChangeCurrenciesAction
discriminator: action
discriminatorValue: changeCurrencies
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCurrencies
    required: true
  currencies:
    type: array
    items:
      type: CurrencyCode
    (builtinType): array
    required: true