#%RAML 1.0 DataType
displayName: ShippingRateInputType
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartClassificationType
- CartScoreType
- CartValueType
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    required: true