#%RAML 1.0 DataType
displayName: ShippingRateInputType
type: object
(builtinType): object
discriminator: type
(oneOf):
- CartClassificationType
- CartScoreType
- CartValueType
(package): "Project"
(docs-uri): "https://docs.commercetools.com/http-api-projects-project.html#shippingrateinputtype"
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartValue
    - CartClassification
    - CartScore
    required: true