#%RAML 1.0 DataType
type: object
(originalType): ReturnItem
displayName: CustomLineItemReturnItem
# discriminator: type
# discriminatorValue: CustomLineItemReturnItem
properties:
  shipmentState:
    required: true
    type: ReturnShipmentState
  createdAt:
    required: true
    type: datetime
  lastModifiedAt:
    required: true
    type: datetime
  quantity:
    required: true
    format: int64
    type: number
  comment:
    required: false
    type: string
  id:
    required: true
    type: string
  paymentState:
    required: true
    type: ReturnPaymentState
  type:
    default: CustomLineItemReturnItem
    required: true
    type: string
  customLineItemId:
    required: true
    type: string