#%RAML 1.0 DataType
displayName: DeliveryItem
type: object
(builtinType): object
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#deliveryitem"
properties:
  id:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: float
    type: number
    (builtinType): number
    required: true