#%RAML 1.0 DataType
type: object
(originalType): object
displayName: DiscountedLineItemPriceDraft


properties:
  includedDiscounts:
    type: array
    items:
      type: DiscountedLineItemPortion
  value:
    type: Money