#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: DiscountedLineItemPriceDraft
properties:
  includedDiscounts:
    type: array
    items:
      type: DiscountedLineItemPortion
    (builtinType): array
    required: true
  value:
    type: Money
    (builtinType): object
    required: true