#%RAML 1.0 DataType
displayName: ItemState
type: object
(builtinType): object
properties:
  quantity:
    format: int16
    type: integer
    (builtinType): integer
    required: true
  state:
    type: StateReference
    (builtinType): object
    required: true