#%RAML 1.0 DataType
(builtinType): object
type: ReturnItem
displayName: LineItemReturnItem
discriminator: type
discriminatorValue: LineItemReturnItem
properties:
  shipmentState:
    type: ReturnShipmentState
    (builtinType): string
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  comment:
    type: string
    (builtinType): string
    required: false
  id:
    type: string
    (builtinType): string
    required: true
  paymentState:
    type: ReturnPaymentState
    (builtinType): string
    required: true
  type:
    type: string
    (builtinType): string
    enum:
    - LineItemReturnItem
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true