#%RAML 1.0 DataType
displayName: LineItemImportDraft
type: object
(builtinType): object
properties:
  productId:
    type: string
    (builtinType): string
    description: |-
      ID of the existing product.
      You also need to specify the ID of the variant if this property is set or alternatively you can just specify SKU of the product variant.
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    description: |-
      The product name.
    required: true
  variant:
    type: ProductVariantImportDraft
    (builtinType): object
    required: true
  price:
    type: PriceDraft
    (builtinType): object
    required: true
  quantity:
    format: int16
    type: number
    (builtinType): number
    required: true
  state:
    type: array
    items:
      type: ItemState
    (builtinType): array
    required: false
  supplyChannel:
    discriminatorValue: "channel"
    type: ChannelResourceIdentifier
    (builtinType): object
    description: |-
      Optional connection to a particular supplier.
      By providing supply channel information, you can uniquely identify
      inventory entries that should be reserved.
      The provided channel should have the
      InventorySupply role.
    required: false
  distributionChannel:
    discriminatorValue: "channel"
    type: ChannelResourceIdentifier
    (builtinType): object
    description: |-
      The channel is used to select a ProductPrice.
      The provided channel should have the ProductDistribution role.
    required: false
  taxRate:
    type: TaxRate
    (builtinType): object
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false