#%RAML 1.0 DataType
displayName: LineItemReturnItem
type: ReturnItem
(builtinType): object
discriminatorValue: LineItemReturnItem
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - LineItemReturnItem
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true