#%RAML 1.0 DataType
type: object
(originalType): object
displayName: LineItemImportDraft


properties:
  taxRate:
    type: TaxRate
  quantity:
    format: int16
    type: number
  shippingDetails:
    type: ItemShippingDetailsDraft
  productId:
    description: |-
      ID of the existing product.
      You also need to specify the ID of the variant if this property is set or alternatively you can just specify SKU of the product variant.
    type: string
  price:
    type: PriceDraft
  custom:
    description: |-
      The custom fields.
    type: CustomFieldsDraft
  variant:
    type: ProductVariantImportDraft
  name:
    description: |-
      The product name.
    type: LocalizedString
  supplyChannel:
    description: |-
      Optional connection to a particular supplier.
      By providing supply channel information, you can uniquely identify
      inventory entries that should be reserved.
      The provided channel should have the
      InventorySupply role.
    discriminatorValue: channel
    type: ChannelResourceIdentifier
  state:
    type: array
    items:
      type: ItemState
  distributionChannel:
    description: |-
      The channel is used to select a ProductPrice.
      The provided channel should have the ProductDistribution role.
    discriminatorValue: channel
    type: ChannelResourceIdentifier