#%RAML 1.0 DataType
displayName: OrderTransitionStateAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: transitionState
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#transition-state"
examples:
  postman: !include ../../examples/Order/OrderTransitionStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionState
    required: true
  state:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: false