#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: OrderUpdate
properties:
  actions:
    type: array
    items:
      type: OrderUpdateAction
    (builtinType): array
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true