#%RAML 1.0 DataType
type: object
(originalType): OrderUpdateAction
displayName: OrderUpdateSyncInfoAction

discriminatorValue: updateSyncInfo
properties:
  action:
    required: true
    type: string
  channel:
    required: true
    type: ChannelResourceIdentifier
  externalId:
    required: false
    type: string
  syncedAt:
    required: false
    type: datetime