#%RAML 1.0 DataType
(builtinType): object
type: OrderUpdateAction
displayName: OrderTransitionLineItemStateAction
discriminator: action
discriminatorValue: transitionLineItemState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionLineItemState
    required: true
  toState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  fromState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  actualTransitionDate:
    type: datetime
    (builtinType): datetime
    required: false