#%RAML 1.0 DataType
displayName: OrderSetCustomerIdAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setCustomerId
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-customer-id"
examples:
  postman: !include ../../examples/Order/OrderSetCustomerIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerId
    required: true
  customerId:
    type: string
    (builtinType): string
    required: false