#%RAML 1.0 DataType
displayName: OrderChangePaymentStateAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: changePaymentState
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#change-paymentstate"
examples:
  postman:
    strict: true
    value: !include ../../examples/Order/OrderChangePaymentStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePaymentState
    required: true
  paymentState:
    type: PaymentState
    (builtinType): string
    enum:
    - BalanceDue
    - Failed
    - Pending
    - CreditOwed
    - Paid
    required: false