#%RAML 1.0 DataType
(builtinType): object
type: OrderUpdateAction
displayName: OrderChangePaymentStateAction
discriminator: action
discriminatorValue: changePaymentState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePaymentState
    required: true
  paymentState:
    type: PaymentState
    (builtinType): string
    required: false