#%RAML 1.0 DataType
displayName: OrderSetParcelItemsAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setParcelItems
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-parcel-items"
examples:
  postman: !include ../../examples/Order/OrderSetParcelItemsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setParcelItems
    required: true
  parcelId:
    type: string
    (builtinType): string
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true