#%RAML 1.0 DataType
type: object
(originalType): ResourceIdentifier
displayName: OrderResourceIdentifier

discriminatorValue: order
properties:
  typeId:
    type: ReferenceTypeId
  id:
    type: string
  key:
    type: string