#%RAML 1.0 DataType
displayName: OrderRemovePaymentAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: removePayment
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#remove-payment"
examples:
  postman: !include ../../examples/Order/OrderRemovePaymentAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removePayment
    required: true
  payment:
    type: PaymentResourceIdentifier
    (builtinType): object
    required: true