#%RAML 1.0 DataType
type: object
(originalType): OrderUpdateAction
displayName: OrderChangeOrderStateAction
# discriminator: action
# discriminatorValue: changeOrderState
properties:
  action:
    default: changeOrderState
    required: true
    type: string
  orderState:
    required: true
    type: OrderState