#%RAML 1.0 DataType
displayName: OrderSetDeliveryItemsAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setDeliveryItems
examples:
  postman: !include ../../examples/Order/OrderSetDeliveryItemsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDeliveryItems
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true