#%RAML 1.0 DataType
(builtinType): object
type: OrderUpdateAction
displayName: OrderRemoveDeliveryAction
discriminator: action
discriminatorValue: removeDelivery
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeDelivery
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true