#%RAML 1.0 DataType
displayName: OrderResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: order
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#order"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - order
    required: false