#%RAML 1.0 DataType
displayName: OrderSetOrderNumberAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setOrderNumber
examples:
  postman: !include ../../examples/Order/OrderSetOrderNumberAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setOrderNumber
    required: true
  orderNumber:
    type: string
    (builtinType): string
    required: false