#%RAML 1.0 DataType
displayName: OrderImportDraft
type: object
(builtinType): object
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders-import.html#orderimportdraft"
properties:
  orderNumber:
    type: string
    (builtinType): string
    description: |-
      String that unique identifies an order.
      It can be used to create more human-readable (in contrast to ID) identifier for the order.
      It should be unique within a project.
    required: false
  customerId:
    type: string
    (builtinType): string
    description: |-
      If given the customer with that ID must exist in the project.
    required: false
  customerEmail:
    type: string
    (builtinType): string
    description: |-
      The customer email can be used when no check against existing Customers is desired during order import.
    required: false
  lineItems:
    type: array
    items:
      type: LineItemImportDraft
    (builtinType): array
    description: |-
      If not given `customLineItems` must not be empty.
    required: false
  customLineItems:
    type: array
    items:
      type: CustomLineItemDraft
    (builtinType): array
    description: |-
      If not given `lineItems` must not be empty.
    required: false
  totalPrice:
    type: Money
    (builtinType): object
    required: true
  taxedPrice:
    type: TaxedPriceDraft
    (builtinType): object
    description: |-
      Order Import does not support calculation of taxes.
      When setting the draft the taxedPrice is to be provided.
    required: false
  shippingAddress:
    type: Address
    (builtinType): object
    required: false
  billingAddress:
    type: Address
    (builtinType): object
    required: false
  customerGroup:
    type: CustomerGroupResourceIdentifier
    (builtinType): object
    description: |-
      Set when the customer is set and the customer is a member of a customer group.
      Used for product variant price selection.
    required: false
  country:
    type: string
    (builtinType): string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
      Used for product variant price selection.
    required: false
  orderState:
    type: OrderState
    (builtinType): string
    description: |-
      If not given the `Open` state will be assigned by default.
    required: false
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: false
  paymentState:
    type: PaymentState
    (builtinType): string
    required: false
  shippingInfo:
    type: ShippingInfoImportDraft
    (builtinType): object
    description: |-
      Set if the ShippingMethod is set.
    required: false
  completedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  inventoryMode:
    type: InventoryMode
    (builtinType): string
    description: |-
      If not given the mode `None` will be assigned by default.
    required: false
  taxRoundingMode:
    type: RoundingMode
    (builtinType): string
    description: |-
      If not given the tax rounding mode `HalfEven` will be assigned by default.
    required: false
  itemShippingAddresses:
    type: array
    items:
      type: Address
    (builtinType): array
    description: |-
      Contains addresses for orders with multiple shipping addresses.
    required: false
  store:
    type: StoreResourceIdentifier
    (builtinType): object
    required: false
  origin:
    type: CartOrigin
    (builtinType): string
    description: |-
      The default origin is `Customer`.
    required: false