#%RAML 1.0 DataType
displayName: OrderSetLineItemShippingDetailsAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemShippingDetails
examples:
  postman: !include ../../examples/Order/OrderSetLineItemShippingDetailsAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemShippingDetails
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false