#%RAML 1.0 DataType
displayName: OrderImportLineItemStateAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: importLineItemState
examples:
  postman: !include ../../examples/Order/OrderImportLineItemStateAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - importLineItemState
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  state:
    type: array
    items:
      type: ItemState
    (builtinType): array
    required: true