#%RAML 1.0 DataType
displayName: OrderSetShippingAddressAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setShippingAddress
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingAddress
    required: true
  address:
    type: Address
    (builtinType): object
    required: false