#%RAML 1.0 DataType
displayName: OrderChangeShipmentStateAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: changeShipmentState
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#change-shipmentstate"
examples:
  postman: !include ../../examples/Order/OrderChangeShipmentStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeShipmentState
    required: true
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: false