#%RAML 1.0 DataType
displayName: OrderUpdateSyncInfoAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: updateSyncInfo
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#update-syncinfo"
examples:
  postman: !include ../../examples/Order/OrderUpdateSyncInfoAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - updateSyncInfo
    required: true
  channel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false
  syncedAt:
    type: datetime
    (builtinType): datetime
    required: false