#%RAML 1.0 DataType
type: object
(originalType): OrderUpdateAction
displayName: OrderSetLocaleAction
# discriminator: action
# discriminatorValue: setLocale
properties:
  action:
    default: setLocale
    required: true
    type: string
  locale:
    required: false
    type: string