#%RAML 1.0 DataType
displayName: OrderAddReturnInfoAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: addReturnInfo
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addReturnInfo
    required: true
  returnTrackingId:
    type: string
    (builtinType): string
    required: false
  items:
    type: array
    items:
      type: ReturnItemDraft
    (builtinType): array
    required: true
  returnDate:
    type: datetime
    (builtinType): datetime
    required: false