#%RAML 1.0 DataType
displayName: OrderResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: order
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - order
    required: false