#%RAML 1.0 DataType
(builtinType): object
type: OrderUpdateAction
displayName: OrderTransitionCustomLineItemStateAction
discriminator: action
discriminatorValue: transitionCustomLineItemState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionCustomLineItemState
    required: true
  toState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  fromState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  actualTransitionDate:
    type: datetime
    (builtinType): datetime
    required: false