#%RAML 1.0 DataType
(builtinType): object
type: OrderUpdateAction
displayName: OrderChangeOrderStateAction
discriminator: action
discriminatorValue: changeOrderState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeOrderState
    required: true
  orderState:
    type: OrderState
    (builtinType): string
    required: true