#%RAML 1.0 DataType
displayName: OrderChangeShipmentStateAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: changeShipmentState
examples:
  postman: !include ../../examples/Order/OrderChangeShipmentStateAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeShipmentState
    required: true
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: false