#%RAML 1.0 DataType
displayName: OrderUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- OrderAddDeliveryAction
- OrderAddItemShippingAddressAction
- OrderAddParcelToDeliveryAction
- OrderAddPaymentAction
- OrderAddReturnInfoAction
- OrderChangeOrderStateAction
- OrderChangePaymentStateAction
- OrderChangeShipmentStateAction
- OrderImportCustomLineItemStateAction
- OrderImportLineItemStateAction
- OrderRemoveDeliveryAction
- OrderRemoveItemShippingAddressAction
- OrderRemoveParcelFromDeliveryAction
- OrderRemovePaymentAction
- OrderSetBillingAddressAction
- OrderSetCustomFieldAction
- OrderSetCustomLineItemCustomFieldAction
- OrderSetCustomLineItemCustomTypeAction
- OrderSetCustomLineItemShippingDetailsAction
- OrderSetCustomTypeAction
- OrderSetCustomerEmailAction
- OrderSetCustomerIdAction
- OrderSetDeliveryAddressAction
- OrderSetDeliveryItemsAction
- OrderSetLineItemCustomFieldAction
- OrderSetLineItemCustomTypeAction
- OrderSetLineItemShippingDetailsAction
- OrderSetLocaleAction
- OrderSetOrderNumberAction
- OrderSetParcelItemsAction
- OrderSetParcelMeasurementsAction
- OrderSetParcelTrackingDataAction
- OrderSetReturnPaymentStateAction
- OrderSetReturnShipmentStateAction
- OrderSetShippingAddressAction
- OrderTransitionCustomLineItemStateAction
- OrderTransitionLineItemStateAction
- OrderTransitionStateAction
- OrderUpdateItemShippingAddressAction
- OrderUpdateSyncInfoAction
properties:
  action:
    type: string
    (builtinType): string
    required: true