#%RAML 1.0 DataType
type: object
(originalType): OrderUpdateAction
displayName: OrderSetLineItemShippingDetailsAction

discriminatorValue: setLineItemShippingDetails
properties:
  action:
    type: string
  shippingDetails:
    type: ItemShippingDetailsDraft
  lineItemId:
    type: string