#%RAML 1.0 DataType
displayName: OrderRemoveItemShippingAddressAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: removeItemShippingAddress
examples:
  postman: !include ../../examples/Order/OrderRemoveItemShippingAddressAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeItemShippingAddress
    required: true
  addressKey:
    type: string
    (builtinType): string
    required: true