#%RAML 1.0 DataType
displayName: OrderRemoveItemShippingAddressAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: removeItemShippingAddress
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#remove-itemshippingaddress"
examples:
  postman:
    strict: true
    value: !include ../../examples/Order/OrderRemoveItemShippingAddressAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeItemShippingAddress
    required: true
  addressKey:
    type: string
    (builtinType): string
    required: true