#%RAML 1.0 DataType
displayName: OrderRemoveDeliveryAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: removeDelivery
examples:
  postman: !include ../../examples/Order/OrderRemoveDeliveryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeDelivery
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true