#%RAML 1.0 DataType
displayName: OrderSetLineItemCustomFieldAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemCustomField
examples:
  postman: !include ../../examples/Order/OrderSetLineItemCustomFieldAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemCustomField
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false