#%RAML 1.0 DataType
displayName: OrderFromCartDraft
type: object
(builtinType): object
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique id of the cart from which an order is created.
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  orderNumber:
    type: string
    (builtinType): string
    description: |-
      String that uniquely identifies an order.
               It can be used to create more human-readable (in contrast to ID) identifier for the order.
               It should be unique across a project.
               Once it's set it cannot be changed.
               For easier use on Get, Update and Delete actions we suggest assigning order numbers that match the regular expression `[a-z0-9_-]{2,36}`.
    required: false
  paymentState:
    type: PaymentState
    (builtinType): string
    required: false
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: false
  orderState:
    type: OrderState
    (builtinType): string
    description: |-
      Order will be created with `Open` status by default.
    required: false
  state:
    type: StateResourceIdentifier
    (builtinType): object
    required: false