#%RAML 1.0 DataType
displayName: OrderSetCustomLineItemCustomFieldAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setCustomLineItemCustomField
examples:
  postman: !include ../../examples/Order/OrderSetCustomLineItemCustomFieldAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemCustomField
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false