#%RAML 1.0 DataType
displayName: OrderSetCustomLineItemCustomTypeAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setCustomLineItemCustomType
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-customlineitem-custom-type"
examples:
  postman:
    strict: true
    value: !include ../../examples/Order/OrderSetCustomLineItemCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemCustomType
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false