#%RAML 1.0 DataType
displayName: OrderReference
type: Reference
(builtinType): object
discriminatorValue: order
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - order
    required: true
  obj:
    type: Order
    (builtinType): object
    required: false