#%RAML 1.0 DataType
displayName: OrderAddPaymentAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: addPayment
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#add-payment"
examples:
  postman: !include ../../examples/Order/OrderAddPaymentAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addPayment
    required: true
  payment:
    type: PaymentResourceIdentifier
    (builtinType): object
    required: true