#%RAML 1.0 DataType
type: object
(originalType): OrderUpdateAction
displayName: OrderAddReturnInfoAction

discriminatorValue: addReturnInfo
properties:
  action:
    type: string
  returnDate:
    type: datetime
  returnTrackingId:
    type: string
  items:
    type: array
    items:
      type: ReturnItemDraft