#%RAML 1.0 DataType
displayName: OrderRemoveParcelFromDeliveryAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: removeParcelFromDelivery
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#remove-parcel-from-delivery"
examples:
  postman:
    strict: true
    value: !include ../../examples/Order/OrderRemoveParcelFromDeliveryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeParcelFromDelivery
    required: true
  parcelId:
    type: string
    (builtinType): string
    required: true