#%RAML 1.0 DataType
displayName: OrderSetOrderNumberAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setOrderNumber
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-order-number"
examples:
  postman: !include ../../examples/Order/OrderSetOrderNumberAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setOrderNumber
    required: true
  orderNumber:
    type: string
    (builtinType): string
    required: false