#%RAML 1.0 DataType
displayName: OrderSetLineItemCustomTypeAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemCustomType
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-lineitem-custom-type"
examples:
  postman:
    strict: true
    value: !include ../../examples/Order/OrderSetLineItemCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemCustomType
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false