#%RAML 1.0 DataType
displayName: OrderSetCustomerEmailAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setCustomerEmail
examples:
  postman: !include ../../examples/Order/OrderSetCustomerEmailAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerEmail
    required: true
  email:
    type: string
    (builtinType): string
    required: false