#%RAML 1.0 DataType
type: object
(originalType): OrderUpdateAction
displayName: OrderTransitionLineItemStateAction
# discriminator: action
# discriminatorValue: transitionLineItemState
properties:
  action:
    default: transitionLineItemState
    required: true
    type: string
  toState:
    required: true
    type: StateResourceIdentifier
  fromState:
    required: true
    type: StateResourceIdentifier
  quantity:
    required: true
    format: int64
    type: number
  lineItemId:
    required: true
    type: string
  actualTransitionDate:
    required: false
    type: datetime