#%RAML 1.0 DataType
(builtinType): object
type: OrderUpdateAction
displayName: OrderAddItemShippingAddressAction
discriminator: action
discriminatorValue: addItemShippingAddress
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addItemShippingAddress
    required: true
  address:
    type: Address
    (builtinType): object
    required: true