#%RAML 1.0 DataType
displayName: OrderTransitionLineItemStateAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: transitionLineItemState
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#change-the-state-of-lineitem-according-to-allowed-transitions"
examples:
  postman:
    strict: true
    value: !include ../../examples/Order/OrderTransitionLineItemStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionLineItemState
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  fromState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  toState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  actualTransitionDate:
    type: datetime
    (builtinType): datetime
    required: false