#%RAML 1.0 DataType
displayName: OrderSetLineItemShippingDetailsAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemShippingDetails
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-lineitemshippingdetails"
examples:
  postman:
    strict: true
    value: !include ../../examples/Order/OrderSetLineItemShippingDetailsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemShippingDetails
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false