#%RAML 1.0 DataType
displayName: OrderSetCustomLineItemShippingDetailsAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setCustomLineItemShippingDetails
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-customlineitemshippingdetails"
examples:
  postman: !include ../../examples/Order/OrderSetCustomLineItemShippingDetailsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemShippingDetails
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false