#%RAML 1.0 DataType
type: object
(originalType): OrderUpdateAction
displayName: OrderSetParcelItemsAction
# discriminator: action
# discriminatorValue: setParcelItems
properties:
  action:
    default: setParcelItems
    required: true
    type: string
  items:
    required: true
    type: array
    items:
      type: DeliveryItem
  parcelId:
    required: true
    type: string