#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: OrderReference
discriminator: typeId
discriminatorValue: order
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - order
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Order
    (builtinType): object
    required: false