#%RAML 1.0 DataType
displayName: OrderSetLocaleAction
type: OrderUpdateAction
(builtinType): object
discriminatorValue: setLocale
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#set-locale"
examples:
  postman: !include ../../examples/Order/OrderSetLocaleAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLocale
    required: true
  locale:
    type: string
    (builtinType): string
    required: false