#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ParcelDraft
properties:
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    description: |-
      The delivery items contained in this parcel.
    required: false
  trackingData:
    type: TrackingData
    (builtinType): object
    required: false
  measurements:
    type: ParcelMeasurements
    (builtinType): object
    required: false