#%RAML 1.0 DataType
type: object
displayName: ParcelMeasurements


properties:
   heightInMillimeter:
      format: int16
      type: number
   lengthInMillimeter:
      format: int16
      type: number
   widthInMillimeter:
      format: int16
      type: number
   weightInGram:
      format: int16
      type: number