#%RAML 1.0 DataType
displayName: ParcelMeasurements
type: object
(builtinType): object
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#parcelmeasurements"
properties:
  heightInMillimeter:
    format: float
    type: number
    (builtinType): number
    required: false
  lengthInMillimeter:
    format: float
    type: number
    (builtinType): number
    required: false
  widthInMillimeter:
    format: float
    type: number
    (builtinType): number
    required: false
  weightInGram:
    format: float
    type: number
    (builtinType): number
    required: false