#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ParcelMeasurements
# 
# 
properties:
  weightInGram:
    required: false
    format: int16
    type: number
  lengthInMillimeter:
    required: false
    format: int16
    type: number
  heightInMillimeter:
    required: false
    format: int16
    type: number
  widthInMillimeter:
    required: false
    format: int16
    type: number