#%RAML 1.0 DataType
displayName: Parcel
type: object
(builtinType): object
properties:
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    description: |-
      The delivery items contained in this parcel.
    required: false
  trackingData:
    type: TrackingData
    (builtinType): object
    required: false
  measurements:
    type: ParcelMeasurements
    (builtinType): object
    required: false