#%RAML 1.0 DataType
displayName: PaymentInfo
type: object
(builtinType): object
properties:
  payments:
    type: array
    items:
      type: PaymentReference
    (builtinType): array
    required: true