#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: PaymentInfo
properties:
  payments:
    type: array
    items:
      type: PaymentReference
    (builtinType): array
    required: true