#%RAML 1.0 DataType
displayName: PaymentState

type: string
enum:
- BalanceDue
- Failed
- Pending
- CreditOwed
- Paid
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#paymentstate"