#%RAML 1.0 DataType
displayName: PaymentInfo
type: object
(builtinType): object
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#paymentinfo"
properties:
  payments:
    type: array
    items:
      type: PaymentReference
    (builtinType): array
    required: true