#%RAML 1.0 DataType
type: object
displayName: ReturnItem
discriminator: type

properties:
   id:
      type: string
   quantity:
      format: int64
      type: number
   type:
      type: string
   comment:
      type: string
   shipmentState:
      type: ReturnShipmentState
   paymentState:
      type: ReturnPaymentState
   lastModifiedAt:
      type: datetime
   createdAt:
      type: datetime