#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ReturnInfo


properties:
  returnDate:
    format: rfc3339
    type: datetime
  returnTrackingId:
    description: |-
      Identifies, which return tracking ID is connected to this particular return.
    type: string
  items:
    type: array
    items:
      type: ReturnItem