#%RAML 1.0 DataType
displayName: ReturnPaymentState

type: string
enum:
- NonRefundable
- Initial
- Refunded
- NotRefunded
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#returnpaymentstate"