#%RAML 1.0 DataType
displayName: ReturnItem
type: object
(builtinType): object
discriminator: type
(oneOf):
- CustomLineItemReturnItem
- LineItemReturnItem
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#returnitem"
properties:
  id:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  type:
    type: string
    (builtinType): string
    required: true
  comment:
    type: string
    (builtinType): string
    required: false
  shipmentState:
    type: ReturnShipmentState
    (builtinType): string
    required: true
  paymentState:
    type: ReturnPaymentState
    (builtinType): string
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true