#%RAML 1.0 DataType
displayName: ReturnItemDraft
type: object
(builtinType): object
(package): "Order"
properties:
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: false
  customLineItemId:
    type: string
    (builtinType): string
    required: false
  comment:
    type: string
    (builtinType): string
    required: false
  shipmentState:
    type: ReturnShipmentState
    (builtinType): string
    required: true