#%RAML 1.0 DataType
displayName: ReturnShipmentState

type: string
enum:
- Advised
- Returned
- BackInStock
- Unusable
(package): "Order"
(docs-uri): "https://docs.commercetools.com/http-api-projects-orders.html#returnshipmentstate"