#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ReturnInfo
properties:
  returnDate:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false
  returnTrackingId:
    type: string
    (builtinType): string
    description: |-
      Identifies, which return tracking ID is connected to this particular return.
    required: false
  items:
    type: array
    items:
      type: ReturnItem
    (builtinType): array
    required: true