#%RAML 1.0 DataType
displayName: ShippingInfoImportDraft
type: object
(builtinType): object
properties:
  shippingMethodName:
    type: string
    (builtinType): string
    required: true
  price:
    type: Money
    (builtinType): object
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    description: |-
      The shipping rate used to determine the price.
    required: true
  taxRate:
    type: TaxRate
    (builtinType): object
    required: false
  taxCategory:
    type: TaxCategoryResourceIdentifier
    (builtinType): object
    required: false
  shippingMethod:
    type: ShippingMethodResourceIdentifier
    (builtinType): object
    description: |-
      Not set if custom shipping method is used.
    required: false
  deliveries:
    type: array
    items:
      type: Delivery
    (builtinType): array
    description: |-
      Deliveries are compilations of information on how the articles are being delivered to the customers.
    required: false
  discountedPrice:
    type: DiscountedLineItemPriceDraft
    (builtinType): object
    required: false
  shippingMethodState:
    type: ShippingMethodState
    (builtinType): string
    description: |-
      Indicates whether the ShippingMethod referenced is allowed for the cart or not.
    required: false