#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ShippingInfoImportDraft


properties:
  taxRate:
    type: TaxRate
  shippingRate:
    description: |-
      The shipping rate used to determine the price.
    type: ShippingRateDraft
  discountedPrice:
    type: DiscountedLineItemPriceDraft
  shippingMethodState:
    description: |-
      Indicates whether the ShippingMethod referenced is allowed for the cart or not.
    type: ShippingMethodState
  price:
    type: Money
  shippingMethod:
    description: |-
      Not set if custom shipping method is used.
    type: ShippingMethodResourceIdentifier
  shippingMethodName:
    type: string
  deliveries:
    description: |-
      Deliveries are compilations of information on how the articles are being delivered to the customers.
    type: array
    items:
      type: Delivery
  taxCategory:
    type: TaxCategoryResourceIdentifier