#%RAML 1.0 DataType
displayName: TaxedItemPriceDraft
type: object
(builtinType): object
properties:
  totalGross:
    type: Money
    (builtinType): object
    required: true
  totalNet:
    type: Money
    (builtinType): object
    required: true