#%RAML 1.0 DataType
displayName: TaxedItemPriceDraft
type: object
(builtinType): object
(package): "Order"
properties:
  totalNet:
    type: Money
    (builtinType): object
    required: true
  totalGross:
    type: Money
    (builtinType): object
    required: true