#%RAML 1.0 DataType
(builtinType): object
type: ExtensionUpdateAction
displayName: ExtensionChangeDestinationAction
discriminator: action
discriminatorValue: changeDestination
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeDestination
    required: true
  destination:
    type: ExtensionDestination
    (builtinType): object
    required: true