#%RAML 1.0 DataType
displayName: ExtensionChangeDestinationAction
type: ExtensionUpdateAction
(builtinType): object
discriminatorValue: changeDestination
examples:
  postman: !include ../../examples/Extension/ExtensionChangeDestinationAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeDestination
    required: true
  destination:
    type: ExtensionDestination
    (builtinType): object
    required: true