#%RAML 1.0 DataType
displayName: ExtensionInput
type: object
(builtinType): object
properties:
  resource:
    type: Reference
    (builtinType): object
    required: true
  action:
    type: ExtensionAction
    (builtinType): string
    required: true