#%RAML 1.0 DataType
displayName: ExtensionHttpDestinationAuthentication
type: object
(builtinType): object
discriminator: type
(oneOf):
- ExtensionAuthorizationHeaderAuthentication
- ExtensionAzureFunctionsAuthentication
properties:
  type:
    type: string
    (builtinType): string
    required: true