#%RAML 1.0 DataType
type: object
(originalType): ExtensionUpdateAction
displayName: ExtensionChangeTriggersAction

discriminatorValue: changeTriggers
properties:
  action:
    required: true
    type: string
  triggers:
    required: true
    type: array
    items:
      type: ExtensionTrigger