#%RAML 1.0 DataType
type: object
displayName: ExtensionDraft


properties:
   key:
      description: |-
        User-specific unique identifier for the extension
      type: string
   destination:
      description: |-
        Details where the extension can be reached
      discriminator: type
      type: ExtensionDestination
   triggers:
      description: |-
        Describes what triggers the extension
      type: array
      items:
        type: ExtensionTrigger
   timeoutInMs:
      description: |-
        The maximum time the commercetools platform waits for a response from the extension.
        The maximum value is 2000 ms (2 seconds).
        This limit can be increased per project after we review the performance impact.
        Please contact Support via the [Support Portal](https://support.commercetools.com) and provide the region, project key and use case.
      format: int16
      type: integer