#%RAML 1.0 DataType
displayName: ExtensionHttpDestination
type: ExtensionDestination
(builtinType): object
discriminatorValue: HTTP
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - HTTP
    required: true
  url:
    type: string
    (builtinType): string
    required: true
  authentication:
    type: ExtensionHttpDestinationAuthentication
    (builtinType): object
    required: false