#%RAML 1.0 DataType
displayName: ExtensionAuthorizationHeaderAuthentication
type: ExtensionHttpDestinationAuthentication
(builtinType): object
discriminatorValue: AuthorizationHeader
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - AuthorizationHeader
    required: true
  headerValue:
    type: string
    (builtinType): string
    required: true