#%RAML 1.0 DataType
(builtinType): object
type: ExtensionHttpDestinationAuthentication
displayName: ExtensionAuthorizationHeaderAuthentication
discriminator: type
discriminatorValue: AuthorizationHeader
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - AuthorizationHeader
    required: true
  headerValue:
    type: string
    (builtinType): string
    required: true