#%RAML 1.0 DataType
(builtinType): object
type: ExtensionDestination
displayName: ExtensionAWSLambdaDestination
discriminator: type
discriminatorValue: AWSLambda
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - AWSLambda
    required: true
  accessKey:
    type: string
    (builtinType): string
    required: true
  arn:
    type: string
    (builtinType): string
    required: true
  accessSecret:
    type: string
    (builtinType): string
    required: true