#%RAML 1.0 DataType
displayName: ExtensionDraft
type: object
(builtinType): object
(package): "Extension"
properties:
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for the extension
    required: false
  destination:
    type: ExtensionDestination
    (builtinType): object
    description: |-
      Details where the extension can be reached
    required: true
  triggers:
    type: array
    items:
      type: ExtensionTrigger
    (builtinType): array
    description: |-
      Describes what triggers the extension
    required: true
  timeoutInMs:
    format: int
    type: integer
    (builtinType): integer
    description: |-
      The maximum time the commercetools platform waits for a response from the extension.
      The maximum value is 2000 ms (2 seconds).
      This limit can be increased per project after we review the performance impact.
      Please contact Support via the [Support Portal](https://support.commercetools.com) and provide the region, project key and use case.
    required: false