#%RAML 1.0 DataType
type: object
(originalType): ExtensionUpdateAction
displayName: ExtensionSetTimeoutInMsAction
# discriminator: action
# discriminatorValue: setTimeoutInMs
properties:
  action:
    default: setTimeoutInMs
    required: true
    type: string
  timeoutInMs:
    required: false
    type: integer