#%RAML 1.0 DataType
displayName: ExtensionUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- ExtensionChangeDestinationAction
- ExtensionChangeTriggersAction
- ExtensionSetKeyAction
- ExtensionSetTimeoutInMsAction
(package): "Extension"
properties:
  action:
    type: string
    (builtinType): string
    required: true