#%RAML 1.0 DataType
displayName: ExtensionAWSLambdaDestination
type: ExtensionDestination
(builtinType): object
discriminatorValue: AWSLambda
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - AWSLambda
    required: true
  arn:
    type: string
    (builtinType): string
    required: true
  accessKey:
    type: string
    (builtinType): string
    required: true
  accessSecret:
    type: string
    (builtinType): string
    required: true