#%RAML 1.0 DataType
type: object
(originalType): ExtensionHttpDestinationAuthentication
displayName: ExtensionAuthorizationHeaderAuthentication
# discriminator: type
# discriminatorValue: AuthorizationHeader
properties:
  type:
    default: AuthorizationHeader
    required: true
    type: string
  headerValue:
    required: true
    type: string