#%RAML 1.0 DataType
type: object
(originalType): ExtensionDestination
displayName: ExtensionHttpDestination
# discriminator: type
# discriminatorValue: HTTP
properties:
  type:
    default: HTTP
    required: true
    type: string
  url:
    required: true
    type: string
  authentication:
    required: false
    type: ExtensionHttpDestinationAuthentication