#%RAML 1.0 DataType
displayName: ExtensionAzureFunctionsAuthentication
type: ExtensionHttpDestinationAuthentication
(builtinType): object
discriminatorValue: AzureFunctions
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - AzureFunctions
    required: true
  key:
    type: string
    (builtinType): string
    required: true