#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ExtensionTrigger
properties:
  resourceTypeId:
    type: ExtensionResourceTypeId
    (builtinType): string
    required: true
  actions:
    type: array
    items:
      type: ExtensionAction
    (builtinType): array
    required: true