#%RAML 1.0 DataType
displayName: ExtensionDestination
type: object
(builtinType): object
discriminator: type
(oneOf):
- ExtensionAWSLambdaDestination
- ExtensionHttpDestination
properties:
  type:
    type: string
    (builtinType): string
    required: true