#%RAML 1.0 DataType
displayName: ExtensionUpdate
type: object
(builtinType): object
(package): "Extension"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: ExtensionUpdateAction
    (builtinType): array
    required: true