#%RAML 1.0 DataType
(builtinType): object
type: ExtensionUpdateAction
displayName: ExtensionSetTimeoutInMsAction
discriminator: action
discriminatorValue: setTimeoutInMs
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTimeoutInMs
    required: true
  timeoutInMs:
    type: integer
    (builtinType): integer
    required: false