#%RAML 1.0 DataType
displayName: ExtensionChangeTriggersAction
type: ExtensionUpdateAction
(builtinType): object
discriminatorValue: changeTriggers
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTriggers
    required: true
  triggers:
    type: array
    items:
      type: ExtensionTrigger
    (builtinType): array
    required: true