#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategorySetAssetCustomTypeAction
discriminator: action
discriminatorValue: setAssetCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetCustomType
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  fields:
    type: object
    (builtinType): object
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false