#%RAML 1.0 DataType
displayName: CategoryResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: category
(package): "Category"
(docs-uri): "https://docs.commercetools.com/http-api-projects-categories.html#category"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - category
    required: false