#%RAML 1.0 DataType
displayName: CategoryRemoveAssetAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: removeAsset
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAsset
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false