#%RAML 1.0 DataType
displayName: CategorySetExternalIdAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setExternalId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExternalId
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false