#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategorySetMetaKeywordsAction

discriminatorValue: setMetaKeywords
properties:
  action:
    required: true
    type: string
  metaKeywords:
    required: false
    type: LocalizedString