#%RAML 1.0 DataType
displayName: CategoryUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- CategoryAddAssetAction
- CategoryChangeAssetNameAction
- CategoryChangeAssetOrderAction
- CategoryChangeNameAction
- CategoryChangeOrderHintAction
- CategoryChangeParentAction
- CategoryChangeSlugAction
- CategoryRemoveAssetAction
- CategorySetAssetCustomFieldAction
- CategorySetAssetCustomTypeAction
- CategorySetAssetDescriptionAction
- CategorySetAssetKeyAction
- CategorySetAssetSourcesAction
- CategorySetAssetTagsAction
- CategorySetCustomFieldAction
- CategorySetCustomTypeAction
- CategorySetDescriptionAction
- CategorySetExternalIdAction
- CategorySetKeyAction
- CategorySetMetaDescriptionAction
- CategorySetMetaKeywordsAction
- CategorySetMetaTitleAction
properties:
  action:
    type: string
    (builtinType): string
    required: true