#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategoryChangeOrderHintAction

discriminatorValue: changeOrderHint
properties:
  action:
    required: true
    type: string
  orderHint:
    required: true
    type: string