#%RAML 1.0 DataType
displayName: CategoryChangeAssetOrderAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: changeAssetOrder
examples:
  postman: !include ../../examples/Category/CategoryChangeAssetOrderAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAssetOrder
    required: true
  assetOrder:
    type: array
    items:
      type: string
    (builtinType): array
    required: true