#%RAML 1.0 DataType
displayName: CategoryChangeAssetNameAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: changeAssetName
examples:
  postman: !include ../../examples/Category/CategoryChangeAssetNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAssetName
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true