#%RAML 1.0 DataType
displayName: CategorySetAssetDescriptionAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setAssetDescription
(package): "Category"
(docs-uri): "https://docs.commercetools.com/http-api-projects-categories.html#set-asset-description"
examples:
  postman:
    strict: true
    value: !include ../../examples/Category/CategorySetAssetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetDescription
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false