#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategorySetAssetTagsAction
# discriminator: action
# discriminatorValue: setAssetTags
properties:
  action:
    default: setAssetTags
    required: true
    type: string
  assetId:
    required: false
    type: string
  assetKey:
    required: false
    type: string
  tags:
    required: false
    type: array
    items:
      type: string