#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: CategoryReference
discriminator: typeId
discriminatorValue: category
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - category
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Category
    (builtinType): object
    required: false