#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategorySetAssetTagsAction

discriminatorValue: setAssetTags
properties:
  action:
    type: string
  assetId:
    type: string
  assetKey:
    type: string
  tags:
    type: array
    items:
      type: string