#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategoryChangeAssetNameAction
discriminator: action
discriminatorValue: changeAssetName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAssetName
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  assetKey:
    type: string
    (builtinType): string
    required: false