#%RAML 1.0 DataType
displayName: CategoryAddAssetAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: addAsset
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addAsset
    required: true
  asset:
    type: AssetDraft
    (builtinType): object
    required: true
  position:
    format: int32
    type: number
    (builtinType): number
    required: false