#%RAML 1.0 DataType
displayName: CategoryChangeParentAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: changeParent
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeParent
    required: true
  parent:
    type: CategoryResourceIdentifier
    (builtinType): object
    required: true