#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategoryChangeSlugAction
discriminator: action
discriminatorValue: changeSlug
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeSlug
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: true