#%RAML 1.0 DataType
displayName: CategorySetMetaTitleAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setMetaTitle
examples:
  postman: !include ../../examples/Category/CategorySetMetaTitleAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMetaTitle
    required: true
  metaTitle:
    type: LocalizedString
    (builtinType): object
    required: false