#%RAML 1.0 DataType
type: object
(originalType): Reference
displayName: CategoryReference
# discriminator: typeId
# discriminatorValue: category
properties:
  typeId:
    default: category
    required: true
    type: ReferenceTypeId
  id:
    required: true
    type: string
  obj:
    required: false
    type: Category