#%RAML 1.0 DataType
displayName: CategoryChangeOrderHintAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: changeOrderHint
examples:
  postman: !include ../../examples/Category/CategoryChangeOrderHintAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeOrderHint
    required: true
  orderHint:
    type: string
    (builtinType): string
    required: true