#%RAML 1.0 DataType
displayName: CategorySetAssetKeyAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setAssetKey
(package): "Category"
(docs-uri): "https://docs.commercetools.com/http-api-projects-categories.html#set-asset-key"
examples:
  postman: !include ../../examples/Category/CategorySetAssetKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetKey
    required: true
  assetId:
    type: string
    (builtinType): string
    required: true
  assetKey:
    type: string
    (builtinType): string
    required: false