#%RAML 1.0 DataType
displayName: CategorySetMetaKeywordsAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setMetaKeywords
examples:
  postman: !include ../../examples/Category/CategorySetMetaKeywordsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMetaKeywords
    required: true
  metaKeywords:
    type: LocalizedString
    (builtinType): object
    required: false