#%RAML 1.0 DataType
displayName: CategoryReference
type: Reference
(builtinType): object
discriminatorValue: category
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - category
    required: true
  obj:
    type: Category
    (builtinType): object
    required: false