#%RAML 1.0 DataType
displayName: CategoryResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: category
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - category
    required: false