#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategorySetAssetDescriptionAction
discriminator: action
discriminatorValue: setAssetDescription
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetDescription
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false