#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategoryRemoveAssetAction
discriminator: action
discriminatorValue: removeAsset
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAsset
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false