#%RAML 1.0 DataType
displayName: CategorySetCustomTypeAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setCustomType
examples:
  postman: !include ../../examples/Category/CategorySetCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false