#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategoryAddAssetAction

discriminatorValue: addAsset
properties:
  action:
    required: true
    type: string
  position:
    required: false
    format: int32
    type: number
  asset:
    required: true
    type: AssetDraft