#%RAML 1.0 DataType
displayName: CategoryChangeSlugAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: changeSlug
examples:
  postman: !include ../../examples/Category/CategoryChangeSlugAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeSlug
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: true