#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategorySetDescriptionAction
discriminator: action
discriminatorValue: setDescription
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false