#%RAML 1.0 DataType
displayName: CategorySetAssetSourcesAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setAssetSources
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetSources
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  sources:
    type: array
    items:
      type: AssetSource
    (builtinType): array
    required: true