#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategoryChangeNameAction
discriminator: action
discriminatorValue: changeName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true