#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategorySetMetaDescriptionAction

discriminatorValue: setMetaDescription
properties:
  action:
    required: true
    type: string
  metaDescription:
    required: false
    type: LocalizedString