#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategoryChangeParentAction
# discriminator: action
# discriminatorValue: changeParent
properties:
  action:
    default: changeParent
    required: true
    type: string
  parent:
    required: true
    type: CategoryResourceIdentifier