#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategorySetAssetKeyAction

discriminatorValue: setAssetKey
properties:
  action:
    required: true
    type: string
  assetId:
    required: true
    type: string
  assetKey:
    required: false
    type: string