#%RAML 1.0 DataType
displayName: CategorySetAssetCustomFieldAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setAssetCustomField
examples:
  postman: !include ../../examples/Category/CategorySetAssetCustomFieldAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetCustomField
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false