#%RAML 1.0 DataType
displayName: CategorySetAssetCustomTypeAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setAssetCustomType
examples:
  postman: !include ../../examples/Category/CategorySetAssetCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetCustomType
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: object
    (builtinType): object
    required: false