#%RAML 1.0 DataType
displayName: CategorySetMetaDescriptionAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setMetaDescription
examples:
  postman: !include ../../examples/Category/CategorySetMetaDescriptionAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMetaDescription
    required: true
  metaDescription:
    type: LocalizedString
    (builtinType): object
    required: false