#%RAML 1.0 DataType
(builtinType): object
type: CategoryUpdateAction
displayName: CategoryChangeAssetOrderAction
discriminator: action
discriminatorValue: changeAssetOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAssetOrder
    required: true
  assetOrder:
    type: array
    items:
      type: string
    (builtinType): array
    required: true