#%RAML 1.0 DataType
type: object
(originalType): CategoryUpdateAction
displayName: CategorySetAssetSourcesAction

discriminatorValue: setAssetSources
properties:
  action:
    type: string
  sources:
    type: array
    items:
      type: AssetSource
  assetId:
    type: string
  assetKey:
    type: string