#%RAML 1.0 DataType
displayName: CategorySetKeyAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: setKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false