#%RAML 1.0 DataType
displayName: CategoryChangeSlugAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: changeSlug
(package): "Category"
(docs-uri): "https://docs.commercetools.com/http-api-projects-categories.html#change-slug"
examples:
  postman:
    strict: true
    value: !include ../../examples/Category/CategoryChangeSlugAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeSlug
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: true