#%RAML 1.0 DataType
displayName: CategoryChangeParentAction
type: CategoryUpdateAction
(builtinType): object
discriminatorValue: changeParent
examples:
  postman: !include ../../examples/Category/CategoryChangeParentAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeParent
    required: true
  parent:
    type: CategoryResourceIdentifier
    (builtinType): object
    required: true