#%RAML 1.0 DataType
type: object
(originalType): Destination
displayName: AzureServiceBusDestination

discriminatorValue: AzureServiceBus
properties:
  type:
    type: string
  connectionString:
    type: string