#%RAML 1.0 DataType
displayName: AzureEventGridDestination
type: Destination
(builtinType): object
discriminatorValue: EventGrid
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - EventGrid
    required: true
  uri:
    type: string
    (builtinType): string
    required: true
  accessKey:
    type: string
    (builtinType): string
    required: true