#%RAML 1.0 DataType
type: object
(originalType): Destination
displayName: AzureEventGridDestination

discriminatorValue: EventGrid
properties:
  type:
    required: true
    type: string
  accessKey:
    required: true
    type: string
  uri:
    required: true
    type: string