#%RAML 1.0 DataType
(builtinType): object
type: Destination
displayName: AzureEventGridDestination
discriminator: type
discriminatorValue: EventGrid
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - EventGrid
    required: true
  accessKey:
    type: string
    (builtinType): string
    required: true
  uri:
    type: string
    (builtinType): string
    required: true