#%RAML 1.0 DataType
displayName: DeliveryCloudEventsFormat
type: DeliveryFormat
(builtinType): object
discriminatorValue: CloudEvents
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CloudEvents
    required: true
  cloudEventsVersion:
    type: string
    (builtinType): string
    required: true