#%RAML 1.0 DataType
displayName: DeliveryCloudEventsFormat
type: DeliveryFormat
(builtinType): object
discriminatorValue: CloudEvents
(package): "Subscription"
(docs-uri): "https://docs.commercetools.com/http-api-projects-subscriptions.html#cloudevents-format-preview"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CloudEvents
    required: true
  cloudEventsVersion:
    type: string
    (builtinType): string
    enum:
    - 0.1
    required: true