#%RAML 1.0 DataType
displayName: DeliveryFormat
type: object
(builtinType): object
discriminator: type
(oneOf):
- DeliveryCloudEventsFormat
- DeliveryPlatformFormat
properties:
  type:
    type: string
    (builtinType): string
    required: true