#%RAML 1.0 DataType
displayName: DeliveryPlatformFormat
type: DeliveryFormat
(builtinType): object
discriminatorValue: Platform
(package): "Subscription"
(docs-uri): "https://docs.commercetools.com/http-api-projects-subscriptions.html#platform-format"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Platform
    required: true