#%RAML 1.0 DataType
(builtinType): object
type: DeliveryFormat
displayName: DeliveryCloudEventsFormat
discriminator: type
discriminatorValue: CloudEvents
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - CloudEvents
    required: true
  cloudEventsVersion:
    type: string
    (builtinType): string
    required: true