#%RAML 1.0 DataType
displayName: DeliveryPlatformFormat
type: DeliveryFormat
(builtinType): object
discriminatorValue: Platform
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Platform
    required: true