#%RAML 1.0 DataType
(builtinType): object
type: DeliveryFormat
displayName: DeliveryPlatformFormat
discriminator: type
discriminatorValue: Platform
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Platform
    required: true