#%RAML 1.0 DataType
displayName: Destination
type: object
(builtinType): object
discriminator: type
(oneOf):
- AzureEventGridDestination
- AzureServiceBusDestination
- GoogleCloudPubSubDestination
- IronMqDestination
- SnsDestination
- SqsDestination
(package): "Subscription"
properties:
  type:
    type: string
    (builtinType): string
    required: true