#%RAML 1.0 DataType
type: object
(originalType): Destination
displayName: GoogleCloudPubSubDestination
# discriminator: type
# discriminatorValue: GoogleCloudPubSub
properties:
  type:
    default: GoogleCloudPubSub
    required: true
    type: string
  topic:
    required: true
    type: string
  projectId:
    required: true
    type: string