#%RAML 1.0 DataType
displayName: GoogleCloudPubSubDestination
type: Destination
(builtinType): object
discriminatorValue: GoogleCloudPubSub
(package): "Subscription"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - GoogleCloudPubSub
    required: true
  projectId:
    type: string
    (builtinType): string
    required: true
  topic:
    type: string
    (builtinType): string
    required: true