#%RAML 1.0 DataType
(builtinType): object
type: Destination
displayName: GoogleCloudPubSubDestination
discriminator: type
discriminatorValue: GoogleCloudPubSub
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - GoogleCloudPubSub
    required: true
  topic:
    type: string
    (builtinType): string
    required: true
  projectId:
    type: string
    (builtinType): string
    required: true