#%RAML 1.0 DataType
displayName: IronMqDestination
type: Destination
(builtinType): object
discriminatorValue: IronMQ
(package): "Subscription"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - IronMQ
    required: true
  uri:
    type: string
    (builtinType): string
    required: true