#%RAML 1.0 DataType
(builtinType): object
type: Destination
displayName: IronMqDestination
discriminator: type
discriminatorValue: IronMQ
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - IronMQ
    required: true
  uri:
    type: string
    (builtinType): string
    required: true