#%RAML 1.0 DataType
displayName: MessageSubscription
type: object
(builtinType): object
(package): "Subscription"
properties:
  resourceTypeId:
    type: string
    (builtinType): string
    required: true
  types:
    type: array
    items:
      type: string
    (builtinType): array
    required: false