#%RAML 1.0 DataType
displayName: MessageSubscription
type: object
(builtinType): object
properties:
  types:
    type: array
    items:
      type: string
    (builtinType): array
    required: false
  resourceTypeId:
    type: string
    (builtinType): string
    required: true