#%RAML 1.0 DataType
(builtinType): object
type: SubscriptionDelivery
displayName: MessageDelivery
discriminator: notificationType
discriminatorValue: Message
properties:
  projectKey:
    type: string
    (builtinType): string
    required: true
  resource:
    type: Reference
    (builtinType): object
    required: true
  resourceUserProvidedIdentifiers:
    type: UserProvidedIdentifiers
    (builtinType): object
    required: false
  notificationType:
    type: string
    (builtinType): string
    enum:
    - Message
    required: true
  sequenceNumber:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  resourceVersion:
    format: int64
    type: number
    (builtinType): number
    required: true
  payloadNotIncluded:
    type: PayloadNotIncluded
    (builtinType): object
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true