#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: PayloadNotIncluded
properties:
  reason:
    type: string
    (builtinType): string
    required: true
  payloadType:
    type: string
    (builtinType): string
    required: true