#%RAML 1.0 DataType
type: object
(originalType): SubscriptionDelivery
displayName: ResourceDeletedDelivery

discriminatorValue: ResourceDeleted
properties:
  projectKey:
    type: string
  resource:
    type: Reference
  resourceUserProvidedIdentifiers:
    type: UserProvidedIdentifiers
  notificationType:
    type: string
  modifiedAt:
    type: datetime
  version:
    format: int64
    type: number