#%RAML 1.0 DataType
type: object
(originalType): SubscriptionDelivery
displayName: ResourceUpdatedDelivery
# discriminator: notificationType
# discriminatorValue: ResourceUpdated
properties:
  projectKey:
    required: true
    type: string
  resource:
    required: true
    type: Reference
  resourceUserProvidedIdentifiers:
    required: false
    type: UserProvidedIdentifiers
  notificationType:
    default: ResourceUpdated
    required: true
    type: string
  modifiedAt:
    required: true
    type: datetime
  oldVersion:
    required: true
    format: int64
    type: number
  version:
    required: true
    format: int64
    type: number