#%RAML 1.0 DataType
displayName: SnsDestination
type: Destination
(builtinType): object
discriminatorValue: SNS
(package): "Subscription"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - SNS
    required: true
  accessKey:
    type: string
    (builtinType): string
    required: true
  accessSecret:
    type: string
    (builtinType): string
    required: true
  topicArn:
    type: string
    (builtinType): string
    required: true