#%RAML 1.0 DataType
displayName: SqsDestination
type: Destination
(builtinType): object
discriminatorValue: SQS
(package): "Subscription"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - SQS
    required: true
  accessKey:
    type: string
    (builtinType): string
    required: true
  accessSecret:
    type: string
    (builtinType): string
    required: true
  queueUrl:
    type: string
    (builtinType): string
    required: true
  region:
    type: string
    (builtinType): string
    required: true