#%RAML 1.0 DataType
displayName: Subscription
type: LoggedResource
(builtinType): object
properties:
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  changes:
    type: array
    items:
      type: ChangeSubscription
    (builtinType): array
    required: true
  destination:
    discriminator: "type"
    type: Destination
    (builtinType): object
    required: true
  key:
    type: string
    (builtinType): string
    required: false
  messages:
    type: array
    items:
      type: MessageSubscription
    (builtinType): array
    required: true
  format:
    discriminator: "type"
    type: DeliveryFormat
    (builtinType): object
    required: true
  status:
    type: SubscriptionHealthStatus
    (builtinType): string
    required: true