#%RAML 1.0 DataType
displayName: SubscriptionDraft
type: object
(builtinType): object
(package): "Subscription"
(docs-uri): "https://docs.commercetools.com/http-api-projects-subscriptions.html#subscriptiondraft"
properties:
  changes:
    type: array
    items:
      type: ChangeSubscription
    (builtinType): array
    required: false
  destination:
    type: Destination
    (builtinType): object
    required: true
  key:
    type: string
    (builtinType): string
    required: false
  messages:
    type: array
    items:
      type: MessageSubscription
    (builtinType): array
    required: false
  format:
    type: DeliveryFormat
    (builtinType): object
    required: false