#%RAML 1.0 DataType
displayName: SubscriptionDelivery
type: object
(builtinType): object
discriminator: notificationType
(oneOf):
- MessageDelivery
- ResourceCreatedDelivery
- ResourceDeletedDelivery
- ResourceUpdatedDelivery
properties:
  projectKey:
    type: string
    (builtinType): string
    required: true
  notificationType:
    type: string
    (builtinType): string
    required: true
  resource:
    type: Reference
    (builtinType): object
    required: true
  resourceUserProvidedIdentifiers:
    type: UserProvidedIdentifiers
    (builtinType): object
    required: false