#%RAML 1.0 DataType
displayName: SubscriptionChangeDestinationAction
type: SubscriptionUpdateAction
(builtinType): object
discriminatorValue: changeDestination
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeDestination
    required: true
  destination:
    type: Destination
    (builtinType): object
    required: true