#%RAML 1.0 DataType
displayName: SubscriptionPagedQueryResponse
type: object
(builtinType): object
properties:
  limit:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  count:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  total:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  offset:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  results:
    type: array
    items:
      type: Subscription
    (builtinType): array
    required: true