#%RAML 1.0 DataType
displayName: SubscriptionSetMessagesAction
type: SubscriptionUpdateAction
(builtinType): object
discriminatorValue: setMessages
(package): "Subscription"
(docs-uri): "https://docs.commercetools.com/http-api-projects-subscriptions.html#set-messages"
examples:
  postman: !include ../../examples/Subscription/SubscriptionSetMessagesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMessages
    required: true
  messages:
    type: array
    items:
      type: MessageSubscription
    (builtinType): array
    required: false