#%RAML 1.0 DataType
displayName: SubscriptionChangeDestinationAction
type: SubscriptionUpdateAction
(builtinType): object
discriminatorValue: changeDestination
(package): "Subscription"
(docs-uri): "https://docs.commercetools.com/http-api-projects-subscriptions.html#change-destination"
examples:
  postman:
    strict: true
    value: !include ../../examples/Subscription/SubscriptionChangeDestinationAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeDestination
    required: true
  destination:
    type: Destination
    (builtinType): object
    required: true