#%RAML 1.0 DataType
displayName: SubscriptionSetChangesAction
type: SubscriptionUpdateAction
(builtinType): object
discriminatorValue: setChanges
examples:
  postman: !include ../../examples/Subscription/SubscriptionSetChangesAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setChanges
    required: true
  changes:
    type: array
    items:
      type: ChangeSubscription
    (builtinType): array
    required: false