#%RAML 1.0 DataType
type: object
(originalType): SubscriptionUpdateAction
displayName: SubscriptionSetChangesAction
# discriminator: action
# discriminatorValue: setChanges
properties:
  action:
    default: setChanges
    required: true
    type: string
  changes:
    required: false
    type: array
    items:
      type: ChangeSubscription