#%RAML 1.0 DataType
(builtinType): object
type: SubscriptionUpdateAction
displayName: SubscriptionSetMessagesAction
discriminator: action
discriminatorValue: setMessages
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMessages
    required: true
  messages:
    type: array
    items:
      type: MessageSubscription
    (builtinType): array
    required: false