#%RAML 1.0 DataType
(builtinType): object
type: SubscriptionUpdateAction
displayName: SubscriptionChangeDestinationAction
discriminator: action
discriminatorValue: changeDestination
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeDestination
    required: true
  destination:
    type: Destination
    (builtinType): object
    required: true