#%RAML 1.0 DataType
displayName: SubscriptionSetMessagesAction
type: SubscriptionUpdateAction
(builtinType): object
discriminatorValue: setMessages
examples:
  postman: !include ../../examples/Subscription/SubscriptionSetMessagesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMessages
    required: true
  messages:
    type: array
    items:
      type: MessageSubscription
    (builtinType): array
    required: false