#%RAML 1.0 DataType
displayName: SubscriptionUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- SubscriptionChangeDestinationAction
- SubscriptionSetChangesAction
- SubscriptionSetKeyAction
- SubscriptionSetMessagesAction
(package): "Subscription"
properties:
  action:
    type: string
    (builtinType): string
    required: true