#%RAML 1.0 DataType
displayName: SubscriptionDraft
type: object
(builtinType): object
properties:
  format:
    discriminator: type
    type: DeliveryFormat
    (builtinType): object
    required: false
  destination:
    discriminator: type
    type: Destination
    (builtinType): object
    required: true
  changes:
    type: array
    items:
      type: ChangeSubscription
    (builtinType): array
    required: false
  messages:
    type: array
    items:
      type: MessageSubscription
    (builtinType): array
    required: false
  key:
    type: string
    (builtinType): string
    required: false