#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeDateTimeType
discriminator: name
discriminatorValue: datetime
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - datetime
    required: true