#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeMoneyType
discriminator: name
discriminatorValue: money
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - money
    required: true