#%RAML 1.0 DataType
displayName: AttributeNestedType
type: AttributeType
(builtinType): object
discriminatorValue: nested
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#nestedtype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - nested
    required: true
  typeReference:
    type: ProductTypeReference
    (builtinType): object
    required: true