#%RAML 1.0 DataType
displayName: AttributeSetType
type: AttributeType
(builtinType): object
discriminatorValue: set
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#settype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - set
    required: true
  elementType:
    type: AttributeType
    (builtinType): object
    required: true