#%RAML 1.0 DataType
displayName: AttributePlainEnumValue
type: object
(builtinType): object
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#plainenumvalue"
properties:
  key:
    type: string
    (builtinType): string
    required: true
  label:
    type: string
    (builtinType): string
    required: true