#%RAML 1.0 DataType
type: object
(originalType): AttributeType
displayName: AttributeEnumType
# discriminator: name
# discriminatorValue: enum
properties:
  name:
    default: enum
    required: true
    type: string
  values:
    required: true
    type: array
    items:
      type: AttributePlainEnumValue