#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeNestedType
discriminator: name
discriminatorValue: nested
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - nested
    required: true
  typeReference:
    type: ProductTypeReference
    (builtinType): object
    required: true