#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeEnumType
discriminator: name
discriminatorValue: enum
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - enum
    required: true
  values:
    type: array
    items:
      type: AttributePlainEnumValue
    (builtinType): array
    required: true