#%RAML 1.0 DataType
displayName: AttributeBooleanType
type: AttributeType
(builtinType): object
discriminatorValue: boolean
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#booleantype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - boolean
    required: true