#%RAML 1.0 DataType
displayName: AttributeTimeType
type: AttributeType
(builtinType): object
discriminatorValue: time
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#timetype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - time
    required: true