#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeTextType
discriminator: name
discriminatorValue: text
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - text
    required: true