#%RAML 1.0 DataType
displayName: AttributeTextType
type: AttributeType
(builtinType): object
discriminatorValue: text
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#texttype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - text
    required: true