#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeNumberType
discriminator: name
discriminatorValue: number
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - number
    required: true