#%RAML 1.0 DataType
type: object
(originalType): AttributeType
displayName: AttributeTimeType
# discriminator: name
# discriminatorValue: time
properties:
  name:
    default: time
    required: true
    type: string