#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeLocalizedEnumType
discriminator: name
discriminatorValue: lenum
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - lenum
    required: true
  values:
    type: array
    items:
      type: AttributeLocalizedEnumValue
    (builtinType): array
    required: true