#%RAML 1.0 DataType
displayName: AttributeNestedType
type: AttributeType
(builtinType): object
discriminatorValue: nested
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - nested
    required: true
  typeReference:
    type: ProductTypeReference
    (builtinType): object
    required: true