#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeBooleanType
discriminator: name
discriminatorValue: boolean
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - boolean
    required: true