#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeTimeType
discriminator: name
discriminatorValue: time
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - time
    required: true