#%RAML 1.0 DataType
displayName: AttributeDateType
type: AttributeType
(builtinType): object
discriminatorValue: date
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#datetype"
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - date
    required: true