#%RAML 1.0 DataType
(builtinType): object
type: AttributeType
displayName: AttributeDateType
discriminator: name
discriminatorValue: date
properties:
  name:
    type: string
    (builtinType): string
    enum:
    - date
    required: true