#%RAML 1.0 DataType
displayName: ProductTypeReference
type: Reference
(builtinType): object
discriminatorValue: product-type
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-type
    required: true
  obj:
    type: ProductType
    (builtinType): object
    required: false