#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeAddLocalizedEnumValueAction

discriminatorValue: addLocalizedEnumValue
properties:
  action:
    type: string
  attributeName:
    type: string
  value:
    type: AttributeLocalizedEnumValue