#%RAML 1.0 DataType
displayName: ProductTypeUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- ProductTypeAddAttributeDefinitionAction
- ProductTypeAddLocalizedEnumValueAction
- ProductTypeAddPlainEnumValueAction
- ProductTypeChangeAttributeConstraintAction
- ProductTypeChangeAttributeNameAction
- ProductTypeChangeAttributeOrderAction
- ProductTypeChangeAttributeOrderByNameAction
- ProductTypeChangeDescriptionAction
- ProductTypeChangeEnumKeyAction
- ProductTypeChangeInputHintAction
- ProductTypeChangeIsSearchableAction
- ProductTypeChangeLabelAction
- ProductTypeChangeLocalizedEnumValueLabelAction
- ProductTypeChangeLocalizedEnumValueOrderAction
- ProductTypeChangeNameAction
- ProductTypeChangePlainEnumValueLabelAction
- ProductTypeChangePlainEnumValueOrderAction
- ProductTypeRemoveAttributeDefinitionAction
- ProductTypeRemoveEnumValuesAction
- ProductTypeSetInputTipAction
- ProductTypeSetKeyAction
(package): "ProductType"
properties:
  action:
    type: string
    (builtinType): string
    required: true