#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeEnumKeyAction
discriminator: action
discriminatorValue: changeEnumKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeEnumKey
    required: true
  newKey:
    type: string
    (builtinType): string
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  key:
    type: string
    (builtinType): string
    required: true