#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeRemoveAttributeDefinitionAction

discriminatorValue: removeAttributeDefinition
properties:
  action:
    required: true
    type: string
  name:
    required: true
    type: string