#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeChangePlainEnumValueLabelAction
# discriminator: action
# discriminatorValue: changePlainEnumValueLabel
properties:
  action:
    default: changePlainEnumValueLabel
    required: true
    type: string
  newValue:
    required: true
    type: AttributePlainEnumValue
  attributeName:
    required: true
    type: string