#%RAML 1.0 DataType
displayName: ProductTypeChangeAttributeOrderByNameAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeAttributeOrderByName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeOrderByName
    required: true
  attributeNames:
    type: array
    items:
      type: string
    (builtinType): array
    required: true