#%RAML 1.0 DataType
displayName: ProductTypeResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: product-type
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-type
    required: false