#%RAML 1.0 DataType
displayName: ProductTypeChangeAttributeConstraintAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeAttributeConstraint
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#change-attributedefinition-attributeconstraint"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeConstraint
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  newValue:
    type: AttributeConstraintEnumDraft
    (builtinType): string
    enum:
    - None
    required: true