#%RAML 1.0 DataType
displayName: ProductTypeAddLocalizedEnumValueAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: addLocalizedEnumValue
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addLocalizedEnumValue
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  value:
    type: AttributeLocalizedEnumValue
    (builtinType): object
    required: true