#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeOrderAction
discriminator: action
discriminatorValue: changeAttributeOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeOrder
    required: true
  attributes:
    type: array
    items:
      type: AttributeDefinition
    (builtinType): array
    required: true