#%RAML 1.0 DataType
displayName: ProductTypeChangePlainEnumValueOrderAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changePlainEnumValueOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePlainEnumValueOrder
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  values:
    type: array
    items:
      type: AttributePlainEnumValue
    (builtinType): array
    required: true