#%RAML 1.0 DataType
displayName: ProductTypeChangeEnumKeyAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeEnumKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeEnumKey
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  key:
    type: string
    (builtinType): string
    required: true
  newKey:
    type: string
    (builtinType): string
    required: true