#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeNameAction
discriminator: action
discriminatorValue: changeAttributeName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeName
    required: true
  newAttributeName:
    type: string
    (builtinType): string
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true