#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeConstraintAction

discriminatorValue: changeAttributeConstraint
properties:
  action:
    required: true
    type: string
  newValue:
    required: true
    type: AttributeConstraintEnumDraft
  attributeName:
    required: true
    type: string