#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangePlainEnumValueLabelAction
discriminator: action
discriminatorValue: changePlainEnumValueLabel
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePlainEnumValueLabel
    required: true
  newValue:
    type: AttributePlainEnumValue
    (builtinType): object
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true