#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeChangePlainEnumValueOrderAction

discriminatorValue: changePlainEnumValueOrder
properties:
  action:
    type: string
  values:
    type: array
    items:
      type: AttributePlainEnumValue
  attributeName:
    type: string