#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductTypeUpdate


properties:
  actions:
    required: true
    type: array
    items:
      type: ProductTypeUpdateAction
  version:
    required: true
    format: int64
    type: number