#%RAML 1.0 DataType
displayName: ProductTypeChangeLocalizedEnumValueLabelAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeLocalizedEnumValueLabel
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#change-the-label-of-an-enumvalue"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLocalizedEnumValueLabel
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  newValue:
    type: AttributeLocalizedEnumValue
    (builtinType): object
    required: true