#%RAML 1.0 DataType
displayName: ProductTypeAddAttributeDefinitionAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: addAttributeDefinition
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addAttributeDefinition
    required: true
  attribute:
    type: AttributeDefinitionDraft
    (builtinType): object
    required: true