#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangePlainEnumValueOrderAction
discriminator: action
discriminatorValue: changePlainEnumValueOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePlainEnumValueOrder
    required: true
  values:
    type: array
    items:
      type: AttributePlainEnumValue
    (builtinType): array
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true