#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeOrderByNameAction
discriminator: action
discriminatorValue: changeAttributeOrderByName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeOrderByName
    required: true
  attributeNames:
    type: array
    items:
      type: string
    (builtinType): array
    required: true