#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeLabelAction
discriminator: action
discriminatorValue: changeLabel
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLabel
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  label:
    type: LocalizedString
    (builtinType): object
    required: true