#%RAML 1.0 DataType
displayName: ProductTypeResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: product-type
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#producttype"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-type
    required: false