#%RAML 1.0 DataType
displayName: ProductTypeChangeAttributeNameAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeAttributeName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeName
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  newAttributeName:
    type: string
    (builtinType): string
    required: true