#%RAML 1.0 DataType
displayName: ProductTypeChangePlainEnumValueLabelAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changePlainEnumValueLabel
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePlainEnumValueLabel
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  newValue:
    type: AttributePlainEnumValue
    (builtinType): object
    required: true