#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeChangeLabelAction
# discriminator: action
# discriminatorValue: changeLabel
properties:
  action:
    default: changeLabel
    required: true
    type: string
  attributeName:
    required: true
    type: string
  label:
    required: true
    type: LocalizedString