#%RAML 1.0 DataType
displayName: ProductTypeChangeInputHintAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeInputHint
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeInputHint
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  newValue:
    type: TextInputHint
    (builtinType): string
    required: true