#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeAddAttributeDefinitionAction
discriminator: action
discriminatorValue: addAttributeDefinition
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addAttributeDefinition
    required: true
  attribute:
    type: AttributeDefinitionDraft
    (builtinType): object
    required: true