#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeLocalizedEnumValueLabelAction
discriminator: action
discriminatorValue: changeLocalizedEnumValueLabel
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLocalizedEnumValueLabel
    required: true
  newValue:
    type: AttributeLocalizedEnumValue
    (builtinType): object
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true