#%RAML 1.0 DataType
displayName: ProductTypeChangeNameAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeName
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#change-name"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: string
    (builtinType): string
    required: true