#%RAML 1.0 DataType
type: object
(originalType): Reference
displayName: ProductTypeReference

discriminatorValue: product-type
properties:
  typeId:
    type: ReferenceTypeId
  id:
    type: string
  obj:
    type: ProductType