#%RAML 1.0 DataType
displayName: ProductTypeUpdate
type: object
(builtinType): object
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: ProductTypeUpdateAction
    (builtinType): array
    required: true