#%RAML 1.0 DataType
displayName: ProductTypeChangeAttributeOrderAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeAttributeOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeOrder
    required: true
  attributes:
    type: array
    items:
      type: AttributeDefinition
    (builtinType): array
    required: true