#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeSetInputTipAction
discriminator: action
discriminatorValue: setInputTip
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setInputTip
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  inputTip:
    type: LocalizedString
    (builtinType): object
    required: false