#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeAddPlainEnumValueAction
discriminator: action
discriminatorValue: addPlainEnumValue
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addPlainEnumValue
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  value:
    type: AttributePlainEnumValue
    (builtinType): object
    required: true