#%RAML 1.0 DataType
displayName: ProductTypeRemoveEnumValuesAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: removeEnumValues
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#remove-enumvalues-from-attributedefinition"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeEnumValues
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  keys:
    type: array
    items:
      type: string
    (builtinType): array
    required: true