#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeLocalizedEnumValueOrderAction
discriminator: action
discriminatorValue: changeLocalizedEnumValueOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLocalizedEnumValueOrder
    required: true
  values:
    type: array
    items:
      type: AttributeLocalizedEnumValue
    (builtinType): array
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true