#%RAML 1.0 DataType
displayName: ProductTypeAddPlainEnumValueAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: addPlainEnumValue
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addPlainEnumValue
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  value:
    type: AttributePlainEnumValue
    (builtinType): object
    required: true