#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeOrderByNameAction
# discriminator: action
# discriminatorValue: changeAttributeOrderByName
properties:
  action:
    default: changeAttributeOrderByName
    required: true
    type: string
  attributeNames:
    required: true
    type: array
    items:
      type: string