#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ProductTypeReference
discriminator: typeId
discriminatorValue: product-type
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-type
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: ProductType
    (builtinType): object
    required: false