#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeSetInputTipAction

discriminatorValue: setInputTip
properties:
  action:
    required: true
    type: string
  attributeName:
    required: true
    type: string
  inputTip:
    required: false
    type: LocalizedString