#%RAML 1.0 DataType
displayName: ProductTypeRemoveAttributeDefinitionAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: removeAttributeDefinition
(package): "ProductType"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productTypes.html#remove-attributedefinition"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAttributeDefinition
    required: true
  name:
    type: string
    (builtinType): string
    required: true