#%RAML 1.0 DataType
displayName: ProductTypeRemoveAttributeDefinitionAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: removeAttributeDefinition
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAttributeDefinition
    required: true
  name:
    type: string
    (builtinType): string
    required: true