#%RAML 1.0 DataType
(builtinType): object
type: ResourceIdentifier
displayName: ProductTypeResourceIdentifier
discriminator: typeId
discriminatorValue: product-type
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-type
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false