#%RAML 1.0 DataType
displayName: ProductTypeChangeLocalizedEnumValueOrderAction
type: ProductTypeUpdateAction
(builtinType): object
discriminatorValue: changeLocalizedEnumValueOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLocalizedEnumValueOrder
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true
  values:
    type: array
    items:
      type: AttributeLocalizedEnumValue
    (builtinType): array
    required: true