#%RAML 1.0 DataType
(builtinType): object
type: ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeConstraintAction
discriminator: action
discriminatorValue: changeAttributeConstraint
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAttributeConstraint
    required: true
  newValue:
    type: AttributeConstraintEnumDraft
    (builtinType): string
    required: true
  attributeName:
    type: string
    (builtinType): string
    required: true