#%RAML 1.0 DataType
type: object
(originalType): ProductTypeUpdateAction
displayName: ProductTypeChangeAttributeNameAction

discriminatorValue: changeAttributeName
properties:
  action:
    required: true
    type: string
  newAttributeName:
    required: true
    type: string
  attributeName:
    required: true
    type: string