#%RAML 1.0 DataType
(builtinType): object
type: ChannelUpdateAction
displayName: ChannelRemoveRolesAction
discriminator: action
discriminatorValue: removeRoles
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true