#%RAML 1.0 DataType
(builtinType): object
type: ChannelUpdateAction
displayName: ChannelSetGeoLocationAction
discriminator: action
discriminatorValue: setGeoLocation
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setGeoLocation
    required: true
  geoLocation:
    type: GeoJson
    (builtinType): object
    required: false