#%RAML 1.0 DataType
type: object
(originalType): Reference
displayName: ChannelReference
# discriminator: typeId
# discriminatorValue: channel
properties:
  typeId:
    default: channel
    required: true
    type: ReferenceTypeId
  id:
    required: true
    type: string
  obj:
    required: false
    type: Channel