#%RAML 1.0 DataType
(builtinType): object
type: ChannelUpdateAction
displayName: ChannelSetRolesAction
discriminator: action
discriminatorValue: setRoles
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true