#%RAML 1.0 DataType
displayName: ChannelChangeDescriptionAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: changeDescription
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#change-description"
examples:
  postman:
    strict: true
    value: !include ../../examples/Channel/ChannelChangeDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: true