#%RAML 1.0 DataType
displayName: ChannelSetCustomTypeAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: setCustomType
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#set-custom-type"
examples:
  postman: !include ../../examples/Channel/ChannelSetCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false