#%RAML 1.0 DataType
displayName: ChannelAddRolesAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: addRoles
examples:
  postman: !include ../../examples/Channel/ChannelAddRolesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true