#%RAML 1.0 DataType
displayName: ChannelResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: channel
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#channel"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - channel
    required: false