#%RAML 1.0 DataType
displayName: ChannelSetAddressAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: setAddress
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#set-address"
examples:
  postman:
    strict: true
    value: !include ../../examples/Channel/ChannelSetAddressAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAddress
    required: true
  address:
    type: Address
    (builtinType): object
    required: false