#%RAML 1.0 DataType
displayName: ChannelSetCustomFieldAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: setCustomField
examples:
  postman: !include ../../examples/Channel/ChannelSetCustomFieldAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false