#%RAML 1.0 DataType
displayName: ChannelRemoveRolesAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: removeRoles
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#remove-roles"
examples:
  postman:
    strict: true
    value: !include ../../examples/Channel/ChannelRemoveRolesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true