#%RAML 1.0 DataType
(builtinType): object
type: ChannelUpdateAction
displayName: ChannelAddRolesAction
discriminator: action
discriminatorValue: addRoles
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true