#%RAML 1.0 DataType
displayName: ChannelRemoveRolesAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: removeRoles
examples:
  postman: !include ../../examples/Channel/ChannelRemoveRolesAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true