#%RAML 1.0 DataType
(builtinType): object
type: LoggedResource
displayName: Channel
properties:
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the channel.
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  address:
    type: Address
    (builtinType): object
    description: |-
      The address where this channel is located (e.g.
               if the channel is a physical store).
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    description: |-
      The roles of this channel.
               Each channel must have at least one role.
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    description: |-
      A human-readable description of the channel.
    required: false
  geoLocation:
    type: GeoJson
    (builtinType): object
    description: |-
      A GeoJSON geometry object encoding the geo location of the channel.
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    description: |-
      A human-readable name of the channel.
    required: false
  reviewRatingStatistics:
    type: ReviewRatingStatistics
    (builtinType): object
    description: |-
      Statistics about the review ratings taken into account for this channel.
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      Any arbitrary string key that uniquely identifies this channel within the project.
    required: true