#%RAML 1.0 DataType
displayName: ChannelSetRolesAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: setRoles
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#set-roles"
examples:
  postman: !include ../../examples/Channel/ChannelSetRolesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true