#%RAML 1.0 DataType
displayName: ChannelSetGeoLocationAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: setGeoLocation
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#set-geolocation"
examples:
  postman:
    strict: true
    value: !include ../../examples/Channel/ChannelSetGeoLocationAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setGeoLocation
    required: true
  geoLocation:
    type: GeoJson
    (builtinType): object
    required: false