#%RAML 1.0 DataType
displayName: ChannelChangeNameAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: changeName
(package): "Channel"
(docs-uri): "https://docs.commercetools.com/http-api-projects-channels.html#change-name"
examples:
  postman: !include ../../examples/Channel/ChannelChangeNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true