#%RAML 1.0 DataType
displayName: ChannelResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: channel
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - channel
    required: false