#%RAML 1.0 DataType
displayName: ChannelUpdate
type: object
(builtinType): object
(package): "Channel"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: ChannelUpdateAction
    (builtinType): array
    required: true