#%RAML 1.0 DataType
type: object
(originalType): ChannelUpdateAction
displayName: ChannelSetCustomTypeAction

discriminatorValue: setCustomType
properties:
  action:
    type: string
  fields:
    type: FieldContainer
  type:
    type: TypeResourceIdentifier