#%RAML 1.0 DataType
displayName: ChannelSetRolesAction
type: ChannelUpdateAction
(builtinType): object
discriminatorValue: setRoles
examples:
  postman: !include ../../examples/Channel/ChannelSetRolesAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRoles
    required: true
  roles:
    type: array
    items:
      type: ChannelRoleEnum
    (builtinType): array
    required: true