#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ChannelReference
discriminator: typeId
discriminatorValue: channel
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - channel
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Channel
    (builtinType): object
    required: false