#%RAML 1.0 DataType
displayName: CustomField
type: object
(builtinType): object
discriminator: type
(oneOf):
- BooleanField
- BooleanSetField
- DateField
- DateSetField
- DateTimeField
- DateTimeSetField
- EnumField
- EnumSetField
- LocalizedEnumField
- LocalizedEnumSetField
- LocalizedStringField
- LocalizedStringSetField
- MoneyField
- MoneySetField
- NumberField
- NumberSetField
- ReferenceField
- ReferenceSetField
- StringField
- StringSetField
- TimeField
- TimeSetField
description: |-
  Provides the value for a custom field of a specific type.
properties:
  type:
    type: string
    (builtinType): string
    description: |-
      The type of this field.
    required: true
