#%RAML 1.0 DataType
displayName: LocalizedEnumField
type: CustomField
(builtinType): object
discriminatorValue: LocalizedEnum
description: |-
  A field with a localized enum value.
properties:
  type:
    type: string
    (builtinType): string
    description: |-
      The type of this field.
    enum:
    - LocalizedEnum
    required: true
  value:
    type: string
    (builtinType): string
    required: true
