#%RAML 1.0 DataType
displayName: LocalizedStringField
type: CustomField
(builtinType): object
discriminatorValue: LocalizedString
description: |-
  A field with a localized string value.
properties:
  type:
    type: string
    (builtinType): string
    description: |-
      The type of this field.
    enum:
    - LocalizedString
    required: true
  value:
    type: LocalizedString
    (builtinType): object
    required: true
