#%RAML 1.0 DataType
displayName: NumberField
type: CustomField
(builtinType): object
discriminatorValue: Number
description: |-
  A field with a number value.
properties:
  type:
    type: string
    (builtinType): string
    description: |-
      The type of this field.
    enum:
    - Number
    required: true
  value:
    type: number
    (builtinType): number
    required: true
