#%RAML 1.0 DataType
displayName: TimeField
type: CustomField
(builtinType): object
discriminatorValue: Time
description: |-
  A field with a time value.
properties:
  type:
    type: string
    (builtinType): string
    description: |-
      The type of this field.
    enum:
    - Time
    required: true
  value:
    type: time-only
    (builtinType): time-only
    required: true
