#%RAML 1.0 DataType
displayName: ReviewSetRatingAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setRating
(package): "Review"
(docs-uri): "https://docs.commercetools.com/http-api-projects-reviews.html#set-rating"
examples:
  postman:
    strict: true
    value: !include ../../examples/Review/ReviewSetRatingAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRating
    required: true
  rating:
    format: int8
    type: integer
    (builtinType): integer
    required: false