#%RAML 1.0 DataType
displayName: ReviewSetCustomerAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setCustomer
(package): "Review"
(docs-uri): "https://docs.commercetools.com/http-api-projects-reviews.html#set-customer"
examples:
  postman: !include ../../examples/Review/ReviewSetCustomerAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomer
    required: true
  customer:
    type: CustomerResourceIdentifier
    (builtinType): object
    required: false