#%RAML 1.0 DataType
type: object
(originalType): ReviewUpdateAction
displayName: ReviewSetRatingAction

discriminatorValue: setRating
properties:
  action:
    required: true
    type: string
  rating:
    required: false
    format: int8
    type: number