#%RAML 1.0 DataType
displayName: ReviewSetTargetAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setTarget
(package): "Review"
(docs-uri): "https://docs.commercetools.com/http-api-projects-reviews.html#set-target"
examples:
  postman: !include ../../examples/Review/ReviewSetTargetAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTarget
    required: true
  target:
    type: ProductResourceIdentifier | ChannelResourceIdentifier
    (oneOf):
    - ProductResourceIdentifier
    - ChannelResourceIdentifier
    (builtinType): any
    required: true