#%RAML 1.0 DataType
displayName: ReviewSetCustomFieldAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setCustomField
examples:
  postman: !include ../../examples/Review/ReviewSetCustomFieldAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false