#%RAML 1.0 DataType
displayName: ReviewReference
type: Reference
(builtinType): object
discriminatorValue: review
(package): "Review"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - review
    required: true
  obj:
    type: Review
    (builtinType): object
    required: false