#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ReviewReference
discriminator: typeId
discriminatorValue: review
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - review
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Review
    (builtinType): object
    required: false