#%RAML 1.0 DataType
type: object
(originalType): ReviewUpdateAction
displayName: ReviewSetTextAction
# discriminator: action
# discriminatorValue: setText
properties:
  action:
    default: setText
    required: true
    type: string
  text:
    required: false
    type: string