#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ReviewRatingStatistics
# 
# 
properties:
  highestRating:
    required: true
    description: |-
      Highest rating of one target
    format: int16
    type: number
  averageRating:
    required: true
    description: |-
      Average rating of one target
      This number is rounded with 5 decimals.
    format: int16
    type: number
  count:
    required: true
    description: |-
      Number of ratings taken into account
    format: int16
    type: integer
  ratingsDistribution:
    required: true
    description: |-
      The full distribution of the ratings.
      The keys are the different ratings and the values are the count of reviews having this rating.
      Only the used ratings appear in this object.
    type: object
  lowestRating:
    required: true
    description: |-
      Lowest rating of one target
    format: int16
    type: number