#%RAML 1.0 DataType
(builtinType): object
type: ReviewUpdateAction
displayName: ReviewSetTitleAction
discriminator: action
discriminatorValue: setTitle
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTitle
    required: true
  title:
    type: string
    (builtinType): string
    required: false