#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ReviewUpdate


properties:
  actions:
    type: array
    items:
      type: ReviewUpdateAction
  version:
    format: int64
    type: number