#%RAML 1.0 DataType
displayName: ReviewSetKeyAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setKey
examples:
  postman: !include ../../examples/Review/ReviewSetKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false