#%RAML 1.0 DataType
displayName: ReviewTransitionStateAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: transitionState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionState
    required: true
  state:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: false