#%RAML 1.0 DataType
type: ReviewUpdateAction
displayName: ReviewSetCustomTypeAction

discriminatorValue: setCustomType
properties:
   type:
      type: TypeResourceIdentifier
   fields:
      type: FieldContainer