#%RAML 1.0 DataType
type: object
(originalType): ReviewUpdateAction
displayName: ReviewSetTargetAction

discriminatorValue: setTarget
properties:
  action:
    required: true
    type: string
  target:
    required: true
    type: ProductResourceIdentifier | ChannelResourceIdentifier