#%RAML 1.0 DataType
displayName: ReviewUpdate
type: object
(builtinType): object
(package): "Review"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: ReviewUpdateAction
    (builtinType): array
    required: true