#%RAML 1.0 DataType
displayName: ReviewSetAuthorNameAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setAuthorName
examples:
  postman: !include ../../examples/Review/ReviewSetAuthorNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAuthorName
    required: true
  authorName:
    type: string
    (builtinType): string
    required: false