#%RAML 1.0 DataType
(builtinType): object
type: ReviewUpdateAction
displayName: ReviewSetAuthorNameAction
discriminator: action
discriminatorValue: setAuthorName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAuthorName
    required: true
  authorName:
    type: string
    (builtinType): string
    required: false