#%RAML 1.0 DataType
(builtinType): object
type: ReviewUpdateAction
displayName: ReviewSetCustomerAction
discriminator: action
discriminatorValue: setCustomer
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomer
    required: true
  customer:
    type: CustomerResourceIdentifier
    (builtinType): object
    required: false