#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ReviewRatingStatistics
properties:
  highestRating:
    format: int16
    type: number
    (builtinType): number
    description: |-
      Highest rating of one target
    required: true
  averageRating:
    format: int16
    type: number
    (builtinType): number
    description: |-
      Average rating of one target
               This number is rounded with 5 decimals.
    required: true
  count:
    format: int16
    type: integer
    (builtinType): integer
    description: |-
      Number of ratings taken into account
    required: true
  ratingsDistribution:
    type: object
    (builtinType): object
    description: |-
      The full distribution of the ratings.
               The keys are the different ratings and the values are the count of reviews having this rating.
               Only the used ratings appear in this object.
    required: true
  lowestRating:
    format: int16
    type: number
    (builtinType): number
    description: |-
      Lowest rating of one target
    required: true