#%RAML 1.0 DataType
(builtinType): object
type: ReviewUpdateAction
displayName: ReviewTransitionStateAction
discriminator: action
discriminatorValue: transitionState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionState
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: false
  state:
    type: StateResourceIdentifier
    (builtinType): object
    required: true