#%RAML 1.0 DataType
displayName: ReviewSetTextAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setText
(package): "Review"
(docs-uri): "https://docs.commercetools.com/http-api-projects-reviews.html#set-text"
examples:
  postman: !include ../../examples/Review/ReviewSetTextAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setText
    required: true
  text:
    type: string
    (builtinType): string
    required: false