#%RAML 1.0 DataType
displayName: ReviewSetCustomTypeAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setCustomType
(package): "Review"
(docs-uri): "https://docs.commercetools.com/http-api-projects-reviews.html#set-custom-type"
examples:
  postman: !include ../../examples/Review/ReviewSetCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false