#%RAML 1.0 DataType
displayName: ReviewResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: review
(package): "Review"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - review
    required: false