#%RAML 1.0 DataType
displayName: ReviewSetAuthorNameAction
type: ReviewUpdateAction
(builtinType): object
discriminatorValue: setAuthorName
(package): "Review"
(docs-uri): "https://docs.commercetools.com/http-api-projects-reviews.html#set-author-name"
examples:
  postman:
    strict: true
    value: !include ../../examples/Review/ReviewSetAuthorNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAuthorName
    required: true
  authorName:
    type: string
    (builtinType): string
    required: false