# Resource
(resourceName): ByProjectKeySubscriptionsKeyByKey
(resourcePathUri): /{projectKey}/subscriptions/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
  key:
    type: string
    (builtinType): string
    required: true
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_subscriptions:{projectKey}"
  description: |-
    Retrieves the representation of a subscription by its key.
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Subscription
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_subscriptions:{projectKey}"
  description: |-
    Update Subscription by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: SubscriptionUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Subscription
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_subscriptions:{projectKey}"
  description: |-
    Delete Subscription by key
  queryParameters:
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Subscription
          (builtinType): object