# Resource
(resourceName): ByProjectKeyCustomersEmailTokenByEmailToken
(resourcePathUri): /{projectKey}/customers/email-token={emailToken}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
  emailToken:
    type: string
    (builtinType): string
    required: true
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_customers:{projectKey}"
  description: |-
    Get Customer by emailToken
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Customer
          (builtinType): object