#ByProjectKeyInStoreKeyByStoreKey
(resourcePathUri): /{projectKey}/in-store/key={storeKey}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  storeKey:
    type: string
    (builtinType): string
