#ByProjectKeyTypesByID
(resourcePathUri): /{projectKey}/types/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_types:{projectKey}"
  description: |-
    Get Type by ID
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Type
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_types:{projectKey}"
  description: |-
    Update Type by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: TypeUpdate
  responses:
    200:
      body:
        application/json:
          type: Type
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_types:{projectKey}"
  description: |-
    Delete Type by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Type