#ByProjectKeyShoppingLists
(resourcePathUri): /{projectKey}/shopping-lists

uriParameters:
  projectKey:
    type: string
get:
  description: |-
    Query ShoppingLists
  queryParameters:
    expand:
      type: string
    where:
      type: string
    sort:
      type: string
    limit:
      format: int16
      type: number
    offset:
      format: int16
      type: number
    withTotal:
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: ShoppingListPagedQueryResponse
post:
  description: |-
    Create ShoppingList
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: ShoppingListDraft
  responses:
    201:
      body:
        application/json:
          type: ShoppingList
    200:
      body: