#ByProjectKeyCustomersByID
(resourcePathUri): /{projectKey}/customers/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_customers:{projectKey}"
  description: |-
    Get Customer by ID
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Update Customer by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: CustomerUpdate
  responses:
    200:
      body:
        application/json:
          type: Customer
delete:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Delete Customer by ID
  queryParameters:
    dataErasure:
      required: false
      type: boolean
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer