# Resource
(resourceName): ByProjectKeyOrdersImport
(resourcePathUri): /{projectKey}/orders/import
displayName: import orders

uriParameters:
  projectKey:
    type: string
    (builtinType): string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Create an Order by Import
  body:
    application/json:
      type: OrderImportDraft
      (builtinType): object
  responses:
    201:
      body:
        application/json:
          type: Order
          (builtinType): object
    200:
      body: