#ByProjectKeyProductsKeyByKey
(resourcePathUri): /{projectKey}/products/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Gets the full representation of a product by Key.
  queryParameters:
    priceCurrency:
      required: false
      type: string
      (builtinType): string
    priceCountry:
      required: false
      type: string
      (builtinType): string
    priceCustomerGroup:
      required: false
      type: string
      (builtinType): string
    priceChannel:
      required: false
      type: string
      (builtinType): string
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Product
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update Product by key
  queryParameters:
    priceCurrency:
      required: false
      type: string
      (builtinType): string
    priceCountry:
      required: false
      type: string
      (builtinType): string
    priceCustomerGroup:
      required: false
      type: string
      (builtinType): string
    priceChannel:
      required: false
      type: string
      (builtinType): string
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ProductUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Product
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete Product by key
  queryParameters:
    priceCurrency:
      required: false
      type: string
      (builtinType): string
    priceCountry:
      required: false
      type: string
      (builtinType): string
    priceCustomerGroup:
      required: false
      type: string
      (builtinType): string
    priceChannel:
      required: false
      type: string
      (builtinType): string
    version:
      required: true
      format: int64
      type: number
      (builtinType): number
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Product
          (builtinType): object