# ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordTokenByPasswordToken
(resourceName): ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordTokenByPasswordToken
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/customers/password-token={passwordToken}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  storeKey:
    type: string
    (builtinType): string
  passwordToken:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_customers:{projectKey}"
      - "view_customers:{projectKey}:{storeKey}"
  description: |-
    Get Customer by passwordToken
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Customer
          (builtinType): object