# Resource
(resourceName): ByProjectKeyInStoreKeyByStoreKeyCustomersEmailToken
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/customers/email-token
displayName: Customer's Email Verification
description: |-
  To verify a customer's email, an email token can be created. This should be embedded in a link and sent to the
  customer via email. When the customer clicks on the link,
  the "verify customer's email" endpoint should be called,
  which sets customer's isVerifiedEmail field to true.

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
  storeKey:
    type: string
    (builtinType): string
    required: true
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
      - "manage_customers:{projectKey}:{storeKey}"
  description: |-
    Create a Token for verifying the Customer's Email
  body:
    application/json:
      type: CustomerCreateEmailToken
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: CustomerToken
          (builtinType): object