#ByProjectKeyOrdersOrderNumberByOrderNumber
(resourcePathUri): /{projectKey}/orders/order-number={orderNumber}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  orderNumber:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    In case the orderNumber does not match the regular expression [a-zA-Z0-9_-]+,
    it should be provided in URL-encoded format.
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Order
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update Order by orderNumber
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: OrderUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Order
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete Order by orderNumber
  queryParameters:
    dataErasure:
      required: false
      type: boolean
      (builtinType): boolean
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Order
          (builtinType): object