(resourceName): ByProjectKeyProductProjectionsKeyByKey
(resourcePathUri): /{projectKey}/product-projections/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
      - "view_published_products:{projectKey}"
  description: |-
    Gets the current or staged representation of a product found by Key.
    When used with an API client that has the view_published_products:{projectKey} scope,
    this endpoint only returns published (current) product projections.
  queryParameters:
    staged:
      required: false
      type: boolean
      (builtinType): boolean
      description: |-
        Whether to query for the current or staged projections.
    priceCurrency:
      required: false
      type: string
      (builtinType): string
    priceCountry:
      required: false
      type: string
      (builtinType): string
    priceCustomerGroup:
      required: false
      type: string
      (builtinType): string
    priceChannel:
      required: false
      type: string
      (builtinType): string
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: ProductProjection
          (builtinType): object