#ByProjectKeyDiscountCodesByID
(resourcePathUri): /{projectKey}/discount-codes/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Get DiscountCode by ID
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: DiscountCode
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update DiscountCode by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: DiscountCodeUpdate
  responses:
    200:
      body:
        application/json:
          type: DiscountCode
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete DiscountCode by ID
  queryParameters:
    dataErasure:
      required: false
      type: boolean
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: DiscountCode