#ByProjectKeyOrdersByID

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  (resourcePathUri): "{projectKey}/orders/{ID}"
  description: |-
    Get Order by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Order
post:
  (resourcePathUri): "{projectKey}/orders/{ID}"
  description: |-
    Update Order by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: OrderUpdate
  responses:
    200:
      body:
        application/json:
          type: Order
delete:
  (resourcePathUri): "{projectKey}/orders/{ID}"
  description: |-
    Delete Order by ID
  queryParameters:
    dataErasure:
      type: boolean
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Order