#ByProjectKeyMeCarts

uriParameters:
  projectKey:
    type: string
get:
  (resourcePathUri): "{projectKey}/me/carts"
  description: |-
    Query Carts
  queryParameters:
    expand:
      type: string
    where:
      type: string
    sort:
      type: string
    limit:
      format: int16
      type: number
    offset:
      format: int16
      type: number
    withTotal:
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: CartPagedQueryResponse
post:
  (resourcePathUri): "{projectKey}/me/carts"
  description: |-
    Create MyCart
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: MyCartDraft
  responses:
    201:
      body:
        application/json:
          type: MyCart
    200:
      body: