#ByProjectKeyCustomersPasswordTokenByPasswordToken

uriParameters:
  projectKey:
    type: string
  passwordToken:
    type: string
get:
  (resourcePathUri): "{projectKey}/customers/password-token={passwordToken}"
  description: |-
    Get Customer by passwordToken
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer