# Resource
(resourceName): ByProjectKeyTypesKeyByKey
(resourcePathUri): /{projectKey}/types/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_types:{projectKey}"
  description: |-
    Get Type by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Type
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_types:{projectKey}"
  description: |-
    Update Type by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: TypeUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Type
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_types:{projectKey}"
  description: |-
    Delete Type by key
  queryParameters:
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Type
          (builtinType): object