# ByProjectKeyMeOrdersByID
(resourceName): ByProjectKeyMeOrdersByID
(resourcePathUri): /{projectKey}/me/orders/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_my_orders:{projectKey}"
  description: |-
    Get MyOrder by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: MyOrder
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_my_orders:{projectKey}"
  description: |-
    Update MyOrder by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: Update
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: MyOrder
          (builtinType): object