#ByProjectKeyOrdersEditsByIDApply
(resourcePathUri): /{projectKey}/orders/edits/{ID}/apply

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_order_edits:{projectKey}"
  body:
    application/json:
      type: OrderEditApply
  responses:
    200:
      body: