#ByProjectKeyProductDiscountsMatching
(resourcePathUri): /{projectKey}/product-discounts/matching

uriParameters:
  projectKey:
    type: string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  body:
    application/json:
      type: ProductDiscountMatchQuery
  responses:
    200:
      body:
        application/json:
          type: ProductDiscount