#ByProjectKeyApiClientsByID
(resourcePathUri): /{projectKey}/api-clients/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_api_clients:{projectKey}"
      - "view_api_clients:{projectKey}"
  description: |-
    Get ApiClient by ID
  responses:
    200:
      body:
        application/json:
          type: ApiClient
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_api_clients:{projectKey}"
  description: |-
    Delete ApiClient by ID
  responses:
    200:
      body:
        application/json:
          type: ApiClient