#ByProjectKeyStates

uriParameters:
  projectKey:
    type: string
get:
  (resourcePathUri): "{projectKey}/states"
  description: |-
    Query States
  queryParameters:
    expand:
      type: string
    where:
      type: string
    sort:
      type: string
    limit:
      format: int16
      type: number
    offset:
      format: int16
      type: number
    withTotal:
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: StatePagedQueryResponse
post:
  (resourcePathUri): "{projectKey}/states"
  description: |-
    Create State
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: StateDraft
  responses:
    201:
      body:
        application/json:
          type: State
    200:
      body: