#ByProjectKeyProductTypesByID
(resourcePathUri): /{projectKey}/product-types/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get ProductType by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: ProductType
post:
  description: |-
    Update ProductType by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: ProductTypeUpdate
  responses:
    200:
      body:
        application/json:
          type: ProductType
delete:
  description: |-
    Delete ProductType by ID
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: ProductType