#ByProjectKeyMePassword

uriParameters:
  projectKey:
    type: string
post:
  (resourcePathUri): "{projectKey}/me/password"
  responses:
    200:
      body:
        application/json:
          type: MyCustomer