#ByProjectKeyStoresKeyByKey
(resourcePathUri): /{projectKey}/stores/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  description: |-
    Get Store by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Store
post:
  description: |-
    Update Store by key
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: StoreUpdate
  responses:
    200:
      body:
        application/json:
          type: Store
delete:
  description: |-
    Delete Store by key
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Store