#ByProjectKeyMePaymentKeyByKey
(resourcePathUri): /{projectKey}/me/payment/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
post:
  body:
    application/json:
      type: MyPaymentUpdate