# ByProjectKeyExtensionsByID
(resourceName): ByProjectKeyExtensionsByID
(resourcePathUri): /{projectKey}/extensions/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Retrieves the representation of an extension by its id.
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Extension
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Update Extension by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ExtensionUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Extension
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Delete Extension by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Extension
          (builtinType): object