#ByProjectKeyMePaymentByID
(resourcePathUri): /{projectKey}/me/payment/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
post:
  body:
    application/json:
      type: MyPaymentUpdate