#ByProjectKeyTaxCategoriesKeyByKey
(resourcePathUri): /{projectKey}/tax-categories/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Get TaxCategory by key
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: TaxCategory
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update TaxCategory by key
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: TaxCategoryUpdate
  responses:
    200:
      body:
        application/json:
          type: TaxCategory
delete:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete TaxCategory by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: TaxCategory