#ByProjectKeySubscriptionsKeyByKey
(resourcePathUri): /{projectKey}/subscriptions/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_subscriptions:{projectKey}"
  description: |-
    Retrieves the representation of a subscription by its key.
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Subscription
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_subscriptions:{projectKey}"
  description: |-
    Update Subscription by key
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: SubscriptionUpdate
  responses:
    200:
      body:
        application/json:
          type: Subscription
delete:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_subscriptions:{projectKey}"
  description: |-
    Delete Subscription by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Subscription