#ByProjectKeyCustomersPasswordTokenByPasswordToken
(resourcePathUri): /{projectKey}/customers/password-token={passwordToken}

uriParameters:
  projectKey:
    type: string
  passwordToken:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_customers:{projectKey}"
  description: |-
    Get Customer by passwordToken
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer