#ByProjectKeyStores
(resourcePathUri): /{projectKey}/stores

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_stores:{projectKey}"
  description: |-
    Query Stores
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: StorePagedQueryResponse
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_stores:{projectKey}"
  description: |-
    Create Store
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: StoreDraft
  responses:
    201:
      body:
        application/json:
          type: Store
    200:
      body: