#ByProjectKeyInStoreKeyByStoreKeyCustomersPassword
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/customers/password

uriParameters:
  projectKey:
    type: string
  storeKey:
    type: string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
      - "manage_customers:{projectKey}:{storeKey}"
  description: |-
    Change a customers password
  body:
    application/json:
      type: CustomerChangePassword
  responses:
    200:
      body:
        application/json:
          type: Customer