#ByProjectKeyCartsByID

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  (resourcePathUri): "{projectKey}/carts/{ID}"
  description: |-
    The cart may not contain up-to-date prices, discounts etc.
    If you want to ensure they’re up-to-date, send an Update request with the Recalculate update action instead.
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Cart
post:
  (resourcePathUri): "{projectKey}/carts/{ID}"
  description: |-
    Update Cart by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: CartUpdate
  responses:
    200:
      body:
        application/json:
          type: Cart
delete:
  (resourcePathUri): "{projectKey}/carts/{ID}"
  description: |-
    Delete Cart by ID
  queryParameters:
    dataErasure:
      type: boolean
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Cart