#ByProjectKeyCartDiscountsKeyByKey
(resourcePathUri): /{projectKey}/cart-discounts/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  description: |-
    Get CartDiscount by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: CartDiscount
post:
  description: |-
    Update CartDiscount by key
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: CartDiscountUpdate
  responses:
    200:
      body:
        application/json:
          type: CartDiscount
delete:
  description: |-
    Delete CartDiscount by key
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: CartDiscount