(resourceName): ByProjectKeyShippingMethodsByID
(resourcePathUri): /{projectKey}/shipping-methods/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Get ShippingMethod by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update ShippingMethod by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ShippingMethodUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete ShippingMethod by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
          (builtinType): object