#ByProjectKeyExtensionsKeyByKey
(resourcePathUri): /{projectKey}/extensions/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Retrieves the representation of an extension by its key.
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Extension
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Update Extension by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ExtensionUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Extension
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Delete Extension by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
      (builtinType): number
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Extension
          (builtinType): object