#ByProjectKeyMeOrders
(resourcePathUri): /{projectKey}/me/orders

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_my_orders:{projectKey}"
  description: |-
    Query Orders
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: OrderPagedQueryResponse
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_my_orders:{projectKey}"
  description: |-
    Create MyOrder
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: MyOrderFromCartDraft
  responses:
    201:
      body:
        application/json:
          type: MyOrder
    200:
      body: