#ByProjectKeyCustomersPassword

uriParameters:
  projectKey:
    type: string
post:
  (resourcePathUri): "{projectKey}/customers/password"
  description: |-
    Change a customers password
  body:
    application/json:
      type: CustomerChangePassword
  responses:
    200:
      body:
        application/json:
          type: Customer