#ByProjectKeyCartDiscountsByID
(resourcePathUri): /{projectKey}/cart-discounts/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get CartDiscount by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: CartDiscount
post:
  description: |-
    Update CartDiscount by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: CartDiscountUpdate
  responses:
    200:
      body:
        application/json:
          type: CartDiscount
delete:
  description: |-
    Delete CartDiscount by ID
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: CartDiscount