# ByProjectKeyCartsReplicate
(resourceName): ByProjectKeyCartsReplicate
(resourcePathUri): /{projectKey}/carts/replicate

uriParameters:
  projectKey:
    type: string
    (builtinType): string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  body:
    application/json:
      type: ReplicaCartDraft
      (builtinType): object
  responses:
    201:
      body:
        application/json:
          type: Cart
          (builtinType): object
    200:
      body: