#ByProjectKeyCustomersEmailConfirm
(resourcePathUri): /{projectKey}/customers/email/confirm

uriParameters:
  projectKey:
    type: string
post:
  description: |-
    Verifies customer's email using a token.
  body:
    application/json:
      type: CustomerEmailVerify
  responses:
    200:
      body: