#ByProjectKeyMePasswordReset
(resourcePathUri): /{projectKey}/me/password/reset

uriParameters:
  projectKey:
    type: string
post:
  responses:
    200:
      body:
        application/json:
          type: MyCustomer