#ByProjectKeyProductDiscountsMatching
(resourcePathUri): /{projectKey}/product-discounts/matching

uriParameters:
  projectKey:
    type: string
post:
  body:
    application/json:
      type: ProductDiscountMatchQuery
  responses:
    200:
      body:
        application/json:
          type: ProductDiscount