#ByProjectKeyCustomersPassword
(resourcePathUri): /{projectKey}/customers/password

uriParameters:
  projectKey:
    type: string
post:
  description: |-
    Change a customers password
  body:
    application/json:
      type: CustomerChangePassword
  responses:
    200:
      body:
        application/json:
          type: Customer