#ByProjectKeyTaxCategoriesKeyByKey
(resourcePathUri): /{projectKey}/tax-categories/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  description: |-
    Get TaxCategory by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: TaxCategory
post:
  description: |-
    Update TaxCategory by key
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: TaxCategoryUpdate
  responses:
    200:
      body:
        application/json:
          type: TaxCategory
delete:
  description: |-
    Delete TaxCategory by key
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: TaxCategory