# ByProjectKeyInStoreKeyByStoreKeyLogin
(resourceName): ByProjectKeyInStoreKeyByStoreKeyLogin
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/login
displayName: Authenticate Customer (Sign In)
description: |-
  Retrieves the authenticated customer.

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  storeKey:
    type: string
    (builtinType): string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
      - "manage_customers:{projectKey}:{storeKey}"
  description: |-
    Authenticate Customer (Sign In)
  body:
    application/json:
      type: CustomerSignin
      (builtinType): object
  responses:
    201:
      body:
        application/json:
          type: CustomerSignInResult
          (builtinType): object
    200:
      body: