#ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordReset
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/customers/password/reset

uriParameters:
  projectKey:
    type: string
  storeKey:
    type: string
post:
  description: |-
    Set a new password using a token.
  body:
    application/json:
      type: CustomerResetPassword
  responses:
    200:
      body:
        application/json:
          type: Customer