#ByProjectKeyCategoriesKeyByKey
(resourcePathUri): /{projectKey}/categories/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Get Category by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Category
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update Category by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: CategoryUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Category
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete Category by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
      (builtinType): number
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Category
          (builtinType): object