#ByProjectKeyReviewsByID
(resourcePathUri): /{projectKey}/reviews/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Get Review by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Review
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update Review by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ReviewUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Review
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete Review by ID
  queryParameters:
    dataErasure:
      required: false
      type: boolean
      (builtinType): boolean
    version:
      required: true
      format: int64
      type: number
      (builtinType): number
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Review
          (builtinType): object