#ByProjectKeyTypesByID
(resourcePathUri): /{projectKey}/types/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get Type by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Type
post:
  description: |-
    Update Type by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: TypeUpdate
  responses:
    200:
      body:
        application/json:
          type: Type
delete:
  description: |-
    Delete Type by ID
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Type