#ByProjectKeyCustomersEmailConfirm
(resourcePathUri): /{projectKey}/customers/email/confirm

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Verifies customer's email using a token.
  body:
    application/json:
      type: CustomerEmailVerify
      (builtinType): object
  responses:
    200:
      body: