#ByProjectKeyInStoreKeyByStoreKeyMeOrdersByID
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/me/orders/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
  storeKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_my_orders:{projectKey}"
      - "manage_my_orders:{projectKey}:{storeKey}"
  description: |-
    Get Order by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Order
          (builtinType): object