# Resource
(resourceName): ByProjectKeyShoppingListsByID
(resourcePathUri): /{projectKey}/shopping-lists/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
  ID:
    type: string
    (builtinType): string
    required: true
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_shopping_lists:{projectKey}"
  description: |-
    Gets a shopping list by ID.
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: ShoppingList
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_shopping_lists:{projectKey}"
  description: |-
    Update ShoppingList by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ShoppingListUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: ShoppingList
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_shopping_lists:{projectKey}"
  description: |-
    Delete ShoppingList by ID
  queryParameters:
    dataErasure:
      required: false
      type: boolean
      (builtinType): boolean
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: ShoppingList
          (builtinType): object