#ByProjectKeyOrdersEdits
(resourcePathUri): /{projectKey}/orders/edits

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_order_edits:{projectKey}"
  description: |-
    Query Edits
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: OrderEditPagedQueryResponse
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_order_edits:{projectKey}"
  description: |-
    Create OrderEdit
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: OrderEditDraft
  responses:
    201:
      body:
        application/json:
          type: OrderEdit
    200:
      body: