#ByProjectKeyCustomersPasswordToken
(resourcePathUri): /{projectKey}/customers/password-token

uriParameters:
  projectKey:
    type: string
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    The token value is used to reset the password of the customer with the given email. The token is
    valid only for 10 minutes.
  body:
    application/json:
      type: CustomerCreatePasswordResetToken
  responses:
    201:
      body:
        application/json:
          type: CustomerToken
    200:
      body: