(resourceName): ByProjectKeyInStoreKeyByStoreKeyMeActiveCart
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/me/active-cart

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  storeKey:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_my_orders:{projectKey}"
      - "manage_my_orders:{projectKey}:{storeKey}"
  responses:
    200:
      body:
        application/json:
          type: Cart
          (builtinType): object