#ByProjectKeyCustomersKeyByKey
(resourcePathUri): /{projectKey}/customers/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  description: |-
    Get Customer by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer
post:
  description: |-
    Update Customer by key
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: CustomerUpdate
  responses:
    200:
      body:
        application/json:
          type: Customer
delete:
  description: |-
    Delete Customer by key
  queryParameters:
    dataErasure:
      type: boolean
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer