#ByProjectKeyInStoreKeyByStoreKeyMeCartsByID

uriParameters:
  projectKey:
    type: string
  storeKey:
    type: string
  ID:
    type: string
get:
  (resourcePathUri): "{projectKey}/in-store/key={storeKey}/me/carts/{ID}"
  description: |-
    Get Cart by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Cart
post:
  (resourcePathUri): "{projectKey}/in-store/key={storeKey}/me/carts/{ID}"
  description: |-
    Update Cart by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: Update
  responses:
    200:
      body:
        application/json:
          type: Cart
delete:
  (resourcePathUri): "{projectKey}/in-store/key={storeKey}/me/carts/{ID}"
  description: |-
    Delete Cart by ID
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Cart