#ByProjectKeyMessagesByID
(resourcePathUri): /{projectKey}/messages/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get Message by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          discriminator: type
          type: Message