#ByProjectKeyMePaymentByID
(resourcePathUri): /{projectKey}/me/payment/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
  ID:
    type: string
    (builtinType): string
post:
  body:
    application/json:
      type: MyPaymentUpdate
      (builtinType): object