#ByProjectKeyMe
(resourcePathUri): /{projectKey}/me

uriParameters:
  projectKey:
    type: string
get:
  queryParameters:
    where:
      type: string
    sort:
      type: string
    limit:
      format: int16
      type: number
    offset:
      format: int16
      type: number
    withTotal:
      type: boolean
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: MyCustomer
post:
  description: |-
    Create a customer
  body:
    application/json:
      type: Update
  responses:
    200:
      body:
        application/json:
          type: MyCustomer
delete:
  description: |-
    Delete a Customer
  queryParameters:
    version:
      format: int64
      type: number
  responses:
    200:
      body:
        application/json:
          type: MyCustomer