#ByProjectKeyPaymentsKeyByKey
(resourcePathUri): /{projectKey}/payments/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_payments:{projectKey}"
  description: |-
    Get Payment by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Payment
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_payments:{projectKey}"
  description: |-
    Update Payment by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: PaymentUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Payment
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_payments:{projectKey}"
  description: |-
    Delete Payment by key
  queryParameters:
    dataErasure:
      required: false
      type: boolean
      (builtinType): boolean
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Payment
          (builtinType): object