# ByProjectKeyMessagesByID
(resourceName): ByProjectKeyMessagesByID
(resourcePathUri): /{projectKey}/messages/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Get Message by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          discriminator: "type"
          type: Message
          (builtinType): object