#ByProjectKeyStoresByID
(resourcePathUri): /{projectKey}/stores/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_stores:{projectKey}"
  description: |-
    Get Store by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Store
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_stores:{projectKey}"
  description: |-
    Update Store by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: StoreUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Store
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_stores:{projectKey}"
  description: |-
    Delete Store by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: number
      (builtinType): number
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Store
          (builtinType): object