#ByProjectKeyMeSignup
(resourcePathUri): /{projectKey}/me/signup

uriParameters:
  projectKey:
    type: string
post:
  body:
    application/json:
      type: MyCustomerDraft
  responses:
    201:
      body:
        application/json:
          type: CustomerSignInResult
    200:
      body: