# Resource
(resourceName): ByProjectKeyGraphql
(resourcePathUri): /{projectKey}/graphql
displayName: graphql
description: |-
  The commercetools™ platform provides a GraphQL API

uriParameters:
  projectKey:
    type: string
    (builtinType): string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Execute a GraphQL query
  body:
    application/graphql:
      type: GraphQLRequest
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: GraphQLResponse
          (builtinType): object