#ByProjectKeyChannels
(resourcePathUri): /{projectKey}/channels

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Query Channels
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: ChannelPagedQueryResponse
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Create Channel
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ChannelDraft
  responses:
    201:
      body:
        application/json:
          type: Channel
    200:
      body: