#ByProjectKeyMePayments
(resourcePathUri): /{projectKey}/me/payments

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_my_payments:{projectKey}"
  description: |-
    Query Payments
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: MyPaymentPagedQueryResponse
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_my_payments:{projectKey}"
  description: |-
    Create MyPayment
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: MyPaymentDraft
  responses:
    201:
      body:
        application/json:
          type: MyPayment
    200:
      body: