#ByProjectKeyProductsByID
(resourcePathUri): /{projectKey}/products/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Gets the full representation of a product by ID.
  queryParameters:
    priceCurrency:
      required: false
      type: string
    priceCountry:
      required: false
      type: string
    priceCustomerGroup:
      required: false
      type: string
    priceChannel:
      required: false
      type: string
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Product
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update Product by ID
  queryParameters:
    priceCurrency:
      required: false
      type: string
    priceCountry:
      required: false
      type: string
    priceCustomerGroup:
      required: false
      type: string
    priceChannel:
      required: false
      type: string
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ProductUpdate
  responses:
    200:
      body:
        application/json:
          type: Product
delete:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete Product by ID
  queryParameters:
    priceCurrency:
      required: false
      type: string
    priceCountry:
      required: false
      type: string
    priceCustomerGroup:
      required: false
      type: string
    priceChannel:
      required: false
      type: string
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Product