#ByProjectKeyShippingMethodsByID
(resourcePathUri): /{projectKey}/shipping-methods/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Get ShippingMethod by ID
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update ShippingMethod by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ShippingMethodUpdate
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete ShippingMethod by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod