#ByProjectKeyInStoreKeyByStoreKeyLogin
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/login

uriParameters:
  projectKey:
    type: string
  storeKey:
    type: string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
      - "manage_customers:{projectKey}:{storeKey}"
  description: |-
    Authenticate Customer (Sign In)
  body:
    application/json:
      type: CustomerSignin
  responses:
    201:
      body:
        application/json:
          type: CustomerSignInResult
    200:
      body: