#ByProjectKeyProductDiscountsKeyByKey
(resourcePathUri): /{projectKey}/product-discounts/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Get ProductDiscount by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: ProductDiscount
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update ProductDiscount by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ProductDiscountUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: ProductDiscount
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete ProductDiscount by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
      (builtinType): number
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: ProductDiscount
          (builtinType): object