#ByProjectKeyStoresByID
(resourcePathUri): /{projectKey}/stores/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_stores:{projectKey}"
  description: |-
    Get Store by ID
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Store
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_stores:{projectKey}"
  description: |-
    Update Store by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: StoreUpdate
  responses:
    200:
      body:
        application/json:
          type: Store
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_stores:{projectKey}"
  description: |-
    Delete Store by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Store