# Resource
(resourceName): ByProjectKeyInStoreKeyByStoreKeyCustomersPasswordReset
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/customers/password/reset
displayName: Reset Customer's Password

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
  storeKey:
    type: string
    (builtinType): string
    required: true
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
      - "manage_customers:{projectKey}:{storeKey}"
  description: |-
    Set a new password using a token.
  body:
    application/json:
      type: CustomerResetPassword
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Customer
          (builtinType): object