#ByProjectKeyInStoreKeyByStoreKeyCustomersPassword
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/customers/password

uriParameters:
  projectKey:
    type: string
  storeKey:
    type: string
post:
  description: |-
    Change a customers password
  body:
    application/json:
      type: CustomerChangePassword
  responses:
    200:
      body:
        application/json:
          type: Customer