#ByProjectKeyStoresByID
(resourcePathUri): /{projectKey}/stores/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get Store by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Store
post:
  description: |-
    Update Store by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: StoreUpdate
  responses:
    200:
      body:
        application/json:
          type: Store
delete:
  description: |-
    Delete Store by ID
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Store