#ByProjectKeyShoppingListsKeyByKey

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  (resourcePathUri): "{projectKey}/shopping-lists/key={key}"
  description: |-
    Gets a shopping list by Key.
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShoppingList
post:
  (resourcePathUri): "{projectKey}/shopping-lists/key={key}"
  description: |-
    Update a shopping list found by its Key.
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: ShoppingListUpdate
  responses:
    200:
      body:
        application/json:
          type: ShoppingList
delete:
  (resourcePathUri): "{projectKey}/shopping-lists/key={key}"
  description: |-
    Delete ShoppingList by key
  queryParameters:
    dataErasure:
      type: boolean
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShoppingList