#ByProjectKeyGraphql
(resourcePathUri): /{projectKey}/graphql

uriParameters:
  projectKey:
    type: string
post:
  description: |-
    Execute a GraphQL query
  body:
    application/graphql:
      type: any
  responses:
    200:
      body:
        application/json:
          type: any