# Resource
(resourceName): ByProjectKeyStatesByID
(resourcePathUri): /{projectKey}/states/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
  ID:
    type: string
    (builtinType): string
    required: true
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Get State by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: State
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update State by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: StateUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: State
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete State by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: State
          (builtinType): object