#ByProjectKeyMeLogin
(resourcePathUri): /{projectKey}/me/login

uriParameters:
  projectKey:
    type: string
post:
  responses:
    200:
      body:
        application/json:
          type: CustomerSignInResult