#ByProjectKeyPayments
(resourcePathUri): /{projectKey}/payments

uriParameters:
  projectKey:
    type: string
get:
  description: |-
    Query Payments
  queryParameters:
    expand:
      type: string
    where:
      type: string
    sort:
      type: string
    limit:
      format: int16
      type: number
    offset:
      format: int16
      type: number
    withTotal:
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: PaymentPagedQueryResponse
post:
  description: |-
    To create a payment object a payment draft object has to be given with the request.
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: PaymentDraft
  responses:
    201:
      body:
        application/json:
          type: Payment
    200:
      body: