#ByProjectKeyProductProjectionsKeyByKey
(resourcePathUri): /{projectKey}/product-projections/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
      - "view_published_products:{projectKey}"
  description: |-
    Gets the current or staged representation of a product found by Key.
    When used with an API client that has the view_published_products:{projectKey} scope,
    this endpoint only returns published (current) product projections.
  queryParameters:
    staged:
      required: false
      type: boolean
    priceCurrency:
      required: false
      type: string
    priceCountry:
      required: false
      type: string
    priceCustomerGroup:
      required: false
      type: string
    priceChannel:
      required: false
      type: string
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: ProductProjection