# ByProjectKeyInStoreKeyByStoreKeyCustomersEmailConfirm
(resourceName): ByProjectKeyInStoreKeyByStoreKeyCustomersEmailConfirm
(resourcePathUri): /{projectKey}/in-store/key={storeKey}/customers/email/confirm
displayName: Verify Customer's Email

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  storeKey:
    type: string
    (builtinType): string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
      - "manage_customers:{projectKey}:{storeKey}"
  description: |-
    Verifies customer's email using a token.
  body:
    application/json:
      type: CustomerEmailVerify
      (builtinType): object
  responses:
    200:
      description: |-
        The email was verified.
      body: