#ByProjectKeyTypes
(resourcePathUri): /{projectKey}/types

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_types:{projectKey}"
  description: |-
    Query Types
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: TypePagedQueryResponse
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_types:{projectKey}"
  description: |-
    Create Type
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: TypeDraft
  responses:
    201:
      body:
        application/json:
          type: Type
    200:
      body: