#ByProjectKeyCustomersEmailToken
(resourcePathUri): /{projectKey}/customers/email-token

uriParameters:
  projectKey:
    type: string
post:
  description: |-
    Create a Token for verifying the Customer's Email
  body:
    application/json:
      type: CustomerCreateEmailToken
  responses:
    200:
      body:
        application/json:
          type: CustomerToken