# Resource
(resourceName): ByProjectKeyMeSignup
(resourcePathUri): /{projectKey}/me/signup

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    required: true
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_my_profile:{projectKey}"
  body:
    application/json:
      type: MyCustomerDraft
      (builtinType): object
  responses:
    201:
      body:
        application/json:
          type: CustomerSignInResult
          (builtinType): object
    200:
      body: