#ByProjectKeyStores

uriParameters:
  projectKey:
    type: string
get:
  (resourcePathUri): "{projectKey}/stores"
  description: |-
    Query Stores
  queryParameters:
    expand:
      type: string
    where:
      type: string
    sort:
      type: string
    limit:
      format: int16
      type: number
    offset:
      format: int16
      type: number
    withTotal:
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: StorePagedQueryResponse
post:
  (resourcePathUri): "{projectKey}/stores"
  description: |-
    Create Store
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: StoreDraft
  responses:
    201:
      body:
        application/json:
          type: Store
    200:
      body: