#ByProjectKeyZonesKeyByKey
(resourcePathUri): /{projectKey}/zones/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Get Zone by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Zone
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update Zone by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: ZoneUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Zone
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete Zone by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
      (builtinType): number
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Zone
          (builtinType): object