#ByProjectKeyCategories
(resourcePathUri): /{projectKey}/categories

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Query Categories
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: CategoryPagedQueryResponse
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Creating a category produces the CategoryCreated message.
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: CategoryDraft
  responses:
    201:
      body:
        application/json:
          type: Category
    200:
      body: