#ByProjectKeyShoppingLists
(resourcePathUri): /{projectKey}/shopping-lists

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_shopping_lists:{projectKey}"
  description: |-
    Query ShoppingLists
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: ShoppingListPagedQueryResponse
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_shopping_lists:{projectKey}"
  description: |-
    Create ShoppingList
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ShoppingListDraft
  responses:
    201:
      body:
        application/json:
          type: ShoppingList
    200:
      body: