# ByProjectKeyMeShoppingListsKeyByKey
(resourceName): ByProjectKeyMeShoppingListsKeyByKey
(resourcePathUri): /{projectKey}/me/shopping-lists/key={key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  key:
    type: string
    (builtinType): string
post:
  body:
    application/json:
      type: MyShoppingListUpdate
      (builtinType): object