#ByProjectKeyShippingMethodsKeyByKey
(resourcePathUri): /{projectKey}/shipping-methods/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  description: |-
    Get ShippingMethod by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
post:
  description: |-
    Update ShippingMethod by key
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: ShippingMethodUpdate
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
delete:
  description: |-
    Delete ShippingMethod by key
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod