#ByProjectKeyChannels
(resourcePathUri): /{projectKey}/channels

uriParameters:
  projectKey:
    type: string
get:
  description: |-
    Query Channels
  queryParameters:
    expand:
      type: string
    where:
      type: string
    sort:
      type: string
    limit:
      format: int16
      type: number
    offset:
      format: int16
      type: number
    withTotal:
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: ChannelPagedQueryResponse
post:
  description: |-
    Create Channel
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: ChannelDraft
  responses:
    201:
      body:
        application/json:
          type: Channel
    200:
      body: