#ByProjectKeyPaymentsByID
(resourcePathUri): /{projectKey}/payments/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get Payment by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Payment
post:
  description: |-
    Update Payment by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: PaymentUpdate
  responses:
    200:
      body:
        application/json:
          type: Payment
delete:
  description: |-
    Delete Payment by ID
  queryParameters:
    dataErasure:
      type: boolean
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Payment