#ByProjectKeyZones
(resourcePathUri): /{projectKey}/zones

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Query Zones
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: ZonePagedQueryResponse
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Create Zone
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ZoneDraft
  responses:
    201:
      body:
        application/json:
          type: Zone
    200:
      body: