#ByProjectKeyCustomerGroupsKeyByKey
(resourcePathUri): /{projectKey}/customer-groups/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_customers:{projectKey}"
  description: |-
    Gets a customer group by Key.
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: CustomerGroup
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Updates a customer group by Key.
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: CustomerGroupUpdate
  responses:
    200:
      body:
        application/json:
          type: CustomerGroup
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Delete CustomerGroup by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: CustomerGroup