#ByProjectKeyCartsReplicate
(resourcePathUri): /{projectKey}/carts/replicate

uriParameters:
  projectKey:
    type: string
post:
  body:
    application/json:
      type: ReplicaCartDraft
  responses:
    201:
      body:
        application/json:
          type: Cart
    200:
      body: