#ByProjectKeyExtensionsByID
(resourcePathUri): /{projectKey}/extensions/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Retrieves the representation of an extension by its id.
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Extension
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Update Extension by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ExtensionUpdate
  responses:
    200:
      body:
        application/json:
          type: Extension
delete:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_extensions:{projectKey}"
  description: |-
    Delete Extension by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Extension