#ByProjectKeyProductTypesKeyByKey
(resourcePathUri): /{projectKey}/product-types/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Get ProductType by key
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: ProductType
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update ProductType by key
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ProductTypeUpdate
  responses:
    200:
      body:
        application/json:
          type: ProductType
delete:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete ProductType by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: ProductType