#ByProjectKeyMeActiveCart
(resourcePathUri): /{projectKey}/me/active-cart

uriParameters:
  projectKey:
    type: string
get:
  responses:
    200:
      body:
        application/json:
          type: MyCart