#ByProjectKeyTypesKeyByKey
(resourcePathUri): /{projectKey}/types/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  description: |-
    Get Type by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Type
post:
  description: |-
    Update Type by key
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: TypeUpdate
  responses:
    200:
      body:
        application/json:
          type: Type
delete:
  description: |-
    Delete Type by key
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Type