# ByProjectKeyCartsByID
(resourceName): ByProjectKeyCartsByID
(resourcePathUri): /{projectKey}/carts/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    The cart may not contain up-to-date prices, discounts etc.
    If you want to ensure they're up-to-date, send an Update request with the Recalculate update action instead.
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Cart
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update Cart by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: CartUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Cart
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete Cart by ID
  queryParameters:
    dataErasure:
      required: false
      type: boolean
      (builtinType): boolean
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: Cart
          (builtinType): object