#ByProjectKeyCustomObjectsByContainerByKey
(resourcePathUri): /{projectKey}/custom-objects/{container}/{key}

uriParameters:
  projectKey:
    type: string
  container:
    type: string
  key:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
      - "view_orders:{projectKey}"
      - "view_customers:{projectKey}"
  description: |-
    Get CustomObject by key
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: CustomObject
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
      - "manage_orders:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Delete CustomObject by key
  queryParameters:
    version:
      required: false
      format: int64
      type: number
    dataErasure:
      required: false
      type: boolean
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: CustomObject