#ByProjectKeyMeShoppingListsByID
(resourcePathUri): /{projectKey}/me/shopping-lists/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_my_shopping_lists:{projectKey}"
  description: |-
    Get MyShoppingList by ID
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: MyShoppingList
post:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_my_shopping_lists:{projectKey}"
  description: |-
    Update MyShoppingList by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: MyShoppingListUpdate
  responses:
    200:
      body:
        application/json:
          type: MyShoppingList
delete:
  securedBy:
    oauth_2_0:
      scopes:
      - "manage_my_shopping_lists:{projectKey}"
  description: |-
    Delete MyShoppingList by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: MyShoppingList