#ByProjectKeyCustomersByID
(resourcePathUri): /{projectKey}/customers/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get Customer by ID
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer
post:
  description: |-
    Update Customer by ID
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: CustomerUpdate
  responses:
    200:
      body:
        application/json:
          type: Customer
delete:
  description: |-
    Delete Customer by ID
  queryParameters:
    dataErasure:
      type: boolean
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Customer