#ByProjectKeyZonesKeyByKey
(resourcePathUri): /{projectKey}/zones/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  description: |-
    Get Zone by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Zone
post:
  description: |-
    Update Zone by key
  queryParameters:
    expand:
      type: string
  body:
    application/json:
      type: ZoneUpdate
  responses:
    200:
      body:
        application/json:
          type: Zone
delete:
  description: |-
    Delete Zone by key
  queryParameters:
    version:
      format: int64
      type: number
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: Zone