#ByProjectKeyOrdersImport
(resourcePathUri): /{projectKey}/orders/import

uriParameters:
  projectKey:
    type: string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Create an Order by Import
  body:
    application/json:
      type: OrderImportDraft
  responses:
    201:
      body:
        application/json:
          type: Order
    200:
      body: