#ByProjectKeyOrdersEditsByIDApply
(resourcePathUri): /{projectKey}/orders/edits/{ID}/apply

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
post:
  body:
    application/json:
      type: OrderEditApply
  responses:
    200:
      body: