#ByProjectKey
(resourcePathUri): /{projectKey}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
    description: |-
      Test
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
  description: |-
    The Endpoint is responding a limited set of information about settings and configuration of the project.
  responses:
    200:
      body:
        application/json:
          type: Project
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
  description: |-
    Update project
  body:
    application/json:
      type: ProjectUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: Project
          (builtinType): object