#ByProjectKeyOrdersEditsByID
(resourcePathUri): /{projectKey}/orders/edits/{ID}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  ID:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_order_edits:{projectKey}"
  description: |-
    Get OrderEdit by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: OrderEdit
          (builtinType): object
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_order_edits:{projectKey}"
  description: |-
    Update OrderEdit by ID
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  body:
    application/json:
      type: OrderEditUpdate
      (builtinType): object
  responses:
    200:
      body:
        application/json:
          type: OrderEdit
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_order_edits:{projectKey}"
  description: |-
    Delete OrderEdit by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: OrderEdit
          (builtinType): object