(resourceName): ByProjectKeyCustomObjectsByContainerByKey
(resourcePathUri): /{projectKey}/custom-objects/{container}/{key}

uriParameters:
  projectKey:
    type: string
    (builtinType): string
  container:
    type: string
    (builtinType): string
  key:
    type: string
    (builtinType): string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
      - "view_orders:{projectKey}"
      - "view_customers:{projectKey}"
  description: |-
    Get CustomObject by key
  queryParameters:
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: CustomObject
          (builtinType): object
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
      - "manage_orders:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Delete CustomObject by key
  queryParameters:
    version:
      required: false
      format: int64
      type: integer
      (builtinType): integer
      description: |-
        Last seen version of the resource
    dataErasure:
      required: false
      type: boolean
      (builtinType): boolean
    expand:
      required: false
      type: string
      (builtinType): string
  responses:
    200:
      body:
        application/json:
          type: CustomObject
          (builtinType): object