#ByProjectKeyApiClientsByID
(resourcePathUri): /{projectKey}/api-clients/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  description: |-
    Get ApiClient by ID
  responses:
    200:
      body:
        application/json:
          type: ApiClient
delete:
  description: |-
    Delete ApiClient by ID
  responses:
    200:
      body:
        application/json:
          type: ApiClient