#ByProjectKeyShippingMethodsKeyByKey
(resourcePathUri): /{projectKey}/shipping-methods/key={key}

uriParameters:
  projectKey:
    type: string
  key:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_orders:{projectKey}"
  description: |-
    Get ShippingMethod by key
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Update ShippingMethod by key
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: ShippingMethodUpdate
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_orders:{projectKey}"
  description: |-
    Delete ShippingMethod by key
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: ShippingMethod