#ByProjectKeyCustomObjectsByContainerByKey
(resourcePathUri): /{projectKey}/custom-objects/{container}/{key}

uriParameters:
  projectKey:
    type: string
  container:
    type: string
  key:
    type: string
get:
  description: |-
    Get CustomObject by key
  queryParameters:
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: CustomObject
delete:
  description: |-
    Delete CustomObject by key
  queryParameters:
    version:
      format: int64
      type: number
    dataErasure:
      type: boolean
    expand:
      type: string
  responses:
    200:
      body:
        application/json:
          type: CustomObject