#ByProjectKeyCategoriesByID
(resourcePathUri): /{projectKey}/categories/{ID}

uriParameters:
  projectKey:
    type: string
  ID:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_products:{projectKey}"
  description: |-
    Get Category by ID
  queryParameters:
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Category
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Update Category by ID
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: CategoryUpdate
  responses:
    200:
      body:
        application/json:
          type: Category
delete:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_products:{projectKey}"
  description: |-
    Delete Category by ID
  queryParameters:
    version:
      required: true
      format: int64
      type: number
    expand:
      required: false
      type: string
  responses:
    200:
      body:
        application/json:
          type: Category