(resourceName): ByProjectKeyMeLogin
(resourcePathUri): /{projectKey}/me/login

uriParameters:
  projectKey:
    type: string
    (builtinType): string
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_my_profile:{projectKey}"
  responses:
    200:
      body:
        application/json:
          type: CustomerSignInResult
          (builtinType): object