#ByProjectKeyCustomers
(resourcePathUri): /{projectKey}/customers

uriParameters:
  projectKey:
    type: string
get:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "view_customers:{projectKey}"
  description: |-
    Query Customers
  queryParameters:
    expand:
      required: false
      type: string
    where:
      required: false
      type: string
    sort:
      required: false
      type: string
    limit:
      required: false
      format: int16
      type: number
    offset:
      required: false
      format: int16
      type: number
    withTotal:
      required: false
      type: boolean
  responses:
    200:
      body:
        application/json:
          type: CustomerPagedQueryResponse
post:
  securedBy:
  - oauth_2_0:
      scopes:
      - "manage_project:{projectKey}"
      - "manage_customers:{projectKey}"
  description: |-
    Creates a customer. If an anonymous cart is passed in,
    then the cart is assigned to the created customer and the version number of the Cart will increase.
    If the ID of an anonymous session is given, all carts and orders will be assigned to the created customer.
  queryParameters:
    expand:
      required: false
      type: string
  body:
    application/json:
      type: CustomerDraft
  responses:
    201:
      body:
        application/json:
          type: CustomerSignInResult
    200:
      body: