#%RAML 1.0 DataType
displayName: CustomerGroupResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: customer-group
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - customer-group
    required: false