#%RAML 1.0 DataType
type: object
(originalType): Reference
displayName: CustomerGroupReference
# discriminator: typeId
# discriminatorValue: customer-group
properties:
  typeId:
    default: customer-group
    required: true
    type: ReferenceTypeId
  id:
    required: true
    type: string
  obj:
    required: false
    type: CustomerGroup