#%RAML 1.0 DataType
displayName: CustomerGroupChangeNameAction
type: CustomerGroupUpdateAction
(builtinType): object
discriminatorValue: changeName
examples:
  postman: !include ../../examples/CustomerGroup/CustomerGroupChangeNameAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: string
    (builtinType): string
    required: true