#%RAML 1.0 DataType
displayName: CustomerGroup
type: LoggedResource
(builtinType): object
(package): "CustomerGroup"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customerGroups.html#customergroup"
(updateType): "CustomerGroupUpdate"
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the customer group.
    (identifier): true
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    description: |-
      The current version of the customer group.
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for the customer group.
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  custom:
    type: CustomFields
    (builtinType): object
    required: false