#%RAML 1.0 DataType
displayName: CustomerGroupDraft
type: object
(builtinType): object
(package): "CustomerGroup"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customerGroups.html#create-a-customergroup"
properties:
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for the customer group.
    required: false
  groupName:
    type: string
    (builtinType): string
    required: true
  custom:
    type: CustomFields
    (builtinType): object
    required: false