#%RAML 1.0 DataType
displayName: CustomerGroupChangeNameAction
type: CustomerGroupUpdateAction
(builtinType): object
discriminatorValue: changeName
(package): "CustomerGroup"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customerGroups.html#change-name"
examples:
  postman:
    strict: true
    value: !include ../../examples/CustomerGroup/CustomerGroupChangeNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: string
    (builtinType): string
    required: true