#%RAML 1.0 DataType
type: object
displayName: CustomerGroupDraft


properties:
   key:
      description: |-
        User-specific unique identifier for the customer group.
      type: string
   groupName:
      type: string
   custom:
      type: CustomFields