#%RAML 1.0 DataType
displayName: CustomerGroupReference
type: Reference
(builtinType): object
discriminatorValue: customer-group
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - customer-group
    required: true
  obj:
    type: CustomerGroup
    (builtinType): object
    required: false