#%RAML 1.0 DataType
displayName: CustomerGroupSetCustomTypeAction
type: CustomerGroupUpdateAction
(builtinType): object
discriminatorValue: setCustomType
(package): "CustomerGroup"
(docs-uri): "https://docs.commercetools.com/http-api-projects-customerGroups.html#set-custom-type"
examples:
  postman:
    strict: true
    value: !include ../../examples/CustomerGroup/CustomerGroupSetCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomType
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    description: |-
      If absent, the custom type and any existing CustomFields are removed.
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    description: |-
      A valid JSON object, based on the FieldDefinitions of the Type.
      Sets the custom fields to this value.
    required: false