#%RAML 1.0 DataType
type: object
(originalType): CustomerGroupUpdateAction
displayName: CustomerGroupChangeNameAction
# discriminator: action
# discriminatorValue: changeName
properties:
  action:
    default: changeName
    required: true
    type: string
  name:
    required: true
    type: string