#%RAML 1.0 DataType
(builtinType): object
type: ResourceIdentifier
displayName: CustomerGroupResourceIdentifier
discriminator: typeId
discriminatorValue: customer-group
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - customer-group
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false