#%RAML 1.0 DataType
displayName: CustomerGroup
type: LoggedResource
(builtinType): object
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the customer group.
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The current version of the customer group.
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for the customer group.
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  custom:
    type: CustomFields
    (builtinType): object
    required: false