#%RAML 1.0 DataType
displayName: CustomerGroupUpdate
type: object
(builtinType): object
(package): "CustomerGroup"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: CustomerGroupUpdateAction
    (builtinType): array
    required: true