#%RAML 1.0 DataType
type: OrderEditUpdateAction
displayName: OrderEditSetStagedActionsAction

discriminatorValue: setStagedActions
properties:
   stagedActions:
      type: array
      items:
        type: StagedOrderUpdateAction