#%RAML 1.0 DataType
displayName: OrderEditSetCustomFieldAction
type: OrderEditUpdateAction
(builtinType): object
discriminatorValue: setCustomField
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#setcustomfield"
examples:
  postman: !include ../../examples/OrderEdit/OrderEditSetCustomFieldAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false