#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: OrderEditReference
discriminator: typeId
discriminatorValue: order-edit
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - order-edit
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: OrderEdit
    (builtinType): object
    required: false