#%RAML 1.0 DataType
(builtinType): object
type: OrderEditUpdateAction
displayName: OrderEditAddStagedActionAction
discriminator: action
discriminatorValue: addStagedAction
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addStagedAction
    required: true
  stagedAction:
    type: StagedOrderUpdateAction
    (builtinType): object
    required: true