#%RAML 1.0 DataType
displayName: OrderEditUpdate
type: object
(builtinType): object
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: OrderEditUpdateAction
    (builtinType): array
    required: true
  dryRun:
    type: boolean
    (builtinType): boolean
    required: false