#%RAML 1.0 DataType
displayName: OrderEditUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- OrderEditAddStagedActionAction
- OrderEditSetCommentAction
- OrderEditSetCustomFieldAction
- OrderEditSetCustomTypeAction
- OrderEditSetKeyAction
- OrderEditSetStagedActionsAction
properties:
  action:
    type: string
    (builtinType): string
    required: true