#%RAML 1.0 DataType
type: object
(originalType): OrderEditUpdateAction
displayName: OrderEditSetStagedActionsAction
# discriminator: action
# discriminatorValue: setStagedActions
properties:
  action:
    default: setStagedActions
    required: true
    type: string
  stagedActions:
    required: true
    type: array
    items:
      type: StagedOrderUpdateAction