#%RAML 1.0 DataType
displayName: OrderEditPreviewFailure
type: OrderEditResult
(builtinType): object
discriminatorValue: PreviewFailure
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#ordereditpreviewfailure"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PreviewFailure
    required: true
  errors:
    type: array
    items:
      type: ErrorObject
    (builtinType): array
    required: true