#%RAML 1.0 DataType
displayName: OrderEditDraft
type: object
(builtinType): object
properties:
  dryRun:
    type: boolean
    (builtinType): boolean
    description: |-
      When set to `true` the edit is applied on the Order without persisting it.
    required: false
  resource:
    type: OrderReference
    (builtinType): object
    description: |-
      The order to be updated with this edit.
    required: true
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  comment:
    type: string
    (builtinType): string
    description: |-
      This field can be used to add additional textual information regarding the edit.
    required: false
  stagedActions:
    type: array
    items:
      type: StagedOrderUpdateAction
    (builtinType): array
    description: |-
      The actions to apply to `resource`.
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      Unique identifier for this edit.
    required: false