#%RAML 1.0 DataType
displayName: OrderEditResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: order-edit
(package): "OrderEdit"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - order-edit
    required: false