#%RAML 1.0 DataType
displayName: OrderEditResult
type: object
(builtinType): object
discriminator: type
(oneOf):
- OrderEditApplied
- OrderEditNotProcessed
- OrderEditPreviewFailure
- OrderEditPreviewSuccess
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#ordereditresult"
properties:
  type:
    type: string
    (builtinType): string
    required: true