#%RAML 1.0 DataType
type: object
(originalType): object
displayName: OrderExcerpt
# 
# 
properties:
  totalPrice:
    required: true
    discriminator: type
    type: TypedMoney
  taxedPrice:
    required: false
    type: TaxedPrice
  version:
    required: true
    format: int16
    type: integer