#%RAML 1.0 DataType
displayName: OrderExcerpt
type: object
(builtinType): object
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#orderexcerpt"
properties:
  totalPrice:
    type: TypedMoney
    (builtinType): object
    required: true
  taxedPrice:
    type: TaxedPrice
    (builtinType): object
    required: false
  version:
    format: int
    type: integer
    (builtinType): integer
    required: true