#%RAML 1.0 DataType
(builtinType): object
type: OrderEditResult
displayName: OrderEditPreviewFailure
discriminator: type
discriminatorValue: PreviewFailure
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PreviewFailure
    required: true
  errors:
    type: array
    items:
      type: ErrorObject
    (builtinType): array
    required: true