#%RAML 1.0 DataType
type: object
(originalType): OrderEditUpdateAction
displayName: OrderEditAddStagedActionAction

discriminatorValue: addStagedAction
properties:
  action:
    type: string
  stagedAction:
    type: StagedOrderUpdateAction