#%RAML 1.0 DataType
displayName: OrderEditResult
type: object
(builtinType): object
discriminator: type
(oneOf):
- OrderEditApplied
- OrderEditNotProcessed
- OrderEditPreviewFailure
- OrderEditPreviewSuccess
properties:
  type:
    type: string
    (builtinType): string
    required: true