#%RAML 1.0 DataType
displayName: OrderEditApplied
type: OrderEditResult
(builtinType): object
discriminatorValue: Applied
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Applied
    required: true
  appliedAt:
    type: datetime
    (builtinType): datetime
    required: true
  excerptBeforeEdit:
    type: OrderExcerpt
    (builtinType): object
    required: true
  excerptAfterEdit:
    type: OrderExcerpt
    (builtinType): object
    required: true