#%RAML 1.0 DataType
type: object
(originalType): object
displayName: OrderEditApply
# 
# 
properties:
  resourceVersion:
    required: true
    type: integer
  editVersion:
    required: true
    type: integer