#%RAML 1.0 DataType
displayName: OrderEditSetStagedActionsAction
type: OrderEditUpdateAction
(builtinType): object
discriminatorValue: setStagedActions
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#setstagedactions"
examples:
  postman: !include ../../examples/OrderEdit/OrderEditSetStagedActionsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setStagedActions
    required: true
  stagedActions:
    type: array
    items:
      type: StagedOrderUpdateAction
    (builtinType): array
    required: true