#%RAML 1.0 DataType
type: object
displayName: OrderEditUpdate


properties:
   version:
      format: int64
      type: number
   actions:
      type: array
      items:
        type: OrderEditUpdateAction
   dryRun:
      type: boolean