#%RAML 1.0 DataType
displayName: OrderEditSetCommentAction
type: OrderEditUpdateAction
(builtinType): object
discriminatorValue: setComment
examples:
  postman: !include ../../examples/OrderEdit/OrderEditSetCommentAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setComment
    required: true
  comment:
    type: string
    (builtinType): string
    required: false