#%RAML 1.0 DataType
displayName: OrderEditNotProcessed
type: OrderEditResult
(builtinType): object
discriminatorValue: NotProcessed
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#ordereditnotprocessed"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - NotProcessed
    required: true