#%RAML 1.0 DataType
displayName: OrderEditNotProcessed
type: OrderEditResult
(builtinType): object
discriminatorValue: NotProcessed
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - NotProcessed
    required: true