#%RAML 1.0 DataType
displayName: OrderEditReference
type: Reference
(builtinType): object
discriminatorValue: order-edit
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - order-edit
    required: true
  obj:
    type: OrderEdit
    (builtinType): object
    required: false