#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: OrderEditApply
properties:
  resourceVersion:
    type: integer
    (builtinType): integer
    required: true
  editVersion:
    type: integer
    (builtinType): integer
    required: true