#%RAML 1.0 DataType
(builtinType): object
type: OrderEditResult
displayName: OrderEditNotProcessed
discriminator: type
discriminatorValue: NotProcessed
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - NotProcessed
    required: true