#%RAML 1.0 DataType
displayName: OrderEditSetKeyAction
type: OrderEditUpdateAction
(builtinType): object
discriminatorValue: setKey
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#setkey"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/OrderEditSetKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false