#%RAML 1.0 DataType
displayName: OrderEditAddStagedActionAction
type: OrderEditUpdateAction
(builtinType): object
discriminatorValue: addStagedAction
examples:
  postman: !include ../../examples/OrderEdit/OrderEditAddStagedActionAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addStagedAction
    required: true
  stagedAction:
    type: StagedOrderUpdateAction
    (builtinType): object
    required: true