#%RAML 1.0 DataType
displayName: OrderEditApply
type: object
(builtinType): object
(package): "OrderEdit"
properties:
  editVersion:
    type: integer
    (builtinType): integer
    required: true
  resourceVersion:
    type: integer
    (builtinType): integer
    required: true