#%RAML 1.0 DataType
type: object
(originalType): ResourceIdentifier
displayName: OrderEditResourceIdentifier

discriminatorValue: order-edit
properties:
  typeId:
    required: false
    type: ReferenceTypeId
  id:
    required: false
    type: string
  key:
    required: false
    type: string