#%RAML 1.0 DataType
(builtinType): object
type: OrderEditResult
displayName: OrderEditPreviewSuccess
discriminator: type
discriminatorValue: PreviewSuccess
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - PreviewSuccess
    required: true
  preview:
    type: StagedOrder
    (builtinType): object
    required: true
  messagePayloads:
    type: array
    items:
      type: MessagePayload
    (builtinType): array
    required: true