#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderChangeLineItemQuantityAction
# discriminator: action
# discriminatorValue: changeLineItemQuantity
properties:
  action:
    default: changeLineItemQuantity
    required: true
    type: string
  quantity:
    required: true
    type: number
  externalTotalPrice:
    required: false
    type: ExternalLineItemTotalPrice
  lineItemId:
    required: true
    type: string
  externalPrice:
    required: false
    type: Money