#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetShippingMethodTaxRateAction
# discriminator: action
# discriminatorValue: setShippingMethodTaxRate
properties:
  action:
    default: setShippingMethodTaxRate
    required: true
    type: string
  externalTaxRate:
    required: false
    type: ExternalTaxRateDraft