#%RAML 1.0 DataType
displayName: StagedOrderSetReturnShipmentStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setReturnShipmentState
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-returnshipmentstate"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderSetReturnShipmentStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setReturnShipmentState
    required: true
  returnItemId:
    type: string
    (builtinType): string
    required: true
  shipmentState:
    type: ReturnShipmentState
    (builtinType): string
    enum:
    - Advised
    - Returned
    - BackInStock
    - Unusable
    required: true