#%RAML 1.0 DataType
displayName: StagedOrderSetShippingMethodAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setShippingMethod
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetShippingMethodAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethod
    required: true
  shippingMethod:
    type: ShippingMethodResourceIdentifier
    (builtinType): object
    required: false
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false