#%RAML 1.0 DataType
displayName: StagedOrderUpdateSyncInfoAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: updateSyncInfo
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#update-syncinfo"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderUpdateSyncInfoAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - updateSyncInfo
    required: true
  channel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false
  syncedAt:
    type: datetime
    (builtinType): datetime
    required: false