#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderAddReturnInfoAction
discriminator: action
discriminatorValue: addReturnInfo
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addReturnInfo
    required: true
  returnDate:
    type: datetime
    (builtinType): datetime
    required: false
  returnTrackingId:
    type: string
    (builtinType): string
    required: false
  items:
    type: array
    items:
      type: ReturnItemDraft
    (builtinType): array
    required: true