#%RAML 1.0 DataType
displayName: StagedOrderChangeTaxModeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeTaxMode
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangeTaxModeAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxMode
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    required: true