#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetShippingMethodAction

discriminatorValue: setShippingMethod
properties:
  action:
    type: string
  externalTaxRate:
    type: ExternalTaxRateDraft
  shippingMethod:
    type: ShippingMethodResourceIdentifier