#%RAML 1.0 DataType
displayName: StagedOrderSetCustomerIdAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setCustomerId
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-customer-id"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderSetCustomerIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerId
    required: true
  customerId:
    type: string
    (builtinType): string
    required: false