#%RAML 1.0 DataType
displayName: StagedOrderUpdateSyncInfoAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: updateSyncInfo
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderUpdateSyncInfoAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - updateSyncInfo
    required: true
  channel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: true
  externalId:
    type: string
    (builtinType): string
    required: false
  syncedAt:
    type: datetime
    (builtinType): datetime
    required: false