#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetReturnPaymentStateAction
# discriminator: action
# discriminatorValue: setReturnPaymentState
properties:
  action:
    default: setReturnPaymentState
    required: true
    type: string
  returnItemId:
    required: true
    type: string
  paymentState:
    required: true
    type: ReturnPaymentState