#%RAML 1.0 DataType
displayName: StagedOrderSetLineItemShippingDetailsAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemShippingDetails
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemShippingDetails
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false