#%RAML 1.0 DataType
displayName: StagedOrderSetLocaleAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setLocale
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-locale"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderSetLocaleAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLocale
    required: true
  locale:
    type: string
    (builtinType): string
    required: false