#%RAML 1.0 DataType
displayName: StagedOrderChangeTaxCalculationModeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeTaxCalculationMode
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#change-taxcalculationmode"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangeTaxCalculationModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxCalculationMode
    required: true
  taxCalculationMode:
    type: TaxCalculationMode
    (builtinType): string
    required: true