#%RAML 1.0 DataType
displayName: StagedOrderTransitionCustomLineItemStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: transitionCustomLineItemState
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#change-the-state-of-customlineitem-according-to-allowed-transitions"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderTransitionCustomLineItemStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionCustomLineItemState
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  fromState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  toState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  actualTransitionDate:
    type: datetime
    (builtinType): datetime
    required: false