#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderAddParcelToDeliveryAction
discriminator: action
discriminatorValue: addParcelToDelivery
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addParcelToDelivery
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: false
  trackingData:
    type: TrackingData
    (builtinType): object
    required: false
  measurements:
    type: ParcelMeasurements
    (builtinType): object
    required: false