#%RAML 1.0 DataType
type: StagedOrderUpdateAction
displayName: StagedOrderSetLineItemShippingDetailsAction

discriminatorValue: setLineItemShippingDetails
properties:
   lineItemId:
      type: string
   shippingDetails:
      type: ItemShippingDetailsDraft