#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetOrderNumberAction
discriminator: action
discriminatorValue: setOrderNumber
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setOrderNumber
    required: true
  orderNumber:
    type: string
    (builtinType): string
    required: false