#%RAML 1.0 DataType
displayName: StagedOrderRemoveItemShippingAddressAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: removeItemShippingAddress
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderRemoveItemShippingAddressAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeItemShippingAddress
    required: true
  addressKey:
    type: string
    (builtinType): string
    required: true