#%RAML 1.0 DataType
displayName: StagedOrderSetLocaleAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setLocale
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLocale
    required: true
  locale:
    type: string
    (builtinType): string
    required: false