#%RAML 1.0 DataType
displayName: StagedOrderChangePaymentStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changePaymentState
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangePaymentStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePaymentState
    required: true
  paymentState:
    type: PaymentState
    (builtinType): string
    required: false