#%RAML 1.0 DataType
displayName: StagedOrderSetCustomLineItemTaxAmountAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setCustomLineItemTaxAmount
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemTaxAmount
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  externalTaxAmount:
    type: ExternalTaxAmountDraft
    (builtinType): object
    required: false