#%RAML 1.0 DataType
displayName: StagedOrderAddDiscountCodeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: addDiscountCode
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderAddDiscountCodeAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addDiscountCode
    required: true
  code:
    type: string
    (builtinType): string
    required: true