#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetCustomerGroupAction

discriminatorValue: setCustomerGroup
properties:
  action:
    type: string
  customerGroup:
    type: CustomerGroupResourceIdentifier