#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderChangeTaxCalculationModeAction

discriminatorValue: changeTaxCalculationMode
properties:
  action:
    required: true
    type: string
  taxCalculationMode:
    required: true
    type: TaxCalculationMode