#%RAML 1.0 DataType
displayName: StagedOrderSetShippingRateInputAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setShippingRateInput
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingRateInput
    required: true
  shippingRateInput:
    type: ShippingRateInputDraft
    (builtinType): object
    required: false