#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderChangeTaxModeAction

discriminatorValue: changeTaxMode
properties:
  action:
    required: true
    type: string
  taxMode:
    required: true
    type: TaxMode