#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetShippingAddressAndCustomShippingMethodAction
# discriminator: action
# discriminatorValue: setShippingAddressAndCustomShippingMethod
properties:
  action:
    default: setShippingAddressAndCustomShippingMethod
    required: true
    type: string
  shippingRate:
    required: true
    type: ShippingRateDraft
  externalTaxRate:
    required: false
    type: ExternalTaxRateDraft
  address:
    required: true
    type: Address
  shippingMethodName:
    required: true
    type: string
  taxCategory:
    required: false
    type: TaxCategoryResourceIdentifier