#%RAML 1.0 DataType
displayName: StagedOrderSetBillingAddressAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setBillingAddress
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetBillingAddressAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setBillingAddress
    required: true
  address:
    type: Address
    (builtinType): object
    required: false