#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetReturnShipmentStateAction
discriminator: action
discriminatorValue: setReturnShipmentState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setReturnShipmentState
    required: true
  shipmentState:
    type: ReturnShipmentState
    (builtinType): string
    required: true
  returnItemId:
    type: string
    (builtinType): string
    required: true