#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetParcelItemsAction

discriminatorValue: setParcelItems
properties:
  action:
    required: true
    type: string
  items:
    required: true
    type: array
    items:
      type: DeliveryItem
  parcelId:
    required: true
    type: string