#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomShippingMethodAction
discriminator: action
discriminatorValue: setCustomShippingMethod
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomShippingMethod
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false
  shippingMethodName:
    type: string
    (builtinType): string
    required: true
  taxCategory:
    type: TaxCategoryResourceIdentifier
    (builtinType): object
    required: false