#%RAML 1.0 DataType
displayName: StagedOrderAddReturnInfoAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: addReturnInfo
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderAddReturnInfoAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addReturnInfo
    required: true
  returnTrackingId:
    type: string
    (builtinType): string
    required: false
  items:
    type: array
    items:
      type: ReturnItemDraft
    (builtinType): array
    required: true
  returnDate:
    type: datetime
    (builtinType): datetime
    required: false