#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetLocaleAction

discriminatorValue: setLocale
properties:
  action:
    type: string
  locale:
    type: string