#%RAML 1.0 DataType
displayName: StagedOrderChangeCustomLineItemQuantityAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeCustomLineItemQuantity
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangeCustomLineItemQuantityAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCustomLineItemQuantity
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    type: number
    (builtinType): number
    required: true