#%RAML 1.0 DataType
displayName: StagedOrderSetOrderTotalTaxAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setOrderTotalTax
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-order-total-tax"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetOrderTotalTaxAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setOrderTotalTax
    required: true
  externalTotalGross:
    type: Money
    (builtinType): object
    required: true
  externalTaxPortions:
    type: array
    items:
      type: TaxPortionDraft
    (builtinType): array
    required: false