#%RAML 1.0 DataType
displayName: StagedOrderSetCountryAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setCountry
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetCountryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCountry
    required: true
  country:
    type: string
    (builtinType): string
    required: false