#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetCustomLineItemShippingDetailsAction
discriminator: action
discriminatorValue: setCustomLineItemShippingDetails
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemShippingDetails
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false