#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderChangePaymentStateAction

discriminatorValue: changePaymentState
properties:
  action:
    required: true
    type: string
  paymentState:
    required: false
    type: PaymentState