#%RAML 1.0 DataType
displayName: StagedOrderAddShoppingListAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: addShoppingList
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderAddShoppingListAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShoppingList
    required: true
  shoppingList:
    type: ShoppingListResourceIdentifier
    (builtinType): object
    required: true
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false
  distributionChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false