#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetCustomLineItemShippingDetailsAction
# discriminator: action
# discriminatorValue: setCustomLineItemShippingDetails
properties:
  action:
    default: setCustomLineItemShippingDetails
    required: true
    type: string
  customLineItemId:
    required: true
    type: string
  shippingDetails:
    required: false
    type: ItemShippingDetailsDraft