#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetParcelTrackingDataAction
discriminator: action
discriminatorValue: setParcelTrackingData
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setParcelTrackingData
    required: true
  trackingData:
    type: TrackingData
    (builtinType): object
    required: false
  parcelId:
    type: string
    (builtinType): string
    required: true