#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderTransitionCustomLineItemStateAction
# discriminator: action
# discriminatorValue: transitionCustomLineItemState
properties:
  action:
    default: transitionCustomLineItemState
    required: true
    type: string
  toState:
    required: true
    type: StateResourceIdentifier
  fromState:
    required: true
    type: StateResourceIdentifier
  customLineItemId:
    required: true
    type: string
  quantity:
    required: true
    format: int64
    type: number
  actualTransitionDate:
    required: false
    type: datetime