#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetOrderTotalTaxAction
discriminator: action
discriminatorValue: setOrderTotalTax
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setOrderTotalTax
    required: true
  externalTaxPortions:
    type: array
    items:
      type: TaxPortionDraft
    (builtinType): array
    required: false
  externalTotalGross:
    type: Money
    (builtinType): object
    required: true