#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetLineItemTotalPriceAction
discriminator: action
discriminatorValue: setLineItemTotalPrice
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemTotalPrice
    required: true
  externalTotalPrice:
    type: ExternalLineItemTotalPrice
    (builtinType): object
    required: false
  lineItemId:
    type: string
    (builtinType): string
    required: true