#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderAddDiscountCodeAction
discriminator: action
discriminatorValue: addDiscountCode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addDiscountCode
    required: true
  code:
    type: string
    (builtinType): string
    required: true