#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetCustomerGroupAction
# discriminator: action
# discriminatorValue: setCustomerGroup
properties:
  action:
    default: setCustomerGroup
    required: true
    type: string
  customerGroup:
    required: false
    type: CustomerGroupResourceIdentifier