#%RAML 1.0 DataType
displayName: StagedOrderSetOrderNumberAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setOrderNumber
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-order-number"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetOrderNumberAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setOrderNumber
    required: true
  orderNumber:
    type: string
    (builtinType): string
    required: false