#%RAML 1.0 DataType
displayName: StagedOrderChangeTaxRoundingModeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeTaxRoundingMode
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangeTaxRoundingModeAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxRoundingMode
    required: true
  taxRoundingMode:
    type: RoundingMode
    (builtinType): string
    required: true