#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderChangeTaxCalculationModeAction
discriminator: action
discriminatorValue: changeTaxCalculationMode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxCalculationMode
    required: true
  taxCalculationMode:
    type: TaxCalculationMode
    (builtinType): string
    required: true