#%RAML 1.0 DataType
displayName: StagedOrderSetParcelItemsAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setParcelItems
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-parcel-items"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetParcelItemsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setParcelItems
    required: true
  parcelId:
    type: string
    (builtinType): string
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true