#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderAddPaymentAction
discriminator: action
discriminatorValue: addPayment
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addPayment
    required: true
  payment:
    type: PaymentResourceIdentifier
    (builtinType): object
    required: true