#%RAML 1.0 DataType
displayName: StagedOrderRemovePaymentAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: removePayment
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#remove-payment"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderRemovePaymentAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removePayment
    required: true
  payment:
    type: PaymentResourceIdentifier
    (builtinType): object
    required: true