#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderImportLineItemStateAction
# discriminator: action
# discriminatorValue: importLineItemState
properties:
  action:
    default: importLineItemState
    required: true
    type: string
  lineItemId:
    required: true
    type: string
  state:
    required: true
    type: array
    items:
      type: ItemState