#%RAML 1.0 DataType
displayName: StagedOrderAddDiscountCodeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: addDiscountCode
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#add-discountcode"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderAddDiscountCodeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addDiscountCode
    required: true
  code:
    type: string
    (builtinType): string
    required: true