#%RAML 1.0 DataType
displayName: StagedOrderSetLineItemTaxRateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemTaxRate
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetLineItemTaxRateAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemTaxRate
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false