#%RAML 1.0 DataType
displayName: StagedOrderSetReturnShipmentStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setReturnShipmentState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setReturnShipmentState
    required: true
  returnItemId:
    type: string
    (builtinType): string
    required: true
  shipmentState:
    type: ReturnShipmentState
    (builtinType): string
    required: true