#%RAML 1.0 DataType
displayName: StagedOrderSetReturnPaymentStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setReturnPaymentState
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-returnpaymentstate"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetReturnPaymentStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setReturnPaymentState
    required: true
  returnItemId:
    type: string
    (builtinType): string
    required: true
  paymentState:
    type: ReturnPaymentState
    (builtinType): string
    required: true