#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderRemoveParcelFromDeliveryAction
discriminator: action
discriminatorValue: removeParcelFromDelivery
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeParcelFromDelivery
    required: true
  parcelId:
    type: string
    (builtinType): string
    required: true