#%RAML 1.0 DataType
displayName: StagedOrderSetDeliveryItemsAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setDeliveryItems
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDeliveryItems
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: true