#%RAML 1.0 DataType
displayName: StagedOrderChangeShipmentStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeShipmentState
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangeShipmentStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeShipmentState
    required: true
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: false