#%RAML 1.0 DataType
displayName: StagedOrderSetShippingAddressAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setShippingAddress
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-shipping-address"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetShippingAddressAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingAddress
    required: true
  address:
    type: Address
    (builtinType): object
    required: false