#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetParcelMeasurementsAction
discriminator: action
discriminatorValue: setParcelMeasurements
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setParcelMeasurements
    required: true
  measurements:
    type: ParcelMeasurements
    (builtinType): object
    required: false
  parcelId:
    type: string
    (builtinType): string
    required: true