#%RAML 1.0 DataType
displayName: StagedOrderTransitionLineItemStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: transitionLineItemState
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderTransitionLineItemStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionLineItemState
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  fromState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  toState:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  actualTransitionDate:
    type: datetime
    (builtinType): datetime
    required: false