#%RAML 1.0 DataType
displayName: StagedOrderRemoveDeliveryAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: removeDelivery
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#remove-delivery"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderRemoveDeliveryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeDelivery
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true