#%RAML 1.0 DataType
displayName: StagedOrderChangeOrderStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeOrderState
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#change-orderstate"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangeOrderStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeOrderState
    required: true
  orderState:
    type: OrderState
    (builtinType): string
    required: true