#%RAML 1.0 DataType
displayName: StagedOrderChangeTaxModeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeTaxMode
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#change-taxmode"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderChangeTaxModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxMode
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    required: true