#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetOrderNumberAction
# discriminator: action
# discriminatorValue: setOrderNumber
properties:
  action:
    default: setOrderNumber
    required: true
    type: string
  orderNumber:
    required: false
    type: string