#%RAML 1.0 DataType
type: StagedOrderUpdateAction
displayName: StagedOrderChangeTaxRoundingModeAction

discriminatorValue: changeTaxRoundingMode
properties:
   taxRoundingMode:
      type: RoundingMode