#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderAddCustomLineItemAction

discriminatorValue: addCustomLineItem
properties:
  action:
    required: true
    type: string
  externalTaxRate:
    required: false
    type: ExternalTaxRateDraft
  quantity:
    required: false
    type: number
  money:
    required: true
    type: Money
  custom:
    required: false
    type: CustomFieldsDraft
  name:
    required: true
    type: LocalizedString
  slug:
    required: true
    type: string
  taxCategory:
    required: false
    type: TaxCategoryResourceIdentifier