#%RAML 1.0 DataType
displayName: StagedOrderRemoveLineItemAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: removeLineItem
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#remove-lineitem"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderRemoveLineItemAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLineItem
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    type: number
    (builtinType): number
    required: false
  externalPrice:
    type: Money
    (builtinType): object
    required: false
  externalTotalPrice:
    type: ExternalLineItemTotalPrice
    (builtinType): object
    required: false
  shippingDetailsToRemove:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false