#%RAML 1.0 DataType
displayName: StagedOrderAddDeliveryAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: addDelivery
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderAddDeliveryAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addDelivery
    required: true
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: false
  address:
    type: Address
    (builtinType): object
    required: false
  parcels:
    type: array
    items:
      type: ParcelDraft
    (builtinType): array
    required: false