#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderImportLineItemStateAction

discriminatorValue: importLineItemState
properties:
  action:
    type: string
  lineItemId:
    type: string
  state:
    type: array
    items:
      type: ItemState