#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetReturnPaymentStateAction
discriminator: action
discriminatorValue: setReturnPaymentState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setReturnPaymentState
    required: true
  returnItemId:
    type: string
    (builtinType): string
    required: true
  paymentState:
    type: ReturnPaymentState
    (builtinType): string
    required: true