#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderChangePaymentStateAction
# discriminator: action
# discriminatorValue: changePaymentState
properties:
  action:
    default: changePaymentState
    required: true
    type: string
  paymentState:
    required: false
    type: PaymentState