#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetShippingRateInputAction
discriminator: action
discriminatorValue: setShippingRateInput
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingRateInput
    required: true
  shippingRateInput:
    type: ShippingRateInputDraft
    (builtinType): object
    required: false