#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetShippingMethodAction
discriminator: action
discriminatorValue: setShippingMethod
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethod
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false
  shippingMethod:
    type: ShippingMethodResourceIdentifier
    (builtinType): object
    required: false