#%RAML 1.0 DataType
displayName: StagedOrderSetLineItemTotalPriceAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemTotalPrice
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-lineitem-totalprice"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderSetLineItemTotalPriceAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemTotalPrice
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  externalTotalPrice:
    type: ExternalLineItemTotalPrice
    (builtinType): object
    required: false