#%RAML 1.0 DataType
type: StagedOrderUpdateAction
displayName: StagedOrderTransitionStateAction

discriminatorValue: transitionState
properties:
   state:
      type: StateResourceIdentifier
   force:
      type: boolean