#%RAML 1.0 DataType
displayName: StagedOrderSetLineItemCustomTypeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setLineItemCustomType
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetLineItemCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemCustomType
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false