#%RAML 1.0 DataType
type: StagedOrderUpdateAction
displayName: StagedOrderChangeLineItemQuantityAction

discriminatorValue: changeLineItemQuantity
properties:
   lineItemId:
      type: string
   quantity:
      type: number
   externalPrice:
      type: Money
   externalTotalPrice:
      type: ExternalLineItemTotalPrice