#%RAML 1.0 DataType
displayName: StagedOrderSetShippingMethodTaxAmountAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setShippingMethodTaxAmount
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-shippingmethod-taxamount"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetShippingMethodTaxAmountAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethodTaxAmount
    required: true
  externalTaxAmount:
    type: ExternalTaxAmountDraft
    (builtinType): object
    required: false