#%RAML 1.0 DataType
displayName: StagedOrderChangeTaxRoundingModeAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeTaxRoundingMode
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#change-tax-roundingmode"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderChangeTaxRoundingModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxRoundingMode
    required: true
  taxRoundingMode:
    type: RoundingMode
    (builtinType): string
    enum:
    - HalfEven
    - HalfUp
    - HalfDown
    required: true