#%RAML 1.0 DataType
displayName: StagedOrderSetParcelMeasurementsAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setParcelMeasurements
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-parcel-measurements"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetParcelMeasurementsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setParcelMeasurements
    required: true
  parcelId:
    type: string
    (builtinType): string
    required: true
  measurements:
    type: ParcelMeasurements
    (builtinType): object
    required: false