#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderRemoveCustomLineItemAction
discriminator: action
discriminatorValue: removeCustomLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeCustomLineItem
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true