#%RAML 1.0 DataType
displayName: StagedOrderChangeLineItemQuantityAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeLineItemQuantity
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderChangeLineItemQuantityAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLineItemQuantity
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    type: number
    (builtinType): number
    required: true
  externalPrice:
    type: Money
    (builtinType): object
    required: false
  externalTotalPrice:
    type: ExternalLineItemTotalPrice
    (builtinType): object
    required: false