#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderSetShippingMethodTaxAmountAction
discriminator: action
discriminatorValue: setShippingMethodTaxAmount
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethodTaxAmount
    required: true
  externalTaxAmount:
    type: ExternalTaxAmountDraft
    (builtinType): object
    required: false