#%RAML 1.0 DataType
(builtinType): object
type: StagedOrderUpdateAction
displayName: StagedOrderChangeShipmentStateAction
discriminator: action
discriminatorValue: changeShipmentState
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeShipmentState
    required: true
  shipmentState:
    type: ShipmentState
    (builtinType): string
    required: false