#%RAML 1.0 DataType
displayName: StagedOrderChangeCustomLineItemMoneyAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: changeCustomLineItemMoney
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#change-customlineitem-money"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderChangeCustomLineItemMoneyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCustomLineItemMoney
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  money:
    type: Money
    (builtinType): object
    required: true