#%RAML 1.0 DataType
displayName: StagedOrderTransitionStateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: transitionState
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#transition-state"
examples:
  postman:
    strict: true
    value: !include ../../examples/OrderEdit/StagedOrderTransitionStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionState
    required: true
  state:
    type: StateResourceIdentifier
    (builtinType): object
    required: true
  force:
    type: boolean
    (builtinType): boolean
    required: false