#%RAML 1.0 DataType
displayName: StagedOrderSetShippingRateInputAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setShippingRateInput
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-shipping-rate-input"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetShippingRateInputAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingRateInput
    required: true
  shippingRateInput:
    type: ShippingRateInputDraft
    (builtinType): object
    required: false