#%RAML 1.0 DataType
displayName: StagedOrderAddShoppingListAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: addShoppingList
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#add-shopping-list"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderAddShoppingListAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShoppingList
    required: true
  shoppingList:
    type: ShoppingListResourceIdentifier
    (builtinType): object
    required: true
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false
  distributionChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false