#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetParcelTrackingDataAction

discriminatorValue: setParcelTrackingData
properties:
  action:
    type: string
  trackingData:
    type: TrackingData
  parcelId:
    type: string