#%RAML 1.0 DataType
displayName: StagedOrderRemovePaymentAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: removePayment
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderRemovePaymentAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removePayment
    required: true
  payment:
    type: PaymentResourceIdentifier
    (builtinType): object
    required: true