#%RAML 1.0 DataType
displayName: StagedOrderAddParcelToDeliveryAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: addParcelToDelivery
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderAddParcelToDeliveryAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addParcelToDelivery
    required: true
  deliveryId:
    type: string
    (builtinType): string
    required: true
  measurements:
    type: ParcelMeasurements
    (builtinType): object
    required: false
  trackingData:
    type: TrackingData
    (builtinType): object
    required: false
  items:
    type: array
    items:
      type: DeliveryItem
    (builtinType): array
    required: false