#%RAML 1.0 DataType
displayName: StagedOrderSetShippingMethodTaxRateAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setShippingMethodTaxRate
(package): "OrderEdit"
(docs-uri): "https://docs.commercetools.com/http-api-projects-order-edits.html#set-shippingmethod-taxrate"
examples:
  postman: !include ../../examples/OrderEdit/StagedOrderSetShippingMethodTaxRateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethodTaxRate
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false