#%RAML 1.0 DataType
type: object
(originalType): StagedOrderUpdateAction
displayName: StagedOrderSetShippingAddressAndShippingMethodAction

discriminatorValue: setShippingAddressAndShippingMethod
properties:
  action:
    type: string
  externalTaxRate:
    type: ExternalTaxRateDraft
  address:
    type: Address
  shippingMethod:
    type: ShippingMethodResourceIdentifier