#%RAML 1.0 DataType
displayName: StagedOrderSetCustomFieldAction
type: StagedOrderUpdateAction
(builtinType): object
discriminatorValue: setCustomField
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomField
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false