#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: DiscountCodeNonApplicableError
discriminator: code
discriminatorValue: DiscountCodeNonApplicable
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - DiscountCodeNonApplicable
    required: true
  message:
    type: string
    (builtinType): string
    required: true
  reason:
    type: string
    (builtinType): string
    required: false
  validityCheckTime:
    type: datetime
    (builtinType): datetime
    required: false
  discountCode:
    type: string
    (builtinType): string
    required: false
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false
  dicountCodeId:
    type: string
    (builtinType): string
    required: false