#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: DiscountCodeNonApplicableError

discriminatorValue: DiscountCodeNonApplicable
properties:
  code:
    type: string
  message:
    type: string
  reason:
    type: string
  validityCheckTime:
    type: datetime
  discountCode:
    type: string
  validUntil:
    type: datetime
  validFrom:
    type: datetime
  dicountCodeId:
    type: string