#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: DiscountCodeNonApplicableError
# discriminator: code
# discriminatorValue: DiscountCodeNonApplicable
properties:
  code:
    default: DiscountCodeNonApplicable
    required: true
    type: string
  message:
    required: true
    type: string
  reason:
    required: false
    type: string
  validityCheckTime:
    required: false
    type: datetime
  discountCode:
    required: false
    type: string
  validUntil:
    required: false
    type: datetime
  validFrom:
    required: false
    type: datetime
  dicountCodeId:
    required: false
    type: string