#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: DuplicateVariantValuesError
# discriminator: code
# discriminatorValue: DuplicateVariantValues
properties:
  code:
    default: DuplicateVariantValues
    required: true
    type: string
  message:
    required: true
    type: string
  variantValues:
    required: true
    type: VariantValues