#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: DuplicatePriceScopeError
discriminator: code
discriminatorValue: DuplicatePriceScope
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - DuplicatePriceScope
    required: true
  message:
    type: string
    (builtinType): string
    required: true
  conflictingPrices:
    type: array
    items:
      type: Price
    (builtinType): array
    required: true