#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: DuplicateFieldError
discriminator: code
discriminatorValue: DuplicateField
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - DuplicateField
    required: true
  message:
    type: string
    (builtinType): string
    required: true
  conflictingResource:
    type: Reference
    (builtinType): object
    required: false
  duplicateValue:
    type: any
    (builtinType): any
    required: false
  field:
    type: string
    (builtinType): string
    required: false