#%RAML 1.0 DataType
displayName: DuplicateFieldWithConflictingResourceError
type: ErrorObject
(builtinType): object
discriminatorValue: DuplicateFieldWithConflictingResource
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - DuplicateFieldWithConflictingResource
    required: true
  field:
    type: string
    (builtinType): string
    required: true
  duplicateValue:
    type: any
    (builtinType): any
    required: true
  conflictingResource:
    type: Reference
    (builtinType): object
    required: true