#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: DuplicateAttributeValuesError

discriminatorValue: DuplicateAttributeValues
properties:
  code:
    type: string
  message:
    type: string
  attributes:
    type: array
    items:
      type: Attribute