#%RAML 1.0 DataType
displayName: DuplicatePriceScopeError
type: ErrorObject
(builtinType): object
discriminatorValue: DuplicatePriceScope
(package): "Error"
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - DuplicatePriceScope
    required: true
  conflictingPrices:
    type: array
    items:
      type: Price
    (builtinType): array
    required: true