#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: DuplicatePriceScopeError

discriminatorValue: DuplicatePriceScope
properties:
  code:
    type: string
  message:
    type: string
  conflictingPrices:
    type: array
    items:
      type: Price