#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: DuplicateAttributeValueError
# discriminator: code
# discriminatorValue: DuplicateAttributeValue
properties:
  code:
    default: DuplicateAttributeValue
    required: true
    type: string
  message:
    required: true
    type: string
  attribute:
    required: true
    type: Attribute