#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: EnumValueIsUsedError
discriminator: code
discriminatorValue: EnumValueIsUsed
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - EnumValueIsUsed
    required: true
  message:
    type: string
    (builtinType): string
    required: true