#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: EnumValueIsUsedError

discriminatorValue: EnumValueIsUsed
properties:
  code:
    required: true
    type: string
  message:
    required: true
    type: string