#%RAML 1.0 DataType
displayName: ErrorObject
type: object
(builtinType): object
discriminator: code
(oneOf):
- AccessDeniedError
- ConcurrentModificationError
- DiscountCodeNonApplicableError
- DuplicateAttributeValueError
- DuplicateAttributeValuesError
- DuplicateFieldError
- DuplicateFieldWithConflictingResourceError
- DuplicatePriceScopeError
- DuplicateVariantValuesError
- EnumValueIsUsedError
- ExtensionBadResponseError
- ExtensionNoResponseError
- ExtensionUpdateActionsFailedError
- InsufficientScopeError
- InvalidCredentialsError
- InvalidCurrentPasswordError
- InvalidFieldError
- InvalidInputError
- InvalidItemShippingDetailsError
- InvalidJsonInputError
- InvalidOperationError
- InvalidSubjectError
- InvalidTokenError
- MatchingPriceNotFoundError
- MissingTaxRateForCountryError
- NoMatchingProductDiscountFoundError
- OutOfStockError
- PriceChangedError
- ReferenceExistsError
- RequiredFieldError
- ResourceNotFoundError
- ShippingMethodDoesNotMatchCartError
(package): "Error"
properties:
  code:
    type: string
    (builtinType): string
    required: true
  message:
    type: string
    (builtinType): string
    required: true