#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ErrorResponse


properties:
  error_description:
    required: false
    type: string
  error:
    required: false
    type: string
  message:
    required: true
    type: string
  errors:
    required: false
    type: array
    items:
      type: ErrorObject
  statusCode:
    required: true
    type: integer