#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: ExtensionNoResponseError
discriminator: code
discriminatorValue: ExtensionNoResponse
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - ExtensionNoResponse
    required: true
  message:
    type: string
    (builtinType): string
    required: true
  localizedMessage:
    type: LocalizedString
    (builtinType): object
    required: false
  extensionExtraInfo:
    type: object
    (builtinType): object
    required: false
  errorByExtension:
    type: ErrorByExtension
    (builtinType): object
    required: true