#%RAML 1.0 DataType
displayName: ExtensionBadResponseError
type: ErrorObject
(builtinType): object
discriminatorValue: ExtensionBadResponse
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - ExtensionBadResponse
    required: true
  localizedMessage:
    type: LocalizedString
    (builtinType): object
    required: false
  extensionExtraInfo:
    type: object
    (builtinType): object
    required: false
  errorByExtension:
    type: ErrorByExtension
    (builtinType): object
    required: true