#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: InsufficientScopeError
discriminator: code
discriminatorValue: insufficient_scope
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - insufficient_scope
    required: true
  message:
    type: string
    (builtinType): string
    required: true