#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: InvalidFieldError
# discriminator: code
# discriminatorValue: InvalidField
properties:
  code:
    default: InvalidField
    required: true
    type: string
  message:
    required: true
    type: string
  allowedValues:
    required: false
    type: array
    items:
      type: any
  field:
    required: true
    type: string
  invalidValue:
    required: true
    type: any