#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: InvalidOperationError
discriminator: code
discriminatorValue: InvalidOperation
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidOperation
    required: true
  message:
    type: string
    (builtinType): string
    required: true