#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: InvalidFieldError

discriminatorValue: InvalidField
properties:
  code:
    type: string
  message:
    type: string
  allowedValues:
    type: array
    items:
      type: any
  field:
    type: string
  invalidValue:
    type: any