#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: InvalidInputError

discriminatorValue: InvalidInput
properties:
  code:
    required: true
    type: string
  message:
    required: true
    type: string