#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: InvalidSubjectError
discriminator: code
discriminatorValue: InvalidSubject
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidSubject
    required: true
  message:
    type: string
    (builtinType): string
    required: true