#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: InvalidSubjectError
# discriminator: code
# discriminatorValue: InvalidSubject
properties:
  code:
    default: InvalidSubject
    required: true
    type: string
  message:
    required: true
    type: string