#%RAML 1.0 DataType
displayName: InvalidItemShippingDetailsError
type: ErrorObject
(builtinType): object
discriminatorValue: InvalidItemShippingDetails
(package): "Error"
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidItemShippingDetails
    required: true
  subject:
    type: string
    (builtinType): string
    required: true
  itemId:
    type: string
    (builtinType): string
    required: true