#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: InvalidInputError
discriminator: code
discriminatorValue: InvalidInput
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidInput
    required: true
  message:
    type: string
    (builtinType): string
    required: true