#%RAML 1.0 DataType
displayName: InvalidSubjectError
type: ErrorObject
(builtinType): object
discriminatorValue: InvalidSubject
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidSubject
    required: true