#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: InvalidItemShippingDetailsError
discriminator: code
discriminatorValue: InvalidItemShippingDetails
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidItemShippingDetails
    required: true
  message:
    type: string
    (builtinType): string
    required: true
  itemId:
    type: string
    (builtinType): string
    required: true
  subject:
    type: string
    (builtinType): string
    required: true