#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: InvalidCredentialsError

discriminatorValue: InvalidCredentials
properties:
  code:
    type: string
  message:
    type: string