#%RAML 1.0 DataType
displayName: InvalidOperationError
type: ErrorObject
(builtinType): object
discriminatorValue: InvalidOperation
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - InvalidOperation
    required: true