#%RAML 1.0 DataType
displayName: MatchingPriceNotFoundError
type: ErrorObject
(builtinType): object
discriminatorValue: MatchingPriceNotFound
(package): "Error"
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - MatchingPriceNotFound
    required: true
  productId:
    type: string
    (builtinType): string
    required: true
  variantId:
    type: integer
    (builtinType): integer
    required: true
  currency:
    type: string
    (builtinType): string
    required: false
  country:
    type: string
    (builtinType): string
    required: false
  customerGroup:
    type: CustomerGroupReference
    (builtinType): object
    required: false
  channel:
    type: ChannelReference
    (builtinType): object
    required: false