#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: MissingTaxRateForCountryError
discriminator: code
discriminatorValue: MissingTaxRateForCountry
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - MissingTaxRateForCountry
    required: true
  message:
    type: string
    (builtinType): string
    required: true
  country:
    type: string
    (builtinType): string
    required: false
  state:
    type: string
    (builtinType): string
    required: false
  taxCategoryId:
    type: string
    (builtinType): string
    required: true