#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: MissingTaxRateForCountryError

discriminatorValue: MissingTaxRateForCountry
properties:
  code:
    type: string
  message:
    type: string
  country:
    type: string
  state:
    type: string
  taxCategoryId:
    type: string