#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: NoMatchingProductDiscountFoundError
discriminator: code
discriminatorValue: NoMatchingProductDiscountFound
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - NoMatchingProductDiscountFound
    required: true
  message:
    type: string
    (builtinType): string
    required: true