#%RAML 1.0 DataType
displayName: OutOfStockError
type: ErrorObject
(builtinType): object
discriminatorValue: OutOfStock
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - OutOfStock
    required: true
  lineItems:
    type: array
    items:
      type: string
    (builtinType): array
    required: true
  skus:
    type: array
    items:
      type: string
    (builtinType): array
    required: true