#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: OutOfStockError

discriminatorValue: OutOfStock
properties:
  code:
    required: true
    type: string
  message:
    required: true
    type: string
  lineItems:
    required: true
    type: array
    items:
      type: string
  skus:
    required: true
    type: array
    items:
      type: string