#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: PriceChangedError
# discriminator: code
# discriminatorValue: PriceChanged
properties:
  code:
    default: PriceChanged
    required: true
    type: string
  message:
    required: true
    type: string
  lineItems:
    required: true
    type: array
    items:
      type: string
  shipping:
    required: true
    type: boolean