#%RAML 1.0 DataType
displayName: PriceChangedError
type: ErrorObject
(builtinType): object
discriminatorValue: PriceChanged
(package): "Error"
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - PriceChanged
    required: true
  lineItems:
    type: array
    items:
      type: string
    (builtinType): array
    required: true
  shipping:
    type: boolean
    (builtinType): boolean
    required: true