#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: ReferenceExistsError
discriminator: code
discriminatorValue: ReferenceExists
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - ReferenceExists
    required: true
  message:
    type: string
    (builtinType): string
    required: true
  referencedBy:
    type: ReferenceTypeId
    (builtinType): string
    required: false