#%RAML 1.0 DataType
type: object
(originalType): ErrorObject
displayName: ShippingMethodDoesNotMatchCartError
# discriminator: code
# discriminatorValue: ShippingMethodDoesNotMatchCart
properties:
  code:
    default: ShippingMethodDoesNotMatchCart
    required: true
    type: string
  message:
    required: true
    type: string