#%RAML 1.0 DataType
displayName: ShippingMethodDoesNotMatchCartError
type: ErrorObject
(builtinType): object
discriminatorValue: ShippingMethodDoesNotMatchCart
(package): "Error"
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - ShippingMethodDoesNotMatchCart
    required: true