#%RAML 1.0 DataType
(builtinType): object
type: ErrorObject
displayName: ShippingMethodDoesNotMatchCartError
discriminator: code
discriminatorValue: ShippingMethodDoesNotMatchCart
properties:
  code:
    type: string
    (builtinType): string
    enum:
    - ShippingMethodDoesNotMatchCart
    required: true
  message:
    type: string
    (builtinType): string
    required: true