#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: VariantValues
properties:
  attributes:
    type: array
    items:
      type: Attribute
    (builtinType): array
    required: true
  prices:
    type: array
    items:
      type: PriceDraft
    (builtinType): array
    required: true
  sku:
    type: string
    (builtinType): string
    required: false