#%RAML 1.0 DataType
(builtinType): object
type: LoggedResource
displayName: CustomObject
properties:
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  container:
    type: string
    (builtinType): string
    description: |-
      A namespace to group custom objects.
    required: true
  value:
    type: any
    (builtinType): any
    required: true
  key:
    type: string
    (builtinType): string
    required: true