#%RAML 1.0 DataType
type: object
(originalType): Reference
displayName: CustomObjectReference

discriminatorValue: key-value-document
properties:
  typeId:
    required: true
    type: ReferenceTypeId
  id:
    required: true
    type: string
  obj:
    required: false
    type: CustomObject