#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: CustomObjectReference
discriminator: typeId
discriminatorValue: key-value-document
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - key-value-document
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: CustomObject
    (builtinType): object
    required: false