#%RAML 1.0 DataType
displayName: CustomObjectReference
type: Reference
(builtinType): object
discriminatorValue: key-value-document
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - key-value-document
    required: true
  obj:
    type: CustomObject
    (builtinType): object
    required: false