#%RAML 1.0 DataType
displayName: ZoneSetDescriptionAction
type: ZoneUpdateAction
(builtinType): object
discriminatorValue: setDescription
examples:
  postman: !include ../../examples/Zone/ZoneSetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: string
    (builtinType): string
    required: false