#%RAML 1.0 DataType
(builtinType): object
type: ZoneUpdateAction
displayName: ZoneRemoveLocationAction
discriminator: action
discriminatorValue: removeLocation
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLocation
    required: true
  location:
    type: Location
    (builtinType): object
    required: true