#%RAML 1.0 DataType
displayName: ZoneRemoveLocationAction
type: ZoneUpdateAction
(builtinType): object
discriminatorValue: removeLocation
examples:
  postman: !include ../../examples/Zone/ZoneRemoveLocationAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLocation
    required: true
  location:
    type: Location
    (builtinType): object
    required: true