#%RAML 1.0 DataType
displayName: ZoneResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: zone
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - zone
    required: false