#%RAML 1.0 DataType
type: object
(originalType): LoggedResource
displayName: Zone


properties:
  createdAt:
    format: rfc3339
    type: datetime
  lastModifiedAt:
    format: rfc3339
    type: datetime
  id:
    description: |-
      The unique ID of the zone.
    type: string
  version:
    description: |-
      The current version of the zone.
    format: int64
    type: number
  createdBy:
    type: CreatedBy
  lastModifiedBy:
    type: LastModifiedBy
  name:
    type: string
  description:
    type: string
  locations:
    type: array
    items:
      type: Location
  key:
    description: |-
      User-specific unique identifier for a zone.
      Must be unique across a project.
      The field can be reset using the Set Key UpdateAction.
    type: string