#%RAML 1.0 DataType
displayName: ZoneAddLocationAction
type: ZoneUpdateAction
(builtinType): object
discriminatorValue: addLocation
examples:
  postman: !include ../../examples/Zone/ZoneAddLocationAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addLocation
    required: true
  location:
    type: Location
    (builtinType): object
    required: true