#%RAML 1.0 DataType
displayName: ZoneUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- ZoneAddLocationAction
- ZoneChangeNameAction
- ZoneRemoveLocationAction
- ZoneSetDescriptionAction
- ZoneSetKeyAction
properties:
  action:
    type: string
    (builtinType): string
    required: true