#%RAML 1.0 DataType
(builtinType): object
type: ZoneUpdateAction
displayName: ZoneAddLocationAction
discriminator: action
discriminatorValue: addLocation
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addLocation
    required: true
  location:
    type: Location
    (builtinType): object
    required: true