#%RAML 1.0 DataType
displayName: ZoneReference
type: Reference
(builtinType): object
discriminatorValue: zone
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - zone
    required: true
  obj:
    type: Zone
    (builtinType): object
    required: false