#%RAML 1.0 DataType
displayName: Zone
type: LoggedResource
(builtinType): object
properties:
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the zone.
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The current version of the zone.
    required: true
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  description:
    type: string
    (builtinType): string
    required: false
  locations:
    type: array
    items:
      type: Location
    (builtinType): array
    required: true
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for a zone.
               Must be unique across a project.
               The field can be reset using the Set Key UpdateAction.
    required: false