#%RAML 1.0 DataType
displayName: ZoneChangeNameAction
type: ZoneUpdateAction
(builtinType): object
discriminatorValue: changeName
examples:
  postman: !include ../../examples/Zone/ZoneChangeNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: string
    (builtinType): string
    required: true