#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ZoneReference
discriminator: typeId
discriminatorValue: zone
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - zone
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Zone
    (builtinType): object
    required: false