#%RAML 1.0 DataType
(builtinType): object
type: ZoneUpdateAction
displayName: ZoneSetDescriptionAction
discriminator: action
discriminatorValue: setDescription
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: string
    (builtinType): string
    required: false