#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ZoneDraft


properties:
  name:
    type: string
  description:
    type: string
  locations:
    type: array
    items:
      type: Location
  key:
    description: |-
      User-specific unique identifier for a zone.
      Must be unique across a project.
      The field can be reset using the Set Key UpdateAction.
    type: string