#%RAML 1.0 DataType
displayName: MyShoppingList
type: LoggedResource
(builtinType): object
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-me-shoppingLists#my-shopping-lists"
(updateType): "MyShoppingListUpdate"
(actionType): "MyShoppingListUpdateAction"
properties:
  id:
    type: string
    (builtinType): string
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  customer:
    type: CustomerReference
    (builtinType): object
    required: false
  deleteDaysAfterLastModification:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  key:
    type: string
    (builtinType): string
    required: false
  lineItems:
    type: array
    items:
      type: ShoppingListLineItem
    (builtinType): array
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: false
  textLineItems:
    type: array
    items:
      type: TextLineItem
    (builtinType): array
    required: false
  anonymousId:
    type: string
    (builtinType): string
    required: false