#%RAML 1.0 DataType
displayName: ShoppingListRemoveLineItemAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: removeLineItem
examples:
  postman: !include ../../examples/ShoppingList/ShoppingListRemoveLineItemAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLineItem
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: false