#%RAML 1.0 DataType
displayName: ShoppingListResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: shopping-list
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shopping-lists.html#shopping-list"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - shopping-list
    required: false