#%RAML 1.0 DataType
displayName: ShoppingListSetAnonymousIdAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setAnonymousId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAnonymousId
    required: true
  anonymousId:
    type: string
    (builtinType): string
    required: false