#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ShoppingListReference
discriminator: typeId
discriminatorValue: shopping-list
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - shopping-list
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: ShoppingList
    (builtinType): object
    required: false