#%RAML 1.0 DataType
displayName: ShoppingListLineItem
type: object
(builtinType): object
properties:
  addedAt:
    type: datetime
    (builtinType): datetime
    required: true
  quantity:
    type: number
    (builtinType): number
    required: true
  productId:
    type: string
    (builtinType): string
    required: true
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  variant:
    type: ProductVariant
    (builtinType): object
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  id:
    type: string
    (builtinType): string
    required: true
  deactivatedAt:
    type: datetime
    (builtinType): datetime
    required: false
  productSlug:
    type: LocalizedString
    (builtinType): object
    required: false
  productType:
    type: ProductTypeReference
    (builtinType): object
    required: true