#%RAML 1.0 DataType
displayName: ShoppingListChangeLineItemQuantityAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeLineItemQuantity
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLineItemQuantity
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true