#%RAML 1.0 DataType
displayName: ShoppingListAddTextLineItemAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: addTextLineItem
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shoppingLists.html#add-textlineitem"
examples:
  postman: !include ../../examples/ShoppingList/ShoppingListAddTextLineItemAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTextLineItem
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  addedAt:
    type: datetime
    (builtinType): datetime
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false