#%RAML 1.0 DataType
displayName: ShoppingListChangeTextLineItemNameAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeTextLineItemName
examples:
  postman: !include ../../examples/ShoppingList/ShoppingListChangeTextLineItemNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTextLineItemName
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true