#%RAML 1.0 DataType
displayName: ShoppingListSetTextLineItemDescriptionAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setTextLineItemDescription
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTextLineItemDescription
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false