#%RAML 1.0 DataType
displayName: ShoppingListSetCustomerAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setCustomer
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-customer"
examples:
  postman:
    strict: true
    value: !include ../../examples/ShoppingList/ShoppingListSetCustomerAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomer
    required: true
  customer:
    type: CustomerResourceIdentifier
    (builtinType): object
    required: false