#%RAML 1.0 DataType
displayName: ShoppingListSetTextLineItemCustomTypeAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setTextLineItemCustomType
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-textlineitem-custom-type"
examples:
  postman: !include ../../examples/ShoppingList/ShoppingListSetTextLineItemCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTextLineItemCustomType
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false