#%RAML 1.0 DataType
displayName: ShoppingListChangeLineItemsOrderAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeLineItemsOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLineItemsOrder
    required: true
  lineItemOrder:
    type: array
    items:
      type: string
    (builtinType): array
    required: true