#%RAML 1.0 DataType
displayName: ShoppingListSetTextLineItemCustomTypeAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setTextLineItemCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTextLineItemCustomType
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false