#%RAML 1.0 DataType
displayName: ShoppingListChangeNameAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true