#%RAML 1.0 DataType
displayName: ShoppingListUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- ShoppingListAddLineItemAction
- ShoppingListAddTextLineItemAction
- ShoppingListChangeLineItemQuantityAction
- ShoppingListChangeLineItemsOrderAction
- ShoppingListChangeNameAction
- ShoppingListChangeTextLineItemNameAction
- ShoppingListChangeTextLineItemQuantityAction
- ShoppingListChangeTextLineItemsOrderAction
- ShoppingListRemoveLineItemAction
- ShoppingListRemoveTextLineItemAction
- ShoppingListSetAnonymousIdAction
- ShoppingListSetCustomFieldAction
- ShoppingListSetCustomTypeAction
- ShoppingListSetCustomerAction
- ShoppingListSetDeleteDaysAfterLastModificationAction
- ShoppingListSetDescriptionAction
- ShoppingListSetKeyAction
- ShoppingListSetLineItemCustomFieldAction
- ShoppingListSetLineItemCustomTypeAction
- ShoppingListSetSlugAction
- ShoppingListSetTextLineItemCustomFieldAction
- ShoppingListSetTextLineItemCustomTypeAction
- ShoppingListSetTextLineItemDescriptionAction
(package): "ShoppingList"
properties:
  action:
    type: string
    (builtinType): string
    required: true