#%RAML 1.0 DataType
displayName: ShoppingListSetTextLineItemCustomFieldAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setTextLineItemCustomField
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-textlineitem-customfield"
examples:
  postman:
    strict: true
    value: !include ../../examples/ShoppingList/ShoppingListSetTextLineItemCustomFieldAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTextLineItemCustomField
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false