#%RAML 1.0 DataType
displayName: ShoppingListChangeNameAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeName
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shoppingLists.html#change-name"
examples:
  postman: !include ../../examples/ShoppingList/ShoppingListChangeNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true