#%RAML 1.0 DataType
(builtinType): object
type: ShoppingListUpdateAction
displayName: ShoppingListAddLineItemAction
discriminator: action
discriminatorValue: addLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addLineItem
    required: true
  addedAt:
    type: datetime
    (builtinType): datetime
    required: false
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: false
  productId:
    type: string
    (builtinType): string
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false