#%RAML 1.0 DataType
(builtinType): object
type: ShoppingListUpdateAction
displayName: ShoppingListRemoveTextLineItemAction
discriminator: action
discriminatorValue: removeTextLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeTextLineItem
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: false
  textLineItemId:
    type: string
    (builtinType): string
    required: true