#%RAML 1.0 DataType
displayName: ShoppingListSetSlugAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setSlug
examples:
  postman: !include ../../examples/ShoppingList/ShoppingListSetSlugAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSlug
    required: true
  slug:
    type: LocalizedString
    (builtinType): object
    required: false