#%RAML 1.0 DataType
displayName: ShoppingListAddTextLineItemAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: addTextLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTextLineItem
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: false
  addedAt:
    type: datetime
    (builtinType): datetime
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false