#%RAML 1.0 DataType
displayName: ShoppingListSetAnonymousIdAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setAnonymousId
(package): "ShoppingList"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shoppingLists.html#set-anonymousid"
examples:
  postman:
    strict: true
    value: !include ../../examples/ShoppingList/ShoppingListSetAnonymousIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAnonymousId
    required: true
  anonymousId:
    type: string
    (builtinType): string
    description: |-
      Anonymous ID of the anonymous customer that this shopping list belongs to.
      If this field is not set any existing `anonymousId` is removed.
    required: false