#%RAML 1.0 DataType
displayName: ShoppingListChangeTextLineItemQuantityAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: changeTextLineItemQuantity
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTextLineItemQuantity
    required: true
  textLineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true