#%RAML 1.0 DataType
displayName: ShoppingListLineItemDraft
type: object
(builtinType): object
properties:
  addedAt:
    type: datetime
    (builtinType): datetime
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  productId:
    type: string
    (builtinType): string
    required: false
  quantity:
    type: integer
    (builtinType): integer
    required: false
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false