#%RAML 1.0 DataType
displayName: ShoppingListSetDescriptionAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setDescription
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false