#%RAML 1.0 DataType
type: object
(originalType): ShoppingListUpdateAction
displayName: ShoppingListSetDeleteDaysAfterLastModificationAction
# discriminator: action
# discriminatorValue: setDeleteDaysAfterLastModification
properties:
  action:
    default: setDeleteDaysAfterLastModification
    required: true
    type: string
  deleteDaysAfterLastModification:
    required: false
    format: int64
    type: number