#%RAML 1.0 DataType
(builtinType): object
type: ShoppingListUpdateAction
displayName: ShoppingListRemoveLineItemAction
discriminator: action
discriminatorValue: removeLineItem
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeLineItem
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: false
  lineItemId:
    type: string
    (builtinType): string
    required: true