#%RAML 1.0 DataType
type: object
(originalType): ShoppingListUpdateAction
displayName: ShoppingListChangeTextLineItemsOrderAction
# discriminator: action
# discriminatorValue: changeTextLineItemsOrder
properties:
  action:
    default: changeTextLineItemsOrder
    required: true
    type: string
  textLineItemOrder:
    required: true
    type: array
    items:
      type: string