#%RAML 1.0 DataType
(builtinType): object
type: ShoppingListUpdateAction
displayName: ShoppingListChangeLineItemQuantityAction
discriminator: action
discriminatorValue: changeLineItemQuantity
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLineItemQuantity
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true