#%RAML 1.0 DataType
type: object
(originalType): ShoppingListUpdateAction
displayName: ShoppingListSetLineItemCustomTypeAction
# discriminator: action
# discriminatorValue: setLineItemCustomType
properties:
  action:
    default: setLineItemCustomType
    required: true
    type: string
  lineItemId:
    required: true
    type: string
  fields:
    required: false
    type: FieldContainer
  type:
    required: false
    type: TypeResourceIdentifier