#%RAML 1.0 DataType
displayName: ShoppingListSetCustomerAction
type: ShoppingListUpdateAction
(builtinType): object
discriminatorValue: setCustomer
examples:
  postman: !include ../../examples/ShoppingList/ShoppingListSetCustomerAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomer
    required: true
  customer:
    type: CustomerResourceIdentifier
    (builtinType): object
    required: false