#%RAML 1.0 DataType
displayName: CartScoreTier
type: ShippingRatePriceTier
(builtinType): object
discriminatorValue: CartScore
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartScore
    required: true
  score:
    type: number
    (builtinType): number
    required: true
  price:
    type: Money
    (builtinType): object
    required: false
  priceFunction:
    type: PriceFunction
    (builtinType): object
    required: false
  isMatching:
    type: boolean
    (builtinType): boolean
    required: false