#%RAML 1.0 DataType
displayName: CartValueTier
type: ShippingRatePriceTier
(builtinType): object
discriminatorValue: CartValue
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartValue
    required: true
  minimumCentAmount:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  price:
    type: Money
    (builtinType): object
    required: true
  isMatching:
    type: boolean
    (builtinType): boolean
    required: false