#%RAML 1.0 DataType
type: ShippingRatePriceTier
displayName: CartValueTier

discriminatorValue: CartValue
properties:
   minimumCentAmount:
      format: int64
      type: integer
   price:
      type: Money
   isMatching:
      type: boolean