#%RAML 1.0 DataType
type: object
(originalType): ShippingRatePriceTier
displayName: CartClassificationTier

discriminatorValue: CartClassification
properties:
  type:
    required: true
    type: ShippingRateTierType
  price:
    required: true
    type: Money
  isMatching:
    required: false
    type: boolean
  value:
    required: true
    type: string