#%RAML 1.0 DataType
(builtinType): object
type: ShippingRatePriceTier
displayName: CartClassificationTier
discriminator: type
discriminatorValue: CartClassification
properties:
  type:
    type: ShippingRateTierType
    (builtinType): string
    enum:
    - CartClassification
    required: true
  price:
    type: Money
    (builtinType): object
    required: true
  isMatching:
    type: boolean
    (builtinType): boolean
    required: false
  value:
    type: string
    (builtinType): string
    required: true