#%RAML 1.0 DataType
type: object
(originalType): object
displayName: PriceFunction


properties:
  function:
    required: true
    type: string
  currencyCode:
    required: true
    description: |-
      The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    type: CurrencyCode