#%RAML 1.0 DataType
displayName: PriceFunction
type: object
(builtinType): object
(package): "ShippingMethod"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shippingMethods.html#pricefunction"
properties:
  currencyCode:
    type: CurrencyCode
    (builtinType): string
    description: |-
      The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    required: true
  function:
    type: string
    (builtinType): string
    required: true