#%RAML 1.0 DataType
displayName: ShippingMethodSetKeyAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: setKey
examples:
  postman: !include ../../examples/ShippingMethod/ShippingMethodSetKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false