#%RAML 1.0 DataType
displayName: ShippingMethodChangeTaxCategoryAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: changeTaxCategory
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxCategory
    required: true
  taxCategory:
    type: TaxCategoryResourceIdentifier
    (builtinType): object
    required: true