#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodAddZoneAction
# discriminator: action
# discriminatorValue: addZone
properties:
  action:
    default: addZone
    required: true
    type: string
  zone:
    required: true
    type: ZoneResourceIdentifier