#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodSetDescriptionAction

discriminatorValue: setDescription
properties:
  action:
    required: true
    type: string
  description:
    required: false
    type: string