#%RAML 1.0 DataType
displayName: ShippingMethodSetPredicateAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: setPredicate
examples:
  postman: !include ../../examples/ShippingMethod/ShippingMethodSetPredicateAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setPredicate
    required: true
  predicate:
    type: string
    (builtinType): string
    required: false