#%RAML 1.0 DataType
displayName: ShippingMethodReference
type: Reference
(builtinType): object
discriminatorValue: shipping-method
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - shipping-method
    required: true
  obj:
    type: ShippingMethod
    (builtinType): object
    required: false