#%RAML 1.0 DataType
displayName: ShippingMethodAddShippingRateAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: addShippingRate
(package): "ShippingMethod"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shippingMethods.html#add-shippingrate"
examples:
  postman:
    strict: true
    value: !include ../../examples/ShippingMethod/ShippingMethodAddShippingRateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShippingRate
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    required: true