#%RAML 1.0 DataType
(builtinType): object
type: ShippingMethodUpdateAction
displayName: ShippingMethodAddShippingRateAction
discriminator: action
discriminatorValue: addShippingRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShippingRate
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true