#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodChangeTaxCategoryAction
# discriminator: action
# discriminatorValue: changeTaxCategory
properties:
  action:
    default: changeTaxCategory
    required: true
    type: string
  taxCategory:
    required: true
    type: TaxCategoryResourceIdentifier