#%RAML 1.0 DataType
displayName: ShippingRateDraft
type: object
(builtinType): object
properties:
  price:
    type: Money
    (builtinType): object
    required: true
  freeAbove:
    type: Money
    (builtinType): object
    description: |-
      The shipping is free if the order total (the sum of line item prices) exceeds the freeAbove value.
      Note: `freeAbove` applies before any Cart or Product discounts, and can cause discounts to apply in invalid scenarios.
      Use a Cart Discount to set the shipping price to 0 to avoid providing free shipping in invalid discount scenarios.
    required: false
  tiers:
    type: array
    items:
      type: ShippingRatePriceTier
    (builtinType): array
    description: |-
      A list of shipping rate price tiers.
    required: false