#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodSetPredicateAction

discriminatorValue: setPredicate
properties:
  action:
    required: true
    type: string
  predicate:
    required: false
    type: string