#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodChangeIsDefaultAction

discriminatorValue: changeIsDefault
properties:
  action:
    type: string
  isDefault:
    type: boolean