#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ShippingMethodReference
discriminator: typeId
discriminatorValue: shipping-method
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - shipping-method
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: ShippingMethod
    (builtinType): object
    required: false