#%RAML 1.0 DataType
(builtinType): object
type: ShippingMethodUpdateAction
displayName: ShippingMethodAddZoneAction
discriminator: action
discriminatorValue: addZone
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addZone
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true