#%RAML 1.0 DataType
displayName: ShippingMethodChangeTaxCategoryAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: changeTaxCategory
(package): "ShippingMethod"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shippingMethods.html#change-taxcategory"
examples:
  postman: !include ../../examples/ShippingMethod/ShippingMethodChangeTaxCategoryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxCategory
    required: true
  taxCategory:
    type: TaxCategoryResourceIdentifier
    (builtinType): object
    required: true