#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodChangeIsDefaultAction
# discriminator: action
# discriminatorValue: changeIsDefault
properties:
  action:
    default: changeIsDefault
    required: true
    type: string
  isDefault:
    required: true
    type: boolean