#%RAML 1.0 DataType
(builtinType): object
type: ShippingMethodUpdateAction
displayName: ShippingMethodRemoveZoneAction
discriminator: action
discriminatorValue: removeZone
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeZone
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true