#%RAML 1.0 DataType
(builtinType): object
type: LoggedResource
displayName: ShippingMethod
properties:
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the shipping method.
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The current version of the shipping method.
    required: true
  createdBy:
    type: CreatedBy
    (builtinType): object
    required: false
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    required: false
  zoneRates:
    type: array
    items:
      type: ZoneRate
    (builtinType): array
    required: true
  predicate:
    type: string
    (builtinType): string
    description: |-
      A Cart predicate which can be used to more precisely select a shipping method for a cart.
    required: false
  isDefault:
    type: boolean
    (builtinType): boolean
    description: |-
      One shipping method in a project can be default.
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  description:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for the shipping method.
    required: false
  taxCategory:
    type: TaxCategoryReference
    (builtinType): object
    required: true