#%RAML 1.0 DataType
displayName: ShippingMethodChangeIsDefaultAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: changeIsDefault
examples:
  postman: !include ../../examples/ShippingMethod/ShippingMethodChangeIsDefaultAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeIsDefault
    required: true
  isDefault:
    type: boolean
    (builtinType): boolean
    required: true