#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodRemoveZoneAction
# discriminator: action
# discriminatorValue: removeZone
properties:
  action:
    default: removeZone
    required: true
    type: string
  zone:
    required: true
    type: ZoneResourceIdentifier