#%RAML 1.0 DataType
(builtinType): object
type: ShippingMethodUpdateAction
displayName: ShippingMethodRemoveShippingRateAction
discriminator: action
discriminatorValue: removeShippingRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeShippingRate
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true