#%RAML 1.0 DataType
type: object
(originalType): ShippingMethodUpdateAction
displayName: ShippingMethodAddShippingRateAction

discriminatorValue: addShippingRate
properties:
  action:
    required: true
    type: string
  shippingRate:
    required: true
    type: ShippingRateDraft
  zone:
    required: true
    type: ZoneResourceIdentifier