#%RAML 1.0 DataType
displayName: ShippingMethodRemoveShippingRateAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: removeShippingRate
examples:
  postman: !include ../../examples/ShippingMethod/ShippingMethodRemoveShippingRateAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeShippingRate
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    required: true