#%RAML 1.0 DataType
displayName: ShippingMethodAddZoneAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: addZone
(package): "ShippingMethod"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shippingMethods.html#add-zone"
examples:
  postman:
    strict: true
    value: !include ../../examples/ShippingMethod/ShippingMethodAddZoneAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addZone
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true