#%RAML 1.0 DataType
displayName: ShippingMethodDraft
type: object
(builtinType): object
(package): "ShippingMethod"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shippingMethods.html#shippingmethoddraft"
properties:
  key:
    type: string
    (builtinType): string
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  description:
    type: string
    (builtinType): string
    required: false
  taxCategory:
    type: TaxCategoryResourceIdentifier
    (builtinType): object
    required: true
  zoneRates:
    type: array
    items:
      type: ZoneRateDraft
    (builtinType): array
    required: true
  isDefault:
    type: boolean
    (builtinType): boolean
    description: |-
      If `true` the shipping method will be the default one in a project.
    required: true
  predicate:
    type: string
    (builtinType): string
    description: |-
      A Cart predicate which can be used to more precisely select a shipping method for a cart.
    required: false