#%RAML 1.0 DataType
(builtinType): object
type: ShippingMethodUpdateAction
displayName: ShippingMethodSetKeyAction
discriminator: action
discriminatorValue: setKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false