#%RAML 1.0 DataType
displayName: ShippingMethodResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: shipping-method
(package): "ShippingMethod"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shippingMethods.html#shippingmethod"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - shipping-method
    required: false