#%RAML 1.0 DataType
displayName: ShippingMethodRemoveShippingRateAction
type: ShippingMethodUpdateAction
(builtinType): object
discriminatorValue: removeShippingRate
(package): "ShippingMethod"
(docs-uri): "https://docs.commercetools.com/http-api-projects-shippingMethods.html#remove-shippingrate"
examples:
  postman: !include ../../examples/ShippingMethod/ShippingMethodRemoveShippingRateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeShippingRate
    required: true
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true
  shippingRate:
    type: ShippingRateDraft
    (builtinType): object
    required: true