#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ShippingMethodUpdate
# 
# 
properties:
  actions:
    required: true
    type: array
    items:
      type: ShippingMethodUpdateAction
  version:
    required: true
    format: int64
    type: number