#%RAML 1.0 DataType
displayName: ZoneRateDraft
type: object
(builtinType): object
properties:
  zone:
    type: ZoneResourceIdentifier
    (builtinType): object
    required: true
  shippingRates:
    type: array
    items:
      type: ShippingRateDraft
    (builtinType): array
    description: |-
      The array must not contain two shipping rates with the same currency.
    required: true