#%RAML 1.0 DataType
displayName: StateChangeTypeAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: changeType
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#change-state-type"
examples:
  postman:
    strict: true
    value: !include ../../examples/State/StateChangeTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeType
    required: true
  type:
    type: StateTypeEnum
    (builtinType): string
    required: true