#%RAML 1.0 DataType
displayName: StateSetTransitionsAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: setTransitions
examples:
  postman: !include ../../examples/State/StateSetTransitionsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTransitions
    required: true
  transitions:
    type: array
    items:
      type: StateResourceIdentifier
    (builtinType): array
    required: false