#%RAML 1.0 DataType
displayName: StateRemoveRolesAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: removeRoles
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#remove-state-roles"
examples:
  postman: !include ../../examples/State/StateRemoveRolesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true