#%RAML 1.0 DataType
(builtinType): object
type: ResourceIdentifier
displayName: StateResourceIdentifier
discriminator: typeId
discriminatorValue: state
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - state
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false