#%RAML 1.0 DataType
displayName: StateChangeTypeAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: changeType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeType
    required: true
  type:
    type: StateTypeEnum
    (builtinType): string
    required: true