#%RAML 1.0 DataType
displayName: StateChangeInitialAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: changeInitial
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#change-initial-state"
examples:
  postman:
    strict: true
    value: !include ../../examples/State/StateChangeInitialAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeInitial
    required: true
  initial:
    type: boolean
    (builtinType): boolean
    required: true