#%RAML 1.0 DataType
displayName: StateUpdate
type: object
(builtinType): object
(package): "State"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: StateUpdateAction
    (builtinType): array
    required: true