#%RAML 1.0 DataType
type: object
(originalType): StateUpdateAction
displayName: StateSetRolesAction

discriminatorValue: setRoles
properties:
  action:
    type: string
  roles:
    type: array
    items:
      type: StateRoleEnum