#%RAML 1.0 DataType
displayName: StateUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- StateAddRolesAction
- StateChangeInitialAction
- StateChangeKeyAction
- StateChangeTypeAction
- StateRemoveRolesAction
- StateSetDescriptionAction
- StateSetNameAction
- StateSetRolesAction
- StateSetTransitionsAction
(package): "State"
properties:
  action:
    type: string
    (builtinType): string
    required: true