#%RAML 1.0 DataType
displayName: StateSetRolesAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: setRoles
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#set-state-roles"
examples:
  postman: !include ../../examples/State/StateSetRolesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true