#%RAML 1.0 DataType
(builtinType): object
type: StateUpdateAction
displayName: StateChangeInitialAction
discriminator: action
discriminatorValue: changeInitial
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeInitial
    required: true
  initial:
    type: boolean
    (builtinType): boolean
    required: true