#%RAML 1.0 DataType
type: object
(originalType): LoggedResource
displayName: State


properties:
  createdAt:
    format: rfc3339
    type: datetime
  lastModifiedAt:
    format: rfc3339
    type: datetime
  id:
    type: string
  version:
    format: int64
    type: number
  createdBy:
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    type: CreatedBy
  lastModifiedBy:
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    type: LastModifiedBy
  initial:
    description: |-
      A state can be declared as an initial state for any state machine.
      When a workflow starts, this first state must be an `initial` state.
    type: boolean
  roles:
    type: array
    items:
      type: StateRoleEnum
  builtIn:
    description: |-
      Builtin states are integral parts of the project that cannot be deleted nor the key can be changed.
    type: boolean
  description:
    description: |-
      A human-readable description of the state.
    type: LocalizedString
  transitions:
    description: |-
      Transitions are a way to describe possible transformations of the current state to other states of the same `type` (e.g.: _Initial_ -> _Shipped_).
      When performing a `transitionState` update action and `transitions` is set, the currently referenced state must have a transition to the new state.
      If `transitions` is an empty list, it means the current state is a final state and no further transitions are allowed.
      If `transitions` is not set, the validation is turned off.
      When performing a `transitionState` update action, any other state of the same `type` can be transitioned to.
    type: array
    items:
      type: StateReference
  type:
    type: StateTypeEnum
  name:
    description: |-
      A human-readable name of the state.
    type: LocalizedString
  key:
    description: |-
      A unique identifier for the state.
    type: string