#%RAML 1.0 DataType
(builtinType): object
type: StateUpdateAction
displayName: StateRemoveRolesAction
discriminator: action
discriminatorValue: removeRoles
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true