#%RAML 1.0 DataType
displayName: StateDraft
type: object
(builtinType): object
properties:
  initial:
    type: boolean
    (builtinType): boolean
    required: false
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  transitions:
    type: array
    items:
      type: StateResourceIdentifier
    (builtinType): array
    required: false
  type:
    type: StateTypeEnum
    (builtinType): string
    required: true
  key:
    type: string
    (builtinType): string
    required: true