#%RAML 1.0 DataType
(builtinType): object
type: StateUpdateAction
displayName: StateChangeKeyAction
discriminator: action
discriminatorValue: changeKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeKey
    required: true
  key:
    type: string
    (builtinType): string
    required: true