#%RAML 1.0 DataType
displayName: StatePagedQueryResponse
type: object
(builtinType): object
properties:
  limit:
    format: int64
    type: number
    (builtinType): number
    required: true
  count:
    format: int64
    type: number
    (builtinType): number
    required: true
  total:
    format: int64
    type: number
    (builtinType): number
    required: false
  offset:
    format: int64
    type: number
    (builtinType): number
    required: true
  results:
    type: array
    items:
      type: State
    (builtinType): array
    required: true