#%RAML 1.0 DataType
displayName: StateAddRolesAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: addRoles
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#add-state-roles"
examples:
  postman:
    strict: true
    value: !include ../../examples/State/StateAddRolesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true