#%RAML 1.0 DataType
(builtinType): object
type: StateUpdateAction
displayName: StateSetTransitionsAction
discriminator: action
discriminatorValue: setTransitions
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTransitions
    required: true
  transitions:
    type: array
    items:
      type: StateResourceIdentifier
    (builtinType): array
    required: false