#%RAML 1.0 DataType
type: object
(originalType): StateUpdateAction
displayName: StateChangeTypeAction
# discriminator: action
# discriminatorValue: changeType
properties:
  action:
    default: changeType
    required: true
    type: string
  type:
    required: true
    type: StateTypeEnum