#%RAML 1.0 DataType
(builtinType): object
type: StateUpdateAction
displayName: StateSetNameAction
discriminator: action
discriminatorValue: setName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true