#%RAML 1.0 DataType
displayName: StateChangeKeyAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: changeKey
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#change-state-key"
examples:
  postman:
    strict: true
    value: !include ../../examples/State/StateChangeKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeKey
    required: true
  key:
    type: string
    (builtinType): string
    required: true