#%RAML 1.0 DataType
displayName: StateSetDescriptionAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: setDescription
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#set-state-description"
examples:
  postman: !include ../../examples/State/StateSetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: true