#%RAML 1.0 DataType
displayName: StateChangeInitialAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: changeInitial
examples:
  postman: !include ../../examples/State/StateChangeInitialAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeInitial
    required: true
  initial:
    type: boolean
    (builtinType): boolean
    required: true