#%RAML 1.0 DataType
type: object
(originalType): StateUpdateAction
displayName: StateSetNameAction
# discriminator: action
# discriminatorValue: setName
properties:
  action:
    default: setName
    required: true
    type: string
  name:
    required: true
    type: LocalizedString