#%RAML 1.0 DataType
displayName: StateSetNameAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: setName
(package): "State"
(docs-uri): "https://docs.commercetools.com/http-api-projects-states.html#set-state-name"
examples:
  postman: !include ../../examples/State/StateSetNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true