#%RAML 1.0 DataType
displayName: StateAddRolesAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: addRoles
examples:
  postman: !include ../../examples/State/StateAddRolesAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true