#%RAML 1.0 DataType
(builtinType): object
type: StateUpdateAction
displayName: StateSetRolesAction
discriminator: action
discriminatorValue: setRoles
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true