#%RAML 1.0 DataType
displayName: StateRemoveRolesAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: removeRoles
examples:
  postman: !include ../../examples/State/StateRemoveRolesAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true