#%RAML 1.0 DataType
(builtinType): object
type: StateUpdateAction
displayName: StateAddRolesAction
discriminator: action
discriminatorValue: addRoles
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addRoles
    required: true
  roles:
    type: array
    items:
      type: StateRoleEnum
    (builtinType): array
    required: true