#%RAML 1.0 DataType
displayName: StateChangeKeyAction
type: StateUpdateAction
(builtinType): object
discriminatorValue: changeKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeKey
    required: true
  key:
    type: string
    (builtinType): string
    required: true