#%RAML 1.0 DataType
displayName: ProductVariantDraftImport
type: object
(builtinType): object
properties:
  sku:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false
  prices:
    type: array
    items:
      type: PriceDraftImport
    (builtinType): array
    required: false
  attributes:
    type: array
    items:
      type: Attribute
    (builtinType): array
    required: false
  images:
    type: array
    items:
      type: Image
    (builtinType): array
    required: false
  assets:
    type: array
    items:
      type: Asset
    (builtinType): array
    required: false
