#%RAML 1.0 DataType
displayName: GraphQLErrorLocation
type: object
(builtinType): object
(package): "GraphQL"
properties:
  line:
    type: integer
    (builtinType): integer
    required: true
  column:
    type: integer
    (builtinType): integer
    required: true