#%RAML 1.0 DataType
displayName: ProductDiscountReference
type: Reference
(builtinType): object
discriminatorValue: product-discount
(package): "ProductDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productDiscounts.html#productdiscount"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-discount
    required: true
  obj:
    type: ProductDiscount
    (builtinType): object
    required: false