#%RAML 1.0 DataType
type: object
(originalType): LoggedResource
displayName: ProductDiscount


properties:
  createdAt:
    format: rfc3339
    type: datetime
  lastModifiedAt:
    format: rfc3339
    type: datetime
  id:
    description: |-
      The unique ID of the product discount
    type: string
  version:
    description: |-
      The current version of the product discount.
    format: int64
    type: number
  createdBy:
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    type: CreatedBy
  lastModifiedBy:
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    type: LastModifiedBy
  references:
    description: |-
      The platform will generate this array from the predicate.
      It contains the references of all the resources that are addressed in the predicate.
    type: array
    items:
      type: Reference
  description:
    type: LocalizedString
  validFrom:
    description: |-
      The time from which the discount should be effective.
      Please take Eventual Consistency into account for calculated product discount values.
    format: rfc3339
    type: datetime
  isActive:
    description: |-
      Only active discount will be applied to product prices.
    type: boolean
  predicate:
    description: |-
      A valid ProductDiscount Predicate.
    type: string
  sortOrder:
    description: |-
      The string contains a number between 0 and 1.
      A discount with greater sortOrder is prioritized higher than a discount with lower sortOrder.
      A sortOrder must be unambiguous.
    type: string
  name:
    type: LocalizedString
  validUntil:
    description: |-
      The time from which the discount should be ineffective.
      Please take Eventual Consistency into account for calculated undiscounted values.
    format: rfc3339
    type: datetime
  value:
    type: ProductDiscountValue
  key:
    description: |-
      User-specific unique identifier for a product discount.
      Must be unique across a project.
    type: string