#%RAML 1.0 DataType
displayName: ProductDiscountResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: product-discount
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-discount
    required: false