#%RAML 1.0 DataType
displayName: ProductDiscount
type: LoggedResource
(builtinType): object
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the product discount
    (identifier): true
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The current version of the product discount.
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for a product discount.
      Must be unique across a project.
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  value:
    type: ProductDiscountValue
    (builtinType): object
    required: true
  predicate:
    type: string
    (builtinType): string
    description: |-
      A valid ProductDiscount Predicate.
    required: true
  sortOrder:
    type: string
    (builtinType): string
    description: |-
      The string contains a number between 0 and 1.
      A discount with greater sortOrder is prioritized higher than a discount with lower sortOrder.
      A sortOrder must be unambiguous.
    required: true
  isActive:
    type: boolean
    (builtinType): boolean
    description: |-
      Only active discount will be applied to product prices.
    required: true
  references:
    type: array
    items:
      type: Reference
    (builtinType): array
    description: |-
      The platform will generate this array from the predicate.
      It contains the references of all the resources that are addressed in the predicate.
    required: true
  validFrom:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      The time from which the discount should be effective.
      Please take Eventual Consistency into account for calculated product discount values.
    required: false
  validUntil:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      The time from which the discount should be ineffective.
      Please take Eventual Consistency into account for calculated undiscounted values.
    required: false