#%RAML 1.0 DataType
displayName: ProductDiscountSetValidFromAndUntilAction
type: ProductDiscountUpdateAction
(builtinType): object
discriminatorValue: setValidFromAndUntil
(package): "ProductDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productDiscounts.html#set-valid-from-and-until"
examples:
  postman: !include ../../examples/ProductDiscount/ProductDiscountSetValidFromAndUntilAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidFromAndUntil
    required: true
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false
  validUntil:
    type: datetime
    (builtinType): datetime
    required: false