#%RAML 1.0 DataType
displayName: ProductDiscountChangePredicateAction
type: ProductDiscountUpdateAction
(builtinType): object
discriminatorValue: changePredicate
(package): "ProductDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productDiscounts.html#change-predicate"
examples:
  postman:
    strict: true
    value: !include ../../examples/ProductDiscount/ProductDiscountChangePredicateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePredicate
    required: true
  predicate:
    type: string
    (builtinType): string
    description: |-
      A valid ProductDiscount Predicate.
    required: true