#%RAML 1.0 DataType
displayName: ProductDiscountSetValidFromAction
type: ProductDiscountUpdateAction
(builtinType): object
discriminatorValue: setValidFrom
examples:
  postman: !include ../../examples/ProductDiscount/ProductDiscountSetValidFromAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setValidFrom
    required: true
  validFrom:
    type: datetime
    (builtinType): datetime
    required: false