#%RAML 1.0 DataType
displayName: ProductDiscountUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- ProductDiscountChangeIsActiveAction
- ProductDiscountChangeNameAction
- ProductDiscountChangePredicateAction
- ProductDiscountChangeSortOrderAction
- ProductDiscountChangeValueAction
- ProductDiscountSetDescriptionAction
- ProductDiscountSetKeyAction
- ProductDiscountSetValidFromAction
- ProductDiscountSetValidFromAndUntilAction
- ProductDiscountSetValidUntilAction
properties:
  action:
    type: string
    (builtinType): string
    required: true