#%RAML 1.0 DataType
displayName: ProductDiscountValueAbsolute
type: ProductDiscountValue
(builtinType): object
discriminatorValue: absolute
(package): "ProductDiscount"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - absolute
    required: true
  money:
    type: array
    items:
      type: TypedMoney
    (builtinType): array
    required: true