#%RAML 1.0 DataType
displayName: ProductDiscountValue
type: object
(builtinType): object
discriminator: type
(oneOf):
- ProductDiscountValueAbsolute
- ProductDiscountValueExternal
- ProductDiscountValueRelative
(package): "ProductDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productDiscounts.html#productdiscountvalue"
properties:
  type:
    type: string
    (builtinType): string
    required: true