#%RAML 1.0 DataType
type: object
(originalType): ProductDiscountValue
displayName: ProductDiscountValueAbsolute

discriminatorValue: absolute
properties:
  type:
    type: string
  money:
    type: array
    items:
      type: TypedMoney