#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductDiscountDraft
# 
# 
properties:
  predicate:
    required: true
    description: |-
      A valid ProductDiscount Predicate.
    type: string
  sortOrder:
    required: true
    description: |-
      The string must contain a decimal number between 0 and 1.
      A discount with greater sortOrder is prioritized higher than a discount with lower sortOrder.
    type: string
  name:
    required: true
    type: LocalizedString
  validUntil:
    required: false
    description: |-
      The time from which the discount should be effective.
      Please take Eventual Consistency into account for calculated undiscounted values.
    format: rfc3339
    type: datetime
  description:
    required: false
    type: LocalizedString
  validFrom:
    required: false
    description: |-
      The time from which the discount should be effective.
      Please take Eventual Consistency into account for calculated product discount values.
    format: rfc3339
    type: datetime
  isActive:
    required: true
    description: |-
      If set to `true` the discount will be applied to product prices.
    type: boolean
  value:
    required: true
    type: ProductDiscountValueDraft
  key:
    required: false
    description: |-
      User-specific unique identifier for a product discount.
      Must be unique across a project.
      The field can be reset using the Set Key UpdateAction
    type: string