#%RAML 1.0 DataType
displayName: ProductDiscountValueDraft
type: object
(builtinType): object
discriminator: type
(oneOf):
- ProductDiscountValueAbsoluteDraft
- ProductDiscountValueExternalDraft
- ProductDiscountValueRelativeDraft
(package): "ProductDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productDiscounts.html#productdiscountvalue"
properties:
  type:
    type: string
    (builtinType): string
    required: true