#%RAML 1.0 DataType
displayName: ProductDiscountSetKeyAction
type: ProductDiscountUpdateAction
(builtinType): object
discriminatorValue: setKey
(package): "ProductDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productDiscounts.html#set-key"
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setKey
    required: true
  key:
    type: string
    (builtinType): string
    required: false