#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ProductDiscountMatchQuery
properties:
  productId:
    type: string
    (builtinType): string
    required: true
  price:
    type: QueryPrice
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: true
  variantId:
    format: int32
    type: number
    (builtinType): number
    required: true