#%RAML 1.0 DataType
displayName: ProductDiscountChangeSortOrderAction
type: ProductDiscountUpdateAction
(builtinType): object
discriminatorValue: changeSortOrder
(package): "ProductDiscount"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productDiscounts.html#change-sort-order"
examples:
  postman:
    strict: true
    value: !include ../../examples/ProductDiscount/ProductDiscountChangeSortOrderAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeSortOrder
    required: true
  sortOrder:
    type: string
    (builtinType): string
    required: true