#%RAML 1.0 DataType
displayName: ProductDiscountChangeValueAction
type: ProductDiscountUpdateAction
(builtinType): object
discriminatorValue: changeValue
examples:
  postman: !include ../../examples/ProductDiscount/ProductDiscountChangeValueAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeValue
    required: true
  value:
    type: ProductDiscountValueDraft
    (builtinType): object
    required: true