#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ProductDiscountUpdateAction
discriminator: action
(subTypes):
- ProductDiscountChangeIsActiveAction
- ProductDiscountChangeNameAction
- ProductDiscountChangePredicateAction
- ProductDiscountChangeSortOrderAction
- ProductDiscountChangeValueAction
- ProductDiscountSetDescriptionAction
- ProductDiscountSetKeyAction
- ProductDiscountSetValidFromAction
- ProductDiscountSetValidFromAndUntilAction
- ProductDiscountSetValidUntilAction
properties:
  action:
    type: string
    (builtinType): string
    required: true