#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ProductDiscountReference
discriminator: typeId
discriminatorValue: product-discount
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product-discount
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: ProductDiscount
    (builtinType): object
    required: false