#%RAML 1.0 DataType
displayName: ProductDiscountValueExternal
type: ProductDiscountValue
(builtinType): object
discriminatorValue: external
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - external
    required: true