#%RAML 1.0 DataType
displayName: ProductDiscountChangeIsActiveAction
type: ProductDiscountUpdateAction
(builtinType): object
discriminatorValue: changeIsActive
examples:
  postman: !include ../../examples/ProductDiscount/ProductDiscountChangeIsActiveAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeIsActive
    required: true
  isActive:
    type: boolean
    (builtinType): boolean
    required: true