#%RAML 1.0 DataType
(builtinType): object
type: ProductDiscountUpdateAction
displayName: ProductDiscountChangePredicateAction
discriminator: action
discriminatorValue: changePredicate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePredicate
    required: true
  predicate:
    type: string
    (builtinType): string
    required: true