#%RAML 1.0 DataType
(builtinType): object
type: ProductDiscountValue
displayName: ProductDiscountValueRelative
discriminator: type
discriminatorValue: relative
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - relative
    required: true
  permyriad:
    format: int64
    type: number
    (builtinType): number
    required: true