#%RAML 1.0
---
title: Commercetools Importer API
annotationTypes:
  resourceName:
    type: string
    allowedTargets: [Resource, Method]
  resourcePathUri:
    type: string
    allowedTargets: [Resource, Method]
  builtinType:
    type: string
    allowedTargets: TypeDeclaration
  oneOf:
    type: array
    items: string
    allowedTargets: TypeDeclaration
  ReferenceType:
     type: string
     (builtinType): string
     description: |-
       This annotation documents the type of an import reference.
securitySchemes:
  oauth_2_0: !include oauth2.raml
securedBy:
- oauth_2_0
baseUri: https://import.commercetools.com
types:
  AccessDeniedError: !include types/errors/AccessDeniedError.raml
  Address: !include types/common/Address.raml
  AnyAttribute: !include types/productvariants/AnyAttribute.raml
  Asset: !include types/common/Asset.raml
  AssetDimensions: !include types/common/AssetDimensions.raml
  AssetSource: !include types/common/AssetSource.raml
  Attribute: !include types/productvariants/Attribute.raml
  AttributeBooleanType: !include types/producttypes/AttributeBooleanType.raml
  AttributeConstraintEnum: !include types/producttypes/AttributeConstraintEnum.raml
  AttributeDateTimeType: !include types/producttypes/AttributeDateTimeType.raml
  AttributeDateType: !include types/producttypes/AttributeDateType.raml
  AttributeDefinition: !include types/producttypes/AttributeDefinition.raml
  AttributeEnumType: !include types/producttypes/AttributeEnumType.raml
  AttributeLocalizableTextType: !include types/producttypes/AttributeLocalizableTextType.raml
  AttributeLocalizedEnumType: !include types/producttypes/AttributeLocalizedEnumType.raml
  AttributeLocalizedEnumValue: !include types/producttypes/AttributeLocalizedEnumValue.raml
  AttributeMoneyType: !include types/producttypes/AttributeMoneyType.raml
  AttributeNestedType: !include types/producttypes/AttributeNestedType.raml
  AttributeNumberType: !include types/producttypes/AttributeNumberType.raml
  AttributePlainEnumValue: !include types/producttypes/AttributePlainEnumValue.raml
  AttributeReferenceType: !include types/producttypes/AttributeReferenceType.raml
  AttributeSetType: !include types/producttypes/AttributeSetType.raml
  AttributeTextType: !include types/producttypes/AttributeTextType.raml
  AttributeTimeType: !include types/producttypes/AttributeTimeType.raml
  AttributeType: !include types/producttypes/AttributeType.raml
  Attributes: !include types/productvariants/Attributes.raml
  BooleanAttribute: !include types/productvariants/BooleanAttribute.raml
  CategoryImport: !include types/categories/CategoryImport.raml
  CategoryImportRequest: !include types/importsinks/CategoryImportRequest.raml
  CategoryOrderHints: !include types/products/CategoryOrderHints.raml
  ConcurrentModificationError: !include types/errors/ConcurrentModificationError.raml
  CountryCode: !include types/CountryCode.raml
  CurrencyCode: !include types/CurrencyCode.raml
  CustomTokenizer: !include types/products/CustomTokenizer.raml
  DateAttribute: !include types/productvariants/DateAttribute.raml
  DateTimeAttribute: !include types/productvariants/DateTimeAttribute.raml
  DuplicateAttributeValueError: !include types/errors/DuplicateAttributeValueError.raml
  DuplicateAttributeValuesError: !include types/errors/DuplicateAttributeValuesError.raml
  DuplicateFieldError: !include types/errors/DuplicateFieldError.raml
  DuplicateVariantValuesError: !include types/errors/DuplicateVariantValuesError.raml
  EnumAttribute: !include types/productvariants/EnumAttribute.raml
  EnumValue: !include types/common/EnumValue.raml
  ErrorObject: !include types/errors/ErrorObject.raml
  ErrorResponse: !include types/errors/ErrorResponse.raml
  Image: !include types/common/Image.raml
  ImportItem: !include types/importitems/ImportItem.raml
  ImportItemPagedResponse: !include types/importitems/ImportItemPagedResponse.raml
  ImportReference: !include types/common/ImportReference.raml
  ImportRequest: !include types/importsinks/ImportRequest.raml
  ImportRequestState: !include types/importsinks/ImportRequestState.raml
  ImportResource: !include types/common/ImportResource.raml
  ImportSink: !include types/importsinks/ImportSink.raml
  ImportSinkDraft: !include types/importsinks/ImportSinkDraft.raml
  InsufficientScopeError: !include types/errors/InsufficientScopeError.raml
  InvalidCredentialsError: !include types/errors/InvalidCredentialsError.raml
  InvalidFieldError: !include types/errors/InvalidFieldError.raml
  InvalidInput: !include types/errors/InvalidInput.raml
  InvalidStateTransitionError: !include types/errors/InvalidStateTransitionError.raml
  InvalidTokenError: !include types/errors/InvalidTokenError.raml
  JavascriptPredicate: !include types/importsinks/JavascriptPredicate.raml
  LocalizableEnumAttribute: !include types/productvariants/LocalizableEnumAttribute.raml
  LocalizableTextAttribute: !include types/productvariants/LocalizableTextAttribute.raml
  LocalizedEnumValue: !include types/common/LocalizedEnumValue.raml
  LocalizedString: !include types/common/LocalizedString.raml
  Money: !include types/common/Money.raml
  MoneyAttribute: !include types/productvariants/MoneyAttribute.raml
  NumberAttribute: !include types/productvariants/NumberAttribute.raml
  Predicate: !include types/importsinks/Predicate.raml
  PriceImport: !include types/prices/PriceImport.raml
  PriceImportRequest: !include types/importsinks/PriceImportRequest.raml
  PriceMapping: !include types/pricemapping/PriceMapping.raml
  ProcessingState: !include types/common/ProcessingState.raml
  ProductImport: !include types/products/ProductImport.raml
  ProductImportRequest: !include types/importsinks/ProductImportRequest.raml
  ProductTypeImport: !include types/producttypes/ProductTypeImport.raml
  ProductTypeImportRequest: !include types/importsinks/ProductTypeImportRequest.raml
  ProductVariantImport: !include types/productvariants/ProductVariantImport.raml
  ProductVariantImportRequest: !include types/importsinks/ProductVariantImportRequest.raml
  ProductVariantPatch: !include types/productvariants/ProductVariantPatch.raml
  ProductVariantPatchRequest: !include types/importsinks/ProductVariantPatchRequest.raml
  RequiredFieldError: !include types/errors/RequiredFieldError.raml
  ResourceCreationError: !include types/errors/ResourceCreationError.raml
  ResourceDeletionError: !include types/errors/ResourceDeletionError.raml
  ResourceNotFoundError: !include types/errors/ResourceNotFoundError.raml
  ResourceType: !include types/common/ResourceType.raml
  ResourceUpdateError: !include types/errors/ResourceUpdateError.raml
  SearchKeyword: !include types/products/SearchKeyword.raml
  SearchKeywords: !include types/products/SearchKeywords.raml
  SuggestTokenizer: !include types/products/SuggestTokenizer.raml
  TextAttribute: !include types/productvariants/TextAttribute.raml
  TextInputHint: !include types/producttypes/TextInputHint.raml
  TimeAttribute: !include types/productvariants/TimeAttribute.raml
  UnresolvedImportResource: !include types/importresources/UnresolvedImportResource.raml
  VariantValues: !include types/errors/VariantValues.raml
  WhitespaceTokenizer: !include types/products/WhitespaceTokenizer.raml
  
/{projectKey}: !include resources/ByProjectKey.raml
/{projectKey}/import-sinks: !include resources/ByProjectKeyImportSinks.raml
/{projectKey}/import-sinks/{importSinkKey}: !include resources/ByProjectKeyImportSinksByImportSinkKey.raml
/{projectKey}/import-sinks/{importSinkKey}/items: !include resources/ByProjectKeyImportSinksByImportSinkKeyItems.raml
/{projectKey}/import-sinks/{importSinkKey}/items/{resourceKey}: !include resources/ByProjectKeyImportSinksByImportSinkKeyItemsByResourceKey.raml
/{projectKey}/import-sinks/{importSinkKey}/requests: !include resources/ByProjectKeyImportSinksByImportSinkKeyRequests.raml