#%RAML 1.0 DataType
displayName: ApiClientDraft
type: object
(builtinType): object
properties:
  deleteDaysAfterCreation:
    format: int64
    type: number
    (builtinType): number
    description: |-
      If set, the client will be deleted after the specified amount of days.
    required: false
  scope:
    type: string
    (builtinType): string
    required: true
  name:
    type: string
    (builtinType): string
    required: true