#%RAML 1.0 DataType
displayName: TypeKeyReference
type: KeyReference
(builtinType): object
discriminatorValue: type
description: |-
  References a type by its key.
properties:
  typeId:
    type: ReferenceType
    (builtinType): string
    description: |-
      The type of the referenced resource.
    enum:
    - type
    required: true
