#%RAML 1.0 DataType
displayName: Attribute
type: object
(builtinType): object
properties:
  name:
    type: string
    (builtinType): string
    (identifier): true
    (elementIdentifier): true
    required: true
  value:
    type: any
    (builtinType): any
    description: |-
      A valid JSON value, based on an AttributeDefinition.
    required: true