#%RAML 1.0 DataType
(builtinType): object
type: SuggestTokenizer
displayName: CustomTokenizer
discriminator: type
discriminatorValue: custom
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - custom
    required: true
  inputs:
    type: array
    items:
      type: string
    (builtinType): array
    required: true