#%RAML 1.0 DataType
type: object
(originalType): object
displayName: FacetResultRange


properties:
  toStr:
    required: true
    type: string
  total:
    required: true
    format: int64
    type: number
  min:
    required: true
    type: number
  fromStr:
    required: true
    type: string
  max:
    required: true
    type: number
  mean:
    required: true
    type: number
  count:
    required: true
    format: int64
    type: number
  from:
    required: true
    type: number
  to:
    required: true
    type: number
  productCount:
    required: false
    format: int64
    type: number