#%RAML 1.0 DataType
displayName: FacetResultRange
type: object
(builtinType): object
properties:
  from:
    type: integer
    (builtinType): integer
    required: true
  fromStr:
    type: string
    (builtinType): string
    required: true
  to:
    type: integer
    (builtinType): integer
    required: true
  toStr:
    type: string
    (builtinType): string
    required: true
  count:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  productCount:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  total:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  min:
    type: integer
    (builtinType): integer
    required: true
  max:
    type: integer
    (builtinType): integer
    required: true
  mean:
    type: integer
    (builtinType): integer
    required: true