#%RAML 1.0 DataType
type: object
(originalType): object
displayName: FacetResultTerm


properties:
  count:
    required: true
    format: int64
    type: number
  term:
    required: true
    type: any
  productCount:
    required: false
    format: int64
    type: number