#%RAML 1.0 DataType
displayName: FacetResults
type: object
(builtinType): object
properties:
  /^[a-z].*$/:
    type: FacetResult | FilteredFacetResult | RangeFacetResult | TermFacetResult
    (oneOf):
    - FacetResult
    - FilteredFacetResult
    - RangeFacetResult
    - TermFacetResult
    (builtinType): any
    required: true