#%RAML 1.0 DataType
displayName: FacetResultTerm
type: object
(builtinType): object
properties:
  term:
    type: any
    (builtinType): any
    required: true
  count:
    format: int64
    type: number
    (builtinType): number
    required: true
  productCount:
    format: int64
    type: number
    (builtinType): number
    required: false