#%RAML 1.0 DataType
(builtinType): object
type: FacetResult
displayName: FilteredFacetResult
discriminator: type
discriminatorValue: filter
properties:
  type:
    type: FacetTypes
    (builtinType): string
    enum:
    - filter
    required: true
  count:
    format: int64
    type: number
    (builtinType): number
    required: true
  productCount:
    format: int64
    type: number
    (builtinType): number
    required: false