#%RAML 1.0 DataType
displayName: FilteredFacetResult
type: FacetResult
(builtinType): object
discriminatorValue: filter
properties:
  type:
    type: FacetTypes
    (builtinType): string
    enum:
    - filter
    required: true
  count:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  productCount:
    format: int64
    type: integer
    (builtinType): integer
    required: false