#%RAML 1.0 DataType
displayName: ProductSetAttributeAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setAttribute
examples:
  postman: !include ../../examples/Product/ProductSetAttributeAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAttribute
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false