#%RAML 1.0 DataType
displayName: ProductRemoveImageAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removeImage
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#remove-image"
examples:
  postman: !include ../../examples/Product/ProductRemoveImageAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeImage
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  imageUrl:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false