#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductPublishAction
discriminator: action
discriminatorValue: publish
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - publish
    required: true
  scope:
    type: ProductPublishScope
    (builtinType): string
    required: false