#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductCatalogData


properties:
  current:
    type: ProductData
  staged:
    type: ProductData
  published:
    type: boolean
  hasStagedChanges:
    type: boolean