#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetProductVariantKeyAction
discriminator: action
discriminatorValue: setProductVariantKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setProductVariantKey
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false