#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductRemovePriceAction
# discriminator: action
# discriminatorValue: removePrice
properties:
  action:
    default: removePrice
    required: true
    type: string
  staged:
    required: false
    type: boolean
  priceId:
    required: true
    type: string