#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductAddToCategoryAction
discriminator: action
discriminatorValue: addToCategory
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addToCategory
    required: true
  orderHint:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  category:
    type: CategoryResourceIdentifier
    (builtinType): object
    required: true