#%RAML 1.0 DataType
displayName: ProductMoveImageToPositionAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: moveImageToPosition
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#move-image-to-position"
examples:
  postman: !include ../../examples/Product/ProductMoveImageToPositionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - moveImageToPosition
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  imageUrl:
    type: string
    (builtinType): string
    required: true
  position:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false