#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductSetCategoryOrderHintAction
# discriminator: action
# discriminatorValue: setCategoryOrderHint
properties:
  action:
    default: setCategoryOrderHint
    required: true
    type: string
  orderHint:
    required: false
    type: string
  staged:
    required: false
    type: boolean
  categoryId:
    required: true
    type: string