#%RAML 1.0 DataType
displayName: ProductRemoveAssetAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removeAsset
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAsset
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false