#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetMetaTitleAction
discriminator: action
discriminatorValue: setMetaTitle
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMetaTitle
    required: true
  metaTitle:
    type: LocalizedString
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false