#%RAML 1.0 DataType
displayName: ProductResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: product
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product
    required: false