#%RAML 1.0 DataType
displayName: ProductSetPricesAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setPrices
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setPrices
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  prices:
    type: array
    items:
      type: PriceDraft
    (builtinType): array
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false