#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductPagedQueryResponse


properties:
  total:
    format: int64
    type: number
  offset:
    format: int64
    type: number
  count:
    format: int64
    type: number
  limit:
    format: int64
    type: number
  results:
    type: array
    items:
      type: Product