#%RAML 1.0 DataType
displayName: ProductUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- ProductAddAssetAction
- ProductAddExternalImageAction
- ProductAddPriceAction
- ProductAddToCategoryAction
- ProductAddVariantAction
- ProductChangeAssetNameAction
- ProductChangeAssetOrderAction
- ProductChangeMasterVariantAction
- ProductChangeNameAction
- ProductChangePriceAction
- ProductChangeSlugAction
- ProductLegacySetSkuAction
- ProductMoveImageToPositionAction
- ProductPublishAction
- ProductRemoveAssetAction
- ProductRemoveFromCategoryAction
- ProductRemoveImageAction
- ProductRemovePriceAction
- ProductRemoveVariantAction
- ProductRevertStagedChangesAction
- ProductRevertStagedVariantChangesAction
- ProductSetAssetCustomFieldAction
- ProductSetAssetCustomTypeAction
- ProductSetAssetDescriptionAction
- ProductSetAssetKeyAction
- ProductSetAssetSourcesAction
- ProductSetAssetTagsAction
- ProductSetAttributeAction
- ProductSetAttributeInAllVariantsAction
- ProductSetCategoryOrderHintAction
- ProductSetDescriptionAction
- ProductSetDiscountedPriceAction
- ProductSetImageLabelAction
- ProductSetKeyAction
- ProductSetMetaDescriptionAction
- ProductSetMetaKeywordsAction
- ProductSetMetaTitleAction
- ProductSetPricesAction
- ProductSetProductPriceCustomFieldAction
- ProductSetProductPriceCustomTypeAction
- ProductSetProductVariantKeyAction
- ProductSetSearchKeywordsAction
- ProductSetSkuAction
- ProductSetTaxCategoryAction
- ProductTransitionStateAction
- ProductUnpublishAction
properties:
  action:
    type: string
    (builtinType): string
    required: true