#%RAML 1.0 DataType
displayName: ProductSetProductPriceCustomTypeAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setProductPriceCustomType
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-product-price-custom-type"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetProductPriceCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setProductPriceCustomType
    required: true
  priceId:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false