#%RAML 1.0 DataType
displayName: ProductUnpublishAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: unpublish
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - unpublish
    required: true