#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductAddAssetAction
discriminator: action
discriminatorValue: addAsset
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addAsset
    required: true
  position:
    format: int32
    type: number
    (builtinType): number
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  asset:
    type: AssetDraft
    (builtinType): object
    required: true
  sku:
    type: string
    (builtinType): string
    required: false