#%RAML 1.0 DataType
displayName: ProductAddToCategoryAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: addToCategory
examples:
  postman: !include ../../examples/Product/ProductAddToCategoryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addToCategory
    required: true
  category:
    type: CategoryResourceIdentifier
    (builtinType): object
    required: true
  orderHint:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false