#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: ProductReference
discriminator: typeId
discriminatorValue: product
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Product
    (builtinType): object
    required: false