#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductChangeAssetOrderAction

discriminatorValue: changeAssetOrder
properties:
  action:
    required: true
    type: string
  assetOrder:
    required: true
    type: array
    items:
      type: string
  staged:
    required: false
    type: boolean
  variantId:
    required: false
    format: int64
    type: number
  sku:
    required: false
    type: string