#%RAML 1.0 DataType
displayName: ProductReference
type: Reference
(builtinType): object
discriminatorValue: product
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#product"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product
    required: true
  obj:
    type: Product
    (builtinType): object
    required: false