#%RAML 1.0 DataType
displayName: ProductCatalogData
type: object
(builtinType): object
properties:
  published:
    type: boolean
    (builtinType): boolean
    required: true
  current:
    type: ProductData
    (builtinType): object
    required: true
  staged:
    type: ProductData
    (builtinType): object
    required: true
  hasStagedChanges:
    type: boolean
    (builtinType): boolean
    required: true