#%RAML 1.0 DataType
displayName: ProductSetSkuAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setSku
examples:
  postman: !include ../../examples/Product/ProductSetSkuAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSku
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: true
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false