#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductRemoveVariantAction
discriminator: action
discriminatorValue: removeVariant
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeVariant
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  id:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false