#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductRemoveImageAction
# discriminator: action
# discriminatorValue: removeImage
properties:
  action:
    default: removeImage
    required: true
    type: string
  imageUrl:
    required: true
    type: string
  staged:
    required: false
    type: boolean
  variantId:
    required: false
    format: int64
    type: number
  sku:
    required: false
    type: string