#%RAML 1.0 DataType
displayName: ProductRemoveVariantAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removeVariant
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#remove-productvariant"
examples:
  postman: !include ../../examples/Product/ProductRemoveVariantAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeVariant
    required: true
  id:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false