#%RAML 1.0 DataType
displayName: ProductSetAssetCustomTypeAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setAssetCustomType
examples:
  postman: !include ../../examples/Product/ProductSetAssetCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetCustomType
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: object
    (builtinType): object
    required: false