#%RAML 1.0 DataType
displayName: ProductSetAttributeAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setAttribute
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-attribute"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetAttributeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAttribute
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    description: |-
      If the attribute exists and the value is omitted or set to `null`, the attribute is removed.
      If the attribute exists and a value is provided, the new value is applied.
      If the attribute does not exist and a value is provided, it is added as a new attribute.
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false