#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductSetPricesAction

discriminatorValue: setPrices
properties:
  action:
    type: string
  staged:
    type: boolean
  variantId:
    format: int64
    type: number
  prices:
    type: array
    items:
      type: PriceDraft
  sku:
    type: string