#%RAML 1.0 DataType
displayName: ProductLegacySetSkuAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: legacySetSku
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - legacySetSku
    required: true
  sku:
    type: string
    (builtinType): string
    required: false
  variantId:
    type: integer
    (builtinType): integer
    required: true