#%RAML 1.0 DataType
displayName: ProductAddToCategoryAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: addToCategory
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#add-to-category"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductAddToCategoryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addToCategory
    required: true
  category:
    type: CategoryResourceIdentifier
    (builtinType): object
    required: true
  orderHint:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false