#%RAML 1.0 DataType
displayName: Product
type: LoggedResource
(builtinType): object
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#product"
(updateType): "ProductUpdate"
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the product.
    (identifier): true
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    description: |-
      The current version of the product.
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier for the product.
      *Product keys are different from product variant keys.*
    required: false
  productType:
    type: ProductTypeReference
    (builtinType): object
    required: true
  masterData:
    type: ProductCatalogData
    (builtinType): object
    description: |-
      The product data in the master catalog.
    required: true
  taxCategory:
    type: TaxCategoryReference
    (builtinType): object
    required: false
  state:
    type: StateReference
    (builtinType): object
    required: false
  reviewRatingStatistics:
    type: ReviewRatingStatistics
    (builtinType): object
    description: |-
      Statistics about the review ratings taken into account for this product.
    required: false