#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductData


properties:
  metaKeywords:
    type: LocalizedString
  categoryOrderHints:
    type: CategoryOrderHints
  searchKeywords:
    type: SearchKeywords
  metaTitle:
    type: LocalizedString
  name:
    type: LocalizedString
  description:
    type: LocalizedString
  variants:
    type: array
    items:
      type: ProductVariant
  masterVariant:
    type: ProductVariant
  categories:
    type: array
    items:
      type: CategoryReference
  metaDescription:
    type: LocalizedString
  slug:
    type: LocalizedString