#%RAML 1.0 DataType
displayName: ProductRemoveAssetAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removeAsset
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#remove-asset"
examples:
  postman: !include ../../examples/Product/ProductRemoveAssetAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeAsset
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false