#%RAML 1.0 DataType
displayName: ProductPublishAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: publish
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#publish"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductPublishAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - publish
    required: true
  scope:
    type: ProductPublishScope
    (builtinType): string
    enum:
    - All
    - Prices
    required: false