#%RAML 1.0 DataType
displayName: ProductRemoveVariantAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removeVariant
examples:
  postman: !include ../../examples/Product/ProductRemoveVariantAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeVariant
    required: true
  id:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false