#%RAML 1.0 DataType
displayName: ProductSetAssetTagsAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setAssetTags
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-asset-tags"
examples:
  postman: !include ../../examples/Product/ProductSetAssetTagsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetTags
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  tags:
    type: array
    items:
      type: string
    (builtinType): array
    required: false