#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ProductVariantAvailability
properties:
  availableQuantity:
    format: int64
    type: number
    (builtinType): number
    required: false
  channels:
    type: ProductVariantChannelAvailabilityMap
    (builtinType): object
    required: false
  restockableInDays:
    format: int64
    type: number
    (builtinType): number
    required: false
  isOnStock:
    type: boolean
    (builtinType): boolean
    required: false