#%RAML 1.0 DataType
type: ProductUpdateAction
displayName: ProductSetAssetCustomTypeAction

discriminatorValue: setAssetCustomType
properties:
   variantId:
      format: int64
      type: number
   sku:
      type: string
   staged:
      type: boolean
   assetId:
      type: string
   assetKey:
      type: string
   type:
      type: TypeResourceIdentifier
   fields:
      type: object