#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductAddPriceAction
# discriminator: action
# discriminatorValue: addPrice
properties:
  action:
    default: addPrice
    required: true
    type: string
  price:
    required: true
    type: PriceDraft
  staged:
    required: false
    type: boolean
  variantId:
    required: false
    format: int64
    type: number
  sku:
    required: false
    type: string