#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetSkuAction
discriminator: action
discriminatorValue: setSku
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSku
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: true
  sku:
    type: string
    (builtinType): string
    required: false