#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetImageLabelAction
discriminator: action
discriminatorValue: setImageLabel
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setImageLabel
    required: true
  imageUrl:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  label:
    type: string
    (builtinType): string
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false