#%RAML 1.0 DataType
displayName: ProductRevertStagedChangesAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: revertStagedChanges
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - revertStagedChanges
    required: true