#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductVariant


properties:
  scopedPrice:
    type: ScopedPrice
  images:
    type: array
    items:
      type: Image
  assets:
    type: array
    items:
      type: Asset
  isMatchingVariant:
    type: boolean
  price:
    type: Price
  scopedPriceDiscounted:
    type: boolean
  attributes:
    type: array
    items:
      type: Attribute
  availability:
    type: ProductVariantAvailability
  id:
    format: int64
    type: number
  prices:
    type: array
    items:
      type: Price
  sku:
    type: string
  key:
    type: string