#%RAML 1.0 DataType
displayName: ProductSetCategoryOrderHintAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setCategoryOrderHint
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCategoryOrderHint
    required: true
  categoryId:
    type: string
    (builtinType): string
    required: true
  orderHint:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false