#%RAML 1.0 DataType
displayName: ProductChangeMasterVariantAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: changeMasterVariant
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#change-master-variant"
examples:
  postman: !include ../../examples/Product/ProductChangeMasterVariantAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeMasterVariant
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false