#%RAML 1.0 DataType
displayName: ProductSetProductPriceCustomFieldAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setProductPriceCustomField
examples:
  postman: !include ../../examples/Product/ProductSetProductPriceCustomFieldAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setProductPriceCustomField
    required: true
  priceId:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false