#%RAML 1.0 DataType
displayName: ProductVariantChannelAvailabilityMap
type: object
(builtinType): object
(package): "Product"
properties:
  //:
    type: ProductVariantChannelAvailability
    (builtinType): object
    required: true