#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetMetaKeywordsAction
discriminator: action
discriminatorValue: setMetaKeywords
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMetaKeywords
    required: true
  metaKeywords:
    type: LocalizedString
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false