#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductMoveImageToPositionAction
discriminator: action
discriminatorValue: moveImageToPosition
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - moveImageToPosition
    required: true
  imageUrl:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  position:
    format: int64
    type: number
    (builtinType): number
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false