#%RAML 1.0 DataType
displayName: ProductPublishAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: publish
examples:
  postman: !include ../../examples/Product/ProductPublishAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - publish
    required: true
  scope:
    type: ProductPublishScope
    (builtinType): string
    required: false