#%RAML 1.0 DataType
displayName: ProductRevertStagedVariantChangesAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: revertStagedVariantChanges
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#revert-staged-variant-changes"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductRevertStagedVariantChangesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - revertStagedVariantChanges
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: true