#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductAddPriceAction
discriminator: action
discriminatorValue: addPrice
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addPrice
    required: true
  price:
    type: PriceDraft
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false