#%RAML 1.0 DataType
displayName: ProductRemovePriceAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removePrice
examples:
  postman: !include ../../examples/Product/ProductRemovePriceAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removePrice
    required: true
  priceId:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false