#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductChangeMasterVariantAction
# discriminator: action
# discriminatorValue: changeMasterVariant
properties:
  action:
    default: changeMasterVariant
    required: true
    type: string
  staged:
    required: false
    type: boolean
  variantId:
    required: false
    format: int64
    type: number
  sku:
    required: false
    type: string