#%RAML 1.0 DataType
displayName: ProductRemovePriceAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removePrice
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#remove-price"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductRemovePriceAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removePrice
    required: true
  priceId:
    type: string
    (builtinType): string
    description: |-
      ID of the [Price](#price)
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false