#%RAML 1.0 DataType
displayName: ProductSetDiscountedPriceAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setDiscountedPrice
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-discounted-price"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetDiscountedPriceAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDiscountedPrice
    required: true
  priceId:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  discounted:
    type: DiscountedPrice
    (builtinType): object
    required: false