#%RAML 1.0 DataType
displayName: ProductAddExternalImageAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: addExternalImage
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addExternalImage
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  image:
    type: Image
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false