#%RAML 1.0 DataType
displayName: ProductSetTaxCategoryAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setTaxCategory
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-taxcategory"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetTaxCategoryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setTaxCategory
    required: true
  taxCategory:
    type: TaxCategoryResourceIdentifier
    (builtinType): object
    required: false