#%RAML 1.0 DataType
displayName: ProductChangePriceAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: changePrice
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#change-price"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductChangePriceAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changePrice
    required: true
  priceId:
    type: string
    (builtinType): string
    required: true
  price:
    type: PriceDraft
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false