#%RAML 1.0 DataType
displayName: ProductVariant
type: object
(builtinType): object
properties:
  scopedPrice:
    type: ScopedPrice
    (builtinType): object
    required: false
  images:
    type: array
    items:
      type: Image
    (builtinType): array
    required: false
  assets:
    type: array
    items:
      type: Asset
    (builtinType): array
    required: false
  isMatchingVariant:
    type: boolean
    (builtinType): boolean
    required: false
  price:
    type: Price
    (builtinType): object
    required: false
  scopedPriceDiscounted:
    type: boolean
    (builtinType): boolean
    required: false
  attributes:
    type: array
    items:
      type: Attribute
    (builtinType): array
    required: false
  availability:
    type: ProductVariantAvailability
    (builtinType): object
    required: false
  id:
    format: int64
    type: number
    (builtinType): number
    required: true
  prices:
    type: array
    items:
      type: Price
    (builtinType): array
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false