#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductSetTaxCategoryAction
# discriminator: action
# discriminatorValue: setTaxCategory
properties:
  action:
    default: setTaxCategory
    required: true
    type: string
  taxCategory:
    required: false
    type: TaxCategoryResourceIdentifier