#%RAML 1.0 DataType
displayName: ProductSetDescriptionAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setDescription
examples:
  postman: !include ../../examples/Product/ProductSetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false