#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetAssetDescriptionAction
discriminator: action
discriminatorValue: setAssetDescription
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetDescription
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false