#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetAssetCustomTypeAction
discriminator: action
discriminatorValue: setAssetCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetCustomType
    required: true
  assetId:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  fields:
    type: object
    (builtinType): object
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false