#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductSetProductPriceCustomFieldAction
# discriminator: action
# discriminatorValue: setProductPriceCustomField
properties:
  action:
    default: setProductPriceCustomField
    required: true
    type: string
  name:
    required: true
    type: string
  staged:
    required: false
    type: boolean
  priceId:
    required: true
    type: string
  value:
    required: false
    type: any