#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductChangeSlugAction
# discriminator: action
# discriminatorValue: changeSlug
properties:
  action:
    default: changeSlug
    required: true
    type: string
  staged:
    required: false
    type: boolean
  slug:
    required: true
    type: LocalizedString