#%RAML 1.0 DataType
displayName: ProductChangeAssetNameAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: changeAssetName
examples:
  postman: !include ../../examples/Product/ProductChangeAssetNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAssetName
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  name:
    type: LocalizedString
    (builtinType): object
    required: true