#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductChangeAssetOrderAction
discriminator: action
discriminatorValue: changeAssetOrder
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeAssetOrder
    required: true
  assetOrder:
    type: array
    items:
      type: string
    (builtinType): array
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false