#%RAML 1.0 DataType
displayName: ProductProjection
type: BaseResource
(builtinType): object
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-productProjections.html#productprojection"
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the Product.
    (identifier): true
    required: true
  version:
    format: int64
    type: integer
    (builtinType): integer
    description: |-
      The current version of the Product.
    required: true
  createdAt:
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    type: datetime
    (builtinType): datetime
    required: true
  key:
    type: string
    (builtinType): string
    description: |-
      User-specific unique identifier of the Product.
    required: false
  productType:
    discriminatorValue: "product-type"
    type: ProductTypeReference
    (builtinType): object
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  description:
    type: LocalizedString
    (builtinType): object
    required: false
  slug:
    type: LocalizedString
    (builtinType): object
    required: true
  categories:
    type: array
    items:
      type: CategoryReference
    (builtinType): array
    description: |-
      References to categories the product is in.
    required: true
  categoryOrderHints:
    type: CategoryOrderHints
    (builtinType): object
    required: false
  metaTitle:
    type: LocalizedString
    (builtinType): object
    required: false
  metaDescription:
    type: LocalizedString
    (builtinType): object
    required: false
  metaKeywords:
    type: LocalizedString
    (builtinType): object
    required: false
  searchKeywords:
    type: SearchKeywords
    (builtinType): object
    required: false
  hasStagedChanges:
    type: boolean
    (builtinType): boolean
    required: false
  published:
    type: boolean
    (builtinType): boolean
    required: false
  masterVariant:
    type: ProductVariant
    (builtinType): object
    required: true
  variants:
    type: array
    items:
      type: ProductVariant
    (builtinType): array
    required: true
  taxCategory:
    type: TaxCategoryReference
    (builtinType): object
    required: false
  state:
    type: StateReference
    (builtinType): object
    required: false
  reviewRatingStatistics:
    type: ReviewRatingStatistics
    (builtinType): object
    description: |-
      Statistics about the review ratings taken into account for this product.
    required: false