#%RAML 1.0 DataType
displayName: ProductRemoveFromCategoryAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: removeFromCategory
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#remove-from-category"
examples:
  postman: !include ../../examples/Product/ProductRemoveFromCategoryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeFromCategory
    required: true
  category:
    type: CategoryResourceIdentifier
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false