#%RAML 1.0 DataType
displayName: ProductSetImageLabelAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setImageLabel
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-image-label"
examples:
  postman: !include ../../examples/Product/ProductSetImageLabelAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setImageLabel
    required: true
  sku:
    type: string
    (builtinType): string
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  imageUrl:
    type: string
    (builtinType): string
    required: true
  label:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false