#%RAML 1.0 DataType
displayName: ProductSetMetaTitleAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setMetaTitle
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-meta-title"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetMetaTitleAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMetaTitle
    required: true
  metaTitle:
    type: LocalizedString
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false