#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetProductPriceCustomTypeAction
discriminator: action
discriminatorValue: setProductPriceCustomType
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setProductPriceCustomType
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  priceId:
    type: string
    (builtinType): string
    required: true