#%RAML 1.0 DataType
(builtinType): object
type: ResourceIdentifier
displayName: ProductResourceIdentifier
discriminator: typeId
discriminatorValue: product
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - product
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false