#%RAML 1.0 DataType
displayName: ProductSetProductVariantKeyAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setProductVariantKey
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-productvariant-key"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetProductVariantKeyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setProductVariantKey
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    description: |-
      If left blank or set to `null`, the key is unset/removed.
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false