#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetDiscountedPriceAction
discriminator: action
discriminatorValue: setDiscountedPrice
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDiscountedPrice
    required: true
  discounted:
    type: DiscountedPrice
    (builtinType): object
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  priceId:
    type: string
    (builtinType): string
    required: true