#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductUnpublishAction
discriminator: action
discriminatorValue: unpublish
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - unpublish
    required: true