#%RAML 1.0 DataType
displayName: ProductSetAssetKeyAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setAssetKey
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetKey
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: true
  assetKey:
    type: string
    (builtinType): string
    required: false