#%RAML 1.0 DataType
displayName: ProductRevertStagedChangesAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: revertStagedChanges
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#revert-staged-changes"
examples:
  postman: !include ../../examples/Product/ProductRevertStagedChangesAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - revertStagedChanges
    required: true