#%RAML 1.0 DataType
displayName: ProductTransitionStateAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: transitionState
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#transition-state"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductTransitionStateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - transitionState
    required: true
  state:
    type: StateResourceIdentifier
    (builtinType): object
    required: false
  force:
    type: boolean
    (builtinType): boolean
    required: false