#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ProductVariantAvailability


properties:
  availableQuantity:
    required: false
    format: int64
    type: number
  channels:
    required: false
    type: ProductVariantChannelAvailabilityMap
  restockableInDays:
    required: false
    format: int64
    type: number
  isOnStock:
    required: false
    type: boolean