#%RAML 1.0 DataType
displayName: ProductSetAssetCustomFieldAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setAssetCustomField
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-asset-custom-field"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetAssetCustomFieldAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetCustomField
    required: true
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  name:
    type: string
    (builtinType): string
    required: true
  value:
    type: any
    (builtinType): any
    required: false