#%RAML 1.0 DataType
displayName: ProductChangeNameAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: changeName
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#change-name"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductChangeNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false