#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetMetaDescriptionAction
discriminator: action
discriminatorValue: setMetaDescription
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setMetaDescription
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  metaDescription:
    type: LocalizedString
    (builtinType): object
    required: false