#%RAML 1.0 DataType
displayName: ProductSetSearchKeywordsAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setSearchKeywords
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-searchkeywords"
examples:
  postman:
    strict: true
    value: !include ../../examples/Product/ProductSetSearchKeywordsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSearchKeywords
    required: true
  searchKeywords:
    type: SearchKeywords
    (builtinType): object
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false