#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductSetProductPriceCustomTypeAction

discriminatorValue: setProductPriceCustomType
properties:
  action:
    type: string
  staged:
    type: boolean
  fields:
    type: FieldContainer
  type:
    type: TypeResourceIdentifier
  priceId:
    type: string