#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductLegacySetSkuAction
discriminator: action
discriminatorValue: legacySetSku
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - legacySetSku
    required: true
  variantId:
    type: integer
    (builtinType): integer
    required: true
  sku:
    type: string
    (builtinType): string
    required: false