#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductSetMetaTitleAction
# discriminator: action
# discriminatorValue: setMetaTitle
properties:
  action:
    default: setMetaTitle
    required: true
    type: string
  metaTitle:
    required: false
    type: LocalizedString
  staged:
    required: false
    type: boolean