#%RAML 1.0 DataType
displayName: ProductSetAssetDescriptionAction
type: ProductUpdateAction
(builtinType): object
discriminatorValue: setAssetDescription
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#set-asset-description"
examples:
  postman: !include ../../examples/Product/ProductSetAssetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAssetDescription
    required: true
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  assetId:
    type: string
    (builtinType): string
    required: false
  assetKey:
    type: string
    (builtinType): string
    required: false
  description:
    type: LocalizedString
    (builtinType): object
    required: false