#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductRemoveFromCategoryAction
# discriminator: action
# discriminatorValue: removeFromCategory
properties:
  action:
    default: removeFromCategory
    required: true
    type: string
  staged:
    required: false
    type: boolean
  category:
    required: true
    type: CategoryResourceIdentifier