#%RAML 1.0 DataType
type: object
(originalType): ProductUpdateAction
displayName: ProductSetMetaKeywordsAction

discriminatorValue: setMetaKeywords
properties:
  action:
    type: string
  metaKeywords:
    type: LocalizedString
  staged:
    type: boolean