#%RAML 1.0 DataType
(builtinType): object
type: ProductUpdateAction
displayName: ProductSetAttributeAction
discriminator: action
discriminatorValue: setAttribute
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAttribute
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  staged:
    type: boolean
    (builtinType): boolean
    required: false
  variantId:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  value:
    type: any
    (builtinType): any
    required: false