#%RAML 1.0 DataType
(builtinType): object
type: FacetResult
displayName: RangeFacetResult
discriminator: type
discriminatorValue: range
properties:
  type:
    type: FacetTypes
    (builtinType): string
    enum:
    - range
    required: true
  ranges:
    type: array
    items:
      type: FacetResultRange
    (builtinType): array
    required: true