#%RAML 1.0 DataType
displayName: RangeFacetResult
type: FacetResult
(builtinType): object
discriminatorValue: range
properties:
  type:
    type: FacetTypes
    (builtinType): string
    enum:
    - range
    required: true
  ranges:
    type: array
    items:
      type: FacetResultRange
    (builtinType): array
    required: true