#%RAML 1.0 DataType
displayName: SearchKeyword
type: object
(builtinType): object
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#searchkeyword"
properties:
  text:
    type: string
    (builtinType): string
    required: true
  suggestTokenizer:
    type: SuggestTokenizer | WhitespaceTokenizer | CustomTokenizer
    (oneOf):
    - SuggestTokenizer
    - WhitespaceTokenizer
    - CustomTokenizer
    (builtinType): any
    required: false