#%RAML 1.0 DataType
displayName: Suggestion
type: object
(builtinType): object
properties:
  text:
    type: string
    (builtinType): string
    description: |-
      The suggested text.
    required: true