#%RAML 1.0 DataType
displayName: SuggestTokenizer
type: object
(builtinType): object
discriminator: type
(oneOf):
- CustomTokenizer
- WhitespaceTokenizer
(package): "Product"
(docs-uri): "https://docs.commercetools.com/http-api-projects-products.html#product-search-keywords-suggest-examples"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - whitespace
    - custom
    required: true