#%RAML 1.0 DataType
type: object
(originalType): SuggestTokenizer
displayName: WhitespaceTokenizer
# discriminator: type
# discriminatorValue: whitespace
properties:
  type:
    default: whitespace
    required: true
    type: string