#%RAML 1.0 DataType
(builtinType): object
type: SuggestTokenizer
displayName: WhitespaceTokenizer
discriminator: type
discriminatorValue: whitespace
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - whitespace
    required: true