#%RAML 1.0 DataType
displayName: InventoryEntry
type: LoggedResource
(builtinType): object
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of the inventory entry.
    required: true
  version:
    format: int64
    type: number
    (builtinType): number
    required: true
  createdAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedAt:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: true
  lastModifiedBy:
    type: LastModifiedBy
    (builtinType): object
    description: |-
      Present on resources updated after 1/02/2019 except for events not tracked.
    required: false
  createdBy:
    type: CreatedBy
    (builtinType): object
    description: |-
      Present on resources created after 1/02/2019 except for events not tracked.
    required: false
  sku:
    type: string
    (builtinType): string
    required: true
  supplyChannel:
    discriminatorValue: channel
    type: ChannelResourceIdentifier
    (builtinType): object
    description: |-
      Optional connection to a particular supplier.
    required: false
  quantityOnStock:
    format: int64
    type: number
    (builtinType): number
    description: |-
      Overall amount of stock.
      (available + reserved)
    required: true
  availableQuantity:
    format: int64
    type: number
    (builtinType): number
    description: |-
      Available amount of stock.
      (available means: `quantityOnStock` - reserved quantity)
    required: true
  restockableInDays:
    format: int64
    type: number
    (builtinType): number
    description: |-
      The time period in days, that tells how often this inventory entry is restocked.
    required: false
  expectedDelivery:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    description: |-
      The date and time of the next restock.
    required: false
  custom:
    type: CustomFields
    (builtinType): object
    required: false