#%RAML 1.0 DataType
(builtinType): object
type: ResourceIdentifier
displayName: InventoryEntryResourceIdentifier
discriminator: typeId
discriminatorValue: inventory-entry
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - inventory-entry
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false