#%RAML 1.0 DataType
displayName: InventoryEntryRemoveQuantityAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: removeQuantity
(package): "Inventory"
(docs-uri): "https://docs.commercetools.com/http-api-projects-inventory.html#remove-quantity"
examples:
  postman:
    strict: true
    value: !include ../../examples/Inventory/InventoryEntryRemoveQuantityAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeQuantity
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true