#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: InventoryEntryDraft
properties:
  expectedDelivery:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  quantityOnStock:
    format: int64
    type: number
    (builtinType): number
    required: true
  supplyChannel:
    discriminatorValue: channel
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false
  restockableInDays:
    format: int64
    type: number
    (builtinType): number
    required: false
  sku:
    type: string
    (builtinType): string
    required: true