#%RAML 1.0 DataType
displayName: InventoryEntryAddQuantityAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: addQuantity
(package): "Inventory"
(docs-uri): "https://docs.commercetools.com/http-api-projects-inventory.html#add-quantity"
examples:
  postman:
    strict: true
    value: !include ../../examples/Inventory/InventoryEntryAddQuantityAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addQuantity
    required: true
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    required: true