#%RAML 1.0 DataType
(builtinType): object
type: InventoryEntryUpdateAction
displayName: InventoryEntrySetExpectedDeliveryAction
discriminator: action
discriminatorValue: setExpectedDelivery
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExpectedDelivery
    required: true
  expectedDelivery:
    type: datetime
    (builtinType): datetime
    required: false