#%RAML 1.0 DataType
displayName: InventoryEntrySetRestockableInDaysAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: setRestockableInDays
(package): "Inventory"
(docs-uri): "https://docs.commercetools.com/http-api-projects-inventory.html#set-restockableindays"
examples:
  postman:
    strict: true
    value: !include ../../examples/Inventory/InventoryEntrySetRestockableInDaysAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRestockableInDays
    required: true
  restockableInDays:
    format: int64
    type: integer
    (builtinType): integer
    required: false