#%RAML 1.0 DataType
displayName: InventoryEntryUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- InventoryEntryAddQuantityAction
- InventoryEntryChangeQuantityAction
- InventoryEntryRemoveQuantityAction
- InventoryEntrySetCustomFieldAction
- InventoryEntrySetCustomTypeAction
- InventoryEntrySetExpectedDeliveryAction
- InventoryEntrySetRestockableInDaysAction
- InventoryEntrySetSupplyChannelAction
(package): "Inventory"
properties:
  action:
    type: string
    (builtinType): string
    required: true