#%RAML 1.0 DataType
displayName: InventoryEntrySetSupplyChannelAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: setSupplyChannel
(package): "Inventory"
(docs-uri): "https://docs.commercetools.com/http-api-projects-inventory.html#set-supplychannel"
examples:
  postman:
    strict: true
    value: !include ../../examples/Inventory/InventoryEntrySetSupplyChannelAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSupplyChannel
    required: true
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false