#%RAML 1.0 DataType
displayName: InventoryEntryReference
type: Reference
(builtinType): object
discriminatorValue: inventory-entry
(package): "Inventory"
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - inventory-entry
    required: true
  obj:
    type: InventoryEntry
    (builtinType): object
    required: false