#%RAML 1.0 DataType
displayName: InventoryEntrySetRestockableInDaysAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: setRestockableInDays
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRestockableInDays
    required: true
  restockableInDays:
    format: int64
    type: number
    (builtinType): number
    required: false