#%RAML 1.0 DataType
displayName: InventoryEntrySetSupplyChannelAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: setSupplyChannel
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSupplyChannel
    required: true
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false