#%RAML 1.0 DataType
displayName: InventoryEntryChangeQuantityAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: changeQuantity
examples:
  postman: !include ../../examples/Inventory/InventoryEntryChangeQuantityAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeQuantity
    required: true
  quantity:
    format: int64
    type: number
    (builtinType): number
    required: true