#%RAML 1.0 DataType
(builtinType): object
type: InventoryEntryUpdateAction
displayName: InventoryEntrySetSupplyChannelAction
discriminator: action
discriminatorValue: setSupplyChannel
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setSupplyChannel
    required: true
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false