#%RAML 1.0 DataType
displayName: InventoryEntrySetExpectedDeliveryAction
type: InventoryEntryUpdateAction
(builtinType): object
discriminatorValue: setExpectedDelivery
(package): "Inventory"
(docs-uri): "https://docs.commercetools.com/http-api-projects-inventory.html#set-expecteddelivery"
examples:
  postman:
    strict: true
    value: !include ../../examples/Inventory/InventoryEntrySetExpectedDeliveryAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setExpectedDelivery
    required: true
  expectedDelivery:
    format: rfc3339
    type: datetime
    (builtinType): datetime
    required: false