#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: InventoryEntryUpdateAction
discriminator: action
(subTypes):
- InventoryEntryAddQuantityAction
- InventoryEntryChangeQuantityAction
- InventoryEntryRemoveQuantityAction
- InventoryEntrySetCustomFieldAction
- InventoryEntrySetCustomTypeAction
- InventoryEntrySetExpectedDeliveryAction
- InventoryEntrySetRestockableInDaysAction
- InventoryEntrySetSupplyChannelAction
properties:
  action:
    type: string
    (builtinType): string
    required: true