#%RAML 1.0 DataType
displayName: InventoryEntryResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: inventory-entry
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - inventory-entry
    required: false