#%RAML 1.0 DataType
(builtinType): object
type: InventoryEntryUpdateAction
displayName: InventoryEntrySetRestockableInDaysAction
discriminator: action
discriminatorValue: setRestockableInDays
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setRestockableInDays
    required: true
  restockableInDays:
    format: int64
    type: number
    (builtinType): number
    required: false