#%RAML 1.0 DataType
displayName: SubRate
type: object
(builtinType): object
properties:
  amount:
    format: int16
    minimum: 0
    maximum: 1
    type: number
    (builtinType): number
    required: true
  name:
    type: string
    (builtinType): string
    required: true