#%RAML 1.0 DataType
(builtinType): object
type: TaxCategoryUpdateAction
displayName: TaxCategoryReplaceTaxRateAction
discriminator: action
discriminatorValue: replaceTaxRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - replaceTaxRate
    required: true
  taxRate:
    type: TaxRateDraft
    (builtinType): object
    required: true
  taxRateId:
    type: string
    (builtinType): string
    required: true