#%RAML 1.0 DataType
displayName: TaxCategoryResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: tax-category
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - tax-category
    required: false