#%RAML 1.0 DataType
displayName: TaxCategoryRemoveTaxRateAction
type: TaxCategoryUpdateAction
(builtinType): object
discriminatorValue: removeTaxRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeTaxRate
    required: true
  taxRateId:
    type: string
    (builtinType): string
    required: true