#%RAML 1.0 DataType
displayName: TaxCategoryReplaceTaxRateAction
type: TaxCategoryUpdateAction
(builtinType): object
discriminatorValue: replaceTaxRate
examples:
  postman: !include ../../examples/TaxCategory/TaxCategoryReplaceTaxRateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - replaceTaxRate
    required: true
  taxRateId:
    type: string
    (builtinType): string
    required: true
  taxRate:
    type: TaxRateDraft
    (builtinType): object
    required: true