#%RAML 1.0 DataType
displayName: TaxCategoryAddTaxRateAction
type: TaxCategoryUpdateAction
(builtinType): object
discriminatorValue: addTaxRate
(package): "TaxCategory"
(docs-uri): "https://docs.commercetools.com/http-api-projects-taxCategories.html#add-tax-rate"
examples:
  postman: !include ../../examples/TaxCategory/TaxCategoryAddTaxRateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTaxRate
    required: true
  taxRate:
    type: TaxRateDraft
    (builtinType): object
    required: true