#%RAML 1.0 DataType
displayName: TaxCategoryAddTaxRateAction
type: TaxCategoryUpdateAction
(builtinType): object
discriminatorValue: addTaxRate
examples:
  postman: !include ../../examples/TaxCategory/TaxCategoryAddTaxRateAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTaxRate
    required: true
  taxRate:
    type: TaxRateDraft
    (builtinType): object
    required: true