#%RAML 1.0 DataType
(builtinType): object
type: ResourceIdentifier
displayName: TaxCategoryResourceIdentifier
discriminator: typeId
discriminatorValue: tax-category
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - tax-category
    required: false
  id:
    type: string
    (builtinType): string
    required: false
  key:
    type: string
    (builtinType): string
    required: false