#%RAML 1.0 DataType
type: object
(originalType): TaxCategoryUpdateAction
displayName: TaxCategoryRemoveTaxRateAction
# discriminator: action
# discriminatorValue: removeTaxRate
properties:
  action:
    default: removeTaxRate
    required: true
    type: string
  taxRateId:
    required: true
    type: string