#%RAML 1.0 DataType
displayName: TaxCategorySetDescriptionAction
type: TaxCategoryUpdateAction
(builtinType): object
discriminatorValue: setDescription
(package): "TaxCategory"
(docs-uri): "https://docs.commercetools.com/http-api-projects-taxCategories.html#set-description"
examples:
  postman: !include ../../examples/TaxCategory/TaxCategorySetDescriptionAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setDescription
    required: true
  description:
    type: string
    (builtinType): string
    required: false