#%RAML 1.0 DataType
displayName: TaxCategoryUpdate
type: object
(builtinType): object
(package): "TaxCategory"
properties:
  version:
    format: int64
    type: integer
    (builtinType): integer
    required: true
  actions:
    type: array
    items:
      type: TaxCategoryUpdateAction
    (builtinType): array
    required: true