#%RAML 1.0 DataType
type: object
(originalType): TaxCategoryUpdateAction
displayName: TaxCategoryReplaceTaxRateAction

discriminatorValue: replaceTaxRate
properties:
  action:
    required: true
    type: string
  taxRate:
    required: true
    type: TaxRateDraft
  taxRateId:
    required: true
    type: string