#%RAML 1.0 DataType
displayName: TaxCategoryChangeNameAction
type: TaxCategoryUpdateAction
(builtinType): object
discriminatorValue: changeName
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeName
    required: true
  name:
    type: string
    (builtinType): string
    required: true