#%RAML 1.0 DataType
(builtinType): object
type: TaxCategoryUpdateAction
displayName: TaxCategoryRemoveTaxRateAction
discriminator: action
discriminatorValue: removeTaxRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeTaxRate
    required: true
  taxRateId:
    type: string
    (builtinType): string
    required: true