#%RAML 1.0 DataType
displayName: TaxCategoryReference
type: Reference
(builtinType): object
discriminatorValue: tax-category
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - tax-category
    required: true
  obj:
    type: TaxCategory
    (builtinType): object
    required: false