#%RAML 1.0 DataType
displayName: TaxCategoryDraft
type: object
(builtinType): object
properties:
  name:
    type: string
    (builtinType): string
    required: true
  description:
    type: string
    (builtinType): string
    required: false
  rates:
    type: array
    items:
      type: TaxRateDraft
    (builtinType): array
    required: true
  key:
    type: string
    (builtinType): string
    required: false