#%RAML 1.0 DataType
(builtinType): object
type: TaxCategoryUpdateAction
displayName: TaxCategoryAddTaxRateAction
discriminator: action
discriminatorValue: addTaxRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addTaxRate
    required: true
  taxRate:
    type: TaxRateDraft
    (builtinType): object
    required: true