#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: TaxCategoryReference
discriminator: typeId
discriminatorValue: tax-category
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - tax-category
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: TaxCategory
    (builtinType): object
    required: false