#%RAML 1.0 DataType
type: object
displayName: TaxRate


properties:
   id:
      description: |-
        The ID is always set if the tax rate is part of a TaxCategory.
        The external tax rates in a
        Cart do not contain an `id`.
      type: string
   name:
      type: string
   amount:
      description: |-
        Percentage in the range of [0..1].
        The sum of the amounts of all `subRates`, if there are any.
      format: int16
      minimum: 0
      maximum: 1
      type: number
   includedInPrice:
      type: boolean
   country:
      description: |-
        A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
      pattern: ^[A-Z]{2}$
      type: CountryCode
   state:
      description: |-
        The state in the country
      type: string
   subRates:
      description: |-
        For countries (e.g.
        the US) where the total tax is a combination of multiple taxes (e.g.
        state and local taxes).
      type: array
      items:
        type: SubRate