#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: TaxRateDraft
properties:
  country:
    pattern: ^[A-Z]{2}$
    type: CountryCode
    (builtinType): string
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    required: true
  amount:
    format: int16
    minimum: 0
    maximum: 1
    type: number
    (builtinType): number
    description: |-
      Percentage in the range of [0..1].
               Must be supplied if no `subRates` are specified.
               If `subRates` are specified
               then the `amount` can be omitted or it must be the sum of the amounts of all `subRates`.
    required: false
  includedInPrice:
    type: boolean
    (builtinType): boolean
    required: true
  name:
    type: string
    (builtinType): string
    required: true
  state:
    type: string
    (builtinType): string
    description: |-
      The state in the country
    required: false
  subRates:
    type: array
    items:
      type: SubRate
    (builtinType): array
    description: |-
      For countries (e.g.
               the US) where the total tax is a combination of multiple taxes (e.g.
               state and local taxes).
    required: false