#%RAML 1.0 DataType
displayName: CategoryImportRequest
type: ImportRequest
(builtinType): object
discriminatorValue: category
properties:
  type:
    type: ResourceType
    (builtinType): string
    enum:
    - category
    required: true
  resources:
    type: array
    items:
      type: CategoryImport
    (builtinType): array
    description: |-
      The individual categories to import.
    required: true