#%RAML 1.0 DataType
displayName: ImportSinkDraft
type: object
(builtinType): object
examples:
  minimal: !include ../../examples/importsinks/ImportSinkDraft-minimal.json
  with-skip-predicate: !include ../../examples/importsinks/ImportSinkDraft-with-skip-predicate.json
description: |-
  This type represents the read model of an ImportSink.
properties:
  key:
    type: string
    (builtinType): string
    description: |-
      The key of import sink.
    required: true
  resourceType:
    type: ResourceType
    (builtinType): string
    description: |-
      The type of the import resource sent to this import sink.
    required: true
  skipPredicate:
    type: Predicate
    (builtinType): object
    description: |-
      A predicate allows to check the current state of a CTP resource. And can be used to detect if an import should
      be performed or should be skipped. And this abstract type allows us to support different syntaxes for our predicates
      without any breaking changes to our api.
    required: false