#%RAML 1.0 DataType
displayName: ImportRequest
type: object
(builtinType): object
discriminator: type
(oneOf):
- CategoryImportRequest
- PriceImportRequest
- ProductImportRequest
- ProductTypeImportRequest
- ProductVariantImportRequest
- ProductVariantPatchRequest
description: |-
  Abstract base type for requesting the import of items.
properties:
  type:
    type: ResourceType
    (builtinType): string
    enum:
    - channel
    - cart-discount
    - category
    - customer
    - customer-group
    - order
    - price
    - product
    - product-type
    - product-variant
    - product-variant-patch
    - shipping-method
    - state
    - tax-category
    required: true