#%RAML 1.0 DataType
displayName: PriceImportRequest
type: ImportRequest
(builtinType): object
discriminatorValue: price
properties:
  type:
    type: ResourceType
    (builtinType): string
    enum:
    - price
    required: true
  resources:
    type: array
    items:
      type: PriceImport
    (builtinType): array
    description: |-
      The individual prices to import.
    required: true