#%RAML 1.0 DataType
displayName: ProductVariantPatchRequest
type: ImportRequest
(builtinType): object
discriminatorValue: product-variant-patch
properties:
  type:
    type: ResourceType
    (builtinType): string
    enum:
    - product-variant-patch
    required: true
  patches:
    type: array
    items:
      type: ProductVariantPatch
    (builtinType): array
    description: |-
      The individual product variant patches.
    required: true