#%RAML 1.0 DataType
displayName: ProductImportRequest
type: ImportRequest
(builtinType): object
discriminatorValue: product
properties:
  type:
    type: ResourceType
    (builtinType): string
    enum:
    - product
    required: true
  resources:
    type: array
    items:
      type: ProductImport
    (builtinType): array
    description: |-
      The individual products to import.
    required: true