#%RAML 1.0 DataType
displayName: CartChangeTaxRoundingModeAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: changeTaxRoundingMode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxRoundingMode
    required: true
  taxRoundingMode:
    type: RoundingMode
    (builtinType): string
    required: true