#%RAML 1.0 DataType
displayName: CartAddDiscountCodeAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: addDiscountCode
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addDiscountCode
    required: true
  code:
    type: string
    (builtinType): string
    required: true