#%RAML 1.0 DataType
displayName: CartSetLineItemPriceAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setLineItemPrice
examples:
  postman: !include ../../examples/Cart/CartSetLineItemPriceAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemPrice
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  externalPrice:
    type: Money
    (builtinType): object
    required: false