#%RAML 1.0 DataType
(builtinType): object
type: CartUpdateAction
displayName: CartAddShoppingListAction
discriminator: action
discriminatorValue: addShoppingList
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShoppingList
    required: true
  shoppingList:
    type: ShoppingListResourceIdentifier
    (builtinType): object
    required: true
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false
  distributionChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false