#%RAML 1.0 DataType
displayName: CartSetCustomerGroupAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCustomerGroup
examples:
  postman: !include ../../examples/Cart/CartSetCustomerGroupAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerGroup
    required: true
  customerGroup:
    type: CustomerGroupResourceIdentifier
    (builtinType): object
    required: false