#%RAML 1.0 DataType
displayName: CartChangeTaxCalculationModeAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: changeTaxCalculationMode
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#change-taxcalculationmode"
examples:
  postman:
    strict: true
    value: !include ../../examples/Cart/CartChangeTaxCalculationModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxCalculationMode
    required: true
  taxCalculationMode:
    type: TaxCalculationMode
    (builtinType): string
    enum:
    - LineItemLevel
    - UnitPriceLevel
    required: true