#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartSetLineItemCustomTypeAction

discriminatorValue: setLineItemCustomType
properties:
  action:
    required: true
    type: string
  lineItemId:
    required: true
    type: string
  fields:
    required: false
    type: FieldContainer
  type:
    required: false
    type: TypeResourceIdentifier