#%RAML 1.0 DataType
(builtinType): object
type: Reference
displayName: CartReference
discriminator: typeId
discriminatorValue: cart
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - cart
    required: true
  id:
    type: string
    (builtinType): string
    required: true
  obj:
    type: Cart
    (builtinType): object
    required: false