#%RAML 1.0 DataType
displayName: CartReference
type: Reference
(builtinType): object
discriminatorValue: cart
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - cart
    required: true
  obj:
    type: Cart
    (builtinType): object
    required: false