#%RAML 1.0 DataType
displayName: CartSetAnonymousIdAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setAnonymousId
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#set-anonymous-id"
examples:
  postman: !include ../../examples/Cart/CartSetAnonymousIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setAnonymousId
    required: true
  anonymousId:
    type: string
    (builtinType): string
    required: false