#%RAML 1.0 DataType
(builtinType): object
type: CartUpdateAction
displayName: CartRecalculateAction
discriminator: action
discriminatorValue: recalculate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - recalculate
    required: true
  updateProductData:
    type: boolean
    (builtinType): boolean
    required: false