#%RAML 1.0 DataType
displayName: CartSetShippingMethodTaxRateAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setShippingMethodTaxRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethodTaxRate
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false