#%RAML 1.0 DataType
displayName: CartChangeTaxModeAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: changeTaxMode
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#change-taxmode"
examples:
  postman:
    strict: true
    value: !include ../../examples/Cart/CartChangeTaxModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxMode
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    enum:
    - Platform
    - External
    - ExternalAmount
    - Disabled
    required: true