#%RAML 1.0 DataType
(builtinType): object
type: CartUpdateAction
displayName: CartSetCustomerEmailAction
discriminator: action
discriminatorValue: setCustomerEmail
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerEmail
    required: true
  email:
    type: string
    (builtinType): string
    required: true