#%RAML 1.0 DataType
displayName: CartChangeCustomLineItemMoneyAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: changeCustomLineItemMoney
examples:
  postman: !include ../../examples/Cart/CartChangeCustomLineItemMoneyAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeCustomLineItemMoney
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  money:
    type: Money
    (builtinType): object
    required: true