#%RAML 1.0 DataType
type: object
(originalType): object
displayName: CartDraft


properties:
  country:
    description: |-
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    type: string
  anonymousId:
    description: |-
      Assigns the new cart to an anonymous session (the customer has not signed up/in yet).
    type: string
  shippingRateInput:
    description: |-
      The shippingRateInput is used as an input to select a ShippingRatePriceTier.
      Based on the definition of ShippingRateInputType.
      If CartClassification is defined, it must be ClassificationShippingRateInput.
      If CartScore is defined, it must be ScoreShippingRateInput.
      Otherwise it can not bet set.
    type: ShippingRateInputDraft
  customerGroup:
    description: |-
      Will be set automatically when the `customerId` is set and the customer is a member of a customer group.
      Can be set explicitly when no `customerId` is present.
    type: CustomerGroupResourceIdentifier
  origin:
    description: |-
      The default origin is `Customer`.
    type: CartOrigin
  deleteDaysAfterLastModification:
    description: |-
      The cart will be deleted automatically if it hasn't been modified for the specified amount of days and it is in the `Active` CartState.
      If a ChangeSubscription for carts exists, a `ResourceDeleted` notification will be sent.
    format: int64
    type: number
  custom:
    description: |-
      The custom fields.
    type: CustomFieldsDraft
  shippingMethod:
    type: ShippingMethodResourceIdentifier
  taxCalculationMode:
    description: |-
      The default tax calculation mode is `LineItemLevel`.
    type: TaxCalculationMode
  store:
    description: |-
      Assigns the new cart to the store.
      The store assignment can not be modified.
    type: StoreResourceIdentifier
  locale:
    description: |-
      Must be one of the languages supported for this project
    type: string
  externalTaxRateForShippingMethod:
    description: |-
      An external tax rate can be set for the `shippingMethod` if the cart has the `External` TaxMode.
    type: ExternalTaxRateDraft
  inventoryMode:
    description: |-
      Default inventory mode is `None`.
    type: InventoryMode
  lineItems:
    type: array
    items:
      type: LineItemDraft
  taxRoundingMode:
    description: |-
      The default tax rounding mode is `HalfEven`.
    type: RoundingMode
  customLineItems:
    type: array
    items:
      type: CustomLineItemDraft
  itemShippingAddresses:
    description: |-
      Contains addresses for carts with multiple shipping addresses.
      Each address must contain a key which is unique in this cart.
      Line items will use these keys to reference the addresses under their `shippingDetails`.
      The addresses captured here are not used to determine eligible shipping methods or the applicable tax rate.
      Only the cart's `shippingAddress` is used for this.
    type: array
    items:
      type: Address
  taxMode:
    description: |-
      The default tax mode is `Platform`.
    type: TaxMode
  customerEmail:
    type: string
  customerId:
    description: |-
      Id of an existing Customer.
    type: string
  shippingAddress:
    description: |-
      The shipping address is used to determine the eligible shipping methods and rates as well as the tax rate of the line items.
    type: Address
  currency:
    description: |-
      A three-digit currency code as per [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    type: CurrencyCode
  billingAddress:
    type: Address