#%RAML 1.0 DataType
displayName: CartSetCustomerEmailAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCustomerEmail
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerEmail
    required: true
  email:
    type: string
    (builtinType): string
    required: true