#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartAddCustomLineItemAction
# discriminator: action
# discriminatorValue: addCustomLineItem
properties:
  action:
    default: addCustomLineItem
    required: true
    type: string
  externalTaxRate:
    required: false
    type: ExternalTaxRateDraft
  quantity:
    required: true
    type: number
  money:
    required: true
    type: Money
  custom:
    required: false
    type: CustomFieldsDraft
  name:
    required: true
    type: LocalizedString
  slug:
    required: true
    type: string
  taxCategory:
    required: false
    type: TaxCategoryResourceIdentifier