#%RAML 1.0 DataType
displayName: CartChangeLineItemQuantityAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: changeLineItemQuantity
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#change-lineitem-quantity"
examples:
  postman:
    strict: true
    value: !include ../../examples/Cart/CartChangeLineItemQuantityAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeLineItemQuantity
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  quantity:
    type: number
    (builtinType): number
    required: true
  externalPrice:
    type: Money
    (builtinType): object
    required: false
  externalTotalPrice:
    type: ExternalLineItemTotalPrice
    (builtinType): object
    required: false