#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartAddLineItemAction
# discriminator: action
# discriminatorValue: addLineItem
properties:
  action:
    default: addLineItem
    required: true
    type: string
  quantity:
    required: false
    type: number
  externalTaxRate:
    required: false
    type: ExternalTaxRateDraft
  shippingDetails:
    required: false
    type: ItemShippingDetailsDraft
  productId:
    required: false
    type: string
  externalTotalPrice:
    required: false
    type: ExternalLineItemTotalPrice
  custom:
    required: false
    type: CustomFieldsDraft
  supplyChannel:
    required: false
    type: ChannelResourceIdentifier
  variantId:
    required: false
    format: int64
    type: number
  sku:
    required: false
    type: string
  distributionChannel:
    required: false
    type: ChannelResourceIdentifier
  externalPrice:
    required: false
    type: Money