#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartSetCustomLineItemTaxAmountAction

discriminatorValue: setCustomLineItemTaxAmount
properties:
  action:
    required: true
    type: string
  customLineItemId:
    required: true
    type: string
  externalTaxAmount:
    required: false
    type: ExternalTaxAmountDraft