#%RAML 1.0 DataType
displayName: CartSetCustomLineItemShippingDetailsAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCustomLineItemShippingDetails
examples:
  postman: !include ../../examples/Cart/CartSetCustomLineItemShippingDetailsAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemShippingDetails
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false