#%RAML 1.0 DataType
displayName: CartSetLineItemTaxRateAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setLineItemTaxRate
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#set-lineitem-taxrate"
examples:
  postman: !include ../../examples/Cart/CartSetLineItemTaxRateAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemTaxRate
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false