#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartApplyDeltaToLineItemShippingDetailsTargetsAction

discriminatorValue: applyDeltaToLineItemShippingDetailsTargets
properties:
  action:
    required: true
    type: string
  lineItemId:
    required: true
    type: string
  targetsDelta:
    required: true
    type: array
    items:
      type: ItemShippingTarget