#%RAML 1.0 DataType
displayName: CartSetCustomLineItemShippingDetailsAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCustomLineItemShippingDetails
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#set-customlineitemshippingdetails"
examples:
  postman:
    strict: true
    value: !include ../../examples/Cart/CartSetCustomLineItemShippingDetailsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemShippingDetails
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    required: false