#%RAML 1.0 DataType
displayName: CartRemoveDiscountCodeAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: removeDiscountCode
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#remove-discountcode"
examples:
  postman:
    strict: true
    value: !include ../../examples/Cart/CartRemoveDiscountCodeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeDiscountCode
    required: true
  discountCode:
    type: DiscountCodeReference
    (builtinType): object
    required: true