#%RAML 1.0 DataType
(builtinType): object
type: CartUpdateAction
displayName: CartSetLineItemTaxRateAction
discriminator: action
discriminatorValue: setLineItemTaxRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setLineItemTaxRate
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false
  lineItemId:
    type: string
    (builtinType): string
    required: true