#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartChangeTaxRoundingModeAction
# discriminator: action
# discriminatorValue: changeTaxRoundingMode
properties:
  action:
    default: changeTaxRoundingMode
    required: true
    type: string
  taxRoundingMode:
    required: true
    type: RoundingMode