#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartSetLineItemTaxRateAction
# discriminator: action
# discriminatorValue: setLineItemTaxRate
properties:
  action:
    default: setLineItemTaxRate
    required: true
    type: string
  externalTaxRate:
    required: false
    type: ExternalTaxRateDraft
  lineItemId:
    required: true
    type: string