#%RAML 1.0 DataType
displayName: CartSetCustomLineItemCustomTypeAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCustomLineItemCustomType
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#set-customlineitem-custom-type"
examples:
  postman: !include ../../examples/Cart/CartSetCustomLineItemCustomTypeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomLineItemCustomType
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  type:
    type: TypeResourceIdentifier
    (builtinType): object
    required: false
  fields:
    type: FieldContainer
    (builtinType): object
    required: false