#%RAML 1.0 DataType
type: object
(originalType): CartUpdateAction
displayName: CartSetLineItemShippingDetailsAction
# discriminator: action
# discriminatorValue: setLineItemShippingDetails
properties:
  action:
    default: setLineItemShippingDetails
    required: true
    type: string
  shippingDetails:
    required: false
    type: ItemShippingDetailsDraft
  lineItemId:
    required: true
    type: string