#%RAML 1.0 DataType
displayName: CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: applyDeltaToCustomLineItemShippingDetailsTargets
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - applyDeltaToCustomLineItemShippingDetailsTargets
    required: true
  customLineItemId:
    type: string
    (builtinType): string
    required: true
  targetsDelta:
    type: array
    items:
      type: ItemShippingTarget
    (builtinType): array
    required: true