#%RAML 1.0 DataType
displayName: CartUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- CartAddCustomLineItemAction
- CartAddDiscountCodeAction
- CartAddItemShippingAddressAction
- CartAddLineItemAction
- CartAddPaymentAction
- CartAddShoppingListAction
- CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction
- CartApplyDeltaToLineItemShippingDetailsTargetsAction
- CartChangeCustomLineItemMoneyAction
- CartChangeCustomLineItemQuantityAction
- CartChangeLineItemQuantityAction
- CartChangeTaxCalculationModeAction
- CartChangeTaxModeAction
- CartChangeTaxRoundingModeAction
- CartRecalculateAction
- CartRemoveCustomLineItemAction
- CartRemoveDiscountCodeAction
- CartRemoveItemShippingAddressAction
- CartRemoveLineItemAction
- CartRemovePaymentAction
- CartSetAnonymousIdAction
- CartSetBillingAddressAction
- CartSetCartTotalTaxAction
- CartSetCountryAction
- CartSetCustomFieldAction
- CartSetCustomLineItemCustomFieldAction
- CartSetCustomLineItemCustomTypeAction
- CartSetCustomLineItemShippingDetailsAction
- CartSetCustomLineItemTaxAmountAction
- CartSetCustomLineItemTaxRateAction
- CartSetCustomShippingMethodAction
- CartSetCustomTypeAction
- CartSetCustomerEmailAction
- CartSetCustomerGroupAction
- CartSetCustomerIdAction
- CartSetDeleteDaysAfterLastModificationAction
- CartSetLineItemCustomFieldAction
- CartSetLineItemCustomTypeAction
- CartSetLineItemPriceAction
- CartSetLineItemShippingDetailsAction
- CartSetLineItemTaxAmountAction
- CartSetLineItemTaxRateAction
- CartSetLineItemTotalPriceAction
- CartSetLocaleAction
- CartSetShippingAddressAction
- CartSetShippingMethodAction
- CartSetShippingMethodTaxAmountAction
- CartSetShippingMethodTaxRateAction
- CartSetShippingRateInputAction
- CartUpdateItemShippingAddressAction
(package): "Cart"
properties:
  action:
    type: string
    (builtinType): string
    required: true