#%RAML 1.0 DataType
displayName: CartSetBillingAddressAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setBillingAddress
examples:
  postman: !include ../../examples/Cart/CartSetBillingAddressAction.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setBillingAddress
    required: true
  address:
    type: Address
    (builtinType): object
    required: false