#%RAML 1.0 DataType
displayName: CartSetCustomerEmailAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCustomerEmail
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#set-customer-email"
examples:
  postman:
    strict: true
    value: !include ../../examples/Cart/CartSetCustomerEmailAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerEmail
    required: true
  email:
    type: string
    (builtinType): string
    required: true