#%RAML 1.0 DataType
displayName: CartChangeTaxModeAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: changeTaxMode
examples:
  postman: !include ../../examples/Cart/CartChangeTaxModeAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - changeTaxMode
    required: true
  taxMode:
    type: TaxMode
    (builtinType): string
    required: true