#%RAML 1.0 DataType
(builtinType): object
type: CartUpdateAction
displayName: CartSetShippingMethodTaxRateAction
discriminator: action
discriminatorValue: setShippingMethodTaxRate
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setShippingMethodTaxRate
    required: true
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: false