#%RAML 1.0 DataType
displayName: CartApplyDeltaToLineItemShippingDetailsTargetsAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: applyDeltaToLineItemShippingDetailsTargets
examples:
  postman: !include ../../examples/Cart/CartApplyDeltaToLineItemShippingDetailsTargetsAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - applyDeltaToLineItemShippingDetailsTargets
    required: true
  lineItemId:
    type: string
    (builtinType): string
    required: true
  targetsDelta:
    type: array
    items:
      type: ItemShippingTarget
    (builtinType): array
    required: true