#%RAML 1.0 DataType
displayName: CartSetCartTotalTaxAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCartTotalTax
examples:
  postman: !include ../../examples/Cart/CartSetCartTotalTaxAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCartTotalTax
    required: true
  externalTotalGross:
    type: Money
    (builtinType): object
    required: true
  externalTaxPortions:
    type: array
    items:
      type: TaxPortionDraft
    (builtinType): array
    required: false