#%RAML 1.0 DataType
displayName: CartSetCustomerIdAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: setCustomerId
examples:
  postman: !include ../../examples/Cart/CartSetCustomerIdAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerId
    required: true
  customerId:
    type: string
    (builtinType): string
    required: false