#%RAML 1.0 DataType
(builtinType): object
type: CartUpdateAction
displayName: CartSetCustomerIdAction
discriminator: action
discriminatorValue: setCustomerId
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setCustomerId
    required: true
  customerId:
    type: string
    (builtinType): string
    required: false