#%RAML 1.0 DataType
displayName: CartRemoveItemShippingAddressAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: removeItemShippingAddress
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#remove-itemshippingaddress"
examples:
  postman: !include ../../examples/Cart/CartRemoveItemShippingAddressAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - removeItemShippingAddress
    required: true
  addressKey:
    type: string
    (builtinType): string
    required: true