#%RAML 1.0 DataType
displayName: CartAddShoppingListAction
type: CartUpdateAction
(builtinType): object
discriminatorValue: addShoppingList
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#add-shopping-list"
examples:
  postman:
    strict: true
    value: !include ../../examples/Cart/CartAddShoppingListAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - addShoppingList
    required: true
  shoppingList:
    type: ShoppingListResourceIdentifier
    (builtinType): object
    required: true
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false
  distributionChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    required: false