#%RAML 1.0 DataType
displayName: ClassificationShippingRateInputDraft
type: ShippingRateInputDraft
(builtinType): object
discriminatorValue: Classification
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Classification
    required: true
  key:
    type: string
    (builtinType): string
    required: true