#%RAML 1.0 DataType
(builtinType): object
type: ShippingRateInput
displayName: ClassificationShippingRateInput
discriminator: type
discriminatorValue: Classification
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Classification
    required: true
  label:
    type: LocalizedString
    (builtinType): object
    required: true
  key:
    type: string
    (builtinType): string
    required: true