#%RAML 1.0 DataType
displayName: ClassificationShippingRateInputDraft
type: ShippingRateInputDraft
(builtinType): object
discriminatorValue: Classification
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#classificationshippingrateinputdraft"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Classification
    required: true
  key:
    type: string
    (builtinType): string
    required: true