#%RAML 1.0 DataType
(builtinType): object
type: ShippingRateInputDraft
displayName: ClassificationShippingRateInputDraft
discriminator: type
discriminatorValue: Classification
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Classification
    required: true
  key:
    type: string
    (builtinType): string
    required: true