#%RAML 1.0 DataType
displayName: CustomLineItem
type: object
(builtinType): object
properties:
  id:
    type: string
    (builtinType): string
    description: |-
      The unique ID of this CustomLineItem.
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    description: |-
      The name of this CustomLineItem.
    required: true
  money:
    type: TypedMoney
    (builtinType): object
    description: |-
      The cost to add to the cart.
               The amount can be negative.
    required: true
  taxedPrice:
    type: TaxedItemPrice
    (builtinType): object
    description: |-
      Set once the `taxRate` is set.
    required: false
  totalPrice:
    type: TypedMoney
    (builtinType): object
    description: |-
      The total price of this custom line item.
               If custom line item is discounted, then the `totalPrice` would be the discounted custom line item price multiplied by `quantity`.
               Otherwise a total price is just a `money` multiplied by the `quantity`.
               `totalPrice` may or may not include the taxes: it depends on the taxRate.includedInPrice property.
    required: true
  slug:
    type: string
    (builtinType): string
    description: |-
      A unique String in the cart to identify this CustomLineItem.
    required: true
  quantity:
    format: int16
    type: number
    (builtinType): number
    description: |-
      The amount of a CustomLineItem in the cart.
               Must be a positive integer.
    required: true
  state:
    type: array
    items:
      type: ItemState
    (builtinType): array
    required: true
  taxCategory:
    type: TaxCategoryReference
    (builtinType): object
    required: false
  taxRate:
    type: TaxRate
    (builtinType): object
    description: |-
      Will be set automatically in the `Platform` TaxMode once the shipping address is set is set.
               For the `External` tax mode the tax rate has to be set explicitly with the ExternalTaxRateDraft.
    required: false
  discountedPricePerQuantity:
    type: array
    items:
      type: DiscountedLineItemPriceForQuantity
    (builtinType): array
    required: true
  custom:
    type: CustomFields
    (builtinType): object
    required: false
  shippingDetails:
    type: ItemShippingDetails
    (builtinType): object
    description: |-
      Container for custom line item specific address(es).
               CustomLineItem fields that can be used in query predicates: `slug`, `name`, `quantity`,
               `money`, `state`, `discountedPricePerQuantity`.
    required: false