#%RAML 1.0 DataType
displayName: DiscountedLineItemPriceForQuantity
type: object
(builtinType): object
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#discountedlineitempriceforquantity"
properties:
  quantity:
    format: float
    type: number
    (builtinType): number
    required: true
  discountedPrice:
    type: DiscountedLineItemPrice
    (builtinType): object
    required: true