#%RAML 1.0 DataType
displayName: DiscountedLineItemPortion
type: object
(builtinType): object
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#discountedlineitemportion"
properties:
  discount:
    discriminatorValue: "cart-discount"
    type: CartDiscountReference
    (builtinType): object
    required: true
  discountedAmount:
    type: TypedMoney
    (builtinType): object
    required: true