#%RAML 1.0 DataType
displayName: DiscountedLineItemPrice
type: object
(builtinType): object
properties:
  value:
    type: TypedMoney
    (builtinType): object
    required: true
  includedDiscounts:
    type: array
    items:
      type: DiscountedLineItemPortion
    (builtinType): array
    required: true