#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ExternalLineItemTotalPrice
properties:
  totalPrice:
    type: Money
    (builtinType): object
    required: true
  price:
    type: Money
    (builtinType): object
    required: true