#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: ExternalTaxAmountDraft
properties:
  taxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    required: true
  totalGross:
    type: Money
    (builtinType): object
    description: |-
      The total gross amount of the item (totalNet + taxes).
    required: true