#%RAML 1.0 DataType
displayName: ExternalLineItemTotalPrice
type: object
(builtinType): object
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#externallineitemtotalprice"
properties:
  price:
    type: Money
    (builtinType): object
    required: true
  totalPrice:
    type: Money
    (builtinType): object
    required: true