#%RAML 1.0 DataType
type: object
(originalType): object
displayName: LineItemDraft


properties:
  externalTaxRate:
    description: |-
      An external tax rate can be set if the cart has the `External` TaxMode.
    type: ExternalTaxRateDraft
  quantity:
    description: |-
      The amount of a `LineItem`in the cart.
      Must be a positive integer.
    format: int64
    type: number
  shippingDetails:
    description: |-
      Container for line item specific address(es).
    type: ItemShippingDetailsDraft
  productId:
    type: string
  externalTotalPrice:
    description: |-
      Sets the line item `price` and `totalPrice` to the given values and sets the line item `priceMode` to `ExternalTotal` LineItemPriceMode.
    type: ExternalLineItemTotalPrice
  custom:
    description: |-
      The custom fields.
    type: CustomFieldsDraft
  supplyChannel:
    description: |-
      By providing supply channel information, you can unique identify
      inventory entries that should be reserved.
      The provided channel should have
      the InventorySupply role.
    type: ChannelResourceIdentifier
  variantId:
    format: int64
    type: number
  distributionChannel:
    description: |-
      The channel is used to select a ProductPrice.
      The provided channel should have the ProductDistribution role.
    type: ChannelResourceIdentifier
  sku:
    type: string
  externalPrice:
    description: |-
      Sets the line item `price` to the given value and sets the line item `priceMode` to `ExternalPrice` LineItemPriceMode.
    type: Money