#%RAML 1.0 DataType
displayName: LineItemDraft
type: object
(builtinType): object
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#lineitemdraft"
(builder):
  - paramNames:
    - "productId"
    - "variantId"
    - "quantity"
  - paramNames:
    - "sku"
    - "quantity"
properties:
  productId:
    type: string
    (builtinType): string
    required: false
  variantId:
    format: int64
    type: integer
    (builtinType): integer
    required: false
  sku:
    type: string
    (builtinType): string
    required: false
  quantity:
    format: int64
    type: integer
    (builtinType): integer
    description: |-
      The amount of a `LineItem`in the cart.
      Must be a positive integer.
    default: 1
    required: false
  supplyChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    description: |-
      By providing supply channel information, you can unique identify
      inventory entries that should be reserved.
      The provided channel should have
      the InventorySupply role.
    required: false
  distributionChannel:
    type: ChannelResourceIdentifier
    (builtinType): object
    description: |-
      The channel is used to select a ProductPrice.
      The provided channel should have the ProductDistribution role.
    required: false
  externalTaxRate:
    type: ExternalTaxRateDraft
    (builtinType): object
    description: |-
      An external tax rate can be set if the cart has the `External` TaxMode.
    required: false
  custom:
    type: CustomFieldsDraft
    (builtinType): object
    description: |-
      The custom fields.
    required: false
  externalPrice:
    type: Money
    (builtinType): object
    description: |-
      Sets the line item `price` to the given value and sets the line item `priceMode` to `ExternalPrice` LineItemPriceMode.
    required: false
  externalTotalPrice:
    type: ExternalLineItemTotalPrice
    (builtinType): object
    description: |-
      Sets the line item `price` and `totalPrice` to the given values and sets the line item `priceMode` to `ExternalTotal` LineItemPriceMode.
    required: false
  shippingDetails:
    type: ItemShippingDetailsDraft
    (builtinType): object
    description: |-
      Container for line item specific address(es).
    required: false