#%RAML 1.0 DataType
displayName: ReplicaCartDraft
type: object
(builtinType): object
properties:
  reference:
    type: CartReference | OrderReference
    (oneOf):
    - CartReference
    - OrderReference
    (builtinType): any
    required: true