#%RAML 1.0 DataType
displayName: ReplicaCartDraft
type: object
(builtinType): object
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#replicacartdraft"
properties:
  reference:
    type: CartReference | OrderReference
    (oneOf):
    - CartReference
    - OrderReference
    (builtinType): any
    required: true