#%RAML 1.0 DataType
displayName: ScoreShippingRateInputDraft
type: ShippingRateInputDraft
(builtinType): object
discriminatorValue: Score
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#scoreshippingrateinputdraft"
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Score
    required: true
  score:
    type: number
    (builtinType): number
    required: true