#%RAML 1.0 DataType
type: object
(originalType): ShippingRateInput
displayName: ScoreShippingRateInput
# discriminator: type
# discriminatorValue: Score
properties:
  type:
    default: Score
    required: true
    type: string
  score:
    required: true
    type: number