#%RAML 1.0 DataType
displayName: ScoreShippingRateInputDraft
type: ShippingRateInputDraft
(builtinType): object
discriminatorValue: Score
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - Score
    required: true
  score:
    type: number
    (builtinType): number
    required: true