#%RAML 1.0 DataType
displayName: ShippingRateInputDraft
type: object
(builtinType): object
discriminator: type
(oneOf):
- ClassificationShippingRateInputDraft
- ScoreShippingRateInputDraft
properties:
  type:
    type: string
    (builtinType): string
    required: true