#%RAML 1.0 DataType
displayName: ShippingRateInput
type: object
(builtinType): object
discriminator: type
(oneOf):
- ClassificationShippingRateInput
- ScoreShippingRateInput
properties:
  type:
    type: string
    (builtinType): string
    required: true