#%RAML 1.0 DataType
displayName: ShippingRateInput
type: object
(builtinType): object
discriminator: type
(oneOf):
- ClassificationShippingRateInput
- ScoreShippingRateInput
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#shippingrateinput"
properties:
  type:
    type: string
    (builtinType): string
    required: true