#%RAML 1.0 DataType
type: object
(originalType): object
displayName: ShippingInfo


properties:
  taxRate:
    description: |-
      Will be set automatically in the `Platform` TaxMode once the shipping address is set is set.
      For the `External` tax mode the tax rate has to be set explicitly with the ExternalTaxRateDraft.
    type: TaxRate
  shippingRate:
    description: |-
      The shipping rate used to determine the price.
    type: ShippingRate
  discountedPrice:
    type: DiscountedLineItemPrice
  shippingMethodState:
    description: |-
      Indicates whether the ShippingMethod referenced in this ShippingInfo is allowed for the cart or not.
    type: ShippingMethodState
  taxedPrice:
    description: |-
      Set once the `taxRate` is set.
    type: TaxedItemPrice
  price:
    description: |-
      Determined based on the ShippingRate and its tiered prices, and either the sum of LineItem prices or the `shippingRateInput` field.
    type: TypedMoney
  shippingMethod:
    description: |-
      Not set if custom shipping method is used.
    type: ShippingMethodReference
  shippingMethodName:
    type: string
  deliveries:
    description: |-
      Deliveries are compilations of information on how the articles are being delivered to the customers.
    type: array
    items:
      type: Delivery
  taxCategory:
    type: TaxCategoryReference