#%RAML 1.0 DataType
displayName: TaxedItemPrice
type: object
(builtinType): object
(package): "Cart"
properties:
  totalNet:
    type: TypedMoney
    (builtinType): object
    required: true
  totalGross:
    type: TypedMoney
    (builtinType): object
    description: |-
      TaxedItemPrice fields can not be used in query predicates.
    required: true