#%RAML 1.0 DataType
displayName: TaxedPriceDraft
type: object
(builtinType): object
properties:
  taxPortions:
    type: array
    items:
      type: TaxPortionDraft
    (builtinType): array
    required: true
  totalGross:
    type: TypedMoneyDraft
    (builtinType): object
    required: true
  totalNet:
    type: TypedMoneyDraft
    (builtinType): object
    required: true