#%RAML 1.0 DataType
(builtinType): object
type: object
displayName: TaxedPrice
properties:
  taxPortions:
    type: array
    items:
      type: TaxPortion
    (builtinType): array
    description: |-
      TaxedPrice fields that can be used in query predicates: `totalNet`, `totalGross`.
    required: true
  totalGross:
    type: TypedMoney
    (builtinType): object
    required: true
  totalNet:
    type: TypedMoney
    (builtinType): object
    required: true