#%RAML 1.0 DataType
displayName: TaxPortionDraft
type: object
(builtinType): object
properties:
  name:
    type: string
    (builtinType): string
    required: false
  rate:
    format: int16
    minimum: 0
    maximum: 1
    type: integer
    (builtinType): integer
    required: true
  amount:
    type: Money
    (builtinType): object
    required: true