#%RAML 1.0 DataType
displayName: TaxPortionDraft
type: object
(builtinType): object
properties:
  amount:
    type: Money
    (builtinType): object
    required: true
  rate:
    format: int16
    minimum: 0
    maximum: 1
    type: number
    (builtinType): number
    required: true
  name:
    type: string
    (builtinType): string
    required: false