#%RAML 1.0 DataType
displayName: TaxPortion
type: object
(builtinType): object
properties:
  name:
    type: string
    (builtinType): string
    required: false
  rate:
    format: int16
    minimum: 0
    maximum: 1
    type: integer
    (builtinType): integer
    description: |-
      A number in the range [0..1]
    required: true
  amount:
    type: TypedMoney
    (builtinType): object
    required: true