#%RAML 1.0 DataType
displayName: TaxPortionDraft
type: object
(builtinType): object
(package): "Cart"
(docs-uri): "https://docs.commercetools.com/http-api-projects-carts.html#taxportion"
properties:
  name:
    type: string
    (builtinType): string
    required: false
  rate:
    format: float
    minimum: 0
    maximum: 1
    type: number
    (builtinType): number
    required: true
  amount:
    type: Money
    (builtinType): object
    required: true