#%RAML 1.0 DataType
displayName: StoreResourceIdentifier
type: ResourceIdentifier
(builtinType): object
discriminatorValue: store
properties:
  typeId:
    type: ReferenceTypeId
    (builtinType): string
    enum:
    - store
    required: false