#%RAML 1.0 DataType
type: object
(originalType): Reference
displayName: StoreReference
# discriminator: typeId
# discriminatorValue: store
properties:
  typeId:
    default: store
    required: true
    type: ReferenceTypeId
  id:
    required: true
    type: string
  obj:
    required: false
    type: Store