#%RAML 1.0 DataType
displayName: StoreSetNameAction
type: StoreUpdateAction
(builtinType): object
discriminatorValue: setName
(package): "Store"
(docs-uri): "https://docs.commercetools.com/http-api-projects-stores#set-name"
examples:
  postman:
    strict: true
    value: !include ../../examples/Store/StoreSetNameAction-postman.json
properties:
  action:
    type: string
    (builtinType): string
    enum:
    - setName
    required: true
  name:
    type: LocalizedString
    (builtinType): object
    description: |-
      The updated name of the store
    required: false