#%RAML 1.0 DataType
type: object
(originalType): ResourceIdentifier
displayName: StoreResourceIdentifier
# discriminator: typeId
# discriminatorValue: store
properties:
  typeId:
    default: store
    required: false
    type: ReferenceTypeId
  id:
    required: false
    type: string
  key:
    required: false
    type: string