#%RAML 1.0 DataType
displayName: StoreUpdateAction
type: object
(builtinType): object
discriminator: action
(oneOf):
- StoreSetNameAction
properties:
  action:
    type: string
    (builtinType): string
    required: true