#%RAML 1.0 DataType
type: object
(originalType): StoreUpdateAction
displayName: StoreSetNameAction
# discriminator: action
# discriminatorValue: setName
properties:
  action:
    default: setName
    required: true
    type: string
  name:
    required: false
    type: LocalizedString