#%RAML 1.0
---
title: Commercetools
types:
  PagedQueryResponse: !include types/Common/PagedQueryResponse.raml
  Update: !include types/Common/Update.raml
  UpdateAction: !include types/Common/UpdateAction.raml
  ApiClient: !include types/ApiClient/ApiClient.raml
  ApiClientDraft: !include types/ApiClient/ApiClientDraft.raml
  ApiClientPagedQueryResponse: !include types/ApiClient/ApiClientPagedQueryResponse.raml
  CartDiscount: !include types/CartDiscount/CartDiscount.raml
  CartDiscountCustomLineItemsTarget: !include types/CartDiscount/CartDiscountCustomLineItemsTarget.raml
  CartDiscountDraft: !include types/CartDiscount/CartDiscountDraft.raml
  CartDiscountLineItemsTarget: !include types/CartDiscount/CartDiscountLineItemsTarget.raml
  CartDiscountPagedQueryResponse: !include types/CartDiscount/CartDiscountPagedQueryResponse.raml
  CartDiscountReference: !include types/CartDiscount/CartDiscountReference.raml
  CartDiscountResourceIdentifier: !include types/CartDiscount/CartDiscountResourceIdentifier.raml
  CartDiscountShippingCostTarget: !include types/CartDiscount/CartDiscountShippingCostTarget.raml
  CartDiscountTarget: !include types/CartDiscount/CartDiscountTarget.raml
  CartDiscountUpdate: !include types/CartDiscount/CartDiscountUpdate.raml
  CartDiscountUpdateAction: !include types/CartDiscount/CartDiscountUpdateAction.raml
  CartDiscountValue: !include types/CartDiscount/CartDiscountValue.raml
  CartDiscountValueAbsolute: !include types/CartDiscount/CartDiscountValueAbsolute.raml
  CartDiscountValueAbsoluteDraft: !include types/CartDiscount/CartDiscountValueAbsoluteDraft.raml
  CartDiscountValueDraft: !include types/CartDiscount/CartDiscountValueDraft.raml
  CartDiscountValueGiftLineItem: !include types/CartDiscount/CartDiscountValueGiftLineItem.raml
  CartDiscountValueGiftLineItemDraft: !include types/CartDiscount/CartDiscountValueGiftLineItemDraft.raml
  CartDiscountValueRelative: !include types/CartDiscount/CartDiscountValueRelative.raml
  CartDiscountValueRelativeDraft: !include types/CartDiscount/CartDiscountValueRelativeDraft.raml
  MultiBuyCustomLineItemsTarget: !include types/CartDiscount/MultiBuyCustomLineItemsTarget.raml
  MultiBuyLineItemsTarget: !include types/CartDiscount/MultiBuyLineItemsTarget.raml
  SelectionMode: !include types/CartDiscount/SelectionMode.raml
  StackingMode: !include types/CartDiscount/StackingMode.raml
  CartDiscountChangeCartPredicateAction: !include types/CartDiscount/CartDiscountChangeCartPredicateAction.raml
  CartDiscountChangeIsActiveAction: !include types/CartDiscount/CartDiscountChangeIsActiveAction.raml
  CartDiscountChangeNameAction: !include types/CartDiscount/CartDiscountChangeNameAction.raml
  CartDiscountChangeRequiresDiscountCodeAction: !include types/CartDiscount/CartDiscountChangeRequiresDiscountCodeAction.raml
  CartDiscountChangeSortOrderAction: !include types/CartDiscount/CartDiscountChangeSortOrderAction.raml
  CartDiscountChangeStackingModeAction: !include types/CartDiscount/CartDiscountChangeStackingModeAction.raml
  CartDiscountChangeTargetAction: !include types/CartDiscount/CartDiscountChangeTargetAction.raml
  CartDiscountChangeValueAction: !include types/CartDiscount/CartDiscountChangeValueAction.raml
  CartDiscountSetCustomFieldAction: !include types/CartDiscount/CartDiscountSetCustomFieldAction.raml
  CartDiscountSetCustomTypeAction: !include types/CartDiscount/CartDiscountSetCustomTypeAction.raml
  CartDiscountSetDescriptionAction: !include types/CartDiscount/CartDiscountSetDescriptionAction.raml
  CartDiscountSetKeyAction: !include types/CartDiscount/CartDiscountSetKeyAction.raml
  CartDiscountSetValidFromAction: !include types/CartDiscount/CartDiscountSetValidFromAction.raml
  CartDiscountSetValidFromAndUntilAction: !include types/CartDiscount/CartDiscountSetValidFromAndUntilAction.raml
  CartDiscountSetValidUntilAction: !include types/CartDiscount/CartDiscountSetValidUntilAction.raml
  Cart: !include types/Cart/Cart.raml
  CartDraft: !include types/Cart/CartDraft.raml
  CartOrigin: !include types/Cart/CartOrigin.raml
  CartPagedQueryResponse: !include types/Cart/CartPagedQueryResponse.raml
  CartReference: !include types/Cart/CartReference.raml
  CartResourceIdentifier: !include types/Cart/CartResourceIdentifier.raml
  CartState: !include types/Cart/CartState.raml
  CartUpdate: !include types/Cart/CartUpdate.raml
  CartUpdateAction: !include types/Cart/CartUpdateAction.raml
  ClassificationShippingRateInput: !include types/Cart/ClassificationShippingRateInput.raml
  ClassificationShippingRateInputDraft: !include types/Cart/ClassificationShippingRateInputDraft.raml
  CustomLineItem: !include types/Cart/CustomLineItem.raml
  CustomLineItemDraft: !include types/Cart/CustomLineItemDraft.raml
  DiscountCodeInfo: !include types/Cart/DiscountCodeInfo.raml
  DiscountCodeState: !include types/Cart/DiscountCodeState.raml
  DiscountedLineItemPortion: !include types/Cart/DiscountedLineItemPortion.raml
  DiscountedLineItemPrice: !include types/Cart/DiscountedLineItemPrice.raml
  DiscountedLineItemPriceForQuantity: !include types/Cart/DiscountedLineItemPriceForQuantity.raml
  ExternalLineItemTotalPrice: !include types/Cart/ExternalLineItemTotalPrice.raml
  ExternalTaxAmountDraft: !include types/Cart/ExternalTaxAmountDraft.raml
  ExternalTaxRateDraft: !include types/Cart/ExternalTaxRateDraft.raml
  InventoryMode: !include types/Cart/InventoryMode.raml
  ItemShippingDetails: !include types/Cart/ItemShippingDetails.raml
  ItemShippingDetailsDraft: !include types/Cart/ItemShippingDetailsDraft.raml
  ItemShippingTarget: !include types/Cart/ItemShippingTarget.raml
  LineItem: !include types/Cart/LineItem.raml
  LineItemDraft: !include types/Cart/LineItemDraft.raml
  LineItemMode: !include types/Cart/LineItemMode.raml
  LineItemPriceMode: !include types/Cart/LineItemPriceMode.raml
  ReplicaCartDraft: !include types/Cart/ReplicaCartDraft.raml
  RoundingMode: !include types/Cart/RoundingMode.raml
  ScoreShippingRateInput: !include types/Cart/ScoreShippingRateInput.raml
  ScoreShippingRateInputDraft: !include types/Cart/ScoreShippingRateInputDraft.raml
  ShippingInfo: !include types/Cart/ShippingInfo.raml
  ShippingMethodState: !include types/Cart/ShippingMethodState.raml
  ShippingRateInput: !include types/Cart/ShippingRateInput.raml
  ShippingRateInputDraft: !include types/Cart/ShippingRateInputDraft.raml
  TaxCalculationMode: !include types/Cart/TaxCalculationMode.raml
  TaxMode: !include types/Cart/TaxMode.raml
  TaxPortion: !include types/Cart/TaxPortion.raml
  TaxPortionDraft: !include types/Cart/TaxPortionDraft.raml
  TaxedItemPrice: !include types/Cart/TaxedItemPrice.raml
  TaxedPrice: !include types/Cart/TaxedPrice.raml
  TaxedPriceDraft: !include types/Cart/TaxedPriceDraft.raml
  CartAddCustomLineItemAction: !include types/Cart/CartAddCustomLineItemAction.raml
  CartAddDiscountCodeAction: !include types/Cart/CartAddDiscountCodeAction.raml
  CartAddItemShippingAddressAction: !include types/Cart/CartAddItemShippingAddressAction.raml
  CartAddLineItemAction: !include types/Cart/CartAddLineItemAction.raml
  CartAddPaymentAction: !include types/Cart/CartAddPaymentAction.raml
  CartAddShoppingListAction: !include types/Cart/CartAddShoppingListAction.raml
  CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction: !include types/Cart/CartApplyDeltaToCustomLineItemShippingDetailsTargetsAction.raml
  CartApplyDeltaToLineItemShippingDetailsTargetsAction: !include types/Cart/CartApplyDeltaToLineItemShippingDetailsTargetsAction.raml
  CartChangeCustomLineItemMoneyAction: !include types/Cart/CartChangeCustomLineItemMoneyAction.raml
  CartChangeCustomLineItemQuantityAction: !include types/Cart/CartChangeCustomLineItemQuantityAction.raml
  CartChangeLineItemQuantityAction: !include types/Cart/CartChangeLineItemQuantityAction.raml
  CartChangeTaxCalculationModeAction: !include types/Cart/CartChangeTaxCalculationModeAction.raml
  CartChangeTaxModeAction: !include types/Cart/CartChangeTaxModeAction.raml
  CartChangeTaxRoundingModeAction: !include types/Cart/CartChangeTaxRoundingModeAction.raml
  CartRecalculateAction: !include types/Cart/CartRecalculateAction.raml
  CartRemoveCustomLineItemAction: !include types/Cart/CartRemoveCustomLineItemAction.raml
  CartRemoveDiscountCodeAction: !include types/Cart/CartRemoveDiscountCodeAction.raml
  CartRemoveItemShippingAddressAction: !include types/Cart/CartRemoveItemShippingAddressAction.raml
  CartRemoveLineItemAction: !include types/Cart/CartRemoveLineItemAction.raml
  CartRemovePaymentAction: !include types/Cart/CartRemovePaymentAction.raml
  CartSetAnonymousIdAction: !include types/Cart/CartSetAnonymousIdAction.raml
  CartSetBillingAddressAction: !include types/Cart/CartSetBillingAddressAction.raml
  CartSetCartTotalTaxAction: !include types/Cart/CartSetCartTotalTaxAction.raml
  CartSetCountryAction: !include types/Cart/CartSetCountryAction.raml
  CartSetCustomFieldAction: !include types/Cart/CartSetCustomFieldAction.raml
  CartSetCustomLineItemCustomFieldAction: !include types/Cart/CartSetCustomLineItemCustomFieldAction.raml
  CartSetCustomLineItemCustomTypeAction: !include types/Cart/CartSetCustomLineItemCustomTypeAction.raml
  CartSetCustomLineItemShippingDetailsAction: !include types/Cart/CartSetCustomLineItemShippingDetailsAction.raml
  CartSetCustomLineItemTaxAmountAction: !include types/Cart/CartSetCustomLineItemTaxAmountAction.raml
  CartSetCustomLineItemTaxRateAction: !include types/Cart/CartSetCustomLineItemTaxRateAction.raml
  CartSetCustomShippingMethodAction: !include types/Cart/CartSetCustomShippingMethodAction.raml
  CartSetCustomTypeAction: !include types/Cart/CartSetCustomTypeAction.raml
  CartSetCustomerEmailAction: !include types/Cart/CartSetCustomerEmailAction.raml
  CartSetCustomerGroupAction: !include types/Cart/CartSetCustomerGroupAction.raml
  CartSetCustomerIdAction: !include types/Cart/CartSetCustomerIdAction.raml
  CartSetDeleteDaysAfterLastModificationAction: !include types/Cart/CartSetDeleteDaysAfterLastModificationAction.raml
  CartSetLineItemCustomFieldAction: !include types/Cart/CartSetLineItemCustomFieldAction.raml
  CartSetLineItemCustomTypeAction: !include types/Cart/CartSetLineItemCustomTypeAction.raml
  CartSetLineItemPriceAction: !include types/Cart/CartSetLineItemPriceAction.raml
  CartSetLineItemShippingDetailsAction: !include types/Cart/CartSetLineItemShippingDetailsAction.raml
  CartSetLineItemTaxAmountAction: !include types/Cart/CartSetLineItemTaxAmountAction.raml
  CartSetLineItemTaxRateAction: !include types/Cart/CartSetLineItemTaxRateAction.raml
  CartSetLineItemTotalPriceAction: !include types/Cart/CartSetLineItemTotalPriceAction.raml
  CartSetLocaleAction: !include types/Cart/CartSetLocaleAction.raml
  CartSetShippingAddressAction: !include types/Cart/CartSetShippingAddressAction.raml
  CartSetShippingMethodAction: !include types/Cart/CartSetShippingMethodAction.raml
  CartSetShippingMethodTaxAmountAction: !include types/Cart/CartSetShippingMethodTaxAmountAction.raml
  CartSetShippingMethodTaxRateAction: !include types/Cart/CartSetShippingMethodTaxRateAction.raml
  CartSetShippingRateInputAction: !include types/Cart/CartSetShippingRateInputAction.raml
  CartUpdateItemShippingAddressAction: !include types/Cart/CartUpdateItemShippingAddressAction.raml
  Category: !include types/Category/Category.raml
  CategoryDraft: !include types/Category/CategoryDraft.raml
  CategoryPagedQueryResponse: !include types/Category/CategoryPagedQueryResponse.raml
  CategoryReference: !include types/Category/CategoryReference.raml
  CategoryResourceIdentifier: !include types/Category/CategoryResourceIdentifier.raml
  CategoryUpdate: !include types/Category/CategoryUpdate.raml
  CategoryUpdateAction: !include types/Category/CategoryUpdateAction.raml
  CategoryAddAssetAction: !include types/Category/CategoryAddAssetAction.raml
  CategoryChangeAssetNameAction: !include types/Category/CategoryChangeAssetNameAction.raml
  CategoryChangeAssetOrderAction: !include types/Category/CategoryChangeAssetOrderAction.raml
  CategoryChangeNameAction: !include types/Category/CategoryChangeNameAction.raml
  CategoryChangeOrderHintAction: !include types/Category/CategoryChangeOrderHintAction.raml
  CategoryChangeParentAction: !include types/Category/CategoryChangeParentAction.raml
  CategoryChangeSlugAction: !include types/Category/CategoryChangeSlugAction.raml
  CategoryRemoveAssetAction: !include types/Category/CategoryRemoveAssetAction.raml
  CategorySetAssetCustomFieldAction: !include types/Category/CategorySetAssetCustomFieldAction.raml
  CategorySetAssetCustomTypeAction: !include types/Category/CategorySetAssetCustomTypeAction.raml
  CategorySetAssetDescriptionAction: !include types/Category/CategorySetAssetDescriptionAction.raml
  CategorySetAssetKeyAction: !include types/Category/CategorySetAssetKeyAction.raml
  CategorySetAssetSourcesAction: !include types/Category/CategorySetAssetSourcesAction.raml
  CategorySetAssetTagsAction: !include types/Category/CategorySetAssetTagsAction.raml
  CategorySetCustomFieldAction: !include types/Category/CategorySetCustomFieldAction.raml
  CategorySetCustomTypeAction: !include types/Category/CategorySetCustomTypeAction.raml
  CategorySetDescriptionAction: !include types/Category/CategorySetDescriptionAction.raml
  CategorySetExternalIdAction: !include types/Category/CategorySetExternalIdAction.raml
  CategorySetKeyAction: !include types/Category/CategorySetKeyAction.raml
  CategorySetMetaDescriptionAction: !include types/Category/CategorySetMetaDescriptionAction.raml
  CategorySetMetaKeywordsAction: !include types/Category/CategorySetMetaKeywordsAction.raml
  CategorySetMetaTitleAction: !include types/Category/CategorySetMetaTitleAction.raml
  Channel: !include types/Channel/Channel.raml
  ChannelDraft: !include types/Channel/ChannelDraft.raml
  ChannelPagedQueryResponse: !include types/Channel/ChannelPagedQueryResponse.raml
  ChannelReference: !include types/Channel/ChannelReference.raml
  ChannelResourceIdentifier: !include types/Channel/ChannelResourceIdentifier.raml
  ChannelRoleEnum: !include types/Channel/ChannelRoleEnum.raml
  ChannelUpdate: !include types/Channel/ChannelUpdate.raml
  ChannelUpdateAction: !include types/Channel/ChannelUpdateAction.raml
  ChannelAddRolesAction: !include types/Channel/ChannelAddRolesAction.raml
  ChannelChangeDescriptionAction: !include types/Channel/ChannelChangeDescriptionAction.raml
  ChannelChangeKeyAction: !include types/Channel/ChannelChangeKeyAction.raml
  ChannelChangeNameAction: !include types/Channel/ChannelChangeNameAction.raml
  ChannelRemoveRolesAction: !include types/Channel/ChannelRemoveRolesAction.raml
  ChannelSetAddressAction: !include types/Channel/ChannelSetAddressAction.raml
  ChannelSetCustomFieldAction: !include types/Channel/ChannelSetCustomFieldAction.raml
  ChannelSetCustomTypeAction: !include types/Channel/ChannelSetCustomTypeAction.raml
  ChannelSetGeoLocationAction: !include types/Channel/ChannelSetGeoLocationAction.raml
  ChannelSetRolesAction: !include types/Channel/ChannelSetRolesAction.raml
  Address: !include types/Common/Address.raml
  Asset: !include types/Common/Asset.raml
  AssetDimensions: !include types/Common/AssetDimensions.raml
  AssetDraft: !include types/Common/AssetDraft.raml
  AssetSource: !include types/Common/AssetSource.raml
  BaseResource: !include types/Common/BaseResource.raml
  CentPrecisionMoney: !include types/Common/CentPrecisionMoney.raml
  CentPrecisionMoneyDraft: !include types/Common/CentPrecisionMoneyDraft.raml
  ClientLogging: !include types/Common/ClientLogging.raml
  CountryCode: !include 
  CreatedBy: !include types/Common/CreatedBy.raml
  CurrencyCode: !include 
  DiscountedPrice: !include types/Common/DiscountedPrice.raml
  GeoJson: !include types/Common/GeoJson.raml
  GeoJsonPoint: !include types/Common/GeoJsonPoint.raml
  HighPrecisionMoney: !include types/Common/HighPrecisionMoney.raml
  HighPrecisionMoneyDraft: !include types/Common/HighPrecisionMoneyDraft.raml
  Image: !include types/Common/Image.raml
  ImageDimensions: !include types/Common/ImageDimensions.raml
  KeyReference: !include types/Common/KeyReference.raml
  LastModifiedBy: !include types/Common/LastModifiedBy.raml
  Locale: !include 
  LocalizedString: !include types/Common/LocalizedString.raml
  LoggedResource: !include types/Common/LoggedResource.raml
  Money: !include types/Common/Money.raml
  MoneyType: !include types/Common/MoneyType.raml
  Price: !include types/Common/Price.raml
  PriceDraft: !include types/Common/PriceDraft.raml
  PriceTier: !include types/Common/PriceTier.raml
  PriceTierDraft: !include types/Common/PriceTierDraft.raml
  QueryPrice: !include types/Common/QueryPrice.raml
  Reference: !include types/Common/Reference.raml
  ReferenceTypeId: !include types/Common/ReferenceTypeId.raml
  ResourceIdentifier: !include types/Common/ResourceIdentifier.raml
  ScopedPrice: !include types/Common/ScopedPrice.raml
  TypedMoney: !include types/Common/TypedMoney.raml
  TypedMoneyDraft: !include types/Common/TypedMoneyDraft.raml
  CustomObject: !include types/CustomObject/CustomObject.raml
  CustomObjectDraft: !include types/CustomObject/CustomObjectDraft.raml
  CustomObjectPagedQueryResponse: !include types/CustomObject/CustomObjectPagedQueryResponse.raml
  CustomObjectReference: !include types/CustomObject/CustomObjectReference.raml
  CustomerGroup: !include types/CustomerGroup/CustomerGroup.raml
  CustomerGroupDraft: !include types/CustomerGroup/CustomerGroupDraft.raml
  CustomerGroupPagedQueryResponse: !include types/CustomerGroup/CustomerGroupPagedQueryResponse.raml
  CustomerGroupReference: !include types/CustomerGroup/CustomerGroupReference.raml
  CustomerGroupResourceIdentifier: !include types/CustomerGroup/CustomerGroupResourceIdentifier.raml
  CustomerGroupUpdate: !include types/CustomerGroup/CustomerGroupUpdate.raml
  CustomerGroupUpdateAction: !include types/CustomerGroup/CustomerGroupUpdateAction.raml
  CustomerGroupChangeNameAction: !include types/CustomerGroup/CustomerGroupChangeNameAction.raml
  CustomerGroupSetCustomFieldAction: !include types/CustomerGroup/CustomerGroupSetCustomFieldAction.raml
  CustomerGroupSetCustomTypeAction: !include types/CustomerGroup/CustomerGroupSetCustomTypeAction.raml
  CustomerGroupSetKeyAction: !include types/CustomerGroup/CustomerGroupSetKeyAction.raml
  AnonymousCartSignInMode: !include types/Customer/AnonymousCartSignInMode.raml
  Customer: !include types/Customer/Customer.raml
  CustomerChangePassword: !include types/Customer/CustomerChangePassword.raml
  CustomerCreateEmailToken: !include types/Customer/CustomerCreateEmailToken.raml
  CustomerCreatePasswordResetToken: !include types/Customer/CustomerCreatePasswordResetToken.raml
  CustomerDraft: !include types/Customer/CustomerDraft.raml
  CustomerEmailVerify: !include types/Customer/CustomerEmailVerify.raml
  CustomerPagedQueryResponse: !include types/Customer/CustomerPagedQueryResponse.raml
  CustomerReference: !include types/Customer/CustomerReference.raml
  CustomerResetPassword: !include types/Customer/CustomerResetPassword.raml
  CustomerResourceIdentifier: !include types/Customer/CustomerResourceIdentifier.raml
  CustomerSignInResult: !include types/Customer/CustomerSignInResult.raml
  CustomerSignin: !include types/Customer/CustomerSignin.raml
  CustomerToken: !include types/Customer/CustomerToken.raml
  CustomerUpdate: !include types/Customer/CustomerUpdate.raml
  CustomerUpdateAction: !include types/Customer/CustomerUpdateAction.raml
  CustomerAddAddressAction: !include types/Customer/CustomerAddAddressAction.raml
  CustomerAddBillingAddressIdAction: !include types/Customer/CustomerAddBillingAddressIdAction.raml
  CustomerAddShippingAddressIdAction: !include types/Customer/CustomerAddShippingAddressIdAction.raml
  CustomerChangeAddressAction: !include types/Customer/CustomerChangeAddressAction.raml
  CustomerChangeEmailAction: !include types/Customer/CustomerChangeEmailAction.raml
  CustomerRemoveAddressAction: !include types/Customer/CustomerRemoveAddressAction.raml
  CustomerRemoveBillingAddressIdAction: !include types/Customer/CustomerRemoveBillingAddressIdAction.raml
  CustomerRemoveShippingAddressIdAction: !include types/Customer/CustomerRemoveShippingAddressIdAction.raml
  CustomerSetCompanyNameAction: !include types/Customer/CustomerSetCompanyNameAction.raml
  CustomerSetCustomFieldAction: !include types/Customer/CustomerSetCustomFieldAction.raml
  CustomerSetCustomTypeAction: !include types/Customer/CustomerSetCustomTypeAction.raml
  CustomerSetCustomerGroupAction: !include types/Customer/CustomerSetCustomerGroupAction.raml
  CustomerSetCustomerNumberAction: !include types/Customer/CustomerSetCustomerNumberAction.raml
  CustomerSetDateOfBirthAction: !include types/Customer/CustomerSetDateOfBirthAction.raml
  CustomerSetDefaultBillingAddressAction: !include types/Customer/CustomerSetDefaultBillingAddressAction.raml
  CustomerSetDefaultShippingAddressAction: !include types/Customer/CustomerSetDefaultShippingAddressAction.raml
  CustomerSetExternalIdAction: !include types/Customer/CustomerSetExternalIdAction.raml
  CustomerSetFirstNameAction: !include types/Customer/CustomerSetFirstNameAction.raml
  CustomerSetKeyAction: !include types/Customer/CustomerSetKeyAction.raml
  CustomerSetLastNameAction: !include types/Customer/CustomerSetLastNameAction.raml
  CustomerSetLocaleAction: !include types/Customer/CustomerSetLocaleAction.raml
  CustomerSetMiddleNameAction: !include types/Customer/CustomerSetMiddleNameAction.raml
  CustomerSetSalutationAction: !include types/Customer/CustomerSetSalutationAction.raml
  CustomerSetTitleAction: !include types/Customer/CustomerSetTitleAction.raml
  CustomerSetVatIdAction: !include types/Customer/CustomerSetVatIdAction.raml
  DiscountCode: !include types/DiscountCode/DiscountCode.raml
  DiscountCodeDraft: !include types/DiscountCode/DiscountCodeDraft.raml
  DiscountCodePagedQueryResponse: !include types/DiscountCode/DiscountCodePagedQueryResponse.raml
  DiscountCodeReference: !include types/DiscountCode/DiscountCodeReference.raml
  DiscountCodeResourceIdentifier: !include types/DiscountCode/DiscountCodeResourceIdentifier.raml
  DiscountCodeUpdate: !include types/DiscountCode/DiscountCodeUpdate.raml
  DiscountCodeUpdateAction: !include types/DiscountCode/DiscountCodeUpdateAction.raml
  DiscountCodeChangeCartDiscountsAction: !include types/DiscountCode/DiscountCodeChangeCartDiscountsAction.raml
  DiscountCodeChangeGroupsAction: !include types/DiscountCode/DiscountCodeChangeGroupsAction.raml
  DiscountCodeChangeIsActiveAction: !include types/DiscountCode/DiscountCodeChangeIsActiveAction.raml
  DiscountCodeSetCartPredicateAction: !include types/DiscountCode/DiscountCodeSetCartPredicateAction.raml
  DiscountCodeSetCustomFieldAction: !include types/DiscountCode/DiscountCodeSetCustomFieldAction.raml
  DiscountCodeSetCustomTypeAction: !include types/DiscountCode/DiscountCodeSetCustomTypeAction.raml
  DiscountCodeSetDescriptionAction: !include types/DiscountCode/DiscountCodeSetDescriptionAction.raml
  DiscountCodeSetMaxApplicationsAction: !include types/DiscountCode/DiscountCodeSetMaxApplicationsAction.raml
  DiscountCodeSetMaxApplicationsPerCustomerAction: !include types/DiscountCode/DiscountCodeSetMaxApplicationsPerCustomerAction.raml
  DiscountCodeSetNameAction: !include types/DiscountCode/DiscountCodeSetNameAction.raml
  DiscountCodeSetValidFromAction: !include types/DiscountCode/DiscountCodeSetValidFromAction.raml
  DiscountCodeSetValidFromAndUntilAction: !include types/DiscountCode/DiscountCodeSetValidFromAndUntilAction.raml
  DiscountCodeSetValidUntilAction: !include types/DiscountCode/DiscountCodeSetValidUntilAction.raml
  AccessDeniedError: !include types/Error/AccessDeniedError.raml
  ConcurrentModificationError: !include types/Error/ConcurrentModificationError.raml
  DiscountCodeNonApplicableError: !include types/Error/DiscountCodeNonApplicableError.raml
  DuplicateAttributeValueError: !include types/Error/DuplicateAttributeValueError.raml
  DuplicateAttributeValuesError: !include types/Error/DuplicateAttributeValuesError.raml
  DuplicateFieldError: !include types/Error/DuplicateFieldError.raml
  DuplicateFieldWithConflictingResourceError: !include types/Error/DuplicateFieldWithConflictingResourceError.raml
  DuplicatePriceScopeError: !include types/Error/DuplicatePriceScopeError.raml
  DuplicateVariantValuesError: !include types/Error/DuplicateVariantValuesError.raml
  EnumValueIsUsedError: !include types/Error/EnumValueIsUsedError.raml
  ErrorByExtension: !include types/Error/ErrorByExtension.raml
  ErrorObject: !include types/Error/ErrorObject.raml
  ErrorResponse: !include types/Error/ErrorResponse.raml
  ExtensionBadResponseError: !include types/Error/ExtensionBadResponseError.raml
  ExtensionNoResponseError: !include types/Error/ExtensionNoResponseError.raml
  ExtensionUpdateActionsFailedError: !include types/Error/ExtensionUpdateActionsFailedError.raml
  InsufficientScopeError: !include types/Error/InsufficientScopeError.raml
  InvalidCredentialsError: !include types/Error/InvalidCredentialsError.raml
  InvalidCurrentPasswordError: !include types/Error/InvalidCurrentPasswordError.raml
  InvalidFieldError: !include types/Error/InvalidFieldError.raml
  InvalidInputError: !include types/Error/InvalidInputError.raml
  InvalidItemShippingDetailsError: !include types/Error/InvalidItemShippingDetailsError.raml
  InvalidJsonInputError: !include types/Error/InvalidJsonInputError.raml
  InvalidOperationError: !include types/Error/InvalidOperationError.raml
  InvalidSubjectError: !include types/Error/InvalidSubjectError.raml
  InvalidTokenError: !include types/Error/InvalidTokenError.raml
  MatchingPriceNotFoundError: !include types/Error/MatchingPriceNotFoundError.raml
  MissingTaxRateForCountryError: !include types/Error/MissingTaxRateForCountryError.raml
  NoMatchingProductDiscountFoundError: !include types/Error/NoMatchingProductDiscountFoundError.raml
  OutOfStockError: !include types/Error/OutOfStockError.raml
  PriceChangedError: !include types/Error/PriceChangedError.raml
  ReferenceExistsError: !include types/Error/ReferenceExistsError.raml
  RequiredFieldError: !include types/Error/RequiredFieldError.raml
  ResourceNotFoundError: !include types/Error/ResourceNotFoundError.raml
  ShippingMethodDoesNotMatchCartError: !include types/Error/ShippingMethodDoesNotMatchCartError.raml
  VariantValues: !include types/Error/VariantValues.raml
  Extension: !include types/Extension/Extension.raml
  ExtensionAWSLambdaDestination: !include types/Extension/ExtensionAWSLambdaDestination.raml
  ExtensionAction: !include types/Extension/ExtensionAction.raml
  ExtensionAuthorizationHeaderAuthentication: !include types/Extension/ExtensionAuthorizationHeaderAuthentication.raml
  ExtensionAzureFunctionsAuthentication: !include types/Extension/ExtensionAzureFunctionsAuthentication.raml
  ExtensionDestination: !include types/Extension/ExtensionDestination.raml
  ExtensionDraft: !include types/Extension/ExtensionDraft.raml
  ExtensionHttpDestination: !include types/Extension/ExtensionHttpDestination.raml
  ExtensionHttpDestinationAuthentication: !include types/Extension/ExtensionHttpDestinationAuthentication.raml
  ExtensionInput: !include types/Extension/ExtensionInput.raml
  ExtensionPagedQueryResponse: !include types/Extension/ExtensionPagedQueryResponse.raml
  ExtensionResourceTypeId: !include types/Extension/ExtensionResourceTypeId.raml
  ExtensionTrigger: !include types/Extension/ExtensionTrigger.raml
  ExtensionUpdate: !include types/Extension/ExtensionUpdate.raml
  ExtensionUpdateAction: !include types/Extension/ExtensionUpdateAction.raml
  ExtensionChangeDestinationAction: !include types/Extension/ExtensionChangeDestinationAction.raml
  ExtensionChangeTriggersAction: !include types/Extension/ExtensionChangeTriggersAction.raml
  ExtensionSetKeyAction: !include types/Extension/ExtensionSetKeyAction.raml
  ExtensionSetTimeoutInMsAction: !include types/Extension/ExtensionSetTimeoutInMsAction.raml
  InventoryEntry: !include types/Inventory/InventoryEntry.raml
  InventoryEntryDraft: !include types/Inventory/InventoryEntryDraft.raml
  InventoryEntryReference: !include types/Inventory/InventoryEntryReference.raml
  InventoryEntryResourceIdentifier: !include types/Inventory/InventoryEntryResourceIdentifier.raml
  InventoryEntryUpdate: !include types/Inventory/InventoryEntryUpdate.raml
  InventoryEntryUpdateAction: !include types/Inventory/InventoryEntryUpdateAction.raml
  InventoryPagedQueryResponse: !include types/Inventory/InventoryPagedQueryResponse.raml
  InventoryEntryAddQuantityAction: !include types/Inventory/InventoryEntryAddQuantityAction.raml
  InventoryEntryChangeQuantityAction: !include types/Inventory/InventoryEntryChangeQuantityAction.raml
  InventoryEntryRemoveQuantityAction: !include types/Inventory/InventoryEntryRemoveQuantityAction.raml
  InventoryEntrySetCustomFieldAction: !include types/Inventory/InventoryEntrySetCustomFieldAction.raml
  InventoryEntrySetCustomTypeAction: !include types/Inventory/InventoryEntrySetCustomTypeAction.raml
  InventoryEntrySetExpectedDeliveryAction: !include types/Inventory/InventoryEntrySetExpectedDeliveryAction.raml
  InventoryEntrySetRestockableInDaysAction: !include types/Inventory/InventoryEntrySetRestockableInDaysAction.raml
  InventoryEntrySetSupplyChannelAction: !include types/Inventory/InventoryEntrySetSupplyChannelAction.raml
  MyCart: !include types/Me/MyCart.raml
  MyCartDraft: !include types/Me/MyCartDraft.raml
  MyCartUpdateAction: !include types/Me/MyCartUpdateAction.raml
  MyCustomer: !include types/Me/MyCustomer.raml
  MyCustomerDraft: !include types/Me/MyCustomerDraft.raml
  MyCustomerUpdateAction: !include types/Me/MyCustomerUpdateAction.raml
  MyLineItemDraft: !include types/Me/MyLineItemDraft.raml
  MyOrder: !include types/Me/MyOrder.raml
  MyOrderFromCartDraft: !include types/Me/MyOrderFromCartDraft.raml
  MyPayment: !include types/Me/MyPayment.raml
  MyPaymentDraft: !include types/Me/MyPaymentDraft.raml
  MyPaymentPagedQueryResponse: !include types/Me/MyPaymentPagedQueryResponse.raml
  MyPaymentUpdate: !include types/Me/MyPaymentUpdate.raml
  MyPaymentUpdateAction: !include types/Me/MyPaymentUpdateAction.raml
  MyShoppingList: !include types/ShoppingList/MyShoppingList.raml
  MyShoppingListDraft: !include types/Me/MyShoppingListDraft.raml
  MyShoppingListUpdate: !include types/Me/MyShoppingListUpdate.raml
  MyShoppingListUpdateAction: !include types/Me/MyShoppingListUpdateAction.raml
  MyTransactionDraft: !include types/Me/MyTransactionDraft.raml
  MyCartAddDiscountCodeAction: !include types/Me/MyCartAddDiscountCodeAction.raml
  MyCartAddItemShippingAddressAction: !include types/Me/MyCartAddItemShippingAddressAction.raml
  MyCartAddLineItemAction: !include types/Me/MyCartAddLineItemAction.raml
  MyCartAddPaymentAction: !include types/Me/MyCartAddPaymentAction.raml
  MyCartApplyDeltaToLineItemShippingDetailsTargetsAction: !include types/Me/MyCartApplyDeltaToLineItemShippingDetailsTargetsAction.raml
  MyCartChangeLineItemQuantityAction: !include types/Me/MyCartChangeLineItemQuantityAction.raml
  MyCartChangeTaxModeAction: !include types/Me/MyCartChangeTaxModeAction.raml
  MyCartRecalculateAction: !include types/Me/MyCartRecalculateAction.raml
  MyCartRemoveDiscountCodeAction: !include types/Me/MyCartRemoveDiscountCodeAction.raml
  MyCartRemoveItemShippingAddressAction: !include types/Me/MyCartRemoveItemShippingAddressAction.raml
  MyCartRemoveLineItemAction: !include types/Me/MyCartRemoveLineItemAction.raml
  MyCartRemovePaymentAction: !include types/Me/MyCartRemovePaymentAction.raml
  MyCartSetBillingAddressAction: !include types/Me/MyCartSetBillingAddressAction.raml
  MyCartSetCountryAction: !include types/Me/MyCartSetCountryAction.raml
  MyCartSetCustomFieldAction: !include types/Me/MyCartSetCustomFieldAction.raml
  MyCartSetCustomShippingMethodAction: !include types/Me/MyCartSetCustomShippingMethodAction.raml
  MyCartSetCustomTypeAction: !include types/Me/MyCartSetCustomTypeAction.raml
  MyCartSetDeleteDaysAfterLastModificationAction: !include types/Me/MyCartSetDeleteDaysAfterLastModificationAction.raml
  MyCartSetLineItemCustomFieldAction: !include types/Me/MyCartSetLineItemCustomFieldAction.raml
  MyCartSetLineItemCustomTypeAction: !include types/Me/MyCartSetLineItemCustomTypeAction.raml
  MyCartSetLineItemShippingDetailsAction: !include types/Me/MyCartSetLineItemShippingDetailsAction.raml
  MyCartSetLocaleAction: !include types/Me/MyCartSetLocaleAction.raml
  MyCartSetShippingAddressAction: !include types/Me/MyCartSetShippingAddressAction.raml
  MyCartSetShippingMethodAction: !include types/Me/MyCartSetShippingMethodAction.raml
  MyCartUpdateItemShippingAddressAction: !include types/Me/MyCartUpdateItemShippingAddressAction.raml
  MyCustomerAddAddressAction: !include types/Me/MyCustomerAddAddressAction.raml
  MyCustomerAddBillingAddressIdAction: !include types/Me/MyCustomerAddBillingAddressIdAction.raml
  MyCustomerAddShippingAddressIdAction: !include types/Me/MyCustomerAddShippingAddressIdAction.raml
  MyCustomerChangeAddressAction: !include types/Me/MyCustomerChangeAddressAction.raml
  MyCustomerChangeEmailAction: !include types/Me/MyCustomerChangeEmailAction.raml
  MyCustomerRemoveAddressAction: !include types/Me/MyCustomerRemoveAddressAction.raml
  MyCustomerRemoveBillingAddressIdAction: !include types/Me/MyCustomerRemoveBillingAddressIdAction.raml
  MyCustomerRemoveShippingAddressIdAction: !include types/Me/MyCustomerRemoveShippingAddressIdAction.raml
  MyCustomerSetCompanyNameAction: !include types/Me/MyCustomerSetCompanyNameAction.raml
  MyCustomerSetCustomFieldAction: !include types/Me/MyCustomerSetCustomFieldAction.raml
  MyCustomerSetCustomTypeAction: !include types/Me/MyCustomerSetCustomTypeAction.raml
  MyCustomerSetDateOfBirthAction: !include types/Me/MyCustomerSetDateOfBirthAction.raml
  MyCustomerSetDefaultBillingAddressAction: !include types/Me/MyCustomerSetDefaultBillingAddressAction.raml
  MyCustomerSetDefaultShippingAddressAction: !include types/Me/MyCustomerSetDefaultShippingAddressAction.raml
  MyCustomerSetFirstNameAction: !include types/Me/MyCustomerSetFirstNameAction.raml
  MyCustomerSetLastNameAction: !include types/Me/MyCustomerSetLastNameAction.raml
  MyCustomerSetLocaleAction: !include types/Me/MyCustomerSetLocaleAction.raml
  MyCustomerSetMiddleNameAction: !include types/Me/MyCustomerSetMiddleNameAction.raml
  MyCustomerSetSalutationAction: !include types/Me/MyCustomerSetSalutationAction.raml
  MyCustomerSetTitleAction: !include types/Me/MyCustomerSetTitleAction.raml
  MyCustomerSetVatIdAction: !include types/Me/MyCustomerSetVatIdAction.raml
  MyPaymentAddTransactionAction: !include types/Me/MyPaymentAddTransactionAction.raml
  MyPaymentChangeAmountPlannedAction: !include types/Me/MyPaymentChangeAmountPlannedAction.raml
  MyPaymentSetCustomFieldAction: !include types/Me/MyPaymentSetCustomFieldAction.raml
  MyPaymentSetMethodInfoInterfaceAction: !include types/Me/MyPaymentSetMethodInfoInterfaceAction.raml
  MyPaymentSetMethodInfoMethodAction: !include types/Me/MyPaymentSetMethodInfoMethodAction.raml
  MyPaymentSetMethodInfoNameAction: !include types/Me/MyPaymentSetMethodInfoNameAction.raml
  MyShoppingListAddLineItemAction: !include types/Me/MyShoppingListAddLineItemAction.raml
  MyShoppingListAddTextLineItemAction: !include types/Me/MyShoppingListAddTextLineItemAction.raml
  MyShoppingListChangeLineItemQuantityAction: !include types/Me/MyShoppingListChangeLineItemQuantityAction.raml
  MyShoppingListChangeLineItemsOrderAction: !include types/Me/MyShoppingListChangeLineItemsOrderAction.raml
  MyShoppingListChangeNameAction: !include types/Me/MyShoppingListChangeNameAction.raml
  MyShoppingListChangeTextLineItemNameAction: !include types/Me/MyShoppingListChangeTextLineItemNameAction.raml
  MyShoppingListChangeTextLineItemQuantityAction: !include types/Me/MyShoppingListChangeTextLineItemQuantityAction.raml
  MyShoppingListChangeTextLineItemsOrderAction: !include types/Me/MyShoppingListChangeTextLineItemsOrderAction.raml
  MyShoppingListRemoveLineItemAction: !include types/Me/MyShoppingListRemoveLineItemAction.raml
  MyShoppingListRemoveTextLineItemAction: !include types/Me/MyShoppingListRemoveTextLineItemAction.raml
  MyShoppingListSetCustomFieldAction: !include types/Me/MyShoppingListSetCustomFieldAction.raml
  MyShoppingListSetCustomTypeAction: !include types/Me/MyShoppingListSetCustomTypeAction.raml
  MyShoppingListSetDeleteDaysAfterLastModificationAction: !include types/Me/MyShoppingListSetDeleteDaysAfterLastModificationAction.raml
  MyShoppingListSetDescriptionAction: !include types/Me/MyShoppingListSetDescriptionAction.raml
  MyShoppingListSetLineItemCustomFieldAction: !include types/Me/MyShoppingListSetLineItemCustomFieldAction.raml
  MyShoppingListSetLineItemCustomTypeAction: !include types/Me/MyShoppingListSetLineItemCustomTypeAction.raml
  MyShoppingListSetTextLineItemCustomFieldAction: !include types/Me/MyShoppingListSetTextLineItemCustomFieldAction.raml
  MyShoppingListSetTextLineItemCustomTypeAction: !include types/Me/MyShoppingListSetTextLineItemCustomTypeAction.raml
  MyShoppingListSetTextLineItemDescriptionAction: !include types/Me/MyShoppingListSetTextLineItemDescriptionAction.raml
  CategoryCreatedMessage: !include types/Message/CategoryCreatedMessage.raml
  CategorySlugChangedMessage: !include types/Message/CategorySlugChangedMessage.raml
  CustomLineItemStateTransitionMessage: !include types/Message/CustomLineItemStateTransitionMessage.raml
  CustomerAddressAddedMessage: !include types/Message/CustomerAddressAddedMessage.raml
  CustomerAddressChangedMessage: !include types/Message/CustomerAddressChangedMessage.raml
  CustomerAddressRemovedMessage: !include types/Message/CustomerAddressRemovedMessage.raml
  CustomerCompanyNameSetMessage: !include types/Message/CustomerCompanyNameSetMessage.raml
  CustomerCreatedMessage: !include types/Message/CustomerCreatedMessage.raml
  CustomerDateOfBirthSetMessage: !include types/Message/CustomerDateOfBirthSetMessage.raml
  CustomerEmailChangedMessage: !include types/Message/CustomerEmailChangedMessage.raml
  CustomerEmailVerifiedMessage: !include types/Message/CustomerEmailVerifiedMessage.raml
  CustomerGroupSetMessage: !include types/Message/CustomerGroupSetMessage.raml
  DeliveryAddedMessage: !include types/Message/DeliveryAddedMessage.raml
  DeliveryAddressSetMessage: !include types/Message/DeliveryAddressSetMessage.raml
  DeliveryItemsUpdatedMessage: !include types/Message/DeliveryItemsUpdatedMessage.raml
  DeliveryRemovedMessage: !include types/Message/DeliveryRemovedMessage.raml
  InventoryEntryDeletedMessage: !include types/Message/InventoryEntryDeletedMessage.raml
  LineItemStateTransitionMessage: !include types/Message/LineItemStateTransitionMessage.raml
  Message: !include types/Message/Message.raml
  MessageConfiguration: !include types/Message/MessageConfiguration.raml
  MessageConfigurationDraft: !include types/Message/MessageConfigurationDraft.raml
  MessagePagedQueryResponse: !include types/Message/MessagePagedQueryResponse.raml
  OrderBillingAddressSetMessage: !include types/Message/OrderBillingAddressSetMessage.raml
  OrderCreatedMessage: !include types/Message/OrderCreatedMessage.raml
  OrderCustomLineItemDiscountSetMessage: !include types/Message/OrderCustomLineItemDiscountSetMessage.raml
  OrderCustomerEmailSetMessage: !include types/Message/OrderCustomerEmailSetMessage.raml
  OrderCustomerSetMessage: !include types/Message/OrderCustomerSetMessage.raml
  OrderDeletedMessage: !include types/Message/OrderDeletedMessage.raml
  OrderDiscountCodeAddedMessage: !include types/Message/OrderDiscountCodeAddedMessage.raml
  OrderDiscountCodeRemovedMessage: !include types/Message/OrderDiscountCodeRemovedMessage.raml
  OrderDiscountCodeStateSetMessage: !include types/Message/OrderDiscountCodeStateSetMessage.raml
  OrderEditAppliedMessage: !include types/Message/OrderEditAppliedMessage.raml
  OrderImportedMessage: !include types/Message/OrderImportedMessage.raml
  OrderLineItemAddedMessage: !include types/Message/OrderLineItemAddedMessage.raml
  OrderLineItemDiscountSetMessage: !include types/Message/OrderLineItemDiscountSetMessage.raml
  OrderPaymentStateChangedMessage: !include types/Message/OrderPaymentStateChangedMessage.raml
  OrderReturnInfoAddedMessage: !include types/Message/OrderReturnInfoAddedMessage.raml
  OrderReturnShipmentStateChangedMessage: !include types/Message/OrderReturnShipmentStateChangedMessage.raml
  OrderShipmentStateChangedMessage: !include types/Message/OrderShipmentStateChangedMessage.raml
  OrderShippingAddressSetMessage: !include types/Message/OrderShippingAddressSetMessage.raml
  OrderShippingInfoSetMessage: !include types/Message/OrderShippingInfoSetMessage.raml
  OrderShippingRateInputSetMessage: !include types/Message/OrderShippingRateInputSetMessage.raml
  OrderStateChangedMessage: !include types/Message/OrderStateChangedMessage.raml
  OrderStateTransitionMessage: !include types/Message/OrderStateTransitionMessage.raml
  ParcelAddedToDeliveryMessage: !include types/Message/ParcelAddedToDeliveryMessage.raml
  ParcelItemsUpdatedMessage: !include types/Message/ParcelItemsUpdatedMessage.raml
  ParcelMeasurementsUpdatedMessage: !include types/Message/ParcelMeasurementsUpdatedMessage.raml
  ParcelRemovedFromDeliveryMessage: !include types/Message/ParcelRemovedFromDeliveryMessage.raml
  ParcelTrackingDataUpdatedMessage: !include types/Message/ParcelTrackingDataUpdatedMessage.raml
  PaymentCreatedMessage: !include types/Message/PaymentCreatedMessage.raml
  PaymentInteractionAddedMessage: !include types/Message/PaymentInteractionAddedMessage.raml
  PaymentStatusInterfaceCodeSetMessage: !include types/Message/PaymentStatusInterfaceCodeSetMessage.raml
  PaymentStatusStateTransitionMessage: !include types/Message/PaymentStatusStateTransitionMessage.raml
  PaymentTransactionAddedMessage: !include types/Message/PaymentTransactionAddedMessage.raml
  PaymentTransactionStateChangedMessage: !include types/Message/PaymentTransactionStateChangedMessage.raml
  ProductAddedToCategoryMessage: !include types/Message/ProductAddedToCategoryMessage.raml
  ProductCreatedMessage: !include types/Message/ProductCreatedMessage.raml
  ProductDeletedMessage: !include types/Message/ProductDeletedMessage.raml
  ProductImageAddedMessage: !include types/Message/ProductImageAddedMessage.raml
  ProductPriceDiscountsSetMessage: !include types/Message/ProductPriceDiscountsSetMessage.raml
  ProductPriceDiscountsSetUpdatedPrice: !include types/Message/ProductPriceDiscountsSetUpdatedPrice.raml
  ProductPriceExternalDiscountSetMessage: !include types/Message/ProductPriceExternalDiscountSetMessage.raml
  ProductPublishedMessage: !include types/Message/ProductPublishedMessage.raml
  ProductRemovedFromCategoryMessage: !include types/Message/ProductRemovedFromCategoryMessage.raml
  ProductRevertedStagedChangesMessage: !include types/Message/ProductRevertedStagedChangesMessage.raml
  ProductSlugChangedMessage: !include types/Message/ProductSlugChangedMessage.raml
  ProductStateTransitionMessage: !include types/Message/ProductStateTransitionMessage.raml
  ProductUnpublishedMessage: !include types/Message/ProductUnpublishedMessage.raml
  ProductVariantDeletedMessage: !include types/Message/ProductVariantDeletedMessage.raml
  ReviewCreatedMessage: !include types/Message/ReviewCreatedMessage.raml
  ReviewRatingSetMessage: !include types/Message/ReviewRatingSetMessage.raml
  ReviewStateTransitionMessage: !include types/Message/ReviewStateTransitionMessage.raml
  UserProvidedIdentifiers: !include types/Message/UserProvidedIdentifiers.raml
  CategoryCreatedMessagePayload: !include types/Message/CategoryCreatedMessagePayload.raml
  CategorySlugChangedMessagePayload: !include types/Message/CategorySlugChangedMessagePayload.raml
  CustomLineItemStateTransitionMessagePayload: !include types/Message/CustomLineItemStateTransitionMessagePayload.raml
  CustomerAddressAddedMessagePayload: !include types/Message/CustomerAddressAddedMessagePayload.raml
  CustomerAddressChangedMessagePayload: !include types/Message/CustomerAddressChangedMessagePayload.raml
  CustomerAddressRemovedMessagePayload: !include types/Message/CustomerAddressRemovedMessagePayload.raml
  CustomerCompanyNameSetMessagePayload: !include types/Message/CustomerCompanyNameSetMessagePayload.raml
  CustomerCreatedMessagePayload: !include types/Message/CustomerCreatedMessagePayload.raml
  CustomerDateOfBirthSetMessagePayload: !include types/Message/CustomerDateOfBirthSetMessagePayload.raml
  CustomerEmailChangedMessagePayload: !include types/Message/CustomerEmailChangedMessagePayload.raml
  CustomerEmailVerifiedMessagePayload: !include types/Message/CustomerEmailVerifiedMessagePayload.raml
  CustomerGroupSetMessagePayload: !include types/Message/CustomerGroupSetMessagePayload.raml
  DeliveryAddedMessagePayload: !include types/Message/DeliveryAddedMessagePayload.raml
  DeliveryAddressSetMessagePayload: !include types/Message/DeliveryAddressSetMessagePayload.raml
  DeliveryItemsUpdatedMessagePayload: !include types/Message/DeliveryItemsUpdatedMessagePayload.raml
  DeliveryRemovedMessagePayload: !include types/Message/DeliveryRemovedMessagePayload.raml
  InventoryEntryDeletedMessagePayload: !include types/Message/InventoryEntryDeletedMessagePayload.raml
  LineItemStateTransitionMessagePayload: !include types/Message/LineItemStateTransitionMessagePayload.raml
  MessagePayload: !include types/Message/MessagePayload.raml
  OrderBillingAddressSetMessagePayload: !include types/Message/OrderBillingAddressSetMessagePayload.raml
  OrderCreatedMessagePayload: !include types/Message/OrderCreatedMessagePayload.raml
  OrderCustomLineItemDiscountSetMessagePayload: !include types/Message/OrderCustomLineItemDiscountSetMessagePayload.raml
  OrderCustomerEmailSetMessagePayload: !include types/Message/OrderCustomerEmailSetMessagePayload.raml
  OrderCustomerSetMessagePayload: !include types/Message/OrderCustomerSetMessagePayload.raml
  OrderDeletedMessagePayload: !include types/Message/OrderDeletedMessagePayload.raml
  OrderDiscountCodeAddedMessagePayload: !include types/Message/OrderDiscountCodeAddedMessagePayload.raml
  OrderDiscountCodeRemovedMessagePayload: !include types/Message/OrderDiscountCodeRemovedMessagePayload.raml
  OrderDiscountCodeStateSetMessagePayload: !include types/Message/OrderDiscountCodeStateSetMessagePayload.raml
  OrderEditAppliedMessagePayload: !include types/Message/OrderEditAppliedMessagePayload.raml
  OrderImportedMessagePayload: !include types/Message/OrderImportedMessagePayload.raml
  OrderLineItemAddedMessagePayload: !include types/Message/OrderLineItemAddedMessagePayload.raml
  OrderLineItemDiscountSetMessagePayload: !include types/Message/OrderLineItemDiscountSetMessagePayload.raml
  OrderPaymentStateChangedMessagePayload: !include types/Message/OrderPaymentStateChangedMessagePayload.raml
  OrderReturnInfoAddedMessagePayload: !include types/Message/OrderReturnInfoAddedMessagePayload.raml
  OrderReturnShipmentStateChangedMessagePayload: !include types/Message/OrderReturnShipmentStateChangedMessagePayload.raml
  OrderShipmentStateChangedMessagePayload: !include types/Message/OrderShipmentStateChangedMessagePayload.raml
  OrderShippingAddressSetMessagePayload: !include types/Message/OrderShippingAddressSetMessagePayload.raml
  OrderShippingInfoSetMessagePayload: !include types/Message/OrderShippingInfoSetMessagePayload.raml
  OrderShippingRateInputSetMessagePayload: !include types/Message/OrderShippingRateInputSetMessagePayload.raml
  OrderStateChangedMessagePayload: !include types/Message/OrderStateChangedMessagePayload.raml
  OrderStateTransitionMessagePayload: !include types/Message/OrderStateTransitionMessagePayload.raml
  ParcelAddedToDeliveryMessagePayload: !include types/Message/ParcelAddedToDeliveryMessagePayload.raml
  ParcelItemsUpdatedMessagePayload: !include types/Message/ParcelItemsUpdatedMessagePayload.raml
  ParcelMeasurementsUpdatedMessagePayload: !include types/Message/ParcelMeasurementsUpdatedMessagePayload.raml
  ParcelRemovedFromDeliveryMessagePayload: !include types/Message/ParcelRemovedFromDeliveryMessagePayload.raml
  ParcelTrackingDataUpdatedMessagePayload: !include types/Message/ParcelTrackingDataUpdatedMessagePayload.raml
  PaymentCreatedMessagePayload: !include types/Message/PaymentCreatedMessagePayload.raml
  PaymentInteractionAddedMessagePayload: !include types/Message/PaymentInteractionAddedMessagePayload.raml
  PaymentStatusInterfaceCodeSetMessagePayload: !include types/Message/PaymentStatusInterfaceCodeSetMessagePayload.raml
  PaymentStatusStateTransitionMessagePayload: !include types/Message/PaymentStatusStateTransitionMessagePayload.raml
  PaymentTransactionAddedMessagePayload: !include types/Message/PaymentTransactionAddedMessagePayload.raml
  PaymentTransactionStateChangedMessagePayload: !include types/Message/PaymentTransactionStateChangedMessagePayload.raml
  ProductAddedToCategoryMessagePayload: !include types/Message/ProductAddedToCategoryMessagePayload.raml
  ProductCreatedMessagePayload: !include types/Message/ProductCreatedMessagePayload.raml
  ProductDeletedMessagePayload: !include types/Message/ProductDeletedMessagePayload.raml
  ProductImageAddedMessagePayload: !include types/Message/ProductImageAddedMessagePayload.raml
  ProductPriceDiscountsSetMessagePayload: !include types/Message/ProductPriceDiscountsSetMessagePayload.raml
  ProductPriceExternalDiscountSetMessagePayload: !include types/Message/ProductPriceExternalDiscountSetMessagePayload.raml
  ProductPublishedMessagePayload: !include types/Message/ProductPublishedMessagePayload.raml
  ProductRemovedFromCategoryMessagePayload: !include types/Message/ProductRemovedFromCategoryMessagePayload.raml
  ProductRevertedStagedChangesMessagePayload: !include types/Message/ProductRevertedStagedChangesMessagePayload.raml
  ProductSlugChangedMessagePayload: !include types/Message/ProductSlugChangedMessagePayload.raml
  ProductStateTransitionMessagePayload: !include types/Message/ProductStateTransitionMessagePayload.raml
  ProductUnpublishedMessagePayload: !include types/Message/ProductUnpublishedMessagePayload.raml
  ProductVariantDeletedMessagePayload: !include types/Message/ProductVariantDeletedMessagePayload.raml
  ReviewCreatedMessagePayload: !include types/Message/ReviewCreatedMessagePayload.raml
  ReviewRatingSetMessagePayload: !include types/Message/ReviewRatingSetMessagePayload.raml
  ReviewStateTransitionMessagePayload: !include types/Message/ReviewStateTransitionMessagePayload.raml
  OrderEdit: !include types/OrderEdit/OrderEdit.raml
  OrderEditApplied: !include types/OrderEdit/OrderEditApplied.raml
  OrderEditApply: !include types/OrderEdit/OrderEditApply.raml
  OrderEditDraft: !include types/OrderEdit/OrderEditDraft.raml
  OrderEditNotProcessed: !include types/OrderEdit/OrderEditNotProcessed.raml
  OrderEditPagedQueryResponse: !include types/OrderEdit/OrderEditPagedQueryResponse.raml
  OrderEditPreviewFailure: !include types/OrderEdit/OrderEditPreviewFailure.raml
  OrderEditPreviewSuccess: !include types/OrderEdit/OrderEditPreviewSuccess.raml
  OrderEditReference: !include types/OrderEdit/OrderEditReference.raml
  OrderEditResourceIdentifier: !include types/OrderEdit/OrderEditResourceIdentifier.raml
  OrderEditResult: !include types/OrderEdit/OrderEditResult.raml
  OrderEditUpdate: !include types/OrderEdit/OrderEditUpdate.raml
  OrderEditUpdateAction: !include types/OrderEdit/OrderEditUpdateAction.raml
  OrderExcerpt: !include types/OrderEdit/OrderExcerpt.raml
  StagedOrder: !include types/OrderEdit/StagedOrder.raml
  StagedOrderUpdateAction: !include types/Order/StagedOrderUpdateAction.raml
  OrderEditAddStagedActionAction: !include types/OrderEdit/OrderEditAddStagedActionAction.raml
  OrderEditSetCommentAction: !include types/OrderEdit/OrderEditSetCommentAction.raml
  OrderEditSetCustomFieldAction: !include types/OrderEdit/OrderEditSetCustomFieldAction.raml
  OrderEditSetCustomTypeAction: !include types/OrderEdit/OrderEditSetCustomTypeAction.raml
  OrderEditSetKeyAction: !include types/OrderEdit/OrderEditSetKeyAction.raml
  OrderEditSetStagedActionsAction: !include types/OrderEdit/OrderEditSetStagedActionsAction.raml
  StagedOrderAddCustomLineItemAction: !include types/OrderEdit/StagedOrderAddCustomLineItemAction.raml
  StagedOrderAddDeliveryAction: !include types/OrderEdit/StagedOrderAddDeliveryAction.raml
  StagedOrderAddDiscountCodeAction: !include types/OrderEdit/StagedOrderAddDiscountCodeAction.raml
  StagedOrderAddItemShippingAddressAction: !include types/OrderEdit/StagedOrderAddItemShippingAddressAction.raml
  StagedOrderAddLineItemAction: !include types/OrderEdit/StagedOrderAddLineItemAction.raml
  StagedOrderAddParcelToDeliveryAction: !include types/OrderEdit/StagedOrderAddParcelToDeliveryAction.raml
  StagedOrderAddPaymentAction: !include types/OrderEdit/StagedOrderAddPaymentAction.raml
  StagedOrderAddReturnInfoAction: !include types/OrderEdit/StagedOrderAddReturnInfoAction.raml
  StagedOrderAddShoppingListAction: !include types/OrderEdit/StagedOrderAddShoppingListAction.raml
  StagedOrderChangeCustomLineItemMoneyAction: !include types/OrderEdit/StagedOrderChangeCustomLineItemMoneyAction.raml
  StagedOrderChangeCustomLineItemQuantityAction: !include types/OrderEdit/StagedOrderChangeCustomLineItemQuantityAction.raml
  StagedOrderChangeLineItemQuantityAction: !include types/OrderEdit/StagedOrderChangeLineItemQuantityAction.raml
  StagedOrderChangeOrderStateAction: !include types/OrderEdit/StagedOrderChangeOrderStateAction.raml
  StagedOrderChangePaymentStateAction: !include types/OrderEdit/StagedOrderChangePaymentStateAction.raml
  StagedOrderChangeShipmentStateAction: !include types/OrderEdit/StagedOrderChangeShipmentStateAction.raml
  StagedOrderChangeTaxCalculationModeAction: !include types/OrderEdit/StagedOrderChangeTaxCalculationModeAction.raml
  StagedOrderChangeTaxModeAction: !include types/OrderEdit/StagedOrderChangeTaxModeAction.raml
  StagedOrderChangeTaxRoundingModeAction: !include types/OrderEdit/StagedOrderChangeTaxRoundingModeAction.raml
  StagedOrderImportCustomLineItemStateAction: !include types/OrderEdit/StagedOrderImportCustomLineItemStateAction.raml
  StagedOrderImportLineItemStateAction: !include types/OrderEdit/StagedOrderImportLineItemStateAction.raml
  StagedOrderRemoveCustomLineItemAction: !include types/OrderEdit/StagedOrderRemoveCustomLineItemAction.raml
  StagedOrderRemoveDeliveryAction: !include types/OrderEdit/StagedOrderRemoveDeliveryAction.raml
  StagedOrderRemoveDiscountCodeAction: !include types/OrderEdit/StagedOrderRemoveDiscountCodeAction.raml
  StagedOrderRemoveItemShippingAddressAction: !include types/OrderEdit/StagedOrderRemoveItemShippingAddressAction.raml
  StagedOrderRemoveLineItemAction: !include types/OrderEdit/StagedOrderRemoveLineItemAction.raml
  StagedOrderRemoveParcelFromDeliveryAction: !include types/OrderEdit/StagedOrderRemoveParcelFromDeliveryAction.raml
  StagedOrderRemovePaymentAction: !include types/OrderEdit/StagedOrderRemovePaymentAction.raml
  StagedOrderSetBillingAddressAction: !include types/OrderEdit/StagedOrderSetBillingAddressAction.raml
  StagedOrderSetCountryAction: !include types/OrderEdit/StagedOrderSetCountryAction.raml
  StagedOrderSetCustomFieldAction: !include types/OrderEdit/StagedOrderSetCustomFieldAction.raml
  StagedOrderSetCustomLineItemCustomFieldAction: !include types/OrderEdit/StagedOrderSetCustomLineItemCustomFieldAction.raml
  StagedOrderSetCustomLineItemCustomTypeAction: !include types/OrderEdit/StagedOrderSetCustomLineItemCustomTypeAction.raml
  StagedOrderSetCustomLineItemShippingDetailsAction: !include types/OrderEdit/StagedOrderSetCustomLineItemShippingDetailsAction.raml
  StagedOrderSetCustomLineItemTaxAmountAction: !include types/OrderEdit/StagedOrderSetCustomLineItemTaxAmountAction.raml
  StagedOrderSetCustomLineItemTaxRateAction: !include types/OrderEdit/StagedOrderSetCustomLineItemTaxRateAction.raml
  StagedOrderSetCustomShippingMethodAction: !include types/OrderEdit/StagedOrderSetCustomShippingMethodAction.raml
  StagedOrderSetCustomTypeAction: !include types/OrderEdit/StagedOrderSetCustomTypeAction.raml
  StagedOrderSetCustomerEmailAction: !include types/OrderEdit/StagedOrderSetCustomerEmailAction.raml
  StagedOrderSetCustomerGroupAction: !include types/OrderEdit/StagedOrderSetCustomerGroupAction.raml
  StagedOrderSetCustomerIdAction: !include types/OrderEdit/StagedOrderSetCustomerIdAction.raml
  StagedOrderSetDeliveryAddressAction: !include types/OrderEdit/StagedOrderSetDeliveryAddressAction.raml
  StagedOrderSetDeliveryItemsAction: !include types/OrderEdit/StagedOrderSetDeliveryItemsAction.raml
  StagedOrderSetLineItemCustomFieldAction: !include types/OrderEdit/StagedOrderSetLineItemCustomFieldAction.raml
  StagedOrderSetLineItemCustomTypeAction: !include types/OrderEdit/StagedOrderSetLineItemCustomTypeAction.raml
  StagedOrderSetLineItemPriceAction: !include types/OrderEdit/StagedOrderSetLineItemPriceAction.raml
  StagedOrderSetLineItemShippingDetailsAction: !include types/OrderEdit/StagedOrderSetLineItemShippingDetailsAction.raml
  StagedOrderSetLineItemTaxAmountAction: !include types/OrderEdit/StagedOrderSetLineItemTaxAmountAction.raml
  StagedOrderSetLineItemTaxRateAction: !include types/OrderEdit/StagedOrderSetLineItemTaxRateAction.raml
  StagedOrderSetLineItemTotalPriceAction: !include types/OrderEdit/StagedOrderSetLineItemTotalPriceAction.raml
  StagedOrderSetLocaleAction: !include types/OrderEdit/StagedOrderSetLocaleAction.raml
  StagedOrderSetOrderNumberAction: !include types/OrderEdit/StagedOrderSetOrderNumberAction.raml
  StagedOrderSetOrderTotalTaxAction: !include types/OrderEdit/StagedOrderSetOrderTotalTaxAction.raml
  StagedOrderSetParcelItemsAction: !include types/OrderEdit/StagedOrderSetParcelItemsAction.raml
  StagedOrderSetParcelMeasurementsAction: !include types/OrderEdit/StagedOrderSetParcelMeasurementsAction.raml
  StagedOrderSetParcelTrackingDataAction: !include types/OrderEdit/StagedOrderSetParcelTrackingDataAction.raml
  StagedOrderSetReturnPaymentStateAction: !include types/OrderEdit/StagedOrderSetReturnPaymentStateAction.raml
  StagedOrderSetReturnShipmentStateAction: !include types/OrderEdit/StagedOrderSetReturnShipmentStateAction.raml
  StagedOrderSetShippingAddressAction: !include types/OrderEdit/StagedOrderSetShippingAddressAction.raml
  StagedOrderSetShippingAddressAndCustomShippingMethodAction: !include types/OrderEdit/StagedOrderSetShippingAddressAndCustomShippingMethodAction.raml
  StagedOrderSetShippingAddressAndShippingMethodAction: !include types/OrderEdit/StagedOrderSetShippingAddressAndShippingMethodAction.raml
  StagedOrderSetShippingMethodAction: !include types/OrderEdit/StagedOrderSetShippingMethodAction.raml
  StagedOrderSetShippingMethodTaxAmountAction: !include types/OrderEdit/StagedOrderSetShippingMethodTaxAmountAction.raml
  StagedOrderSetShippingMethodTaxRateAction: !include types/OrderEdit/StagedOrderSetShippingMethodTaxRateAction.raml
  StagedOrderSetShippingRateInputAction: !include types/OrderEdit/StagedOrderSetShippingRateInputAction.raml
  StagedOrderTransitionCustomLineItemStateAction: !include types/OrderEdit/StagedOrderTransitionCustomLineItemStateAction.raml
  StagedOrderTransitionLineItemStateAction: !include types/OrderEdit/StagedOrderTransitionLineItemStateAction.raml
  StagedOrderTransitionStateAction: !include types/OrderEdit/StagedOrderTransitionStateAction.raml
  StagedOrderUpdateItemShippingAddressAction: !include types/OrderEdit/StagedOrderUpdateItemShippingAddressAction.raml
  StagedOrderUpdateSyncInfoAction: !include types/OrderEdit/StagedOrderUpdateSyncInfoAction.raml
  CustomLineItemReturnItem: !include types/Order/CustomLineItemReturnItem.raml
  Delivery: !include types/Order/Delivery.raml
  DeliveryItem: !include types/Order/DeliveryItem.raml
  DiscountedLineItemPriceDraft: !include types/Order/DiscountedLineItemPriceDraft.raml
  ItemState: !include types/Order/ItemState.raml
  LineItemImportDraft: !include types/Order/LineItemImportDraft.raml
  LineItemReturnItem: !include types/Order/LineItemReturnItem.raml
  Order: !include types/Order/Order.raml
  OrderFromCartDraft: !include types/Order/OrderFromCartDraft.raml
  OrderImportDraft: !include types/Order/OrderImportDraft.raml
  OrderPagedQueryResponse: !include types/Order/OrderPagedQueryResponse.raml
  OrderReference: !include types/Order/OrderReference.raml
  OrderResourceIdentifier: !include types/Order/OrderResourceIdentifier.raml
  OrderState: !include types/Order/OrderState.raml
  OrderUpdate: !include types/Order/OrderUpdate.raml
  OrderUpdateAction: !include types/Order/OrderUpdateAction.raml
  Parcel: !include types/Order/Parcel.raml
  ParcelDraft: !include types/Order/ParcelDraft.raml
  ParcelMeasurements: !include types/Order/ParcelMeasurements.raml
  PaymentInfo: !include types/Order/PaymentInfo.raml
  PaymentState: !include types/Order/PaymentState.raml
  ProductVariantImportDraft: !include types/Order/ProductVariantImportDraft.raml
  ReturnInfo: !include types/Order/ReturnInfo.raml
  ReturnItem: !include types/Order/ReturnItem.raml
  ReturnItemDraft: !include types/Order/ReturnItemDraft.raml
  ReturnPaymentState: !include types/Order/ReturnPaymentState.raml
  ReturnShipmentState: !include types/Order/ReturnShipmentState.raml
  ShipmentState: !include types/Order/ShipmentState.raml
  ShippingInfoImportDraft: !include types/Order/ShippingInfoImportDraft.raml
  SyncInfo: !include types/Order/SyncInfo.raml
  TaxedItemPriceDraft: !include types/Order/TaxedItemPriceDraft.raml
  TrackingData: !include types/Order/TrackingData.raml
  OrderAddDeliveryAction: !include types/Order/OrderAddDeliveryAction.raml
  OrderAddItemShippingAddressAction: !include types/Order/OrderAddItemShippingAddressAction.raml
  OrderAddParcelToDeliveryAction: !include types/Order/OrderAddParcelToDeliveryAction.raml
  OrderAddPaymentAction: !include types/Order/OrderAddPaymentAction.raml
  OrderAddReturnInfoAction: !include types/Order/OrderAddReturnInfoAction.raml
  OrderChangeOrderStateAction: !include types/Order/OrderChangeOrderStateAction.raml
  OrderChangePaymentStateAction: !include types/Order/OrderChangePaymentStateAction.raml
  OrderChangeShipmentStateAction: !include types/Order/OrderChangeShipmentStateAction.raml
  OrderImportCustomLineItemStateAction: !include types/Order/OrderImportCustomLineItemStateAction.raml
  OrderImportLineItemStateAction: !include types/Order/OrderImportLineItemStateAction.raml
  OrderRemoveDeliveryAction: !include types/Order/OrderRemoveDeliveryAction.raml
  OrderRemoveItemShippingAddressAction: !include types/Order/OrderRemoveItemShippingAddressAction.raml
  OrderRemoveParcelFromDeliveryAction: !include types/Order/OrderRemoveParcelFromDeliveryAction.raml
  OrderRemovePaymentAction: !include types/Order/OrderRemovePaymentAction.raml
  OrderSetBillingAddressAction: !include types/Order/OrderSetBillingAddressAction.raml
  OrderSetCustomFieldAction: !include types/Order/OrderSetCustomFieldAction.raml
  OrderSetCustomLineItemCustomFieldAction: !include types/Order/OrderSetCustomLineItemCustomFieldAction.raml
  OrderSetCustomLineItemCustomTypeAction: !include types/Order/OrderSetCustomLineItemCustomTypeAction.raml
  OrderSetCustomLineItemShippingDetailsAction: !include types/Order/OrderSetCustomLineItemShippingDetailsAction.raml
  OrderSetCustomTypeAction: !include types/Order/OrderSetCustomTypeAction.raml
  OrderSetCustomerEmailAction: !include types/Order/OrderSetCustomerEmailAction.raml
  OrderSetCustomerIdAction: !include types/Order/OrderSetCustomerIdAction.raml
  OrderSetDeliveryAddressAction: !include types/Order/OrderSetDeliveryAddressAction.raml
  OrderSetDeliveryItemsAction: !include types/Order/OrderSetDeliveryItemsAction.raml
  OrderSetLineItemCustomFieldAction: !include types/Order/OrderSetLineItemCustomFieldAction.raml
  OrderSetLineItemCustomTypeAction: !include types/Order/OrderSetLineItemCustomTypeAction.raml
  OrderSetLineItemShippingDetailsAction: !include types/Order/OrderSetLineItemShippingDetailsAction.raml
  OrderSetLocaleAction: !include types/Order/OrderSetLocaleAction.raml
  OrderSetOrderNumberAction: !include types/Order/OrderSetOrderNumberAction.raml
  OrderSetParcelItemsAction: !include types/Order/OrderSetParcelItemsAction.raml
  OrderSetParcelMeasurementsAction: !include types/Order/OrderSetParcelMeasurementsAction.raml
  OrderSetParcelTrackingDataAction: !include types/Order/OrderSetParcelTrackingDataAction.raml
  OrderSetReturnPaymentStateAction: !include types/Order/OrderSetReturnPaymentStateAction.raml
  OrderSetReturnShipmentStateAction: !include types/Order/OrderSetReturnShipmentStateAction.raml
  OrderSetShippingAddressAction: !include types/Order/OrderSetShippingAddressAction.raml
  OrderTransitionCustomLineItemStateAction: !include types/Order/OrderTransitionCustomLineItemStateAction.raml
  OrderTransitionLineItemStateAction: !include types/Order/OrderTransitionLineItemStateAction.raml
  OrderTransitionStateAction: !include types/Order/OrderTransitionStateAction.raml
  OrderUpdateItemShippingAddressAction: !include types/Order/OrderUpdateItemShippingAddressAction.raml
  OrderUpdateSyncInfoAction: !include types/Order/OrderUpdateSyncInfoAction.raml
  Payment: !include types/Payment/Payment.raml
  PaymentDraft: !include types/Payment/PaymentDraft.raml
  PaymentMethodInfo: !include types/Payment/PaymentMethodInfo.raml
  PaymentPagedQueryResponse: !include types/Payment/PaymentPagedQueryResponse.raml
  PaymentReference: !include types/Payment/PaymentReference.raml
  PaymentResourceIdentifier: !include types/Payment/PaymentResourceIdentifier.raml
  PaymentStatus: !include types/Payment/PaymentStatus.raml
  PaymentStatusDraft: !include types/Payment/PaymentStatusDraft.raml
  PaymentUpdate: !include types/Payment/PaymentUpdate.raml
  PaymentUpdateAction: !include types/Payment/PaymentUpdateAction.raml
  Transaction: !include types/Payment/Transaction.raml
  TransactionDraft: !include types/Payment/TransactionDraft.raml
  TransactionState: !include types/Payment/TransactionState.raml
  TransactionType: !include types/Payment/TransactionType.raml
  PaymentAddInterfaceInteractionAction: !include types/Payment/PaymentAddInterfaceInteractionAction.raml
  PaymentAddTransactionAction: !include types/Payment/PaymentAddTransactionAction.raml
  PaymentChangeAmountPlannedAction: !include types/Payment/PaymentChangeAmountPlannedAction.raml
  PaymentChangeTransactionInteractionIdAction: !include types/Payment/PaymentChangeTransactionInteractionIdAction.raml
  PaymentChangeTransactionStateAction: !include types/Payment/PaymentChangeTransactionStateAction.raml
  PaymentChangeTransactionTimestampAction: !include types/Payment/PaymentChangeTransactionTimestampAction.raml
  PaymentSetAmountPaidAction: !include types/Payment/PaymentSetAmountPaidAction.raml
  PaymentSetAmountRefundedAction: !include types/Payment/PaymentSetAmountRefundedAction.raml
  PaymentSetAnonymousIdAction: !include types/Payment/PaymentSetAnonymousIdAction.raml
  PaymentSetAuthorizationAction: !include types/Payment/PaymentSetAuthorizationAction.raml
  PaymentSetCustomFieldAction: !include types/Payment/PaymentSetCustomFieldAction.raml
  PaymentSetCustomTypeAction: !include types/Payment/PaymentSetCustomTypeAction.raml
  PaymentSetCustomerAction: !include types/Payment/PaymentSetCustomerAction.raml
  PaymentSetExternalIdAction: !include types/Payment/PaymentSetExternalIdAction.raml
  PaymentSetInterfaceIdAction: !include types/Payment/PaymentSetInterfaceIdAction.raml
  PaymentSetKeyAction: !include types/Payment/PaymentSetKeyAction.raml
  PaymentSetMethodInfoInterfaceAction: !include types/Payment/PaymentSetMethodInfoInterfaceAction.raml
  PaymentSetMethodInfoMethodAction: !include types/Payment/PaymentSetMethodInfoMethodAction.raml
  PaymentSetMethodInfoNameAction: !include types/Payment/PaymentSetMethodInfoNameAction.raml
  PaymentSetStatusInterfaceCodeAction: !include types/Payment/PaymentSetStatusInterfaceCodeAction.raml
  PaymentSetStatusInterfaceTextAction: !include types/Payment/PaymentSetStatusInterfaceTextAction.raml
  PaymentTransitionStateAction: !include types/Payment/PaymentTransitionStateAction.raml
  ProductDiscount: !include types/ProductDiscount/ProductDiscount.raml
  ProductDiscountDraft: !include types/ProductDiscount/ProductDiscountDraft.raml
  ProductDiscountMatchQuery: !include types/ProductDiscount/ProductDiscountMatchQuery.raml
  ProductDiscountPagedQueryResponse: !include types/ProductDiscount/ProductDiscountPagedQueryResponse.raml
  ProductDiscountReference: !include types/ProductDiscount/ProductDiscountReference.raml
  ProductDiscountResourceIdentifier: !include types/ProductDiscount/ProductDiscountResourceIdentifier.raml
  ProductDiscountUpdate: !include types/ProductDiscount/ProductDiscountUpdate.raml
  ProductDiscountUpdateAction: !include types/ProductDiscount/ProductDiscountUpdateAction.raml
  ProductDiscountValue: !include types/ProductDiscount/ProductDiscountValue.raml
  ProductDiscountValueAbsolute: !include types/ProductDiscount/ProductDiscountValueAbsolute.raml
  ProductDiscountValueAbsoluteDraft: !include types/ProductDiscount/ProductDiscountValueAbsoluteDraft.raml
  ProductDiscountValueDraft: !include types/ProductDiscount/ProductDiscountValueDraft.raml
  ProductDiscountValueExternal: !include types/ProductDiscount/ProductDiscountValueExternal.raml
  ProductDiscountValueExternalDraft: !include types/ProductDiscount/ProductDiscountValueExternalDraft.raml
  ProductDiscountValueRelative: !include types/ProductDiscount/ProductDiscountValueRelative.raml
  ProductDiscountValueRelativeDraft: !include types/ProductDiscount/ProductDiscountValueRelativeDraft.raml
  ProductDiscountChangeIsActiveAction: !include types/ProductDiscount/ProductDiscountChangeIsActiveAction.raml
  ProductDiscountChangeNameAction: !include types/ProductDiscount/ProductDiscountChangeNameAction.raml
  ProductDiscountChangePredicateAction: !include types/ProductDiscount/ProductDiscountChangePredicateAction.raml
  ProductDiscountChangeSortOrderAction: !include types/ProductDiscount/ProductDiscountChangeSortOrderAction.raml
  ProductDiscountChangeValueAction: !include types/ProductDiscount/ProductDiscountChangeValueAction.raml
  ProductDiscountSetDescriptionAction: !include types/ProductDiscount/ProductDiscountSetDescriptionAction.raml
  ProductDiscountSetKeyAction: !include types/ProductDiscount/ProductDiscountSetKeyAction.raml
  ProductDiscountSetValidFromAction: !include types/ProductDiscount/ProductDiscountSetValidFromAction.raml
  ProductDiscountSetValidFromAndUntilAction: !include types/ProductDiscount/ProductDiscountSetValidFromAndUntilAction.raml
  ProductDiscountSetValidUntilAction: !include types/ProductDiscount/ProductDiscountSetValidUntilAction.raml
  AttributeBooleanType: !include types/ProductType/AttributeBooleanType.raml
  AttributeConstraintEnum: !include types/ProductType/AttributeConstraintEnum.raml
  AttributeConstraintEnumDraft: !include types/ProductType/AttributeConstraintEnumDraft.raml
  AttributeDateTimeType: !include types/ProductType/AttributeDateTimeType.raml
  AttributeDateType: !include types/ProductType/AttributeDateType.raml
  AttributeDefinition: !include types/ProductType/AttributeDefinition.raml
  AttributeDefinitionDraft: !include types/ProductType/AttributeDefinitionDraft.raml
  AttributeEnumType: !include types/ProductType/AttributeEnumType.raml
  AttributeLocalizableTextType: !include types/ProductType/AttributeLocalizableTextType.raml
  AttributeLocalizedEnumType: !include types/ProductType/AttributeLocalizedEnumType.raml
  AttributeLocalizedEnumValue: !include types/ProductType/AttributeLocalizedEnumValue.raml
  AttributeMoneyType: !include types/ProductType/AttributeMoneyType.raml
  AttributeNestedType: !include types/ProductType/AttributeNestedType.raml
  AttributeNumberType: !include types/ProductType/AttributeNumberType.raml
  AttributePlainEnumValue: !include types/ProductType/AttributePlainEnumValue.raml
  AttributeReferenceType: !include types/ProductType/AttributeReferenceType.raml
  AttributeSetType: !include types/ProductType/AttributeSetType.raml
  AttributeTextType: !include types/ProductType/AttributeTextType.raml
  AttributeTimeType: !include types/ProductType/AttributeTimeType.raml
  AttributeType: !include types/ProductType/AttributeType.raml
  ProductType: !include types/ProductType/ProductType.raml
  ProductTypeDraft: !include types/ProductType/ProductTypeDraft.raml
  ProductTypePagedQueryResponse: !include types/ProductType/ProductTypePagedQueryResponse.raml
  ProductTypeReference: !include types/ProductType/ProductTypeReference.raml
  ProductTypeResourceIdentifier: !include types/ProductType/ProductTypeResourceIdentifier.raml
  ProductTypeUpdate: !include types/ProductType/ProductTypeUpdate.raml
  ProductTypeUpdateAction: !include types/ProductType/ProductTypeUpdateAction.raml
  TextInputHint: !include types/ProductType/TextInputHint.raml
  ProductTypeAddAttributeDefinitionAction: !include types/ProductType/ProductTypeAddAttributeDefinitionAction.raml
  ProductTypeAddLocalizedEnumValueAction: !include types/ProductType/ProductTypeAddLocalizedEnumValueAction.raml
  ProductTypeAddPlainEnumValueAction: !include types/ProductType/ProductTypeAddPlainEnumValueAction.raml
  ProductTypeChangeAttributeConstraintAction: !include types/ProductType/ProductTypeChangeAttributeConstraintAction.raml
  ProductTypeChangeAttributeNameAction: !include types/ProductType/ProductTypeChangeAttributeNameAction.raml
  ProductTypeChangeAttributeOrderAction: !include types/ProductType/ProductTypeChangeAttributeOrderAction.raml
  ProductTypeChangeAttributeOrderByNameAction: !include types/ProductType/ProductTypeChangeAttributeOrderByNameAction.raml
  ProductTypeChangeDescriptionAction: !include types/ProductType/ProductTypeChangeDescriptionAction.raml
  ProductTypeChangeEnumKeyAction: !include types/ProductType/ProductTypeChangeEnumKeyAction.raml
  ProductTypeChangeInputHintAction: !include types/ProductType/ProductTypeChangeInputHintAction.raml
  ProductTypeChangeIsSearchableAction: !include types/ProductType/ProductTypeChangeIsSearchableAction.raml
  ProductTypeChangeLabelAction: !include types/ProductType/ProductTypeChangeLabelAction.raml
  ProductTypeChangeLocalizedEnumValueLabelAction: !include types/ProductType/ProductTypeChangeLocalizedEnumValueLabelAction.raml
  ProductTypeChangeLocalizedEnumValueOrderAction: !include types/ProductType/ProductTypeChangeLocalizedEnumValueOrderAction.raml
  ProductTypeChangeNameAction: !include types/ProductType/ProductTypeChangeNameAction.raml
  ProductTypeChangePlainEnumValueLabelAction: !include types/ProductType/ProductTypeChangePlainEnumValueLabelAction.raml
  ProductTypeChangePlainEnumValueOrderAction: !include types/ProductType/ProductTypeChangePlainEnumValueOrderAction.raml
  ProductTypeRemoveAttributeDefinitionAction: !include types/ProductType/ProductTypeRemoveAttributeDefinitionAction.raml
  ProductTypeRemoveEnumValuesAction: !include types/ProductType/ProductTypeRemoveEnumValuesAction.raml
  ProductTypeSetInputTipAction: !include types/ProductType/ProductTypeSetInputTipAction.raml
  ProductTypeSetKeyAction: !include types/ProductType/ProductTypeSetKeyAction.raml
  Attribute: !include types/Product/Attribute.raml
  AttributeValue: !include types/Product/AttributeValue.raml
  CategoryOrderHints: !include types/Product/CategoryOrderHints.raml
  CustomTokenizer: !include types/Product/CustomTokenizer.raml
  FacetResult: !include types/Product/FacetResult.raml
  FacetResultRange: !include types/Product/FacetResultRange.raml
  FacetResultTerm: !include types/Product/FacetResultTerm.raml
  FacetResults: !include types/Product/FacetResults.raml
  FacetTypes: !include types/Product/FacetTypes.raml
  FilteredFacetResult: !include types/Product/FilteredFacetResult.raml
  Product: !include types/Product/Product.raml
  ProductCatalogData: !include types/Product/ProductCatalogData.raml
  ProductData: !include types/Product/ProductData.raml
  ProductDraft: !include types/Product/ProductDraft.raml
  ProductPagedQueryResponse: !include types/Product/ProductPagedQueryResponse.raml
  ProductProjection: !include types/Product/ProductProjection.raml
  ProductProjectionPagedQueryResponse: !include types/Product/ProductProjectionPagedQueryResponse.raml
  ProductProjectionPagedSearchResponse: !include types/Product/ProductProjectionPagedSearchResponse.raml
  ProductPublishScope: !include types/Cart/ProductPublishScope.raml
  ProductReference: !include types/Product/ProductReference.raml
  ProductResourceIdentifier: !include types/Product/ProductResourceIdentifier.raml
  ProductUpdate: !include types/Product/ProductUpdate.raml
  ProductUpdateAction: !include types/Product/ProductUpdateAction.raml
  ProductVariant: !include types/Product/ProductVariant.raml
  ProductVariantAvailability: !include types/Product/ProductVariantAvailability.raml
  ProductVariantChannelAvailability: !include types/Product/ProductVariantChannelAvailability.raml
  ProductVariantChannelAvailabilityMap: !include types/Product/ProductVariantChannelAvailabilityMap.raml
  ProductVariantDraft: !include types/Product/ProductVariantDraft.raml
  RangeFacetResult: !include types/Product/RangeFacetResult.raml
  SearchKeyword: !include types/Product/SearchKeyword.raml
  SearchKeywords: !include types/Product/SearchKeywords.raml
  SuggestTokenizer: !include types/Product/SuggestTokenizer.raml
  Suggestion: !include types/Product/Suggestion.raml
  SuggestionResult: !include types/Product/SuggestionResult.raml
  TermFacetResult: !include types/Product/TermFacetResult.raml
  TermFacetResultType: !include types/Product/TermFacetResultType.raml
  WhitespaceTokenizer: !include types/Product/WhitespaceTokenizer.raml
  ProductAddAssetAction: !include types/Product/ProductAddAssetAction.raml
  ProductAddExternalImageAction: !include types/Product/ProductAddExternalImageAction.raml
  ProductAddPriceAction: !include types/Product/ProductAddPriceAction.raml
  ProductAddToCategoryAction: !include types/Product/ProductAddToCategoryAction.raml
  ProductAddVariantAction: !include types/Product/ProductAddVariantAction.raml
  ProductChangeAssetNameAction: !include types/Product/ProductChangeAssetNameAction.raml
  ProductChangeAssetOrderAction: !include types/Product/ProductChangeAssetOrderAction.raml
  ProductChangeMasterVariantAction: !include types/Product/ProductChangeMasterVariantAction.raml
  ProductChangeNameAction: !include types/Product/ProductChangeNameAction.raml
  ProductChangePriceAction: !include types/Product/ProductChangePriceAction.raml
  ProductChangeSlugAction: !include types/Product/ProductChangeSlugAction.raml
  ProductLegacySetSkuAction: !include types/Product/ProductLegacySetSkuAction.raml
  ProductMoveImageToPositionAction: !include types/Product/ProductMoveImageToPositionAction.raml
  ProductPublishAction: !include types/Product/ProductPublishAction.raml
  ProductRemoveAssetAction: !include types/Product/ProductRemoveAssetAction.raml
  ProductRemoveFromCategoryAction: !include types/Product/ProductRemoveFromCategoryAction.raml
  ProductRemoveImageAction: !include types/Product/ProductRemoveImageAction.raml
  ProductRemovePriceAction: !include types/Product/ProductRemovePriceAction.raml
  ProductRemoveVariantAction: !include types/Product/ProductRemoveVariantAction.raml
  ProductRevertStagedChangesAction: !include types/Product/ProductRevertStagedChangesAction.raml
  ProductRevertStagedVariantChangesAction: !include types/Product/ProductRevertStagedVariantChangesAction.raml
  ProductSetAssetCustomFieldAction: !include types/Product/ProductSetAssetCustomFieldAction.raml
  ProductSetAssetCustomTypeAction: !include types/Product/ProductSetAssetCustomTypeAction.raml
  ProductSetAssetDescriptionAction: !include types/Product/ProductSetAssetDescriptionAction.raml
  ProductSetAssetKeyAction: !include types/Product/ProductSetAssetKeyAction.raml
  ProductSetAssetSourcesAction: !include types/Product/ProductSetAssetSourcesAction.raml
  ProductSetAssetTagsAction: !include types/Product/ProductSetAssetTagsAction.raml
  ProductSetAttributeAction: !include types/Product/ProductSetAttributeAction.raml
  ProductSetAttributeInAllVariantsAction: !include types/Product/ProductSetAttributeInAllVariantsAction.raml
  ProductSetCategoryOrderHintAction: !include types/Product/ProductSetCategoryOrderHintAction.raml
  ProductSetDescriptionAction: !include types/Product/ProductSetDescriptionAction.raml
  ProductSetDiscountedPriceAction: !include types/Product/ProductSetDiscountedPriceAction.raml
  ProductSetImageLabelAction: !include types/Product/ProductSetImageLabelAction.raml
  ProductSetKeyAction: !include types/Product/ProductSetKeyAction.raml
  ProductSetMetaDescriptionAction: !include types/Product/ProductSetMetaDescriptionAction.raml
  ProductSetMetaKeywordsAction: !include types/Product/ProductSetMetaKeywordsAction.raml
  ProductSetMetaTitleAction: !include types/Product/ProductSetMetaTitleAction.raml
  ProductSetPricesAction: !include types/Product/ProductSetPricesAction.raml
  ProductSetProductPriceCustomFieldAction: !include types/Product/ProductSetProductPriceCustomFieldAction.raml
  ProductSetProductPriceCustomTypeAction: !include types/Product/ProductSetProductPriceCustomTypeAction.raml
  ProductSetProductVariantKeyAction: !include types/Product/ProductSetProductVariantKeyAction.raml
  ProductSetSearchKeywordsAction: !include types/Product/ProductSetSearchKeywordsAction.raml
  ProductSetSkuAction: !include types/Product/ProductSetSkuAction.raml
  ProductSetTaxCategoryAction: !include types/Product/ProductSetTaxCategoryAction.raml
  ProductTransitionStateAction: !include types/Product/ProductTransitionStateAction.raml
  ProductUnpublishAction: !include types/Product/ProductUnpublishAction.raml
  CartClassificationType: !include types/Project/CartClassificationType.raml
  CartScoreType: !include types/Project/CartScoreType.raml
  CartValueType: !include types/Project/CartValueType.raml
  ExternalOAuth: !include types/Project/ExternalOAuth.raml
  Project: !include types/Project/Project.raml
  ProjectUpdate: !include types/Project/ProjectUpdate.raml
  ProjectUpdateAction: !include types/Project/ProjectUpdateAction.raml
  ShippingRateInputType: !include types/Project/ShippingRateInputType.raml
  ProjectChangeCountriesAction: !include types/Project/ProjectChangeCountriesAction.raml
  ProjectChangeCurrenciesAction: !include types/Project/ProjectChangeCurrenciesAction.raml
  ProjectChangeLanguagesAction: !include types/Project/ProjectChangeLanguagesAction.raml
  ProjectChangeMessagesConfigurationAction: !include types/Project/ProjectChangeMessagesConfigurationAction.raml
  ProjectChangeMessagesEnabledAction: !include types/Project/ProjectChangeMessagesEnabledAction.raml
  ProjectChangeNameAction: !include types/Project/ProjectChangeNameAction.raml
  ProjectSetExternalOAuthAction: !include types/Project/ProjectSetExternalOAuthAction.raml
  ProjectSetShippingRateInputTypeAction: !include types/Project/ProjectSetShippingRateInputTypeAction.raml
  Review: !include types/Review/Review.raml
  ReviewDraft: !include types/Review/ReviewDraft.raml
  ReviewPagedQueryResponse: !include types/Review/ReviewPagedQueryResponse.raml
  ReviewRatingStatistics: !include types/Review/ReviewRatingStatistics.raml
  ReviewReference: !include types/Review/ReviewReference.raml
  ReviewResourceIdentifier: !include types/Review/ReviewResourceIdentifier.raml
  ReviewUpdate: !include types/Review/ReviewUpdate.raml
  ReviewUpdateAction: !include types/Review/ReviewUpdateAction.raml
  ReviewSetAuthorNameAction: !include types/Review/ReviewSetAuthorNameAction.raml
  ReviewSetCustomFieldAction: !include types/Review/ReviewSetCustomFieldAction.raml
  ReviewSetCustomTypeAction: !include types/Review/ReviewSetCustomTypeAction.raml
  ReviewSetCustomerAction: !include types/Review/ReviewSetCustomerAction.raml
  ReviewSetKeyAction: !include types/Review/ReviewSetKeyAction.raml
  ReviewSetLocaleAction: !include types/Review/ReviewSetLocaleAction.raml
  ReviewSetRatingAction: !include types/Review/ReviewSetRatingAction.raml
  ReviewSetTargetAction: !include types/Review/ReviewSetTargetAction.raml
  ReviewSetTextAction: !include types/Review/ReviewSetTextAction.raml
  ReviewSetTitleAction: !include types/Review/ReviewSetTitleAction.raml
  ReviewTransitionStateAction: !include types/Review/ReviewTransitionStateAction.raml
  CartClassificationTier: !include types/ShippingMethod/CartClassificationTier.raml
  CartScoreTier: !include types/ShippingMethod/CartScoreTier.raml
  CartValueTier: !include types/ShippingMethod/CartValueTier.raml
  PriceFunction: !include types/ShippingMethod/PriceFunction.raml
  ShippingMethod: !include types/ShippingMethod/ShippingMethod.raml
  ShippingMethodDraft: !include types/ShippingMethod/ShippingMethodDraft.raml
  ShippingMethodPagedQueryResponse: !include types/ShippingMethod/ShippingMethodPagedQueryResponse.raml
  ShippingMethodReference: !include types/ShippingMethod/ShippingMethodReference.raml
  ShippingMethodResourceIdentifier: !include types/ShippingMethod/ShippingMethodResourceIdentifier.raml
  ShippingMethodUpdate: !include types/ShippingMethod/ShippingMethodUpdate.raml
  ShippingMethodUpdateAction: !include types/ShippingMethod/ShippingMethodUpdateAction.raml
  ShippingRate: !include types/ShippingMethod/ShippingRate.raml
  ShippingRateDraft: !include types/ShippingMethod/ShippingRateDraft.raml
  ShippingRatePriceTier: !include types/ShippingMethod/ShippingRatePriceTier.raml
  ShippingRateTierType: !include types/ShippingMethod/ShippingRateTierType.raml
  ZoneRate: !include types/ShippingMethod/ZoneRate.raml
  ZoneRateDraft: !include types/ShippingMethod/ZoneRateDraft.raml
  ShippingMethodAddShippingRateAction: !include types/ShippingMethod/ShippingMethodAddShippingRateAction.raml
  ShippingMethodAddZoneAction: !include types/ShippingMethod/ShippingMethodAddZoneAction.raml
  ShippingMethodChangeIsDefaultAction: !include types/ShippingMethod/ShippingMethodChangeIsDefaultAction.raml
  ShippingMethodChangeNameAction: !include types/ShippingMethod/ShippingMethodChangeNameAction.raml
  ShippingMethodChangeTaxCategoryAction: !include types/ShippingMethod/ShippingMethodChangeTaxCategoryAction.raml
  ShippingMethodRemoveShippingRateAction: !include types/ShippingMethod/ShippingMethodRemoveShippingRateAction.raml
  ShippingMethodRemoveZoneAction: !include types/ShippingMethod/ShippingMethodRemoveZoneAction.raml
  ShippingMethodSetDescriptionAction: !include types/ShippingMethod/ShippingMethodSetDescriptionAction.raml
  ShippingMethodSetKeyAction: !include types/ShippingMethod/ShippingMethodSetKeyAction.raml
  ShippingMethodSetPredicateAction: !include types/ShippingMethod/ShippingMethodSetPredicateAction.raml
  ShoppingList: !include types/ShoppingList/ShoppingList.raml
  ShoppingListDraft: !include types/ShoppingList/ShoppingListDraft.raml
  ShoppingListLineItem: !include types/ShoppingList/ShoppingListLineItem.raml
  ShoppingListLineItemDraft: !include types/ShoppingList/ShoppingListLineItemDraft.raml
  ShoppingListPagedQueryResponse: !include types/ShoppingList/ShoppingListPagedQueryResponse.raml
  ShoppingListReference: !include types/ShoppingList/ShoppingListReference.raml
  ShoppingListResourceIdentifier: !include types/ShoppingList/ShoppingListResourceIdentifier.raml
  ShoppingListUpdate: !include types/ShoppingList/ShoppingListUpdate.raml
  ShoppingListUpdateAction: !include types/ShoppingList/ShoppingListUpdateAction.raml
  TextLineItem: !include types/ShoppingList/TextLineItem.raml
  TextLineItemDraft: !include types/ShoppingList/TextLineItemDraft.raml
  ShoppingListAddLineItemAction: !include types/ShoppingList/ShoppingListAddLineItemAction.raml
  ShoppingListAddTextLineItemAction: !include types/ShoppingList/ShoppingListAddTextLineItemAction.raml
  ShoppingListChangeLineItemQuantityAction: !include types/ShoppingList/ShoppingListChangeLineItemQuantityAction.raml
  ShoppingListChangeLineItemsOrderAction: !include types/ShoppingList/ShoppingListChangeLineItemsOrderAction.raml
  ShoppingListChangeNameAction: !include types/ShoppingList/ShoppingListChangeNameAction.raml
  ShoppingListChangeTextLineItemNameAction: !include types/ShoppingList/ShoppingListChangeTextLineItemNameAction.raml
  ShoppingListChangeTextLineItemQuantityAction: !include types/ShoppingList/ShoppingListChangeTextLineItemQuantityAction.raml
  ShoppingListChangeTextLineItemsOrderAction: !include types/ShoppingList/ShoppingListChangeTextLineItemsOrderAction.raml
  ShoppingListRemoveLineItemAction: !include types/ShoppingList/ShoppingListRemoveLineItemAction.raml
  ShoppingListRemoveTextLineItemAction: !include types/ShoppingList/ShoppingListRemoveTextLineItemAction.raml
  ShoppingListSetAnonymousIdAction: !include types/ShoppingList/ShoppingListSetAnonymousIdAction.raml
  ShoppingListSetCustomFieldAction: !include types/ShoppingList/ShoppingListSetCustomFieldAction.raml
  ShoppingListSetCustomTypeAction: !include types/ShoppingList/ShoppingListSetCustomTypeAction.raml
  ShoppingListSetCustomerAction: !include types/ShoppingList/ShoppingListSetCustomerAction.raml
  ShoppingListSetDeleteDaysAfterLastModificationAction: !include types/ShoppingList/ShoppingListSetDeleteDaysAfterLastModificationAction.raml
  ShoppingListSetDescriptionAction: !include types/ShoppingList/ShoppingListSetDescriptionAction.raml
  ShoppingListSetKeyAction: !include types/ShoppingList/ShoppingListSetKeyAction.raml
  ShoppingListSetLineItemCustomFieldAction: !include types/ShoppingList/ShoppingListSetLineItemCustomFieldAction.raml
  ShoppingListSetLineItemCustomTypeAction: !include types/ShoppingList/ShoppingListSetLineItemCustomTypeAction.raml
  ShoppingListSetSlugAction: !include types/ShoppingList/ShoppingListSetSlugAction.raml
  ShoppingListSetTextLineItemCustomFieldAction: !include types/ShoppingList/ShoppingListSetTextLineItemCustomFieldAction.raml
  ShoppingListSetTextLineItemCustomTypeAction: !include types/ShoppingList/ShoppingListSetTextLineItemCustomTypeAction.raml
  ShoppingListSetTextLineItemDescriptionAction: !include types/ShoppingList/ShoppingListSetTextLineItemDescriptionAction.raml
  State: !include types/State/State.raml
  StateDraft: !include types/State/StateDraft.raml
  StatePagedQueryResponse: !include types/State/StatePagedQueryResponse.raml
  StateReference: !include types/State/StateReference.raml
  StateResourceIdentifier: !include types/State/StateResourceIdentifier.raml
  StateRoleEnum: !include types/State/StateRoleEnum.raml
  StateTypeEnum: !include types/State/StateTypeEnum.raml
  StateUpdate: !include types/State/StateUpdate.raml
  StateUpdateAction: !include types/State/StateUpdateAction.raml
  StateAddRolesAction: !include types/State/StateAddRolesAction.raml
  StateChangeInitialAction: !include types/State/StateChangeInitialAction.raml
  StateChangeKeyAction: !include types/State/StateChangeKeyAction.raml
  StateChangeTypeAction: !include types/State/StateChangeTypeAction.raml
  StateRemoveRolesAction: !include types/State/StateRemoveRolesAction.raml
  StateSetDescriptionAction: !include types/State/StateSetDescriptionAction.raml
  StateSetNameAction: !include types/State/StateSetNameAction.raml
  StateSetRolesAction: !include types/State/StateSetRolesAction.raml
  StateSetTransitionsAction: !include types/State/StateSetTransitionsAction.raml
  Store: !include types/Store/Store.raml
  StoreDraft: !include types/Store/StoreDraft.raml
  StoreKeyReference: !include types/Store/StoreKeyReference.raml
  StorePagedQueryResponse: !include types/Store/StorePagedQueryResponse.raml
  StoreReference: !include types/Store/StoreReference.raml
  StoreResourceIdentifier: !include types/Store/StoreResourceIdentifier.raml
  StoreUpdate: !include types/Store/StoreUpdate.raml
  StoreUpdateAction: !include types/Store/StoreUpdateAction.raml
  StoreSetNameAction: !include types/Store/StoreSetNameAction.raml
  AzureEventGridDestination: !include types/Subscription/AzureEventGridDestination.raml
  AzureServiceBusDestination: !include types/Subscription/AzureServiceBusDestination.raml
  ChangeSubscription: !include types/Subscription/ChangeSubscription.raml
  DeliveryCloudEventsFormat: !include types/Subscription/DeliveryCloudEventsFormat.raml
  DeliveryFormat: !include types/Subscription/DeliveryFormat.raml
  DeliveryPlatformFormat: !include types/Subscription/DeliveryPlatformFormat.raml
  Destination: !include types/Subscription/Destination.raml
  GoogleCloudPubSubDestination: !include types/Subscription/GoogleCloudPubSubDestination.raml
  IronMqDestination: !include types/Subscription/IronMqDestination.raml
  MessageDelivery: !include types/Subscription/MessageDelivery.raml
  MessageSubscription: !include types/Subscription/MessageSubscription.raml
  PayloadNotIncluded: !include types/Subscription/PayloadNotIncluded.raml
  ResourceCreatedDelivery: !include types/Subscription/ResourceCreatedDelivery.raml
  ResourceDeletedDelivery: !include types/Subscription/ResourceDeletedDelivery.raml
  ResourceUpdatedDelivery: !include types/Subscription/ResourceUpdatedDelivery.raml
  SnsDestination: !include types/Subscription/SnsDestination.raml
  SqsDestination: !include types/Subscription/SqsDestination.raml
  Subscription: !include types/Subscription/Subscription.raml
  SubscriptionDelivery: !include types/Subscription/SubscriptionDelivery.raml
  SubscriptionDraft: !include types/Subscription/SubscriptionDraft.raml
  SubscriptionHealthStatus: !include types/Subscription/SubscriptionHealthStatus.raml
  SubscriptionPagedQueryResponse: !include types/Subscription/SubscriptionPagedQueryResponse.raml
  SubscriptionUpdate: !include types/Subscription/SubscriptionUpdate.raml
  SubscriptionUpdateAction: !include types/Subscription/SubscriptionUpdateAction.raml
  SubscriptionChangeDestinationAction: !include types/Subscription/SubscriptionChangeDestinationAction.raml
  SubscriptionSetChangesAction: !include types/Subscription/SubscriptionSetChangesAction.raml
  SubscriptionSetKeyAction: !include types/Subscription/SubscriptionSetKeyAction.raml
  SubscriptionSetMessagesAction: !include types/Subscription/SubscriptionSetMessagesAction.raml
  SubRate: !include types/TaxCategory/SubRate.raml
  TaxCategory: !include types/TaxCategory/TaxCategory.raml
  TaxCategoryDraft: !include types/TaxCategory/TaxCategoryDraft.raml
  TaxCategoryPagedQueryResponse: !include types/TaxCategory/TaxCategoryPagedQueryResponse.raml
  TaxCategoryReference: !include types/TaxCategory/TaxCategoryReference.raml
  TaxCategoryResourceIdentifier: !include types/TaxCategory/TaxCategoryResourceIdentifier.raml
  TaxCategoryUpdate: !include types/TaxCategory/TaxCategoryUpdate.raml
  TaxCategoryUpdateAction: !include types/TaxCategory/TaxCategoryUpdateAction.raml
  TaxRate: !include types/TaxCategory/TaxRate.raml
  TaxRateDraft: !include types/TaxCategory/TaxRateDraft.raml
  TaxCategoryAddTaxRateAction: !include types/TaxCategory/TaxCategoryAddTaxRateAction.raml
  TaxCategoryChangeNameAction: !include types/TaxCategory/TaxCategoryChangeNameAction.raml
  TaxCategoryRemoveTaxRateAction: !include types/TaxCategory/TaxCategoryRemoveTaxRateAction.raml
  TaxCategoryReplaceTaxRateAction: !include types/TaxCategory/TaxCategoryReplaceTaxRateAction.raml
  TaxCategorySetDescriptionAction: !include types/TaxCategory/TaxCategorySetDescriptionAction.raml
  TaxCategorySetKeyAction: !include types/TaxCategory/TaxCategorySetKeyAction.raml
  CustomFieldBooleanType: !include types/Type/CustomFieldBooleanType.raml
  CustomFieldDateTimeType: !include types/Type/CustomFieldDateTimeType.raml
  CustomFieldDateType: !include types/Type/CustomFieldDateType.raml
  CustomFieldEnumType: !include types/Type/CustomFieldEnumType.raml
  CustomFieldEnumValue: !include types/Type/CustomFieldEnumValue.raml
  CustomFieldLocalizedEnumType: !include types/Type/CustomFieldLocalizedEnumType.raml
  CustomFieldLocalizedEnumValue: !include types/Type/CustomFieldLocalizedEnumValue.raml
  CustomFieldLocalizedStringType: !include types/Type/CustomFieldLocalizedStringType.raml
  CustomFieldMoneyType: !include types/Type/CustomFieldMoneyType.raml
  CustomFieldNumberType: !include types/Type/CustomFieldNumberType.raml
  CustomFieldReferenceType: !include types/Type/CustomFieldReferenceType.raml
  CustomFieldSetType: !include types/Type/CustomFieldSetType.raml
  CustomFieldStringType: !include types/Type/CustomFieldStringType.raml
  CustomFieldTimeType: !include types/Type/CustomFieldTimeType.raml
  CustomFields: !include types/Type/CustomFields.raml
  CustomFieldsDraft: !include types/Type/CustomFieldsDraft.raml
  FieldContainer: !include types/Type/FieldContainer.raml
  FieldDefinition: !include types/Type/FieldDefinition.raml
  FieldType: !include types/Type/FieldType.raml
  ResourceTypeId: !include types/Type/ResourceTypeId.raml
  Type: !include types/Type/Type.raml
  TypeDraft: !include types/Type/TypeDraft.raml
  TypePagedQueryResponse: !include types/Type/TypePagedQueryResponse.raml
  TypeReference: !include types/Type/TypeReference.raml
  TypeResourceIdentifier: !include types/Type/TypeResourceIdentifier.raml
  TypeTextInputHint: !include types/Type/TypeTextInputHint.raml
  TypeUpdate: !include types/Type/TypeUpdate.raml
  TypeUpdateAction: !include types/Type/TypeUpdateAction.raml
  TypeAddEnumValueAction: !include types/Type/TypeAddEnumValueAction.raml
  TypeAddFieldDefinitionAction: !include types/Type/TypeAddFieldDefinitionAction.raml
  TypeAddLocalizedEnumValueAction: !include types/Type/TypeAddLocalizedEnumValueAction.raml
  TypeChangeEnumValueLabelAction: !include types/Type/TypeChangeEnumValueLabelAction.raml
  TypeChangeEnumValueOrderAction: !include types/Type/TypeChangeEnumValueOrderAction.raml
  TypeChangeFieldDefinitionLabelAction: !include types/Type/TypeChangeFieldDefinitionLabelAction.raml
  TypeChangeFieldDefinitionOrderAction: !include types/Type/TypeChangeFieldDefinitionOrderAction.raml
  TypeChangeInputHintAction: !include types/Type/TypeChangeInputHintAction.raml
  TypeChangeKeyAction: !include types/Type/TypeChangeKeyAction.raml
  TypeChangeLabelAction: !include types/Type/TypeChangeLabelAction.raml
  TypeChangeLocalizedEnumValueLabelAction: !include types/Type/TypeChangeLocalizedEnumValueLabelAction.raml
  TypeChangeLocalizedEnumValueOrderAction: !include types/Type/TypeChangeLocalizedEnumValueOrderAction.raml
  TypeChangeNameAction: !include types/Type/TypeChangeNameAction.raml
  TypeRemoveFieldDefinitionAction: !include types/Type/TypeRemoveFieldDefinitionAction.raml
  TypeSetDescriptionAction: !include types/Type/TypeSetDescriptionAction.raml
  Location: !include types/Zone/Location.raml
  Zone: !include types/Zone/Zone.raml
  ZoneDraft: !include types/Zone/ZoneDraft.raml
  ZonePagedQueryResponse: !include types/Zone/ZonePagedQueryResponse.raml
  ZoneReference: !include types/Zone/ZoneReference.raml
  ZoneResourceIdentifier: !include types/Zone/ZoneResourceIdentifier.raml
  ZoneUpdate: !include types/Zone/ZoneUpdate.raml
  ZoneUpdateAction: !include types/Zone/ZoneUpdateAction.raml
  ZoneAddLocationAction: !include types/Zone/ZoneAddLocationAction.raml
  ZoneChangeNameAction: !include types/Zone/ZoneChangeNameAction.raml
  ZoneRemoveLocationAction: !include types/Zone/ZoneRemoveLocationAction.raml
  ZoneSetDescriptionAction: !include types/Zone/ZoneSetDescriptionAction.raml
  ZoneSetKeyAction: !include types/Zone/ZoneSetKeyAction.raml