#%RAML 1.0 DataType
displayName: AnyAttribute
type: Attribute
(builtinType): object
discriminatorValue: any
description: |-
  This type allows to send any json object as value and is mainly intended to ease the migration from the CTP api.
properties:
  type:
    type: string
    (builtinType): string
    enum:
    - any
    required: true
  value:
    type: any
    (builtinType): any
    required: true